// The Persian alphabet: a letter drill, one card per letter (direction "letter").
// Item ids are permanent. Never change or reuse one; add new items with new ids.
F.lesson({
  id: "alphabet",
  kind: 'alphabet',
  label: "Alphabet",
  items: [
    // Letters
    { id: "alpha.alef", type: 'letter', name: "alef", sound: "ā / a", isolated: "ا", initial: "ا", medial: "ـا", final: "ـا", notes: "Long 'a' or silent carrier" },
    { id: "alpha.be", type: 'letter', name: "be", sound: "b", isolated: "ب", initial: "بـ", medial: "ـبـ", final: "ـب", notes: "Like English 'b'" },
    { id: "alpha.pe", type: 'letter', name: "pe", sound: "p", isolated: "پ", initial: "پـ", medial: "ـپـ", final: "ـپ", notes: "Like English 'p' (Persian only)" },
    { id: "alpha.te", type: 'letter', name: "te", sound: "t", isolated: "ت", initial: "تـ", medial: "ـتـ", final: "ـت", notes: "Like English 't'" },
    { id: "alpha.se", type: 'letter', name: "se", sound: "s", isolated: "ث", initial: "ثـ", medial: "ـثـ", final: "ـث", notes: "Like 's' (Arabic loan words)" },
    { id: "alpha.jim", type: 'letter', name: "jim", sound: "j", isolated: "ج", initial: "جـ", medial: "ـجـ", final: "ـج", notes: "Like 'j' in 'judge'" },
    { id: "alpha.che", type: 'letter', name: "che", sound: "ch", isolated: "چ", initial: "چـ", medial: "ـچـ", final: "ـچ", notes: "Like 'ch' in 'chair' (Persian only)" },
    { id: "alpha.he-ha", type: 'letter', name: "he (ḥā)", sound: "h", isolated: "ح", initial: "حـ", medial: "ـحـ", final: "ـح", notes: "Breathy 'h'" },
    { id: "alpha.khe", type: 'letter', name: "khe", sound: "kh", isolated: "خ", initial: "خـ", medial: "ـخـ", final: "ـخ", notes: "Like 'ch' in Scottish 'loch'" },
    { id: "alpha.sin", type: 'letter', name: "sin", sound: "s", isolated: "س", initial: "سـ", medial: "ـسـ", final: "ـس", notes: "Like English 's'" },
    { id: "alpha.shin", type: 'letter', name: "shin", sound: "sh", isolated: "ش", initial: "شـ", medial: "ـشـ", final: "ـش", notes: "Like 'sh' in 'ship'" },
    { id: "alpha.sad", type: 'letter', name: "sād", sound: "s", isolated: "ص", initial: "صـ", medial: "ـصـ", final: "ـص", notes: "Emphatic 's' (Arabic)" },
    { id: "alpha.zad", type: 'letter', name: "zād", sound: "z", isolated: "ض", initial: "ضـ", medial: "ـضـ", final: "ـض", notes: "Emphatic 'z' (Arabic)" },
    { id: "alpha.ta", type: 'letter', name: "tā", sound: "t", isolated: "ط", initial: "طـ", medial: "ـطـ", final: "ـط", notes: "Emphatic 't' (Arabic)" },
    { id: "alpha.za", type: 'letter', name: "zā", sound: "z", isolated: "ظ", initial: "ظـ", medial: "ـظـ", final: "ـظ", notes: "Emphatic 'z' (Arabic)" },
    { id: "alpha.eyn", type: 'letter', name: "eyn", sound: "'", isolated: "ع", initial: "عـ", medial: "ـعـ", final: "ـع", notes: "Glottal sound" },
    { id: "alpha.gheyn", type: 'letter', name: "gheyn", sound: "gh", isolated: "غ", initial: "غـ", medial: "ـغـ", final: "ـغ", notes: "Guttural 'g'" },
    { id: "alpha.fe", type: 'letter', name: "fe", sound: "f", isolated: "ف", initial: "فـ", medial: "ـفـ", final: "ـف", notes: "Like English 'f'" },
    { id: "alpha.qaf", type: 'letter', name: "qāf", sound: "gh / q", isolated: "ق", initial: "قـ", medial: "ـقـ", final: "ـق", notes: "Deep guttural (≈ غ in Persian)" },
    { id: "alpha.kaf", type: 'letter', name: "kāf", sound: "k", isolated: "ک", initial: "کـ", medial: "ـکـ", final: "ـک", notes: "Like English 'k'" },
    { id: "alpha.gaf", type: 'letter', name: "gāf", sound: "g", isolated: "گ", initial: "گـ", medial: "ـگـ", final: "ـگ", notes: "Like 'g' in 'go' (Persian only)" },
    { id: "alpha.lam", type: 'letter', name: "lām", sound: "l", isolated: "ل", initial: "لـ", medial: "ـلـ", final: "ـل", notes: "Like English 'l'" },
    { id: "alpha.mim", type: 'letter', name: "mim", sound: "m", isolated: "م", initial: "مـ", medial: "ـمـ", final: "ـم", notes: "Like English 'm'" },
    { id: "alpha.nun", type: 'letter', name: "nun", sound: "n", isolated: "ن", initial: "نـ", medial: "ـنـ", final: "ـن", notes: "Like English 'n'" },
    { id: "alpha.he", type: 'letter', name: "he", sound: "h / e", isolated: "ه", initial: "هـ", medial: "ـهـ", final: "ـه", notes: "Like 'h' or silent 'e' at end" },
    { id: "alpha.ye", type: 'letter', name: "ye", sound: "y / i", isolated: "ی", initial: "یـ", medial: "ـیـ", final: "ـی", notes: "Like 'y' or long 'ee'" },
    { id: "alpha.dal", type: 'letter', name: "dāl", sound: "d", isolated: "د", initial: "د", medial: "ـد", final: "ـد", notes: "Like English 'd' (non-connecting)" },
    { id: "alpha.zal", type: 'letter', name: "zāl", sound: "z", isolated: "ذ", initial: "ذ", medial: "ـذ", final: "ـذ", notes: "Like 'z' (non-connecting)" },
    { id: "alpha.re", type: 'letter', name: "re", sound: "r", isolated: "ر", initial: "ر", medial: "ـر", final: "ـر", notes: "Rolled 'r' (non-connecting)" },
    { id: "alpha.ze", type: 'letter', name: "ze", sound: "z", isolated: "ز", initial: "ز", medial: "ـز", final: "ـز", notes: "Like English 'z' (non-connecting)" },
    { id: "alpha.zhe", type: 'letter', name: "zhe", sound: "zh", isolated: "ژ", initial: "ژ", medial: "ـژ", final: "ـژ", notes: "Like 's' in 'measure' (Persian only)" },
    { id: "alpha.vav", type: 'letter', name: "vāv", sound: "v / oo / o", isolated: "و", initial: "و", medial: "ـو", final: "ـو", notes: "v, oo, or o sound (non-connecting)" },
  ],
});
