// Session 22.
// Item ids are permanent. Never change or reuse one; add new items with new ids.
F.lesson({
  id: "22",
  label: "Session 22",
  title: "و and گ, to be, pronouns and family",
  notes: "ALEX-SESSION-22_formatted.md",
  items: [
    // Vocabulary
    { id: "22.v.varzesh-kardan", type: "vocabulary", fa: "ورزش کردن", pin: "varzesh kardan", en: "to exercise", notes: "و-ر-ز-ش ک-ر-د-ن" },
    { id: "22.v.va", type: "vocabulary", fa: "وَ", pin: "va", en: "and", notes: "و (vāv)" },
    { id: "22.v.mesvak", type: "vocabulary", fa: "مِسواک", pin: "mesvāk", en: "toothbrush", notes: "م-س-و-ا-ک" },
    { id: "22.v.miveh", type: "vocabulary", fa: "میوه", pin: "miveh", en: "fruit", notes: "م-ی-و-ه" },
    { id: "22.v.livan", type: "vocabulary", fa: "لیوان", pin: "livān", en: "glass", notes: "ل-ی-و-ا-ن" },
    { id: "22.v.parvaneh", type: "vocabulary", fa: "پَروانه", pin: "parvāneh", en: "butterfly", notes: "پ-ر-و-ا-ن-ه" },
    { id: "22.v.oo-oon", type: "vocabulary", fa: "او / اون", pin: "oo / oon", en: "he, she", notes: "ا-و (formal) / ا-و-ن (colloquial)" },
    { id: "22.v.rooz", type: "vocabulary", fa: "روز", pin: "rooz", en: "day", notes: "ر-و-ز" },
    { id: "22.v.emrooz", type: "vocabulary", fa: "امروز", pin: "emrooz", en: "today", notes: "ا-م-ر-و-ز (lit: this day)" },
    { id: "22.v.khoob", type: "vocabulary", fa: "خوب", pin: "khoob", en: "good", notes: "خ-و-ب" },
    { id: "22.v.doost", type: "vocabulary", fa: "دوست", pin: "doost", en: "friend", notes: "د-و-س-ت" },
    { id: "22.v.shoor", type: "vocabulary", fa: "شور", pin: "shoor", en: "salty", notes: "ش-و-ر" },
    { id: "22.v.ordak", type: "vocabulary", fa: "اُردَک", pin: "ordak", en: "duck", notes: "ا-ر-د-ک" },
    { id: "22.v.khosh", type: "vocabulary", fa: "خُوش", pin: "khosh", en: "pleasant", notes: "خ-و-ش" },
    { id: "22.v.khoshmaze", type: "vocabulary", fa: "خُوشمَزه", pin: "khoshmaze", en: "delicious", notes: "خوش (pleasant) + مزه (taste)" },
    { id: "22.v.to", type: "vocabulary", fa: "تو", pin: "to", en: "you (informal)", notes: "ت-و" },
    { id: "22.v.polo", type: "vocabulary", fa: "پُلُو", pin: "polo", en: "cooked rice", notes: "پ-ل-و" },
    { id: "22.v.do", type: "vocabulary", fa: "دو", pin: "do", en: "two", notes: "د-و" },
    { id: "22.v.khod", type: "vocabulary", fa: "خود", pin: "khod", en: "self", notes: "خ-و-د" },
    { id: "22.v.khodkar", type: "vocabulary", fa: "خودکار", pin: "khodkār", en: "pen (ballpoint)", notes: "خود (self) + کار (work) = automatic" },
    { id: "22.v.metro", type: "vocabulary", fa: "مترو", pin: "metro", en: "metro, subway", notes: "م-ت-ر-و" },
    { id: "22.v.gilas", type: "vocabulary", fa: "گیلاس", pin: "gilās", en: "cherry", notes: "گ-ی-ل-ا-س" },
    { id: "22.v.gorbeh", type: "vocabulary", fa: "گُربه", pin: "gorbeh", en: "cat", notes: "گ-ر-ب-ه" },
    { id: "22.v.sag", type: "vocabulary", fa: "سَگ", pin: "sag", en: "dog", notes: "س-گ" },
    { id: "22.v.zendegi", type: "vocabulary", fa: "زندگی", pin: "zendegi", en: "life", notes: "ز-ن-د-گ-ی" },
    { id: "22.v.gav", type: "vocabulary", fa: "گاو", pin: "gāv", en: "cow", notes: "گ-ا-و" },
    { id: "22.v.in", type: "vocabulary", fa: "این", pin: "in", en: "this", notes: "ا-ی-ن" },
    { id: "22.v.an-oon", type: "vocabulary", fa: "آن / اون", pin: "ān / oon", en: "that", notes: "ا-ی-ن (formal) / ا-و-ن (colloquial)" },
    { id: "22.v.inja", type: "vocabulary", fa: "اینجا", pin: "injā", en: "here", notes: "این (this) + جا (place)" },
    { id: "22.v.anja", type: "vocabulary", fa: "آنجا", pin: "ānjā", en: "there", notes: "آن (that) + جا (place)" },
    { id: "22.v.chetor", type: "vocabulary", fa: "چطور", pin: "chetor", en: "how", notes: "چ-ط-و-ر" },
    { id: "22.v.maman", type: "vocabulary", fa: "مامان", pin: "māmān", en: "mom", notes: "م-ا-م-ا-ن" },
    { id: "22.v.baba", type: "vocabulary", fa: "بابا", pin: "bābā", en: "dad", notes: "ب-ا-ب-ا" },
    { id: "22.v.mamanbozorg", type: "vocabulary", fa: "مامان‌بزرگ", pin: "māmānbozorg", en: "grandmother", notes: "مامان + بزرگ (big)" },
    { id: "22.v.bababozorg", type: "vocabulary", fa: "بابابزرگ", pin: "bābābozorg", en: "grandfather", notes: "بابا + بزرگ (big)" },
    { id: "22.v.kheili", type: "vocabulary", fa: "خیلی", pin: "kheili", en: "very", notes: "خ-ی-ل-ی" },
    { id: "22.v.mamnoon", type: "vocabulary", fa: "ممنون", pin: "mamnoon", en: "thank you", notes: "م-م-ن-و-ن" },
    { id: "22.v.bad", type: "vocabulary", fa: "بد", pin: "bad", en: "bad", notes: "ب-د" },
    { id: "22.v.irani", type: "vocabulary", fa: "ایرانی", pin: "irāni", en: "Iranian", notes: "ایران + ی" },
    { id: "22.v.bahoosh", type: "vocabulary", fa: "باهوش", pin: "bāhoosh", en: "smart", notes: "با (with) + هوش (intelligence)" },
    // Grammar
    { id: "22.g.man-hastam", type: "grammar", fa: "من هستم", pin: "man hastam", en: "I am", notes: "هستم = am (1st person singular)" },
    { id: "22.g.to-hasti", type: "grammar", fa: "تو هستی", pin: "to hasti", en: "you are (informal)", notes: "هستی = are (2nd person singular)" },
    { id: "22.g.oo-hast", type: "grammar", fa: "او هست", pin: "oo hast", en: "he/she is", notes: "هست = is (3rd person singular)" },
    { id: "22.g.ma-hastim", type: "grammar", fa: "ما هستیم", pin: "mā hastim", en: "we are", notes: "هستیم = are (1st person plural)" },
    { id: "22.g.shoma-hastid", type: "grammar", fa: "شما هستید", pin: "shomā hastid", en: "you are (formal/plural)", notes: "هستید = are (2nd person plural)" },
    { id: "22.g.anha-hastand", type: "grammar", fa: "آنها هستند", pin: "ānhā hastand", en: "they are", notes: "هستند = are (3rd person plural)" },
    { id: "22.g.khoobam", type: "grammar", fa: "خوبم", pin: "khoobam", en: "I am good", notes: "خوب + ـَم (I am)" },
    { id: "22.g.khoobi", type: "grammar", fa: "خوبی", pin: "khoobi", en: "you are good", notes: "خوب + ـی (you are)" },
    { id: "22.g.khoobeh", type: "grammar", fa: "خوبه", pin: "khoobeh", en: "he/she is good", notes: "خوب + ـه (he/she is)" },
    { id: "22.g.khoobim", type: "grammar", fa: "خوبیم", pin: "khoobim", en: "we are good", notes: "خوب + ـیم (we are)" },
    { id: "22.g.khoobid", type: "grammar", fa: "خوبید", pin: "khoobid", en: "you are good (pl)", notes: "خوب + ـید (you are)" },
    { id: "22.g.khooband", type: "grammar", fa: "خوبند", pin: "khooband", en: "they are good", notes: "خوب + ـند (they are)" },
    // Phrases
    { id: "22.p.to-chetori", type: "phrases", fa: "تو چطوری؟", pin: "to chetori?", en: "How are you? (informal)", notes: "تو (you) + چطوری (how)" },
    { id: "22.p.shoma-chetorid", type: "phrases", fa: "شما چطورید؟", pin: "shomā chetorid?", en: "How are you? (formal)", notes: "شما (you formal) + چطورید (how are)" },
    { id: "22.p.maman-o-baba-chetorand", type: "phrases", fa: "مامان و بابا چطورند؟", pin: "māmān o bābā chetorand?", en: "How are mom and dad?", notes: "چطورند = how are they" },
    { id: "22.p.kheili-mamnoon", type: "phrases", fa: "خیلی ممنون", pin: "kheili mamnoon", en: "thank you very much", notes: "خیلی (very) + ممنون (thanks)" },
    { id: "22.p.bad-nistand", type: "phrases", fa: "بد نیستند", pin: "bad nistand", en: "they're not bad", notes: "بد (bad) + نیستند (are not)" },
  ],
});
