// Session 22.
// Item ids are permanent. Never change or reuse one; add new items with new ids.
F.lesson({
  id: "22",
  label: "Session 22",
  title: "و and گ, to be, pronouns and family",
  notes: "ALEX-SESSION-22_formatted.md",
  items: [
    // Vocabulary
    { id: "22.v.varzesh-kardan", type: "vocabulary", fa: "ورزش کردن", pin: "varzesh kardan", en: "to exercise", notes: "و-ر-ز-ش ک-ر-د-ن",
      examples: [
        { fa: "امروز علی و باباش ورزش می‌کنن.", pin: "Emrooz Ali o bābāsh varzesh mikonan.", en: "Today Ali and his dad are exercising.", source: "story:st-22-1" },
        { fa: "ورزش کردن برای من خیلی مهمه", pin: "varzesh kardan barāye man kheili mohem-e", en: "Exercising is very important to me", source: "phrase:27" },
      ] },
    { id: "22.v.va", type: "vocabulary", fa: "وَ", pin: "va", en: "and", notes: "و (vāv)",
      examples: [
        { fa: "مامان و بابا چطورند؟", pin: "māmān o bābā chetorand?", en: "How are mom and dad?", source: "phrase:22" },
        { fa: "علی ایرانی هست و خیلی باهوشه.", pin: "Ali irāni hast va kheili bāhoosh-eh.", en: "Ali is Iranian and very smart.", source: "story:st-22-1" },
        { fa: "سارا خیلی خوب و باهوشه.", pin: "Sārā kheili khoob o bāhoosh-eh.", en: "Sara is very nice and smart.", source: "story:st-22-1" },
        { fa: "امروز مامان و بابای علی اینجا هستن.", pin: "Emrooz māmān o bābā-ye Ali injā hastan.", en: "Today Ali's mom and dad are here.", source: "story:st-22-1" },
      ] },
    { id: "22.v.mesvak", type: "vocabulary", fa: "مِسواک", pin: "mesvāk", en: "toothbrush", notes: "م-س-و-ا-ک",
      examples: [
        { fa: "دندون‌ها رو مسواک بزن", pin: "dandoon-hā ro mesvāk bezan", en: "Brush your teeth", source: "phrase:33" },
        { fa: "قبل از صبحونه، بچه‌ها دندون‌هاشون رو مسواک می‌زنن.", pin: "Ghabl az sobhooneh, bacheh hā dandoon hāshoon ro mesvāk mizanan.", en: "Before breakfast, the children brush their teeth.", source: "story:st-33-2" },
      ] },
    { id: "22.v.miveh", type: "vocabulary", fa: "میوه", pin: "miveh", en: "fruit", notes: "م-ی-و-ه",
      examples: [
        { fa: "سارا سبزیجات و میوه رو خیلی دوست داره.", pin: "Sārā sabzijāt o miveh ro kheili doost dāreh.", en: "Sara really loves vegetables and fruit.", source: "story:st-23-1" },
        { fa: "میوه‌ها توی یخچال بودند.", pin: "Mive hā tuye yakhchāl boodand.", en: "(But) the fruits were in the fridge.", source: "phrase:35" },
        { fa: "روی میز یه ظرف میوه و یه قوری هست.", pin: "Ruye miz ye zarf-e miveh o ye ghoori hast.", en: "On the table there's a fruit bowl and a teapot.", source: "story:st-35-2" },
      ] },
    { id: "22.v.livan", type: "vocabulary", fa: "لیوان", pin: "livān", en: "glass", notes: "ل-ی-و-ا-ن" },
    { id: "22.v.parvaneh", type: "vocabulary", fa: "پَروانه", pin: "parvāneh", en: "butterfly", notes: "پ-ر-و-ا-ن-ه" },
    { id: "22.v.oo-oon", type: "vocabulary", fa: "او / اون", pin: "oo / oon", en: "he, she", notes: "ا-و (formal) / ا-و-ن (colloquial)",
      examples: [
        { fa: "اون گوشت و ماهی نمی‌خوره.", pin: "Oon goosht o māhi nemikhoreh.", en: "She doesn't eat meat or fish.", source: "story:st-23-1" },
        { fa: "این کیف مال اونه", pin: "in kif māl-e oon-e", en: "This bag is hers/his", source: "phrase:29" },
        { fa: "به اون بگو", pin: "be oon begoo", en: "Tell her/him!", source: "phrase:24-25" },
        { fa: "تو میدونی اون کجاست؟", pin: "to midooni oon kojāst?", en: "Do you know where he/she is?", source: "phrase:26" },
      ] },
    { id: "22.v.rooz", type: "vocabulary", fa: "روز", pin: "rooz", en: "day", notes: "ر-و-ز",
      examples: [
        { fa: "مریم هر روز در آشپزخونه آشپزی می‌کنه.", pin: "Maryam har rooz dar āshpazkhooneh āshpazi mikoneh.", en: "Maryam cooks in the kitchen every day.", source: "story:st-2425-1" },
        { fa: "این روزها خیلی خسته‌ام", pin: "in rooz-hā kheili khasta-am", en: "I'm very tired these days", source: "phrase:28" },
        { fa: "جُمعه بِهتَرین روزِ هَفته اَست.", pin: "Jom'e behtarin rooz-e hafteh ast.", en: "Friday is the best day of the week.", source: "story:34" },
        { fa: "اون هر روز ساعت هفت صبحونه می‌خوره.", pin: "Oon har rooz sāat-e haft sobhooneh mikhoreh.", en: "Every day she has breakfast at seven.", source: "story:st-26-1" },
      ] },
    { id: "22.v.emrooz", type: "vocabulary", fa: "امروز", pin: "emrooz", en: "today", notes: "ا-م-ر-و-ز (lit: this day)",
      examples: [
        { fa: "امروز مامان و بابای علی اینجا هستن.", pin: "Emrooz māmān o bābā-ye Ali injā hastan.", en: "Today Ali's mom and dad are here.", source: "story:st-22-1" },
        { fa: "امروز علی و باباش ورزش می‌کنن.", pin: "Emrooz Ali o bābāsh varzesh mikonan.", en: "Today Ali and his dad are exercising.", source: "story:st-22-1" },
        { fa: "امروز سرت شلوغه؟", pin: "emrooz saret sholugh-e?", en: "Are you busy today?", source: "phrase:24-25" },
        { fa: "امروز جُمعه اَست.", pin: "Emrooz jom'e ast.", en: "Today is Friday.", source: "story:34" },
      ] },
    { id: "22.v.khoob", type: "vocabulary", fa: "خوب", pin: "khoob", en: "good", notes: "خ-و-ب",
      examples: [
        { fa: "سارا خیلی خوب و باهوشه.", pin: "Sārā kheili khoob o bāhoosh-eh.", en: "Sara is very nice and smart.", source: "story:st-22-1" },
        { fa: "مامان: «من خوبم، ممنون. تو چطوری؟»", pin: "Māmān: \"Man khoobam, mamnoon. To chetori?\"", en: "Mom: \"I'm fine, thanks. How are you?\"", source: "story:st-22-1" },
        { fa: "مامان: «اونا خوبن. بد نیستن.»", pin: "Māmān: \"Oonā khooban. Bad nistan.\"", en: "Mom: \"They're well. Not bad.\"", source: "story:st-22-1" },
        { fa: "هوا خوبه، من پیاده می‌رم", pin: "havā khoobeh, man piādeh miram", en: "The weather's good, I'm walking", source: "phrase:30" },
      ] },
    { id: "22.v.doost", type: "vocabulary", fa: "دوست", pin: "doost", en: "friend", notes: "د-و-س-ت",
      examples: [
        { fa: "سارا دوست علی هست.", pin: "Sārā doost-e Ali hast.", en: "Sara is Ali's friend.", source: "story:st-22-1" },
        { fa: "خواهرم امروز با دوست‌هاش صبحونه میخوره", pin: "khāharam emrooz bā doost-hāsh sobhooneh mikhoreh", en: "My sister is having breakfast with her friends today", source: "phrase:26" },
        { fa: "دوستش، علی، گیاه‌خوار نیست.", pin: "Doostesh, Ali, giāh-khār nist.", en: "Her friend Ali isn't a vegetarian.", source: "story:st-23-1" },
        { fa: "امروز من و دوستم به رستوران مریم می‌ریم.", pin: "Emrooz man o doostam be restorān-e Maryam mirim.", en: "Today my friend and I are going to Maryam's restaurant.", source: "story:st-2425-1" },
      ] },
    { id: "22.v.shoor", type: "vocabulary", fa: "شور", pin: "shoor", en: "salty", notes: "ش-و-ر" },
    { id: "22.v.ordak", type: "vocabulary", fa: "اُردَک", pin: "ordak", en: "duck", notes: "ا-ر-د-ک" },
    { id: "22.v.khosh", type: "vocabulary", fa: "خُوش", pin: "khosh", en: "pleasant", notes: "خ-و-ش" },
    { id: "22.v.khoshmaze", type: "vocabulary", fa: "خُوشمَزه", pin: "khoshmaze", en: "delicious", notes: "خوش (pleasant) + مزه (taste)",
      examples: [
        { fa: "پلو خیلی خوشمزه هست!", pin: "Polo kheili khoshmazeh hast!", en: "The rice is really delicious!", source: "story:st-22-1" },
        { fa: "فسنجون خوشمزه‌ترین غذای ایرانی هست.", pin: "Fesenjoon khoshmazzetarin ghazā-ye Irāni hast.", en: "Fesenjoon is the tastiest Iranian food.", source: "phrase:34" },
        { fa: "علی می‌گه: «ولی غذای تهران خوشمزه‌تره!»", pin: "Ali migeh: \"Vali ghazā-ye Tehrān khoshmazetar-eh!\"", en: "Ali says: \"But the food in Tehran is tastier!\"", source: "story:st-34-1" },
        { fa: "غذا خیلی خوشمزه و تازه هست.", pin: "Ghazā kheili khoshmazeh o tāzeh hast.", en: "The food is very tasty and fresh.", source: "story:st-2425-1" },
      ] },
    { id: "22.v.to", type: "vocabulary", fa: "تو", pin: "to", en: "you (informal)", notes: "ت-و",
      examples: [
        { fa: "علی: «مامان، تو چطوری؟»", pin: "Ali: \"Māmān, to chetori?\"", en: "Ali: \"Mom, how are you?\"", source: "story:st-22-1" },
        { fa: "مامان: «من خوبم، ممنون. تو چطوری؟»", pin: "Māmān: \"Man khoobam, mamnoon. To chetori?\"", en: "Mom: \"I'm fine, thanks. How are you?\"", source: "story:st-22-1" },
        { fa: "تو چطوری؟", pin: "to chetori?", en: "How are you? (informal)", source: "phrase:22" },
        { fa: "سعید تو یه مغازه کار می‌کنه و میترا تو یه آرایشگاه کار می‌کنه.", pin: "Saeed too ye maghāzeh kār mikoneh va Mitrā too ye ārāyeshgāh kār mikoneh.", en: "Saeed works at a shop and Mitra works at a hair salon.", source: "story:32" },
      ] },
    { id: "22.v.polo", type: "vocabulary", fa: "پُلُو", pin: "polo", en: "cooked rice", notes: "پ-ل-و",
      examples: [
        { fa: "پلو و گیلاس اینجا هست.", pin: "Polo o gilās injā hast.", en: "There's rice and cherries here.", source: "story:st-22-1" },
        { fa: "پلو خیلی خوشمزه هست!", pin: "Polo kheili khoshmazeh hast!", en: "The rice is really delicious!", source: "story:st-22-1" },
        { fa: "سبزی پلو با ماهی", pin: "sabzi polo bā māhi", en: "herb rice with fish (Nowruz dish)", source: "phrase:23" },
        { fa: "سیاوش شام درست می‌کند: فسنجون و پلو.", pin: "Siāvash shām dorost mikonad: fesenjoon va polo.", en: "Siavash is making dinner: fesenjoon and rice.", source: "story:st-34-2" },
      ] },
    { id: "22.v.do", type: "vocabulary", fa: "دو", pin: "do", en: "two", notes: "د-و",
      examples: [
        { fa: "من هر دو رو دوست دارم", pin: "man har do ro doost dāram", en: "I like both", source: "phrase:23" },
        { fa: "سارا سی و دو سالشه.", pin: "Sārā si-o do sālesh-eh.", en: "Sara is thirty-two.", source: "story:st-26-1" },
        { fa: "من دو بار در هفته می‌رم باشگاه", pin: "man do bār dar hafte miram bāshgāh", en: "I go to the gym twice a week", source: "phrase:30" },
        { fa: "ساعت دو، علی خونه هست.", pin: "Sāat-e do, Ali khooneh hast.", en: "At two, Ali is home.", source: "story:st-31-1" },
      ] },
    { id: "22.v.khod", type: "vocabulary", fa: "خود", pin: "khod", en: "self", notes: "خ-و-د" },
    { id: "22.v.khodkar", type: "vocabulary", fa: "خودکار", pin: "khodkār", en: "pen (ballpoint)", notes: "خود (self) + کار (work) = automatic",
      examples: [
        { fa: "این خودکار مال توئه؟", pin: "in khodkār māl-e to-e?", en: "Is this pen yours?", source: "phrase:29" },
        { fa: "علی می‌خنده و می‌گه: «مراقب خودکارت باش!»", pin: "Ali mikhandeh va migeh: \"Morāgheb-e khodkāret bāsh!\"", en: "Ali laughs and says: \"Look after your pen!\"", source: "story:st-29-1" },
        { fa: "کسی اینجا نیست، ولی یه خودکار و یه مداد اینجا هست.", pin: "Kasi injā nist, vali ye khodkār o ye medād injā hast.", en: "No one is here, but there's a pen and a pencil here.", source: "story:st-29-1" },
        { fa: "سارا می‌گه: «این خودکار مال کیه؟»", pin: "Sārā migeh: \"In khodkār māl-e ki-eh?\"", en: "Sara says: \"Whose pen is this, then?\"", source: "story:st-29-1" },
      ] },
    { id: "22.v.metro", type: "vocabulary", fa: "مترو", pin: "metro", en: "metro, subway", notes: "م-ت-ر-و" },
    { id: "22.v.gilas", type: "vocabulary", fa: "گیلاس", pin: "gilās", en: "cherry", notes: "گ-ی-ل-ا-س",
      examples: [
        { fa: "پلو و گیلاس اینجا هست.", pin: "Polo o gilās injā hast.", en: "There's rice and cherries here.", source: "story:st-22-1" },
        { fa: "علی سیب و گیلاس می‌خره.", pin: "Ali sib o gilās mikhareh.", en: "Ali buys apples and cherries.", source: "story:st-31-1" },
      ] },
    { id: "22.v.gorbeh", type: "vocabulary", fa: "گُربه", pin: "gorbeh", en: "cat", notes: "گ-ر-ب-ه",
      examples: [
        { fa: "گربه‌ام هر روز خودش رو تمیز می‌کنه", pin: "gorbe-am har rooz khodesh ro tamiz mikoneh", en: "My cat cleans itself every day", source: "phrase:29" },
        { fa: "ما سال پیش گربه نداشتیم ولی الان دو تا گربه داریم", pin: "mā sāl-e pish gorbeh nadāshtim vali alān do tā gorbeh dārim", en: "Last year we didn't have a cat but now we have two cats", source: "phrase:32" },
        { fa: "گربه زیر صندلی بود.", pin: "Gorbeh zir-e sandali bood.", en: "The cat was under the chair.", source: "phrase:35" },
      ] },
    { id: "22.v.sag", type: "vocabulary", fa: "سَگ", pin: "sag", en: "dog", notes: "س-گ",
      examples: [
        { fa: "من هیچ‌وقت به سگم بیسکویت نمیدم", pin: "man hich-vaght be sagam biscuit nemidam", en: "I never give my dog biscuits", source: "phrase:24-25" },
        { fa: "سگ داشتن خیلی سخته ولی شیرین هم هست", pin: "sag dāshtan kheili sakht-e vali shirin ham hast", en: "Having a dog is hard, but it's also sweet", source: "phrase:27" },
        { fa: "من سگ‌ها رو دوست نداشتم ولی الان سگ‌ها رو دوست دارم", pin: "man sag-hā ro doost nadāshtam vali alān sag-hā ro doost dāram", en: "I didn't like dogs but now I like dogs", source: "phrase:32" },
        { fa: "سگ از اسب کوچیک‌تر هست.", pin: "Sag az asb koochiktar hast.", en: "A dog is smaller than a horse.", source: "phrase:34" },
      ] },
    { id: "22.v.zendegi", type: "vocabulary", fa: "زندگی", pin: "zendegi", en: "life", notes: "ز-ن-د-گ-ی",
      examples: [
        { fa: "زندگی خوبه!", pin: "Zendegi khoob-eh!", en: "Life is good!", source: "story:st-22-1" },
        { fa: "ما در شهر یزد زندگی میکنیم", pin: "mā dar shahr-e Yazd zendegi mikonim", en: "We live in the city of Yazd", source: "phrase:24-25" },
        { fa: "زندگی کردن در ایران الان خیلی سخته", pin: "zendegi kardan dar Irān alān kheili sakht-e", en: "Living in Iran is very hard right now", source: "phrase:27" },
        { fa: "ما با همدیگه زندگی می‌کنیم", pin: "mā bā hamdige zendegi mikonim", en: "We live together", source: "phrase:28" },
      ] },
    { id: "22.v.gav", type: "vocabulary", fa: "گاو", pin: "gāv", en: "cow", notes: "گ-ا-و" },
    { id: "22.v.in", type: "vocabulary", fa: "این", pin: "in", en: "this", notes: "ا-ی-ن",
      examples: [
        { fa: "این علی هست.", pin: "In Ali hast.", en: "This is Ali.", source: "story:st-22-1" },
        { fa: "این رو بخون", pin: "in ro bekhoon", en: "Read this!", source: "phrase:24-25" },
        { fa: "تو این رو میدونی؟", pin: "to in ro midooni?", en: "Do you know this?", source: "phrase:26" },
        { fa: "من غمگینم چون هوا این هفته ابریه", pin: "man ghamginam chon havā in hafte abri-e", en: "I'm sad because the weather is cloudy this week", source: "phrase:27" },
      ] },
    { id: "22.v.an-oon", type: "vocabulary", fa: "آن / اون", pin: "ān / oon", en: "that", notes: "ا-ی-ن (formal) / ا-و-ن (colloquial)",
      examples: [
        { fa: "اون گوشت و ماهی نمی‌خوره.", pin: "Oon goosht o māhi nemikhoreh.", en: "She doesn't eat meat or fish.", source: "story:st-23-1" },
        { fa: "این کیف مال اونه", pin: "in kif māl-e oon-e", en: "This bag is hers/his", source: "phrase:29" },
        { fa: "به اون بگو", pin: "be oon begoo", en: "Tell her/him!", source: "phrase:24-25" },
        { fa: "تو میدونی اون کجاست؟", pin: "to midooni oon kojāst?", en: "Do you know where he/she is?", source: "phrase:26" },
      ] },
    { id: "22.v.inja", type: "vocabulary", fa: "اینجا", pin: "injā", en: "here", notes: "این (this) + جا (place)",
      examples: [
        { fa: "امروز مامان و بابای علی اینجا هستن.", pin: "Emrooz māmān o bābā-ye Ali injā hastan.", en: "Today Ali's mom and dad are here.", source: "story:st-22-1" },
        { fa: "پلو و گیلاس اینجا هست.", pin: "Polo o gilās injā hast.", en: "There's rice and cherries here.", source: "story:st-22-1" },
        { fa: "من اینجا راحت نیستم", pin: "man injā rāhat nistam", en: "I'm not comfortable here", source: "phrase:27" },
        { fa: "امروز سارا و علی اینجا غذا می‌خورن.", pin: "Emrooz Sārā o Ali injā ghazā mikhoran.", en: "Today Sara and Ali are eating here.", source: "story:st-23-1" },
      ] },
    { id: "22.v.anja", type: "vocabulary", fa: "آنجا", pin: "ānjā", en: "there", notes: "آن (that) + جا (place)" },
    { id: "22.v.chetor", type: "vocabulary", fa: "چطور", pin: "chetor", en: "how", notes: "چ-ط-و-ر",
      examples: [
        { fa: "مامان و بابا چطورند؟", pin: "māmān o bābā chetorand?", en: "How are mom and dad?", source: "phrase:22" },
        { fa: "علی: «مامان، تو چطوری؟»", pin: "Ali: \"Māmān, to chetori?\"", en: "Ali: \"Mom, how are you?\"", source: "story:st-22-1" },
        { fa: "علی: «من خیلی خوبم! مامان‌بزرگ و بابابزرگ چطورن؟»", pin: "Ali: \"Man kheili khoobam! Māmānbozorg o bābābozorg chetoran?\"", en: "Ali: \"I'm really well! How are Grandma and Grandpa?\"", source: "story:st-22-1" },
        { fa: "شما چطورید؟", pin: "shomā chetorid?", en: "How are you? (formal)", source: "phrase:22" },
      ] },
    { id: "22.v.maman", type: "vocabulary", fa: "مامان", pin: "māmān", en: "mom", notes: "م-ا-م-ا-ن",
      examples: [
        { fa: "مامان و بابا چطورند؟", pin: "māmān o bābā chetorand?", en: "How are mom and dad?", source: "phrase:22" },
        { fa: "امروز مامان و بابای علی اینجا هستن.", pin: "Emrooz māmān o bābā-ye Ali injā hastan.", en: "Today Ali's mom and dad are here.", source: "story:st-22-1" },
        { fa: "علی: «مامان، تو چطوری؟»", pin: "Ali: \"Māmān, to chetori?\"", en: "Ali: \"Mom, how are you?\"", source: "story:st-22-1" },
        { fa: "مامان: «من خوبم، ممنون. تو چطوری؟»", pin: "Māmān: \"Man khoobam, mamnoon. To chetori?\"", en: "Mom: \"I'm fine, thanks. How are you?\"", source: "story:st-22-1" },
      ] },
    { id: "22.v.baba", type: "vocabulary", fa: "بابا", pin: "bābā", en: "dad", notes: "ب-ا-ب-ا",
      examples: [
        { fa: "مامان و بابا چطورند؟", pin: "māmān o bābā chetorand?", en: "How are mom and dad?", source: "phrase:22" },
        { fa: "امروز مامان و بابای علی اینجا هستن.", pin: "Emrooz māmān o bābā-ye Ali injā hastan.", en: "Today Ali's mom and dad are here.", source: "story:st-22-1" },
        { fa: "امروز علی و باباش ورزش می‌کنن.", pin: "Emrooz Ali o bābāsh varzesh mikonan.", en: "Today Ali and his dad are exercising.", source: "story:st-22-1" },
        { fa: "بابام امسال ماشینش رو می‌فروشه", pin: "bābām emsāl māshinesh ro miforousheh", en: "My dad is selling his car this year", source: "phrase:31" },
      ] },
    { id: "22.v.mamanbozorg", type: "vocabulary", fa: "مامان‌بزرگ", pin: "māmānbozorg", en: "grandmother", notes: "مامان + بزرگ (big)",
      examples: [
        { fa: "علی: «من خیلی خوبم! مامان‌بزرگ و بابابزرگ چطورن؟»", pin: "Ali: \"Man kheili khoobam! Māmānbozorg o bābābozorg chetoran?\"", en: "Ali: \"I'm really well! How are Grandma and Grandpa?\"", source: "story:st-22-1" },
        { fa: "مامان‌بزرگش ترشی درست میکنه", pin: "māmān-bozorgesh torshi dorost mikoneh", en: "His/her grandma makes pickles", source: "phrase:24-25" },
        { fa: "مامان‌بزرگ سارا هشتاد و پنج سالشه.", pin: "Māmānbozorg-e Sārā hashtād-o panj sālesh-eh.", en: "Sara's grandma is eighty-five.", source: "story:st-30-2" },
        { fa: "سارا ماهی سه بار مامان‌بزرگش رو می‌بینه.", pin: "Sārā māhi seh bār māmānbozorgesh ro mibineh.", en: "Sara sees her grandma three times a month.", source: "story:st-30-2" },
      ] },
    { id: "22.v.bababozorg", type: "vocabulary", fa: "بابابزرگ", pin: "bābābozorg", en: "grandfather", notes: "بابا + بزرگ (big)",
      examples: [
        { fa: "علی: «من خیلی خوبم! مامان‌بزرگ و بابابزرگ چطورن؟»", pin: "Ali: \"Man kheili khoobam! Māmānbozorg o bābābozorg chetoran?\"", en: "Ali: \"I'm really well! How are Grandma and Grandpa?\"", source: "story:st-22-1" },
        { fa: "بابابزرگم فوت کرده", pin: "bābā-bozorgam foat kardeh", en: "My grandpa has passed away", source: "phrase:26" },
      ] },
    { id: "22.v.kheili", type: "vocabulary", fa: "خیلی", pin: "kheili", en: "very", notes: "خ-ی-ل-ی",
      examples: [
        { fa: "علی ایرانی هست و خیلی باهوشه.", pin: "Ali irāni hast va kheili bāhoosh-eh.", en: "Ali is Iranian and very smart.", source: "story:st-22-1" },
        { fa: "سارا خیلی خوب و باهوشه.", pin: "Sārā kheili khoob o bāhoosh-eh.", en: "Sara is very nice and smart.", source: "story:st-22-1" },
        { fa: "علی: «من خیلی خوبم! مامان‌بزرگ و بابابزرگ چطورن؟»", pin: "Ali: \"Man kheili khoobam! Māmānbozorg o bābābozorg chetoran?\"", en: "Ali: \"I'm really well! How are Grandma and Grandpa?\"", source: "story:st-22-1" },
        { fa: "پلو خیلی خوشمزه هست!", pin: "Polo kheili khoshmazeh hast!", en: "The rice is really delicious!", source: "story:st-22-1" },
      ] },
    { id: "22.v.mamnoon", type: "vocabulary", fa: "ممنون", pin: "mamnoon", en: "thank you", notes: "م-م-ن-و-ن",
      examples: [
        { fa: "مامان: «من خوبم، ممنون. تو چطوری؟»", pin: "Māmān: \"Man khoobam, mamnoon. To chetori?\"", en: "Mom: \"I'm fine, thanks. How are you?\"", source: "story:st-22-1" },
        { fa: "خیلی ممنون", pin: "kheili mamnoon", en: "thank you very much", source: "phrase:22" },
        { fa: "سارا: «نه، ممنون. من مشروب نمی‌خورم. من چای سبز می‌خورم.»", pin: "Sārā: \"Na, mamnoon. Man mashroob nemikhoram. Man chāy-e sabz mikhoram.\"", en: "Sara: \"No, thanks. I don't drink alcohol. I'll have green tea.\"", source: "story:st-23-1" },
        { fa: "من به مریم می‌گم: «خیلی ممنون! من عاشق این رستوران هستم!»", pin: "Man be Maryam migam: \"Kheili mamnoon! Man āshegh-e in restorān hastam!\"", en: "I say to Maryam: \"Thank you so much! I love this restaurant!\"", source: "story:st-2425-1" },
      ] },
    { id: "22.v.bad", type: "vocabulary", fa: "بد", pin: "bad", en: "bad", notes: "ب-د",
      examples: [
        { fa: "مامان: «اونا خوبن. بد نیستن.»", pin: "Māmān: \"Oonā khooban. Bad nistan.\"", en: "Mom: \"They're well. Not bad.\"", source: "story:st-22-1" },
        { fa: "بد نیستند", pin: "bad nistand", en: "they're not bad", source: "phrase:22" },
      ] },
    { id: "22.v.irani", type: "vocabulary", fa: "ایرانی", pin: "irāni", en: "Iranian", notes: "ایران + ی",
      examples: [
        { fa: "علی ایرانی هست و خیلی باهوشه.", pin: "Ali irāni hast va kheili bāhoosh-eh.", en: "Ali is Iranian and very smart.", source: "story:st-22-1" },
        { fa: "فسنجون خوشمزه‌ترین غذای ایرانی هست.", pin: "Fesenjoon khoshmazzetarin ghazā-ye Irāni hast.", en: "Fesenjoon is the tastiest Iranian food.", source: "phrase:34" },
        { fa: "سارا می‌گه: «خوشمزه‌ترین غذای ایرانی فسنجونه.»", pin: "Sārā migeh: \"Khoshmazetarin ghazā-ye irāni fesenjoon-eh.\"", en: "Sara says: \"The tastiest Iranian food is fesenjoon.\"", source: "story:st-34-1" },
      ] },
    { id: "22.v.bahoosh", type: "vocabulary", fa: "باهوش", pin: "bāhoosh", en: "smart", notes: "با (with) + هوش (intelligence)",
      examples: [
        { fa: "علی ایرانی هست و خیلی باهوشه.", pin: "Ali irāni hast va kheili bāhoosh-eh.", en: "Ali is Iranian and very smart.", source: "story:st-22-1" },
        { fa: "سارا خیلی خوب و باهوشه.", pin: "Sārā kheili khoob o bāhoosh-eh.", en: "Sara is very nice and smart.", source: "story:st-22-1" },
        { fa: "اون واقعاً باهوشه", pin: "oon vāghean bāhoosh-e", en: "He/she is really smart", source: "phrase:32" },
        { fa: "رضا خیلی باهوشه، ولی ساعت نداره.", pin: "Rezā kheili bāhoosh-eh, vali sāat nadāreh.", en: "Reza is very smart, but he doesn't have a watch.", source: "story:st-26-1" },
      ] },
    // Grammar
    { id: "22.g.man-hastam", type: "grammar", fa: "من هستم", pin: "man hastam", en: "I am", notes: "هستم = am (1st person singular)" },
    { id: "22.g.to-hasti", type: "grammar", fa: "تو هستی", pin: "to hasti", en: "you are (informal)", notes: "هستی = are (2nd person singular)" },
    { id: "22.g.oo-hast", type: "grammar", fa: "او هست", pin: "oo hast", en: "he/she is", notes: "هست = is (3rd person singular)" },
    { id: "22.g.ma-hastim", type: "grammar", fa: "ما هستیم", pin: "mā hastim", en: "we are", notes: "هستیم = are (1st person plural)" },
    { id: "22.g.shoma-hastid", type: "grammar", fa: "شما هستید", pin: "shomā hastid", en: "you are (formal/plural)", notes: "هستید = are (2nd person plural)" },
    { id: "22.g.anha-hastand", type: "grammar", fa: "آنها هستند", pin: "ānhā hastand", en: "they are", notes: "هستند = are (3rd person plural)" },
    { id: "22.g.khoobam", type: "grammar", fa: "خوبم", pin: "khoobam", en: "I am good", notes: "خوب + ـَم (I am)" },
    { id: "22.g.khoobi", type: "grammar", fa: "خوبی", pin: "khoobi", en: "you are good", notes: "خوب + ـی (you are)" },
    { id: "22.g.khoobeh", type: "grammar", fa: "خوبه", pin: "khoobeh", en: "he/she is good", notes: "خوب + ـه (he/she is)" },
    { id: "22.g.khoobim", type: "grammar", fa: "خوبیم", pin: "khoobim", en: "we are good", notes: "خوب + ـیم (we are)" },
    { id: "22.g.khoobid", type: "grammar", fa: "خوبید", pin: "khoobid", en: "you are good (pl)", notes: "خوب + ـید (you are)" },
    { id: "22.g.khooband", type: "grammar", fa: "خوبند", pin: "khooband", en: "they are good", notes: "خوب + ـند (they are)" },
    // Phrases
    { id: "22.p.to-chetori", type: "phrases", fa: "تو چطوری؟", pin: "to chetori?", en: "How are you? (informal)", notes: "تو (you) + چطوری (how)" },
    { id: "22.p.shoma-chetorid", type: "phrases", fa: "شما چطورید؟", pin: "shomā chetorid?", en: "How are you? (formal)", notes: "شما (you formal) + چطورید (how are)" },
    { id: "22.p.maman-o-baba-chetorand", type: "phrases", fa: "مامان و بابا چطورند؟", pin: "māmān o bābā chetorand?", en: "How are mom and dad?", notes: "چطورند = how are they" },
    { id: "22.p.kheili-mamnoon", type: "phrases", fa: "خیلی ممنون", pin: "kheili mamnoon", en: "thank you very much", notes: "خیلی (very) + ممنون (thanks)" },
    { id: "22.p.bad-nistand", type: "phrases", fa: "بد نیستند", pin: "bad nistand", en: "they're not bad", notes: "بد (bad) + نیستند (are not)" },
  ],
});
