// Session 23.
// Item ids are permanent. Never change or reuse one; add new items with new ids.
F.lesson({
  id: "23",
  label: "Session 23",
  title: "خوش compounds, food and drink",
  notes: "ALEX-SESSION-23_formatted.md",
  items: [
    // Vocabulary
    { id: "23.v.khoshtip", type: "vocabulary", fa: "خوشتیپ", pin: "khoshtip", en: "good-looking (men)", notes: "خوش (pleasant) + تیپ (type/look)" },
    { id: "23.v.khoshgel", type: "vocabulary", fa: "خوشگل", pin: "khoshgel", en: "beautiful", notes: "خوش (pleasant) + گل (flower)",
      examples: [
        { fa: "این کفش خوشگل‌تره.", pin: "In kafsh khoshgeltar-eh.", en: "This shoe is prettier.", source: "phrase:34" },
      ] },
    { id: "23.v.khoshmaze", type: "vocabulary", fa: "خوشمزه", pin: "khoshmaze", en: "delicious", notes: "خوش (pleasant) + مزه (taste)",
      examples: [
        { fa: "غذا خیلی خوشمزه هست.", pin: "Ghazā kheili khoshmazeh hast.", en: "The food is very tasty.", source: "story:st-23-1" },
        { fa: "فسنجون خوشمزه‌ترین غذای ایرانی هست.", pin: "Fesenjoon khoshmazzetarin ghazā-ye Irāni hast.", en: "Fesenjoon is the tastiest Iranian food.", source: "phrase:34" },
        { fa: "علی می‌گه: «ولی غذای تهران خوشمزه‌تره!»", pin: "Ali migeh: \"Vali ghazā-ye Tehrān khoshmazetar-eh!\"", en: "Ali says: \"But the food in Tehran is tastier!\"", source: "story:st-34-1" },
        { fa: "سارا می‌گه: «خوشمزه‌ترین غذای ایرانی فسنجونه.»", pin: "Sārā migeh: \"Khoshmazetarin ghazā-ye irāni fesenjoon-eh.\"", en: "Sara says: \"The tastiest Iranian food is fesenjoon.\"", source: "story:st-34-1" },
      ] },
    { id: "23.v.khorosht", type: "vocabulary", fa: "خورشت", pin: "khorosht", en: "stew", notes: "خ-و-ر-ش-ت",
      examples: [
        { fa: "علی گوشت و خورشت رو خیلی دوست داره.", pin: "Ali goosht o khorosht ro kheili doost dāreh.", en: "Ali really loves meat and stew.", source: "story:st-23-1" },
        { fa: "علی خورشت و پلو می‌خوره.", pin: "Ali khorosht o polo mikhoreh.", en: "Ali has stew and rice.", source: "story:st-23-1" },
        { fa: "خورشت بادمجون خورشت مورد علاقم هست", pin: "khorosht-e bādemjoon khorosht-e mored-e alāgham hast", en: "Aubergine stew is my favourite stew", source: "phrase:24-25" },
        { fa: "اون معمولاً خورشت بادمجان درست می‌کنه.", pin: "Oon ma'moolan khorosht-e bādemjān dorost mikoneh.", en: "She usually makes aubergine stew.", source: "story:st-2425-1" },
      ] },
    { id: "23.v.khoshbakht", type: "vocabulary", fa: "خوشبخت", pin: "khoshbakht", en: "fortunate, lucky", notes: "خوش (pleasant) + بخت (fortune)" },
    { id: "23.v.chay", type: "vocabulary", fa: "چای", pin: "chāy", en: "tea", notes: "چ-ا-ی",
      examples: [
        { fa: "سارا: «نه، ممنون. من مشروب نمی‌خورم. من چای سبز می‌خورم.»", pin: "Sārā: \"Na, mamnoon. Man mashroob nemikhoram. Man chāy-e sabz mikhoram.\"", en: "Sara: \"No, thanks. I don't drink alcohol. I'll have green tea.\"", source: "story:st-23-1" },
        { fa: "کی چای می‌خواد؟", pin: "ki chāy mikhād?", en: "Who wants tea?", source: "phrase:29" },
        { fa: "حَلیم، نانِ داغ و چای.", pin: "Halim, nān-e dāgh va chāy.", en: "Halim, hot bread and tea.", source: "story:34" },
        { fa: "بعد از غذا، ما دسر و چای می‌خوریم.", pin: "Ba'd az ghazā, mā deser o chāy mikhorim.", en: "After the meal, we have dessert and tea.", source: "story:st-2425-1" },
      ] },
    { id: "23.v.chatr", type: "vocabulary", fa: "چتر", pin: "chatr", en: "umbrella", notes: "چ-ت-ر" },
    { id: "23.v.pich", type: "vocabulary", fa: "پیچ", pin: "pich", en: "screw, turn", notes: "پ-ی-چ" },
    { id: "23.v.changal", type: "vocabulary", fa: "چنگال", pin: "changāl", en: "fork, claw", notes: "چ-ن-گ-ا-ل" },
    { id: "23.v.bacheh", type: "vocabulary", fa: "بچه", pin: "bacheh", en: "child, kid", notes: "ب-چ-ه",
      examples: [
        { fa: "اونها زن و شوهرن و سه تا بچه دارن.", pin: "oonhā zan-o shohar-an va se tā bache dāran.", en: "They are husband and wife and have three children.", source: "story:32" },
        { fa: "اون بچه‌ش رو کتک می‌زنه", pin: "oon bache-sh ro kotak mizaneh", en: "He/she hits their child", source: "phrase:33" },
        { fa: "بچّه‌ها بیدار هستند و با هم بازی می‌کنند.", pin: "Bachcheh hā bidār hastand va bā ham bāzi mikonand.", en: "The children are awake and playing together.", source: "story:st-34-2" },
        { fa: "بچه خیلی بی‌قرار هست.", pin: "Bacheh kheili bigharār hast.", en: "The kid is very fidgety.", source: "phrase:35" },
      ] },
    { id: "23.v.choopan", type: "vocabulary", fa: "چوپان", pin: "choopān", en: "shepherd", notes: "چ-و-پ-ا-ن" },
    { id: "23.v.goosht", type: "vocabulary", fa: "گوشت", pin: "goosht", en: "meat", notes: "گ-و-ش-ت",
      examples: [
        { fa: "من گوشت می‌خورم", pin: "man goosht mikhoram", en: "I eat meat", source: "phrase:23" },
        { fa: "اون گوشت و ماهی نمی‌خوره.", pin: "Oon goosht o māhi nemikhoreh.", en: "She doesn't eat meat or fish.", source: "story:st-23-1" },
        { fa: "علی گوشت و خورشت رو خیلی دوست داره.", pin: "Ali goosht o khorosht ro kheili doost dāreh.", en: "Ali really loves meat and stew.", source: "story:st-23-1" },
      ] },
    { id: "23.v.sabzijat", type: "vocabulary", fa: "سبزیجات", pin: "sabzijāt", en: "vegetables", notes: "سبزی (herb) + جات (plural)",
      examples: [
        { fa: "سارا سبزیجات و میوه رو خیلی دوست داره.", pin: "Sārā sabzijāt o miveh ro kheili doost dāreh.", en: "Sara really loves vegetables and fruit.", source: "story:st-23-1" },
      ] },
    { id: "23.v.sabz", type: "vocabulary", fa: "سبز", pin: "sabz", en: "green", notes: "س-ب-ز",
      examples: [
        { fa: "سارا: «نه، ممنون. من مشروب نمی‌خورم. من چای سبز می‌خورم.»", pin: "Sārā: \"Na, mamnoon. Man mashroob nemikhoram. Man chāy-e sabz mikhoram.\"", en: "Sara: \"No, thanks. I don't drink alcohol. I'll have green tea.\"", source: "story:st-23-1" },
      ] },
    { id: "23.v.sabzi", type: "vocabulary", fa: "سبزی", pin: "sabzi", en: "herb", notes: "س-ب-ز-ی",
      examples: [
        { fa: "سبزی پلو با ماهی", pin: "sabzi polo bā māhi", en: "herb rice with fish (Nowruz dish)", source: "phrase:23" },
        { fa: "سارا سبزی پلو و ماست می‌خوره.", pin: "Sārā sabzi polo o māst mikhoreh.", en: "Sara has herb rice and yogurt.", source: "story:st-23-1" },
      ] },
    { id: "23.v.mast", type: "vocabulary", fa: "ماست", pin: "māst", en: "yogurt", notes: "م-ا-س-ت",
      examples: [
        { fa: "سارا سبزی پلو و ماست می‌خوره.", pin: "Sārā sabzi polo o māst mikhoreh.", en: "Sara has herb rice and yogurt.", source: "story:st-23-1" },
        { fa: "اون همسایه‌ی ماست", pin: "oon hamsāye-ye māst", en: "He/she is our neighbour", source: "phrase:32" },
      ] },
    { id: "23.v.mahi", type: "vocabulary", fa: "ماهی", pin: "māhi", en: "fish", notes: "م-ا-ه-ی",
      examples: [
        { fa: "من ماهی نمی‌خورم", pin: "man māhi nemikhoram", en: "I don't eat fish", source: "phrase:23" },
        { fa: "اون گوشت و ماهی نمی‌خوره.", pin: "Oon goosht o māhi nemikhoreh.", en: "She doesn't eat meat or fish.", source: "story:st-23-1" },
        { fa: "سبزی پلو با ماهی", pin: "sabzi polo bā māhi", en: "herb rice with fish (Nowruz dish)", source: "phrase:23" },
        { fa: "من ماهی سه بار مامانم رو می‌بینم", pin: "man māhi seh bār māmānam ro mibinam", en: "I see my mom three times a month", source: "phrase:30" },
      ] },
    { id: "23.v.asal", type: "vocabulary", fa: "عسل", pin: "asal", en: "honey", notes: "ع-س-ل" },
    { id: "23.v.darya", type: "vocabulary", fa: "دریا", pin: "daryā", en: "sea", notes: "د-ر-ی-ا" },
    { id: "23.v.ghaza-ye-daryayi", type: "vocabulary", fa: "غذای دریایی", pin: "ghazā-ye daryāyi", en: "seafood", notes: "غذا (food) + دریایی (of sea)" },
    { id: "23.v.giah", type: "vocabulary", fa: "گیاه", pin: "giāh", en: "plant", notes: "گ-ی-ا-ه" },
    { id: "23.v.ghaza-ye-giahi", type: "vocabulary", fa: "غذای گیاهی", pin: "ghazā-ye giāhi", en: "vegetarian food", notes: "غذا (food) + گیاهی (plant-based)" },
    { id: "23.v.giah-khar", type: "vocabulary", fa: "گیاه‌خوار", pin: "giāh-khār", en: "vegetarian (person)", notes: "گیاه (plant) + خوار (eater)",
      examples: [
        { fa: "دوستش، علی، گیاه‌خوار نیست.", pin: "Doostesh, Ali, giāh-khār nist.", en: "Her friend Ali isn't a vegetarian.", source: "story:st-23-1" },
        { fa: "سارا گیاه‌خواره.", pin: "Sārā giāh-khār-eh.", en: "Sara is a vegetarian.", source: "story:st-23-1" },
      ] },
    { id: "23.v.sharab", type: "vocabulary", fa: "شراب", pin: "sharāb", en: "wine", notes: "ش-ر-ا-ب",
      examples: [
        { fa: "علی: «سارا، تو شراب می‌خوری؟»", pin: "Ali: \"Sārā, to sharāb mikhori?\"", en: "Ali: \"Sara, will you have some wine?\"", source: "story:st-23-1" },
      ] },
    { id: "23.v.ghermez", type: "vocabulary", fa: "قرمز", pin: "ghermez", en: "red", notes: "ق-ر-م-ز" },
    { id: "23.v.sefid", type: "vocabulary", fa: "سفید", pin: "sefid", en: "white", notes: "س-ف-ی-د" },
    { id: "23.v.ab-jo", type: "vocabulary", fa: "آب جو", pin: "āb-jo", en: "beer", notes: "آب (water) + جو (barley)",
      examples: [
        { fa: "علی آب جو می‌خوره.", pin: "Ali āb-jo mikhoreh.", en: "Ali drinks beer.", source: "story:st-23-1" },
      ] },
    { id: "23.v.jo", type: "vocabulary", fa: "جو", pin: "jo", en: "barley", notes: "ج-و",
      examples: [
        { fa: "علی آب جو می‌خوره.", pin: "Ali āb-jo mikhoreh.", en: "Ali drinks beer.", source: "story:st-23-1" },
      ] },
    { id: "23.v.ab-miveh", type: "vocabulary", fa: "آب میوه", pin: "āb miveh", en: "juice", notes: "آب (water) + میوه (fruit)" },
    { id: "23.v.ab-sib", type: "vocabulary", fa: "آب سیب", pin: "āb sib", en: "apple juice", notes: "آب (water) + سیب (apple)" },
    { id: "23.v.sib", type: "vocabulary", fa: "سیب", pin: "sib", en: "apple", notes: "س-ی-ب",
      examples: [
        { fa: "میوه‌فروش می‌گه: «سلام آقا! سیب‌ها خیلی تازه هستن.»", pin: "Miveh-foroush migeh: \"Salām āghā! Sib hā kheili tāzeh hastan.\"", en: "The greengrocer says: \"Hello, sir! The apples are really fresh.\"", source: "story:st-31-1" },
        { fa: "من یه سیب می‌خوام", pin: "man ye sib mikhām", en: "I want an apple", source: "phrase:32" },
        { fa: "علی سیب و گیلاس می‌خره.", pin: "Ali sib o gilās mikhareh.", en: "Ali buys apples and cherries.", source: "story:st-31-1" },
      ] },
    { id: "23.v.dam-noosh", type: "vocabulary", fa: "دم‌نوش", pin: "dam-noosh", en: "herbal tea", notes: "د-م-ن-و-ش" },
    { id: "23.v.chay-e-sabz", type: "vocabulary", fa: "چای سبز", pin: "chāy-e sabz", en: "green tea", notes: "چای + سبز (green)",
      examples: [
        { fa: "سارا: «نه، ممنون. من مشروب نمی‌خورم. من چای سبز می‌خورم.»", pin: "Sārā: \"Na, mamnoon. Man mashroob nemikhoram. Man chāy-e sabz mikhoram.\"", en: "Sara: \"No, thanks. I don't drink alcohol. I'll have green tea.\"", source: "story:st-23-1" },
      ] },
    { id: "23.v.chay-e-siah", type: "vocabulary", fa: "چای سیاه", pin: "chāy-e siāh", en: "black tea", notes: "چای + سیاه (black)" },
    { id: "23.v.siah", type: "vocabulary", fa: "سیاه", pin: "siāh", en: "black", notes: "س-ی-ا-ه" },
    { id: "23.v.sharbat", type: "vocabulary", fa: "شربت", pin: "sharbat", en: "syrup drink", notes: "ش-ر-ب-ت" },
    { id: "23.v.nooshabeh", type: "vocabulary", fa: "نوشابه", pin: "nooshābeh", en: "soda", notes: "ن-و-ش-ا-ب-ه" },
    { id: "23.v.shekar", type: "vocabulary", fa: "شکر", pin: "shekar", en: "sugar", notes: "ش-ک-ر",
      examples: [
        { fa: "بدون شکر لطفاً", pin: "bedoon-e shekar lotfan", en: "without sugar please", source: "phrase:23" },
        { fa: "علی: «با شکر؟»", pin: "Ali: \"Bā shekar?\"", en: "Ali: \"With sugar?\"", source: "story:st-23-1" },
        { fa: "سارا: «نه، بدون شکر، لطفاً.»", pin: "Sārā: \"Na, bedoon-e shekar, lotfan.\"", en: "Sara: \"No, without sugar, please.\"", source: "story:st-23-1" },
      ] },
    { id: "23.v.ghand", type: "vocabulary", fa: "قند", pin: "ghand", en: "sugar cube", notes: "ق-ن-د" },
    { id: "23.v.shir", type: "vocabulary", fa: "شیر", pin: "shir", en: "lion / milk", notes: "ش-ی-ر",
      examples: [
        { fa: "ما دیگه شیر نداریم، لطفا شیر می‌خری؟", pin: "mā dige shir nadārim, lotfan shir mikhari?", en: "We're out of milk, will you buy milk please?", source: "phrase:31" },
        { fa: "سارا می‌گه: «علی، ما دیگه شیر نداریم! لطفاً شیر بخر!»", pin: "Sārā migeh: \"Ali, mā dige shir nadārim! Lotfan shir bekhar!\"", en: "Sara says: \"Ali, we're out of milk! Please buy some milk!\"", source: "story:st-31-1" },
        { fa: "شیر بخر", pin: "shir bekhar", en: "Buy some milk", source: "phrase:31" },
      ] },
    { id: "23.v.khorshid", type: "vocabulary", fa: "خورشید", pin: "khorshid", en: "sun", notes: "خ-و-ر-ش-ی-د" },
    { id: "23.v.parcham", type: "vocabulary", fa: "پرچم", pin: "parcham", en: "flag", notes: "پ-ر-چ-م" },
    { id: "23.v.mashroob", type: "vocabulary", fa: "مشروب", pin: "mashroob", en: "alcohol", notes: "م-ش-ر-و-ب",
      examples: [
        { fa: "سارا: «نه، ممنون. من مشروب نمی‌خورم. من چای سبز می‌خورم.»", pin: "Sārā: \"Na, mamnoon. Man mashroob nemikhoram. Man chāy-e sabz mikhoram.\"", en: "Sara: \"No, thanks. I don't drink alcohol. I'll have green tea.\"", source: "story:st-23-1" },
      ] },
    { id: "23.v.mast-2", type: "vocabulary", fa: "مست", pin: "mast", en: "drunk", notes: "م-س-ت",
      examples: [
        { fa: "من مست نیستم", pin: "man mast nistam", en: "I am not drunk", source: "phrase:23" },
        { fa: "اون مسته", pin: "oon masteh", en: "he/she is drunk", source: "phrase:23" },
      ] },
    { id: "23.v.masti", type: "vocabulary", fa: "مستی", pin: "masti", en: "drunkenness", notes: "م-س-ت-ی" },
    { id: "23.v.rah", type: "vocabulary", fa: "راه", pin: "rāh", en: "path, way", notes: "ر-ا-ه",
      examples: [
        { fa: "من از خونه تا سر کار راه می‌رم", pin: "man az khoone tā sar-e kār rāh miram", en: "I walk from home to work", source: "phrase:30" },
        { fa: "علی هر روز از خونه تا سر کار راه می‌ره.", pin: "Ali har rooz az khooneh tā sar-e kār rāh mireh.", en: "Every day Ali walks from home to work.", source: "story:st-30-1" },
        { fa: "هر روز صبح، علی تو راه یه راننده‌ی تاکسی رو می‌بینه.", pin: "Har rooz sobh, Ali too rāh ye rānande-ye tāksi ro mibineh.", en: "Every morning, Ali sees a taxi driver on the way.", source: "story:st-30-1" },
        { fa: "اون از ساعت نه تا ده صبح و از ساعت پنج تا شش بعد از ظهر راه می‌ره.", pin: "Oon az sāat-e noh tā dah-e sobh va az sāat-e panj tā shish-e ba'd az zohr rāh mireh.", en: "She walks from nine to ten in the morning and from five to six in the afternoon.", source: "story:st-30-2" },
      ] },
    { id: "23.v.jahan", type: "vocabulary", fa: "جهان", pin: "jahān", en: "world", notes: "ج-ه-ا-ن" },
    { id: "23.v.noor", type: "vocabulary", fa: "نور", pin: "noor", en: "light", notes: "ن-و-ر" },
    { id: "23.v.tariki", type: "vocabulary", fa: "تاریکی", pin: "tāriki", en: "darkness", notes: "تاریک (dark) + ی" },
    { id: "23.v.pirooz", type: "vocabulary", fa: "پیروز", pin: "pirooz", en: "victorious", notes: "پ-ی-ر-و-ز" },
    { id: "23.v.payan", type: "vocabulary", fa: "پایان", pin: "pāyān", en: "end", notes: "پ-ا-ی-ا-ن" },
    { id: "23.v.shab", type: "vocabulary", fa: "شب", pin: "shab", en: "night", notes: "ش-ب",
      examples: [
        { fa: "شب، سارا با شوهرش شام می‌خوره.", pin: "Shab, Sārā bā shoharesh shām mikhoreh.", en: "In the evening, Sara has dinner with her husband.", source: "story:st-26-1" },
        { fa: "من امروز از ساعت هفت صبح تا ساعت دو شب کار می‌کنم", pin: "man emrooz az sāat-e haft-e sobh tā sāat-e do-e shab kār mikonam", en: "I work from 7 AM to 2 AM today", source: "phrase:30" },
        { fa: "من ساعت ده شب می‌خوابم", pin: "man sāat-e dah-e shab mikhābam", en: "I go to bed at 10 PM", source: "phrase:32" },
        { fa: "شب، مامانم گفت: «به همه سلام برسون!»", pin: "Shab, māmānam goft: \"Be hameh salām beresoon!\"", en: "In the evening, my mom said: \"Say hello to everyone!\"", source: "story:st-33-1" },
      ] },
    // Grammar
    { id: "23.g.mikhoram", type: "grammar", fa: "می‌خورم", pin: "mikhoram", en: "I eat/drink", notes: "می + خور + م" },
    { id: "23.g.mikhori", type: "grammar", fa: "می‌خوری", pin: "mikhori", en: "you eat/drink", notes: "می + خور + ی" },
    { id: "23.g.mikhoreh", type: "grammar", fa: "می‌خوره", pin: "mikhoreh", en: "he/she eats/drinks", notes: "می + خور + ه" },
    { id: "23.g.mikhorim", type: "grammar", fa: "می‌خوریم", pin: "mikhorim", en: "we eat/drink", notes: "می + خور + یم" },
    { id: "23.g.mikhorid", type: "grammar", fa: "می‌خورید", pin: "mikhorid", en: "you eat/drink (formal)", notes: "می + خور + ید" },
    { id: "23.g.mikhorand", type: "grammar", fa: "می‌خورند", pin: "mikhorand", en: "they eat/drink", notes: "می + خور + ند" },
    { id: "23.g.nemikhoram", type: "grammar", fa: "نمی‌خورم", pin: "nemikhoram", en: "I don't eat/drink", notes: "نمی + خور + م" },
    { id: "23.g.nemikhori", type: "grammar", fa: "نمی‌خوری", pin: "nemikhori", en: "you don't eat/drink", notes: "نمی + خور + ی" },
    { id: "23.g.nemikhoreh", type: "grammar", fa: "نمی‌خوره", pin: "nemikhoreh", en: "he/she doesn't eat/drink", notes: "نمی + خور + ه" },
    { id: "23.g.nemikhorim", type: "grammar", fa: "نمی‌خوریم", pin: "nemikhorim", en: "we don't eat/drink", notes: "نمی + خور + یم" },
    { id: "23.g.nemikhorid", type: "grammar", fa: "نمی‌خورید", pin: "nemikhorid", en: "you don't eat/drink (formal)", notes: "نمی + خور + ید" },
    // Phrases
    { id: "23.p.man-goosht-mikhoram", type: "phrases", fa: "من گوشت می‌خورم", pin: "man goosht mikhoram", en: "I eat meat", notes: "Subject + Object + Verb" },
    { id: "23.p.man-mahi-nemikhoram", type: "phrases", fa: "من ماهی نمی‌خورم", pin: "man māhi nemikhoram", en: "I don't eat fish", notes: "Subject + Object + Negative Verb" },
    { id: "23.p.bedoon-e-shekar-lotfan", type: "phrases", fa: "بدون شکر لطفاً", pin: "bedoon-e shekar lotfan", en: "without sugar please", notes: "بدون (without) + شکر + لطفاً (please)" },
    { id: "23.p.noosh-e-jan", type: "phrases", fa: "نوش جان!", pin: "noosh-e jān!", en: "Enjoy your meal!", notes: "نوش (sweet) + جان (soul)" },
    { id: "23.p.be-salamati", type: "phrases", fa: "به سلامتی!", pin: "be salāmati!", en: "Cheers! (to health)", notes: "به (to) + سلامتی (health)" },
    { id: "23.p.har-do", type: "phrases", fa: "هر دو", pin: "har do", en: "both", notes: "هر (every) + دو (two)" },
    { id: "23.p.man-har-do-ro-doost-daram", type: "phrases", fa: "من هر دو رو دوست دارم", pin: "man har do ro doost dāram", en: "I like both", notes: "هر دو (both) + رو (object marker) + دوست دارم (I like)" },
    { id: "23.p.oon-masteh", type: "phrases", fa: "اون مسته", pin: "oon masteh", en: "he/she is drunk", notes: "اون (he/she) + مست (drunk) + ه (is)" },
    { id: "23.p.man-mast-nistam", type: "phrases", fa: "من مست نیستم", pin: "man mast nistam", en: "I am not drunk", notes: "من + مست + نیستم (am not)" },
    { id: "23.p.sabzi-polo-ba-mahi", type: "phrases", fa: "سبزی پلو با ماهی", pin: "sabzi polo bā māhi", en: "herb rice with fish (Nowruz dish)", notes: "سبزی + پلو + با (with) + ماهی" },
  ],
});
