// Session 23.
// Item ids are permanent. Never change or reuse one; add new items with new ids.
F.lesson({
  id: "23",
  label: "Session 23",
  title: "خوش compounds, food and drink",
  notes: "ALEX-SESSION-23_formatted.md",
  items: [
    // Vocabulary
    { id: "23.v.khoshtip", type: "vocabulary", fa: "خوشتیپ", pin: "khoshtip", en: "good-looking (men)", notes: "خوش (pleasant) + تیپ (type/look)" },
    { id: "23.v.khoshgel", type: "vocabulary", fa: "خوشگل", pin: "khoshgel", en: "beautiful", notes: "خوش (pleasant) + گل (flower)" },
    { id: "23.v.khoshmaze", type: "vocabulary", fa: "خوشمزه", pin: "khoshmaze", en: "delicious", notes: "خوش (pleasant) + مزه (taste)" },
    { id: "23.v.khorosht", type: "vocabulary", fa: "خورشت", pin: "khorosht", en: "stew", notes: "خ-و-ر-ش-ت" },
    { id: "23.v.khoshbakht", type: "vocabulary", fa: "خوشبخت", pin: "khoshbakht", en: "fortunate, lucky", notes: "خوش (pleasant) + بخت (fortune)" },
    { id: "23.v.chay", type: "vocabulary", fa: "چای", pin: "chāy", en: "tea", notes: "چ-ا-ی" },
    { id: "23.v.chatr", type: "vocabulary", fa: "چتر", pin: "chatr", en: "umbrella", notes: "چ-ت-ر" },
    { id: "23.v.pich", type: "vocabulary", fa: "پیچ", pin: "pich", en: "screw, turn", notes: "پ-ی-چ" },
    { id: "23.v.changal", type: "vocabulary", fa: "چنگال", pin: "changāl", en: "fork, claw", notes: "چ-ن-گ-ا-ل" },
    { id: "23.v.bacheh", type: "vocabulary", fa: "بچه", pin: "bacheh", en: "child, kid", notes: "ب-چ-ه" },
    { id: "23.v.choopan", type: "vocabulary", fa: "چوپان", pin: "choopān", en: "shepherd", notes: "چ-و-پ-ا-ن" },
    { id: "23.v.goosht", type: "vocabulary", fa: "گوشت", pin: "goosht", en: "meat", notes: "گ-و-ش-ت" },
    { id: "23.v.sabzijat", type: "vocabulary", fa: "سبزیجات", pin: "sabzijāt", en: "vegetables", notes: "سبزی (herb) + جات (plural)" },
    { id: "23.v.sabz", type: "vocabulary", fa: "سبز", pin: "sabz", en: "green", notes: "س-ب-ز" },
    { id: "23.v.sabzi", type: "vocabulary", fa: "سبزی", pin: "sabzi", en: "herb", notes: "س-ب-ز-ی" },
    { id: "23.v.mast", type: "vocabulary", fa: "ماست", pin: "māst", en: "yogurt", notes: "م-ا-س-ت" },
    { id: "23.v.mahi", type: "vocabulary", fa: "ماهی", pin: "māhi", en: "fish", notes: "م-ا-ه-ی" },
    { id: "23.v.asal", type: "vocabulary", fa: "عسل", pin: "asal", en: "honey", notes: "ع-س-ل" },
    { id: "23.v.darya", type: "vocabulary", fa: "دریا", pin: "daryā", en: "sea", notes: "د-ر-ی-ا" },
    { id: "23.v.ghaza-ye-daryayi", type: "vocabulary", fa: "غذای دریایی", pin: "ghazā-ye daryāyi", en: "seafood", notes: "غذا (food) + دریایی (of sea)" },
    { id: "23.v.giah", type: "vocabulary", fa: "گیاه", pin: "giāh", en: "plant", notes: "گ-ی-ا-ه" },
    { id: "23.v.ghaza-ye-giahi", type: "vocabulary", fa: "غذای گیاهی", pin: "ghazā-ye giāhi", en: "vegetarian food", notes: "غذا (food) + گیاهی (plant-based)" },
    { id: "23.v.giah-khar", type: "vocabulary", fa: "گیاه‌خوار", pin: "giāh-khār", en: "vegetarian (person)", notes: "گیاه (plant) + خوار (eater)" },
    { id: "23.v.sharab", type: "vocabulary", fa: "شراب", pin: "sharāb", en: "wine", notes: "ش-ر-ا-ب" },
    { id: "23.v.ghermez", type: "vocabulary", fa: "قرمز", pin: "ghermez", en: "red", notes: "ق-ر-م-ز" },
    { id: "23.v.sefid", type: "vocabulary", fa: "سفید", pin: "sefid", en: "white", notes: "س-ف-ی-د" },
    { id: "23.v.ab-jo", type: "vocabulary", fa: "آب جو", pin: "āb-jo", en: "beer", notes: "آب (water) + جو (barley)" },
    { id: "23.v.jo", type: "vocabulary", fa: "جو", pin: "jo", en: "barley", notes: "ج-و" },
    { id: "23.v.ab-miveh", type: "vocabulary", fa: "آب میوه", pin: "āb miveh", en: "juice", notes: "آب (water) + میوه (fruit)" },
    { id: "23.v.ab-sib", type: "vocabulary", fa: "آب سیب", pin: "āb sib", en: "apple juice", notes: "آب (water) + سیب (apple)" },
    { id: "23.v.sib", type: "vocabulary", fa: "سیب", pin: "sib", en: "apple", notes: "س-ی-ب" },
    { id: "23.v.dam-noosh", type: "vocabulary", fa: "دم‌نوش", pin: "dam-noosh", en: "herbal tea", notes: "د-م-ن-و-ش" },
    { id: "23.v.chay-e-sabz", type: "vocabulary", fa: "چای سبز", pin: "chāy-e sabz", en: "green tea", notes: "چای + سبز (green)" },
    { id: "23.v.chay-e-siah", type: "vocabulary", fa: "چای سیاه", pin: "chāy-e siāh", en: "black tea", notes: "چای + سیاه (black)" },
    { id: "23.v.siah", type: "vocabulary", fa: "سیاه", pin: "siāh", en: "black", notes: "س-ی-ا-ه" },
    { id: "23.v.sharbat", type: "vocabulary", fa: "شربت", pin: "sharbat", en: "syrup drink", notes: "ش-ر-ب-ت" },
    { id: "23.v.nooshabeh", type: "vocabulary", fa: "نوشابه", pin: "nooshābeh", en: "soda", notes: "ن-و-ش-ا-ب-ه" },
    { id: "23.v.shekar", type: "vocabulary", fa: "شکر", pin: "shekar", en: "sugar", notes: "ش-ک-ر" },
    { id: "23.v.ghand", type: "vocabulary", fa: "قند", pin: "ghand", en: "sugar cube", notes: "ق-ن-د" },
    { id: "23.v.shir", type: "vocabulary", fa: "شیر", pin: "shir", en: "lion / milk", notes: "ش-ی-ر" },
    { id: "23.v.khorshid", type: "vocabulary", fa: "خورشید", pin: "khorshid", en: "sun", notes: "خ-و-ر-ش-ی-د" },
    { id: "23.v.parcham", type: "vocabulary", fa: "پرچم", pin: "parcham", en: "flag", notes: "پ-ر-چ-م" },
    { id: "23.v.mashroob", type: "vocabulary", fa: "مشروب", pin: "mashroob", en: "alcohol", notes: "م-ش-ر-و-ب" },
    { id: "23.v.mast-2", type: "vocabulary", fa: "مست", pin: "mast", en: "drunk", notes: "م-س-ت" },
    { id: "23.v.masti", type: "vocabulary", fa: "مستی", pin: "masti", en: "drunkenness", notes: "م-س-ت-ی" },
    { id: "23.v.rah", type: "vocabulary", fa: "راه", pin: "rāh", en: "path, way", notes: "ر-ا-ه" },
    { id: "23.v.jahan", type: "vocabulary", fa: "جهان", pin: "jahān", en: "world", notes: "ج-ه-ا-ن" },
    { id: "23.v.noor", type: "vocabulary", fa: "نور", pin: "noor", en: "light", notes: "ن-و-ر" },
    { id: "23.v.tariki", type: "vocabulary", fa: "تاریکی", pin: "tāriki", en: "darkness", notes: "تاریک (dark) + ی" },
    { id: "23.v.pirooz", type: "vocabulary", fa: "پیروز", pin: "pirooz", en: "victorious", notes: "پ-ی-ر-و-ز" },
    { id: "23.v.payan", type: "vocabulary", fa: "پایان", pin: "pāyān", en: "end", notes: "پ-ا-ی-ا-ن" },
    { id: "23.v.shab", type: "vocabulary", fa: "شب", pin: "shab", en: "night", notes: "ش-ب" },
    // Grammar
    { id: "23.g.mikhoram", type: "grammar", fa: "می‌خورم", pin: "mikhoram", en: "I eat/drink", notes: "می + خور + م" },
    { id: "23.g.mikhori", type: "grammar", fa: "می‌خوری", pin: "mikhori", en: "you eat/drink", notes: "می + خور + ی" },
    { id: "23.g.mikhoreh", type: "grammar", fa: "می‌خوره", pin: "mikhoreh", en: "he/she eats/drinks", notes: "می + خور + ه" },
    { id: "23.g.mikhorim", type: "grammar", fa: "می‌خوریم", pin: "mikhorim", en: "we eat/drink", notes: "می + خور + یم" },
    { id: "23.g.mikhorid", type: "grammar", fa: "می‌خورید", pin: "mikhorid", en: "you eat/drink (formal)", notes: "می + خور + ید" },
    { id: "23.g.mikhorand", type: "grammar", fa: "می‌خورند", pin: "mikhorand", en: "they eat/drink", notes: "می + خور + ند" },
    { id: "23.g.nemikhoram", type: "grammar", fa: "نمی‌خورم", pin: "nemikhoram", en: "I don't eat/drink", notes: "نمی + خور + م" },
    { id: "23.g.nemikhori", type: "grammar", fa: "نمی‌خوری", pin: "nemikhori", en: "you don't eat/drink", notes: "نمی + خور + ی" },
    { id: "23.g.nemikhoreh", type: "grammar", fa: "نمی‌خوره", pin: "nemikhoreh", en: "he/she doesn't eat/drink", notes: "نمی + خور + ه" },
    { id: "23.g.nemikhorim", type: "grammar", fa: "نمی‌خوریم", pin: "nemikhorim", en: "we don't eat/drink", notes: "نمی + خور + یم" },
    { id: "23.g.nemikhorid", type: "grammar", fa: "نمی‌خورید", pin: "nemikhorid", en: "you don't eat/drink (formal)", notes: "نمی + خور + ید" },
    // Phrases
    { id: "23.p.man-goosht-mikhoram", type: "phrases", fa: "من گوشت می‌خورم", pin: "man goosht mikhoram", en: "I eat meat", notes: "Subject + Object + Verb" },
    { id: "23.p.man-mahi-nemikhoram", type: "phrases", fa: "من ماهی نمی‌خورم", pin: "man māhi nemikhoram", en: "I don't eat fish", notes: "Subject + Object + Negative Verb" },
    { id: "23.p.bedoon-e-shekar-lotfan", type: "phrases", fa: "بدون شکر لطفاً", pin: "bedoon-e shekar lotfan", en: "without sugar please", notes: "بدون (without) + شکر + لطفاً (please)" },
    { id: "23.p.noosh-e-jan", type: "phrases", fa: "نوش جان!", pin: "noosh-e jān!", en: "Enjoy your meal!", notes: "نوش (sweet) + جان (soul)" },
    { id: "23.p.be-salamati", type: "phrases", fa: "به سلامتی!", pin: "be salāmati!", en: "Cheers! (to health)", notes: "به (to) + سلامتی (health)" },
    { id: "23.p.har-do", type: "phrases", fa: "هر دو", pin: "har do", en: "both", notes: "هر (every) + دو (two)" },
    { id: "23.p.man-har-do-ro-doost-daram", type: "phrases", fa: "من هر دو رو دوست دارم", pin: "man har do ro doost dāram", en: "I like both", notes: "هر دو (both) + رو (object marker) + دوست دارم (I like)" },
    { id: "23.p.oon-masteh", type: "phrases", fa: "اون مسته", pin: "oon masteh", en: "he/she is drunk", notes: "اون (he/she) + مست (drunk) + ه (is)" },
    { id: "23.p.man-mast-nistam", type: "phrases", fa: "من مست نیستم", pin: "man mast nistam", en: "I am not drunk", notes: "من + مست + نیستم (am not)" },
    { id: "23.p.sabzi-polo-ba-mahi", type: "phrases", fa: "سبزی پلو با ماهی", pin: "sabzi polo bā māhi", en: "herb rice with fish (Nowruz dish)", notes: "سبزی + پلو + با (with) + ماهی" },
  ],
});
