// Sessions 24-25.
// Item ids are permanent. Never change or reuse one; add new items with new ids.
F.lesson({
  id: "24-25",
  label: "Sessions 24-25",
  title: "Imperatives, reading, time and love",
  notes: ["ALEX-SESSION-24_formatted.md", "ALEX-SESSION-25_formatted.md"],
  items: [
    // Vocabulary
    { id: "24-25.v.beresoon", type: "vocabulary", fa: "برسون", pin: "beresoon", en: "send! deliver! (imperative)", notes: "imperative of رسوندن (resoondan)" },
    { id: "24-25.v.begoo", type: "vocabulary", fa: "بگو", pin: "begoo", en: "tell! say! (imperative)", notes: "imperative of گفتن (goftan)" },
    { id: "24-25.v.bedeh", type: "vocabulary", fa: "بده", pin: "bedeh", en: "give! (imperative)", notes: "imperative of دادن (dādan)" },
    { id: "24-25.v.bokon", type: "vocabulary", fa: "بکن", pin: "bokon", en: "do! (imperative)", notes: "imperative of کردن (kardan)" },
    { id: "24-25.v.nakon", type: "vocabulary", fa: "نکن", pin: "nakon", en: "don't! (negative imperative)", notes: "نَ + کن" },
    { id: "24-25.v.bekhoon", type: "vocabulary", fa: "بخون", pin: "bekhoon", en: "read! (imperative)", notes: "imperative of خوندن (khoondan)" },
    { id: "24-25.v.bokhor", type: "vocabulary", fa: "بخور", pin: "bokhor", en: "eat! (imperative)", notes: "imperative of خوردن (khordan)" },
    { id: "24-25.v.boro", type: "vocabulary", fa: "برو", pin: "boro", en: "go! (imperative)", notes: "imperative of رفتن (raftan)" },
    { id: "24-25.v.beshin", type: "vocabulary", fa: "بشین", pin: "beshin", en: "sit! sit down! (imperative)", notes: "imperative of نشستن (neshastan)" },
    { id: "24-25.v.befarmayid", type: "vocabulary", fa: "بفرمایید", pin: "befarmāyid", en: "please (polite invitation)", notes: "formal polite imperative" },
    { id: "24-25.v.khandan-khoondan", type: "vocabulary", fa: "خواندن", pin: "khāndan / khoondan", en: "to read", notes: "خ-و-ا-ن-د-ن" },
    { id: "24-25.v.dars-khoondan", type: "vocabulary", fa: "درس خوندن", pin: "dars khoondan", en: "to study", notes: "درس (lesson) + خوندن (to read)" },
    { id: "24-25.v.avaz-khandan-khoondan", type: "vocabulary", fa: "آواز خواندن", pin: "āvāz khāndan / khoondan", en: "to sing", notes: "آواز (song/singing) + خواندن" },
    { id: "24-25.v.khanandeh", type: "vocabulary", fa: "خواننده", pin: "khānandeh", en: "singer", notes: "خواندن + ـنده (agent suffix)" },
    { id: "24-25.v.ketabkhoone", type: "vocabulary", fa: "کتابخونه", pin: "ketābkhoone", en: "library", notes: "کتاب (book) + خونه (house)" },
    { id: "24-25.v.sholugh", type: "vocabulary", fa: "شلوغ", pin: "sholugh", en: "busy / crowded", notes: "ش-ل-و-غ" },
    { id: "24-25.v.vaght", type: "vocabulary", fa: "وقت", pin: "vaght", en: "time", notes: "و-ق-ت" },
    { id: "24-25.v.hamishe", type: "vocabulary", fa: "همیشه", pin: "hamishe", en: "always", notes: "ه-م-ی-ش-ه" },
    { id: "24-25.v.mamoolan", type: "vocabulary", fa: "معمولاً", pin: "mā'moolan", en: "usually", notes: "م-ع-م-و-ل-ا" },
    { id: "24-25.v.hich-vaght", type: "vocabulary", fa: "هیچ‌وقت", pin: "hich-vaght", en: "never", notes: "هیچ (no/none) + وقت (time)" },
    { id: "24-25.v.baazi-vaght-ha", type: "vocabulary", fa: "بعضی وقت‌ها", pin: "baazi vaght-hā", en: "sometimes", notes: "بعضی (some) + وقت‌ها (times)" },
    { id: "24-25.v.bishtare-vaght-ha", type: "vocabulary", fa: "بیشتر وقت‌ها", pin: "bishtare vaght-hā", en: "most of the time, often", notes: "بیشتر (more/most) + وقت‌ها" },
    { id: "24-25.v.baazi", type: "vocabulary", fa: "بعضی", pin: "baazi", en: "some (of)", notes: "ب-ع-ض-ی" },
    { id: "24-25.v.bishtar-e", type: "vocabulary", fa: "بیشتر", pin: "bishtar-e", en: "most, the majority of", notes: "ب-ی-ش-ت-ر" },
    { id: "24-25.v.bad", type: "vocabulary", fa: "باد", pin: "bād", en: "wind", notes: "ب-ا-د (long ā)" },
    { id: "24-25.v.badi", type: "vocabulary", fa: "بادی", pin: "bādi", en: "windy", notes: "باد (wind) + ی" },
    { id: "24-25.v.bad-2", type: "vocabulary", fa: "بعد", pin: "ba'd", en: "then, after", notes: "ب-ع-د (with glottal)" },
    { id: "24-25.v.bad-az-zohr", type: "vocabulary", fa: "بعد از ظهر", pin: "ba'd az zohr", en: "afternoon", notes: "بعد (after) + از (from) + ظهر (noon)" },
    { id: "24-25.v.bazi", type: "vocabulary", fa: "بازی", pin: "bāzi", en: "play, game", notes: "ب-ا-ز-ی" },
    { id: "24-25.v.khiar-shoor", type: "vocabulary", fa: "خیارشور", pin: "khiār-shoor", en: "gherkins, salt-pickled cucumbers", notes: "خیار (cucumber) + شور (salty)" },
    { id: "24-25.v.khiar", type: "vocabulary", fa: "خیار", pin: "khiār", en: "cucumber", notes: "خ-ی-ا-ر" },
    { id: "24-25.v.torshi", type: "vocabulary", fa: "ترشی", pin: "torshi", en: "sour pickles, vinegar-based pickled vegetables", notes: "ت-ر-ش-ی" },
    { id: "24-25.v.eshgh", type: "vocabulary", fa: "عشق", pin: "eshgh", en: "love", notes: "ع-ش-ق" },
    { id: "24-25.v.eshgham", type: "vocabulary", fa: "عشقم", pin: "eshgham", en: "my love (endearment)", notes: "عشق + م (my)" },
    { id: "24-25.v.ashegh", type: "vocabulary", fa: "عاشق", pin: "āshegh", en: "lover, in love", notes: "ع-ا-ش-ق" },
    { id: "24-25.v.ahang", type: "vocabulary", fa: "آهنگ", pin: "āhang", en: "song", notes: "ا-ه-ن-گ" },
    { id: "24-25.v.safar", type: "vocabulary", fa: "سفر", pin: "safar", en: "travel, trip", notes: "س-ف-ر" },
    { id: "24-25.v.safar-kardan", type: "vocabulary", fa: "سفر کردن", pin: "safar kardan", en: "to travel", notes: "سفر (travel) + کردن (to do)" },
    { id: "24-25.v.shahr", type: "vocabulary", fa: "شهر", pin: "shahr", en: "city", notes: "ش-ه-ر" },
    { id: "24-25.v.dastshooyi", type: "vocabulary", fa: "دستشویی", pin: "dastshooyi", en: "restroom", notes: "دست (hand) + شویی (washing)" },
    { id: "24-25.v.sonnati", type: "vocabulary", fa: "سنتی", pin: "sonnati", en: "traditional", notes: "س-ن-ت-ی" },
    { id: "24-25.v.ghadimi", type: "vocabulary", fa: "قدیمی", pin: "ghadimi", en: "old (things, places)", notes: "ق-د-ی-م-ی" },
    { id: "24-25.v.pir", type: "vocabulary", fa: "پیر", pin: "pir", en: "old (people)", notes: "پ-ی-ر" },
    { id: "24-25.v.daneshgah", type: "vocabulary", fa: "دانشگاه", pin: "dāneshgāh", en: "university", notes: "دانش (knowledge) + گاه (place)" },
    { id: "24-25.v.zarf", type: "vocabulary", fa: "ظرف", pin: "zarf", en: "dish, plate", notes: "ظ-ر-ف" },
    { id: "24-25.v.tamiz", type: "vocabulary", fa: "تمیز", pin: "tamiz", en: "clean", notes: "ت-م-ی-ز" },
    { id: "24-25.v.desser", type: "vocabulary", fa: "دسر", pin: "desser", en: "dessert, pudding", notes: "د-س-ر" },
    { id: "24-25.v.tazeh", type: "vocabulary", fa: "تازه", pin: "tāzeh", en: "fresh", notes: "ت-ا-ز-ه" },
    { id: "24-25.v.amadeh", type: "vocabulary", fa: "آماده", pin: "āmādeh", en: "ready, prepared", notes: "ا-م-ا-د-ه" },
    { id: "24-25.v.bademjan", type: "vocabulary", fa: "بادمجان", pin: "bādemjān", en: "aubergine, eggplant", notes: "ب-ا-د-م-ج-ا-ن" },
    { id: "24-25.v.khorosht-e-bademjan", type: "vocabulary", fa: "خورشت بادمجان", pin: "khorosht-e bādemjān", en: "aubergine stew", notes: "خورشت (stew) + بادمجان" },
    { id: "24-25.v.ashpaz-khooneh", type: "vocabulary", fa: "آشپزخونه", pin: "āshpaz-khooneh", en: "kitchen", notes: "آشپز (cook) + خونه (house)" },
    { id: "24-25.v.ashpazi-kardan", type: "vocabulary", fa: "آشپزی کردن", pin: "āshpazi kardan", en: "to cook", notes: "آشپزی (cooking) + کردن (to do)" },
    { id: "24-25.v.shirini", type: "vocabulary", fa: "شیرینی", pin: "shirini", en: "sweets, pastry", notes: "شیرین (sweet) + ی" },
    { id: "24-25.v.ziba", type: "vocabulary", fa: "زیبا", pin: "zibā", en: "beautiful", notes: "ز-ی-ب-ا" },
    { id: "24-25.v.mored-e-alaghe", type: "vocabulary", fa: "مورد علاقه", pin: "mored-e alāghe", en: "favourite", notes: "مورد (case) + علاقه (interest)" },
    { id: "24-25.v.dars", type: "vocabulary", fa: "درس", pin: "dars", en: "lesson", notes: "د-ر-س" },
    { id: "24-25.v.asr", type: "vocabulary", fa: "عصر", pin: "asr", en: "evening, late afternoon", notes: "ع-ص-ر" },
    { id: "24-25.v.restoran", type: "vocabulary", fa: "رستوران", pin: "restorān", en: "restaurant", notes: "ر-س-ت-و-ر-ا-ن" },
    { id: "24-25.v.chand-ta", type: "vocabulary", fa: "چند تا", pin: "chand tā", en: "a few, several", notes: "چند (how many/some) + تا (counter)" },
    // Grammar
    { id: "24-25.g.bekhand", type: "grammar", fa: "بخند", pin: "bekhand", en: "Laugh! (singular imperative)", notes: "بِ + خند (present stem of خندیدن)" },
    { id: "24-25.g.bekhandid", type: "grammar", fa: "بخندید", pin: "bekhandid", en: "Laugh! (formal/plural imperative)", notes: "بِ + خند + ید" },
    { id: "24-25.g.nakhand", type: "grammar", fa: "نخند", pin: "nakhand", en: "Don't laugh! (negative imperative)", notes: "نَ + خند" },
    { id: "24-25.g.befarmayid-bokhorid", type: "grammar", fa: "بفرمایید بخورید", pin: "befarmāyid bokhorid", en: "Please eat! (formal polite)", notes: "بفرمایید + بخورید" },
    { id: "24-25.g.befarmayid-beshinid", type: "grammar", fa: "بفرمایید بشینید", pin: "befarmāyid beshinid", en: "Please sit down! (formal polite)", notes: "بفرمایید + بشینید" },
    // Phrases
    { id: "24-25.p.salam-beresoon", type: "phrases", fa: "سلام برسون!", pin: "salām beresoon!", en: "Send my regards!", notes: "سلام (regards) + برسون (send/deliver)" },
    { id: "24-25.p.be-maryam-salam-beresoon", type: "phrases", fa: "به مریم سلام برسون!", pin: "be Maryam salām beresoon!", en: "Say hi to Maryam!", notes: "به (to) + مریم + سلام + برسون" },
    { id: "24-25.p.mamanam-salam-miresooneh", type: "phrases", fa: "مامانم سلام میرسونه", pin: "māmānam salām miresooneh", en: "My mom is sending regards", notes: "مامانم + سلام + میرسونه (delivers)" },
    { id: "24-25.p.be-man-begoo", type: "phrases", fa: "به من بگو", pin: "be man begoo", en: "Tell me!", notes: "به (to) + من (me) + بگو (tell)" },
    { id: "24-25.p.be-oon-begoo", type: "phrases", fa: "به اون بگو", pin: "be oon begoo", en: "Tell her/him!", notes: "به (to) + اون (her/him) + بگو (tell)" },
    { id: "24-25.p.be-man-bedeh", type: "phrases", fa: "به من بده", pin: "be man bedeh", en: "Give me!", notes: "به (to) + من (me) + بده (give)" },
    { id: "24-25.p.in-ro-bekhoon", type: "phrases", fa: "این رو بخون", pin: "in ro bekhoon", en: "Read this!", notes: "این (this) + رو (object marker) + بخون (read)" },
    { id: "24-25.p.saram-sholugh-e", type: "phrases", fa: "سرم شلوغه", pin: "saram sholugh-e", en: "I'm busy", notes: "سرم (my head) + شلوغه (is busy)" },
    { id: "24-25.p.emrooz-saret-sholugh-e", type: "phrases", fa: "امروز سرت شلوغه؟", pin: "emrooz saret sholugh-e?", en: "Are you busy today?", notes: "امروز (today) + سرت (your head) + شلوغه" },
    { id: "24-25.p.in-hafte-vaght-nadaram", type: "phrases", fa: "این هفته وقت ندارم", pin: "in hafte vaght nadāram", en: "I don't have time this week", notes: "این هفته + وقت (time) + ندارم" },
    { id: "24-25.p.emrooz-vaght-daram", type: "phrases", fa: "امروز وقت دارم", pin: "emrooz vaght dāram", en: "I have time today", notes: "امروز + وقت + دارم (have)" },
    { id: "24-25.p.man-hamishe-bastani-sefaresh", type: "phrases", fa: "من همیشه بستنی سفارش میدم", pin: "man hamishe bastani sefāresh midam", en: "I always order ice cream", notes: "همیشه (always) + سفارش میدم (I order)" },
    { id: "24-25.p.oon-hamishe-mikhandeh", type: "phrases", fa: "اون همیشه میخنده", pin: "oon hamishe mikhandeh", en: "He/She always laughs", notes: "اون + همیشه + میخنده (laughs)" },
    { id: "24-25.p.man-hich-vaght-be-sagam-biscuit", type: "phrases", fa: "من هیچ‌وقت به سگم بیسکویت نمیدم", pin: "man hich-vaght be sagam biscuit nemidam", en: "I never give my dog biscuits", notes: "هیچ‌وقت (never) + نمیدم (don't give)" },
    { id: "24-25.p.man-asheghet-hastam", type: "phrases", fa: "من عاشقت هستم", pin: "man āsheghet hastam", en: "I am in love with you / I love you", notes: "من + عاشقت (in love with you) + هستم (am)" },
    { id: "24-25.p.man-ashegh-e-in-ahang-hastam", type: "phrases", fa: "من عاشق این آهنگ هستم", pin: "man āshegh-e in āhang hastam", en: "I love this song", notes: "عاشق (in love) + این آهنگ (this song)" },
    { id: "24-25.p.man-ashegh-e-in-shahr-hastam", type: "phrases", fa: "من عاشق این شهر هستم", pin: "man āshegh-e in shahr hastam", en: "I'm in love with this city", notes: "عاشق + این شهر (this city)" },
    { id: "24-25.p.mamanam-ashegh-e-safar-kardan", type: "phrases", fa: "مامانم عاشق سفر کردن هست", pin: "māmānam āshegh-e safar kardan hast", en: "My mom loves traveling", notes: "عاشق + سفر کردن (traveling)" },
    { id: "24-25.p.oon-ashegh-e-shokolat-hast", type: "phrases", fa: "اون عاشق شکلات هست", pin: "oon āshegh-e shokolāt hast", en: "He/She loves chocolate", notes: "عاشق + شکلات" },
    { id: "24-25.p.maman-bozorgesh-torshi-dorost", type: "phrases", fa: "مامان‌بزرگش ترشی درست میکنه", pin: "māmān-bozorgesh torshi dorost mikoneh", en: "His/her grandma makes pickles", notes: "مامان‌بزرگش + ترشی + درست میکنه" },
    { id: "24-25.p.man-ashegh-e-khoonevade-am", type: "phrases", fa: "من عاشق خانواده‌ام هستم", pin: "man āshegh-e khoonevāde-am hastam", en: "I love my family", notes: "عاشق + خانواده‌ام (my family)" },
    { id: "24-25.p.ma-dar-shahr-e-yazd-zendegi", type: "phrases", fa: "ما در شهر یزد زندگی میکنیم", pin: "mā dar shahr-e Yazd zendegi mikonim", en: "We live in the city of Yazd", notes: "زندگی میکنیم (we live)" },
    { id: "24-25.p.ma-hamishe-dar-restoran-emoon", type: "phrases", fa: "ما همیشه در رستورانمون غذای سنتی درست میکنیم", pin: "mā hamishe dar restorān-emoon ghazā-ye sonnati dorost mikonim", en: "We always make traditional food in our restaurant", notes: "رستورانمون = our restaurant (Tehran)" },
    { id: "24-25.p.man-dar-daneshgah-dars-mikhoonam", type: "phrases", fa: "من در دانشگاه درس میخونم", pin: "man dar dāneshgāh dars mikhoonam", en: "I study at university", notes: "درس میخونم (I study)" },
    { id: "24-25.p.man-hichvaght-ashpazi-nemikonam", type: "phrases", fa: "من هیچ‌وقت آشپزی نمیکنم", pin: "man hichvaght āshpazi nemikonam", en: "I never cook", notes: "هیچ‌وقت + آشپزی نمیکنم" },
    { id: "24-25.p.restoran-emrooz-kheili-sholugh", type: "phrases", fa: "رستوران امروز خیلی شلوغ هست", pin: "restorān emrooz kheili sholugh hast", en: "The restaurant is very busy today", notes: "شلوغ (busy/crowded)" },
    { id: "24-25.p.khorosht-e-bademjoon-khorosht-e", type: "phrases", fa: "خورشت بادمجون خورشت مورد علاقم هست", pin: "khorosht-e bādemjoon khorosht-e mored-e alāgham hast", en: "Aubergine stew is my favourite stew", notes: "مورد علاقم (my favourite)" },
  ],
});
