// Sessions 24-25.
// Item ids are permanent. Never change or reuse one; add new items with new ids.
F.lesson({
  id: "24-25",
  label: "Sessions 24-25",
  title: "Imperatives, reading, time and love",
  notes: ["ALEX-SESSION-24_formatted.md", "ALEX-SESSION-25_formatted.md"],
  items: [
    // Vocabulary
    { id: "24-25.v.beresoon", type: "vocabulary", fa: "برسون", pin: "beresoon", en: "send! deliver! (imperative)", notes: "imperative of رسوندن (resoondan)",
      examples: [
        { fa: "به مریم سلام برسون!", pin: "be Maryam salām beresoon!", en: "Say hi to Maryam!", source: "phrase:24-25" },
        { fa: "مریم می‌خنده و می‌گه: «به مامانت سلام برسون!»", pin: "Maryam mikhandeh va migeh: \"Be māmānet salām beresoon!\"", en: "Maryam laughs and says: \"Say hi to your mom!\"", source: "story:st-2425-1" },
        { fa: "سلام برسون!", pin: "salām beresoon!", en: "Send my regards!", source: "phrase:24-25" },
        { fa: "شب، مامانم گفت: «به همه سلام برسون!»", pin: "Shab, māmānam goft: \"Be hameh salām beresoon!\"", en: "In the evening, my mom said: \"Say hello to everyone!\"", source: "story:st-33-1" },
      ] },
    { id: "24-25.v.begoo", type: "vocabulary", fa: "بگو", pin: "begoo", en: "tell! say! (imperative)", notes: "imperative of گفتن (goftan)",
      examples: [
        { fa: "به من بگو", pin: "be man begoo", en: "Tell me!", source: "phrase:24-25" },
        { fa: "به اون بگو", pin: "be oon begoo", en: "Tell her/him!", source: "phrase:24-25" },
      ] },
    { id: "24-25.v.bedeh", type: "vocabulary", fa: "بده", pin: "bedeh", en: "give! (imperative)", notes: "imperative of دادن (dādan)",
      examples: [
        { fa: "به من بده", pin: "be man bedeh", en: "Give me!", source: "phrase:24-25" },
      ] },
    { id: "24-25.v.bokon", type: "vocabulary", fa: "بکن", pin: "bokon", en: "do! (imperative)", notes: "imperative of کردن (kardan)" },
    { id: "24-25.v.nakon", type: "vocabulary", fa: "نکن", pin: "nakon", en: "don't! (negative imperative)", notes: "نَ + کن",
      examples: [
        { fa: "لطفاً در رو باز نکن!", pin: "lotfan dar ro bāz nakon!", en: "Don't open the door please!", source: "phrase:32" },
      ] },
    { id: "24-25.v.bekhoon", type: "vocabulary", fa: "بخون", pin: "bekhoon", en: "read! (imperative)", notes: "imperative of خوندن (khoondan)",
      examples: [
        { fa: "این رو بخون", pin: "in ro bekhoon", en: "Read this!", source: "phrase:24-25" },
      ] },
    { id: "24-25.v.bokhor", type: "vocabulary", fa: "بخور", pin: "bokhor", en: "eat! (imperative)", notes: "imperative of خوردن (khordan)" },
    { id: "24-25.v.boro", type: "vocabulary", fa: "برو", pin: "boro", en: "go! (imperative)", notes: "imperative of رفتن (raftan)",
      examples: [
        { fa: "برو خونه!", pin: "boro khoone!", en: "Go home!", source: "phrase:28" },
      ] },
    { id: "24-25.v.beshin", type: "vocabulary", fa: "بشین", pin: "beshin", en: "sit! sit down! (imperative)", notes: "imperative of نشستن (neshastan)",
      examples: [
        { fa: "مامان‌بزرگ هر بار می‌گه: «بشین! چای می‌خوری؟»", pin: "Māmānbozorg har bār migeh: \"Beshin! Chāy mikhori?\"", en: "Every time, Grandma says: \"Sit down! Will you have some tea?\"", source: "story:st-30-2" },
      ] },
    { id: "24-25.v.befarmayid", type: "vocabulary", fa: "بفرمایید", pin: "befarmāyid", en: "please (polite invitation)", notes: "formal polite imperative",
      examples: [
        { fa: "مریم می‌گه: «سلام! بفرمایید بشینید!»", pin: "Maryam migeh: \"Salām! Befarmāyid beshinid!\"", en: "Maryam says: \"Hello! Please, have a seat!\"", source: "story:st-2425-1" },
        { fa: "بعد می‌گه: «بفرمایید بخورید! نوش جان!»", pin: "Ba'd migeh: \"Befarmāyid bokhorid! Noosh-e jān!\"", en: "Then she says: \"Please, eat! Enjoy!\"", source: "story:st-2425-1" },
      ] },
    { id: "24-25.v.khandan-khoondan", type: "vocabulary", fa: "خواندن", pin: "khāndan / khoondan", en: "to read", notes: "خ-و-ا-ن-د-ن",
      examples: [
        { fa: "این رو بخون", pin: "in ro bekhoon", en: "Read this!", source: "phrase:24-25" },
        { fa: "من در دانشگاه درس میخونم", pin: "man dar dāneshgāh dars mikhoonam", en: "I study at university", source: "phrase:24-25" },
        { fa: "الان علی داره شام درست می‌کنه و سارا داره کتاب می‌خونه.", pin: "Alān Ali dāreh shām dorost mikoneh va Sārā dāreh ketāb mikhooneh.", en: "Right now Ali is making dinner and Sara is reading a book.", source: "story:st-28-1" },
        { fa: "اون داره توی کتابخونه درس می‌خونه", pin: "oon dāreh tooye ketābkhooneh dars mikhooneh", en: "He/she is studying in the library", source: "phrase:31" },
      ] },
    { id: "24-25.v.dars-khoondan", type: "vocabulary", fa: "درس خوندن", pin: "dars khoondan", en: "to study", notes: "درس (lesson) + خوندن (to read)",
      examples: [
        { fa: "من در دانشگاه درس میخونم", pin: "man dar dāneshgāh dars mikhoonam", en: "I study at university", source: "phrase:24-25" },
        { fa: "اون داره توی کتابخونه درس می‌خونه", pin: "oon dāreh tooye ketābkhooneh dars mikhooneh", en: "He/she is studying in the library", source: "phrase:31" },
      ] },
    { id: "24-25.v.avaz-khandan-khoondan", type: "vocabulary", fa: "آواز خواندن", pin: "āvāz khāndan / khoondan", en: "to sing", notes: "آواز (song/singing) + خواندن",
      examples: [
        { fa: "علی سوت می‌زنه و آواز می‌خونه.", pin: "Ali soot mizaneh va āvāz mikhooneh.", en: "Ali whistles and sings.", source: "story:st-33-2" },
      ] },
    { id: "24-25.v.khanandeh", type: "vocabulary", fa: "خواننده", pin: "khānandeh", en: "singer", notes: "خواندن + ـنده (agent suffix)" },
    { id: "24-25.v.ketabkhoone", type: "vocabulary", fa: "کتابخونه", pin: "ketābkhoone", en: "library", notes: "کتاب (book) + خونه (house)",
      examples: [
        { fa: "ما امروز به کتابخونه می‌ریم", pin: "mā emrooz be ketāb-khoone mirim", en: "Today we're going to the library", source: "phrase:28" },
        { fa: "اون داره توی کتابخونه درس می‌خونه", pin: "oon dāreh tooye ketābkhooneh dars mikhooneh", en: "He/she is studying in the library", source: "phrase:31" },
      ] },
    { id: "24-25.v.sholugh", type: "vocabulary", fa: "شلوغ", pin: "sholugh", en: "busy / crowded", notes: "ش-ل-و-غ",
      examples: [
        { fa: "امروز سرت شلوغه؟", pin: "emrooz saret sholugh-e?", en: "Are you busy today?", source: "phrase:24-25" },
        { fa: "رستوران امروز خیلی شلوغ هست", pin: "restorān emrooz kheili sholugh hast", en: "The restaurant is very busy today", source: "phrase:24-25" },
        { fa: "رستوران مریم همیشه شلوغه.", pin: "Restorān-e Maryam hamisheh sholugh-eh.", en: "Maryam's restaurant is always busy.", source: "story:st-2425-1" },
        { fa: "سرم شلوغه", pin: "saram sholugh-e", en: "I'm busy", source: "phrase:24-25" },
      ] },
    { id: "24-25.v.vaght", type: "vocabulary", fa: "وقت", pin: "vaght", en: "time", notes: "و-ق-ت",
      examples: [
        { fa: "این هفته وقت ندارم", pin: "in hafte vaght nadāram", en: "I don't have time this week", source: "phrase:24-25" },
        { fa: "امروز وقت دارم", pin: "emrooz vaght dāram", en: "I have time today", source: "phrase:24-25" },
        { fa: "سارا می‌گه: «من فردا صبح سر کار می‌رم، ولی بعد از ظهر وقت دارم.»", pin: "Sārā migeh: \"Man fardā sobh sar-e kār miram, vali ba'd az zohr vaght dāram.\"", en: "Sara says: \"I'm going to work tomorrow morning, but I'm free in the afternoon.\"", source: "story:st-28-1" },
        { fa: "من سر وقت نمی‌رسم", pin: "man sar-e vaght nemiresam", en: "I won't arrive on time", source: "phrase:29" },
      ] },
    { id: "24-25.v.hamishe", type: "vocabulary", fa: "همیشه", pin: "hamishe", en: "always", notes: "ه-م-ی-ش-ه",
      examples: [
        { fa: "من همیشه بستنی سفارش میدم", pin: "man hamishe bastani sefāresh midam", en: "I always order ice cream", source: "phrase:24-25" },
        { fa: "رستوران مریم همیشه شلوغه.", pin: "Restorān-e Maryam hamisheh sholugh-eh.", en: "Maryam's restaurant is always busy.", source: "story:st-2425-1" },
        { fa: "اون همیشه میخنده", pin: "oon hamishe mikhandeh", en: "He/She always laughs", source: "phrase:24-25" },
        { fa: "ما همیشه در رستورانمون غذای سنتی درست میکنیم", pin: "mā hamishe dar restorān-emoon ghazā-ye sonnati dorost mikonim", en: "We always make traditional food in our restaurant", source: "phrase:24-25" },
      ] },
    { id: "24-25.v.mamoolan", type: "vocabulary", fa: "معمولاً", pin: "mā'moolan", en: "usually", notes: "م-ع-م-و-ل-ا",
      examples: [
        { fa: "اون معمولاً خورشت بادمجان درست می‌کنه.", pin: "Oon ma'moolan khorosht-e bādemjān dorost mikoneh.", en: "She usually makes aubergine stew.", source: "story:st-2425-1" },
      ] },
    { id: "24-25.v.hich-vaght", type: "vocabulary", fa: "هیچ‌وقت", pin: "hich-vaght", en: "never", notes: "هیچ (no/none) + وقت (time)",
      examples: [
        { fa: "من هیچ‌وقت به سگم بیسکویت نمیدم", pin: "man hich-vaght be sagam biscuit nemidam", en: "I never give my dog biscuits", source: "phrase:24-25" },
        { fa: "من هیچ‌وقت آشپزی نمیکنم", pin: "man hichvaght āshpazi nemikonam", en: "I never cook", source: "phrase:24-25" },
        { fa: "علی کلید رو برمی‌داره و می‌گه: «دیگه هیچ‌وقت کلیدم رو روی یخچال نمی‌ذارم!»", pin: "Ali kelid ro barmidāreh va migeh: \"Dige hichvaght kelidam ro ruye yakhchāl nemizāram!\"", en: "Ali picks up the key and says: \"I'll never put my key on the fridge again!\"", source: "story:st-35-1" },
      ] },
    { id: "24-25.v.baazi-vaght-ha", type: "vocabulary", fa: "بعضی وقت‌ها", pin: "baazi vaght-hā", en: "sometimes", notes: "بعضی (some) + وقت‌ها (times)" },
    { id: "24-25.v.bishtare-vaght-ha", type: "vocabulary", fa: "بیشتر وقت‌ها", pin: "bishtare vaght-hā", en: "most of the time, often", notes: "بیشتر (more/most) + وقت‌ها" },
    { id: "24-25.v.baazi", type: "vocabulary", fa: "بعضی", pin: "baazi", en: "some (of)", notes: "ب-ع-ض-ی" },
    { id: "24-25.v.bishtar-e", type: "vocabulary", fa: "بیشتر", pin: "bishtar-e", en: "most, the majority of", notes: "ب-ی-ش-ت-ر" },
    { id: "24-25.v.bad", type: "vocabulary", fa: "باد", pin: "bād", en: "wind", notes: "ب-ا-د (long ā)" },
    { id: "24-25.v.badi", type: "vocabulary", fa: "بادی", pin: "bādi", en: "windy", notes: "باد (wind) + ی" },
    { id: "24-25.v.bad-2", type: "vocabulary", fa: "بعد", pin: "ba'd", en: "then, after", notes: "ب-ع-د (with glottal)",
      examples: [
        { fa: "بعد می‌گه: «بفرمایید بخورید! نوش جان!»", pin: "Ba'd migeh: \"Befarmāyid bokhorid! Noosh-e jān!\"", en: "Then she says: \"Please, eat! Enjoy!\"", source: "story:st-2425-1" },
        { fa: "بعد از غذا، ما دسر و چای می‌خوریم.", pin: "Ba'd az ghazā, mā deser o chāy mikhorim.", en: "After the meal, we have dessert and tea.", source: "story:st-2425-1" },
        { fa: "سارا می‌گه: «آره! بعدش هم با همدیگه شام می‌خوریم.»", pin: "Sārā migeh: \"Āreh! Ba'desh ham bā hamdige shām mikhorim.\"", en: "Sara says: \"Yes! And afterwards we'll have dinner together.\"", source: "story:st-28-1" },
        { fa: "بعد بچه‌ها می‌رن مدرسه و پدر و مادر می‌رن سر کار.", pin: "baad bache-hā miran madreseh va pedar-o mādar miran sar-e kār.", en: "Then the children go to school and the parents go to work.", source: "story:32" },
      ] },
    { id: "24-25.v.bad-az-zohr", type: "vocabulary", fa: "بعد از ظهر", pin: "ba'd az zohr", en: "afternoon", notes: "بعد (after) + از (from) + ظهر (noon)",
      examples: [
        { fa: "سارا می‌گه: «من فردا صبح سر کار می‌رم، ولی بعد از ظهر وقت دارم.»", pin: "Sārā migeh: \"Man fardā sobh sar-e kār miram, vali ba'd az zohr vaght dāram.\"", en: "Sara says: \"I'm going to work tomorrow morning, but I'm free in the afternoon.\"", source: "story:st-28-1" },
        { fa: "اون هر روز از ساعت هفت صبح تا ساعت دو بعد از ظهر کار می‌کنه", pin: "oon har rooz az sāat-e haft-e sobh tā sāat-e do baad az zohr kār mikoneh", en: "She works from 7 AM to 2 PM every day", source: "phrase:30" },
        { fa: "علی تا ساعت سه بعد از ظهر خوابید.", pin: "Ali tā sāat-e seh ba'd az zohr khābid.", en: "Ali slept until three in the afternoon.", source: "story:st-32-2" },
        { fa: "علی می‌گه: «فردا بعد از ظهر با همدیگه می‌ریم سینما؟»", pin: "Ali migeh: \"Fardā ba'd az zohr bā hamdige mirim cinemā?\"", en: "Ali says: \"Shall we go to the cinema together tomorrow afternoon?\"", source: "story:st-28-1" },
      ] },
    { id: "24-25.v.bazi", type: "vocabulary", fa: "بازی", pin: "bāzi", en: "play, game", notes: "ب-ا-ز-ی",
      examples: [
        { fa: "بچه‌ها تا ساعت هفت با همدیگه بازی می‌کنن.", pin: "bache-hā tā sāat-e haft bā hamdige bāzi mikonan.", en: "The children play with each other until seven.", source: "story:32" },
        { fa: "بچّه‌ها بیدار هستند و با هم بازی می‌کنند.", pin: "Bachcheh hā bidār hastand va bā ham bāzi mikonand.", en: "The children are awake and playing together.", source: "story:st-34-2" },
      ] },
    { id: "24-25.v.khiar-shoor", type: "vocabulary", fa: "خیارشور", pin: "khiār-shoor", en: "gherkins, salt-pickled cucumbers", notes: "خیار (cucumber) + شور (salty)" },
    { id: "24-25.v.khiar", type: "vocabulary", fa: "خیار", pin: "khiār", en: "cucumber", notes: "خ-ی-ا-ر" },
    { id: "24-25.v.torshi", type: "vocabulary", fa: "ترشی", pin: "torshi", en: "sour pickles, vinegar-based pickled vegetables", notes: "ت-ر-ش-ی",
      examples: [
        { fa: "مامان‌بزرگش ترشی درست میکنه", pin: "māmān-bozorgesh torshi dorost mikoneh", en: "His/her grandma makes pickles", source: "phrase:24-25" },
      ] },
    { id: "24-25.v.eshgh", type: "vocabulary", fa: "عشق", pin: "eshgh", en: "love", notes: "ع-ش-ق" },
    { id: "24-25.v.eshgham", type: "vocabulary", fa: "عشقم", pin: "eshgham", en: "my love (endearment)", notes: "عشق + م (my)" },
    { id: "24-25.v.ashegh", type: "vocabulary", fa: "عاشق", pin: "āshegh", en: "lover, in love", notes: "ع-ا-ش-ق",
      examples: [
        { fa: "من عاشقت هستم", pin: "man āsheghet hastam", en: "I am in love with you / I love you", source: "phrase:24-25" },
        { fa: "من به مریم می‌گم: «خیلی ممنون! من عاشق این رستوران هستم!»", pin: "Man be Maryam migam: \"Kheili mamnoon! Man āshegh-e in restorān hastam!\"", en: "I say to Maryam: \"Thank you so much! I love this restaurant!\"", source: "story:st-2425-1" },
        { fa: "من عاشق این آهنگ هستم", pin: "man āshegh-e in āhang hastam", en: "I love this song", source: "phrase:24-25" },
        { fa: "مامانم عاشق سفر کردن هست", pin: "māmānam āshegh-e safar kardan hast", en: "My mom loves traveling", source: "phrase:24-25" },
      ] },
    { id: "24-25.v.ahang", type: "vocabulary", fa: "آهنگ", pin: "āhang", en: "song", notes: "ا-ه-ن-گ",
      examples: [
        { fa: "من عاشق این آهنگ هستم", pin: "man āshegh-e in āhang hastam", en: "I love this song", source: "phrase:24-25" },
      ] },
    { id: "24-25.v.safar", type: "vocabulary", fa: "سفر", pin: "safar", en: "travel, trip", notes: "س-ف-ر",
      examples: [
        { fa: "مامانم عاشق سفر کردن هست", pin: "māmānam āshegh-e safar kardan hast", en: "My mom loves traveling", source: "phrase:24-25" },
        { fa: "علی می‌گه: «و سال دیگه با همدیگه به ایران سفر می‌کنیم!»", pin: "Ali migeh: \"Va sāl-e dige bā hamdige be Irān safar mikonim!\"", en: "Ali says: \"And next year we'll travel to Iran together!\"", source: "story:st-28-1" },
        { fa: "اون از تهران به شیراز سفر می‌کنه.", pin: "Oon az Tehrān be Shirāz safar mikoneh.", en: "She's travelling from Tehran to Shiraz.", source: "story:st-31-2" },
        { fa: "سال دیگه به ایران سفر می‌کنم", pin: "sāl-e dige be Irān safar mikonam", en: "I'll travel to Iran next year", source: "phrase:28" },
      ] },
    { id: "24-25.v.safar-kardan", type: "vocabulary", fa: "سفر کردن", pin: "safar kardan", en: "to travel", notes: "سفر (travel) + کردن (to do)",
      examples: [
        { fa: "مامانم عاشق سفر کردن هست", pin: "māmānam āshegh-e safar kardan hast", en: "My mom loves traveling", source: "phrase:24-25" },
        { fa: "علی می‌گه: «و سال دیگه با همدیگه به ایران سفر می‌کنیم!»", pin: "Ali migeh: \"Va sāl-e dige bā hamdige be Irān safar mikonim!\"", en: "Ali says: \"And next year we'll travel to Iran together!\"", source: "story:st-28-1" },
        { fa: "اون از تهران به شیراز سفر می‌کنه.", pin: "Oon az Tehrān be Shirāz safar mikoneh.", en: "She's travelling from Tehran to Shiraz.", source: "story:st-31-2" },
        { fa: "سال دیگه به ایران سفر می‌کنم", pin: "sāl-e dige be Irān safar mikonam", en: "I'll travel to Iran next year", source: "phrase:28" },
      ] },
    { id: "24-25.v.shahr", type: "vocabulary", fa: "شهر", pin: "shahr", en: "city", notes: "ش-ه-ر",
      examples: [
        { fa: "من عاشق این شهر هستم", pin: "man āshegh-e in shahr hastam", en: "I'm in love with this city", source: "phrase:24-25" },
        { fa: "مریم در شهر یزد زندگی می‌کنه.", pin: "Maryam dar shahr-e Yazd zendegi mikoneh.", en: "Maryam lives in the city of Yazd.", source: "story:st-2425-1" },
        { fa: "ما در شهر یزد زندگی میکنیم", pin: "mā dar shahr-e Yazd zendegi mikonim", en: "We live in the city of Yazd", source: "phrase:24-25" },
        { fa: "تهران بزرگ‌ترین شهر ایران هست.", pin: "Tehran bozorgtarin shahr-e Iran hast.", en: "Tehran is the biggest city in Iran.", source: "phrase:34" },
      ] },
    { id: "24-25.v.dastshooyi", type: "vocabulary", fa: "دستشویی", pin: "dastshooyi", en: "restroom", notes: "دست (hand) + شویی (washing)" },
    { id: "24-25.v.sonnati", type: "vocabulary", fa: "سنتی", pin: "sonnati", en: "traditional", notes: "س-ن-ت-ی",
      examples: [
        { fa: "ما همیشه در رستورانمون غذای سنتی درست میکنیم", pin: "mā hamishe dar restorān-emoon ghazā-ye sonnati dorost mikonim", en: "We always make traditional food in our restaurant", source: "phrase:24-25" },
        { fa: "اون یه رستوران سنتی داره.", pin: "Oon ye restorān-e sonnati dāreh.", en: "She has a traditional restaurant.", source: "story:st-2425-1" },
      ] },
    { id: "24-25.v.ghadimi", type: "vocabulary", fa: "قدیمی", pin: "ghadimi", en: "old (things, places)", notes: "ق-د-ی-م-ی",
      examples: [
        { fa: "در شیراز، سارا یه اتاق در یه مهمون‌خونه‌ی قدیمی اجاره می‌کنه.", pin: "Dar Shirāz, Sārā ye otāgh dar ye mehmoon-khoone-ye ghadimi ejāreh mikoneh.", en: "In Shiraz, Sara rents a room in an old guesthouse.", source: "story:st-31-2" },
        { fa: "دوچرخه‌ی من از دوچرخه‌ی تو قدیمی‌تره.", pin: "Docharkhe-ye man az docharkhe-ye to ghadimitar-eh.", en: "My bicycle is older than yours.", source: "phrase:34" },
      ] },
    { id: "24-25.v.pir", type: "vocabulary", fa: "پیر", pin: "pir", en: "old (people)", notes: "پ-ی-ر",
      examples: [
        { fa: "مامان‌بزرگ خیلی پیر هست، ولی روزی دو بار پیاده‌روی می‌کنه.", pin: "Māmānbozorg kheili pir hast, vali roozi do bār piāderavi mikoneh.", en: "Grandma is very old, but she goes for a walk twice a day.", source: "story:st-30-2" },
        { fa: "یه مسافر پیر می‌گه: «سفر کاری می‌رید؟»", pin: "Ye mosāfer-e pir migeh: \"Safar-e kāri mirid?\"", en: "An old passenger says: \"Are you going on a business trip?\"", source: "story:st-31-2" },
      ] },
    { id: "24-25.v.daneshgah", type: "vocabulary", fa: "دانشگاه", pin: "dāneshgāh", en: "university", notes: "دانش (knowledge) + گاه (place)",
      examples: [
        { fa: "من در دانشگاه درس میخونم", pin: "man dar dāneshgāh dars mikhoonam", en: "I study at university", source: "phrase:24-25" },
        { fa: "من از دوشنبه تا جمعه دانشگاه هستم", pin: "man az doshanbe tā jome dāneshgāh hastam", en: "From Monday to Friday I'm at university", source: "phrase:30" },
        { fa: "من از خونه تا دانشگاه دوچرخه‌سواری می‌کنم", pin: "man az khoone tā dāneshgāh docharkheh savāri mikonam", en: "I ride a bicycle from home to university", source: "phrase:31" },
        { fa: "من با قطار به دانشگاه می‌رم", pin: "man bā ghatār be dāneshgāh miram", en: "I go to the university by train", source: "phrase:31" },
      ] },
    { id: "24-25.v.zarf", type: "vocabulary", fa: "ظرف", pin: "zarf", en: "dish, plate", notes: "ظ-ر-ف",
      examples: [
        { fa: "روی میز یه ظرف میوه و یه قوری هست.", pin: "Ruye miz ye zarf-e miveh o ye ghoori hast.", en: "On the table there's a fruit bowl and a teapot.", source: "story:st-35-2" },
      ] },
    { id: "24-25.v.tamiz", type: "vocabulary", fa: "تمیز", pin: "tamiz", en: "clean", notes: "ت-م-ی-ز",
      examples: [
        { fa: "گربه‌ام هر روز خودش رو تمیز می‌کنه", pin: "gorbe-am har rooz khodesh ro tamiz mikoneh", en: "My cat cleans itself every day", source: "phrase:29" },
        { fa: "آشپزخونه‌ی مامانم کوچیکه، ولی خیلی تمیزه.", pin: "Āshpazkhoone-ye māmānam koochik-eh, vali kheili tamiz-eh.", en: "My mom's kitchen is small, but it's very clean.", source: "story:st-35-2" },
      ] },
    { id: "24-25.v.desser", type: "vocabulary", fa: "دسر", pin: "desser", en: "dessert, pudding", notes: "د-س-ر",
      examples: [
        { fa: "بعد از غذا، ما دسر و چای می‌خوریم.", pin: "Ba'd az ghazā, mā deser o chāy mikhorim.", en: "After the meal, we have dessert and tea.", source: "story:st-2425-1" },
      ] },
    { id: "24-25.v.tazeh", type: "vocabulary", fa: "تازه", pin: "tāzeh", en: "fresh", notes: "ت-ا-ز-ه",
      examples: [
        { fa: "غذا خیلی خوشمزه و تازه هست.", pin: "Ghazā kheili khoshmazeh o tāzeh hast.", en: "The food is very tasty and fresh.", source: "story:st-2425-1" },
        { fa: "میوه‌فروش می‌گه: «سلام آقا! سیب‌ها خیلی تازه هستن.»", pin: "Miveh-foroush migeh: \"Salām āghā! Sib hā kheili tāzeh hastan.\"", en: "The greengrocer says: \"Hello, sir! The apples are really fresh.\"", source: "story:st-31-1" },
      ] },
    { id: "24-25.v.amadeh", type: "vocabulary", fa: "آماده", pin: "āmādeh", en: "ready, prepared", notes: "ا-م-ا-د-ه",
      examples: [
        { fa: "بعد از صبحونه، مامان می‌گه: «زود باشید! همه‌چیز آماده‌ست؟»", pin: "Ba'd az sobhooneh, māmān migeh: \"Zood bāshid! Hameh-chiz āmādeh-st?\"", en: "After breakfast, Mom says: \"Hurry up! Is everything ready?\"", source: "story:st-33-2" },
        { fa: "کَم کَم برایِ رفتن آماده می‌شَوَم.", pin: "Kam kam barāye raftan āmādeh mishavam.", en: "Little by little I get ready to leave.", source: "story:34" },
      ] },
    { id: "24-25.v.bademjan", type: "vocabulary", fa: "بادمجان", pin: "bādemjān", en: "aubergine, eggplant", notes: "ب-ا-د-م-ج-ا-ن",
      examples: [
        { fa: "اون معمولاً خورشت بادمجان درست می‌کنه.", pin: "Oon ma'moolan khorosht-e bādemjān dorost mikoneh.", en: "She usually makes aubergine stew.", source: "story:st-2425-1" },
        { fa: "خورشت بادمجان خورشت مورد علاقه‌ی من هست.", pin: "Khorosht-e bādemjān khorosht-e mored-e alāghe-ye man hast.", en: "Aubergine stew is my favourite stew.", source: "story:st-2425-1" },
      ] },
    { id: "24-25.v.khorosht-e-bademjan", type: "vocabulary", fa: "خورشت بادمجان", pin: "khorosht-e bādemjān", en: "aubergine stew", notes: "خورشت (stew) + بادمجان",
      examples: [
        { fa: "اون معمولاً خورشت بادمجان درست می‌کنه.", pin: "Oon ma'moolan khorosht-e bādemjān dorost mikoneh.", en: "She usually makes aubergine stew.", source: "story:st-2425-1" },
        { fa: "خورشت بادمجان خورشت مورد علاقه‌ی من هست.", pin: "Khorosht-e bādemjān khorosht-e mored-e alāghe-ye man hast.", en: "Aubergine stew is my favourite stew.", source: "story:st-2425-1" },
      ] },
    { id: "24-25.v.ashpaz-khooneh", type: "vocabulary", fa: "آشپزخونه", pin: "āshpaz-khooneh", en: "kitchen", notes: "آشپز (cook) + خونه (house)",
      examples: [
        { fa: "مریم هر روز در آشپزخونه آشپزی می‌کنه.", pin: "Maryam har rooz dar āshpazkhooneh āshpazi mikoneh.", en: "Maryam cooks in the kitchen every day.", source: "story:st-2425-1" },
        { fa: "آشپزخونه‌ی مامانم کوچیکه، ولی خیلی تمیزه.", pin: "Āshpazkhoone-ye māmānam koochik-eh, vali kheili tamiz-eh.", en: "My mom's kitchen is small, but it's very clean.", source: "story:st-35-2" },
        { fa: "اون داره تو آشپزخونه غذا درست می‌کنه", pin: "oon dāreh too āshpazkhooneh ghazā dorost mikoneh", en: "He/she is cooking in the kitchen", source: "phrase:31" },
        { fa: "خانواده ساعت هشت تو آشپزخونه شام می‌خورن.", pin: "khānevādeh sāat-e hasht too āshpazkhooneh shām mikhoran.", en: "The family eats dinner in the kitchen at eight.", source: "story:32" },
      ] },
    { id: "24-25.v.ashpazi-kardan", type: "vocabulary", fa: "آشپزی کردن", pin: "āshpazi kardan", en: "to cook", notes: "آشپزی (cooking) + کردن (to do)",
      examples: [
        { fa: "من هیچ‌وقت آشپزی نمیکنم", pin: "man hichvaght āshpazi nemikonam", en: "I never cook", source: "phrase:24-25" },
        { fa: "مریم هر روز در آشپزخونه آشپزی می‌کنه.", pin: "Maryam har rooz dar āshpazkhooneh āshpazi mikoneh.", en: "Maryam cooks in the kitchen every day.", source: "story:st-2425-1" },
        { fa: "علی می‌خنده و می‌گه: «مامان تو از مامان من بهتر آشپزی می‌کنه؟»", pin: "Ali mikhandeh va migeh: \"Māmān-e to az māmān-e man behtar āshpazi mikoneh?\"", en: "Ali laughs and says: \"Your mom cooks better than my mom?\"", source: "story:st-34-1" },
      ] },
    { id: "24-25.v.shirini", type: "vocabulary", fa: "شیرینی", pin: "shirini", en: "sweets, pastry", notes: "شیرین (sweet) + ی" },
    { id: "24-25.v.ziba", type: "vocabulary", fa: "زیبا", pin: "zibā", en: "beautiful", notes: "ز-ی-ب-ا" },
    { id: "24-25.v.mored-e-alaghe", type: "vocabulary", fa: "مورد علاقه", pin: "mored-e alāghe", en: "favourite", notes: "مورد (case) + علاقه (interest)",
      examples: [
        { fa: "خورشت بادمجان خورشت مورد علاقه‌ی من هست.", pin: "Khorosht-e bādemjān khorosht-e mored-e alāghe-ye man hast.", en: "Aubergine stew is my favourite stew.", source: "story:st-2425-1" },
        { fa: "ساز مورد علاقه‌ی تو چیه؟", pin: "sāz-e mored-e alāghe-ye to chi-e?", en: "What's your favourite instrument?", source: "phrase:33" },
        { fa: "ساز مورد علاقه‌ی من ویولن هست", pin: "sāz-e mored-e alāghe-ye man violon hast", en: "My favourite instrument is the violin", source: "phrase:33" },
      ] },
    { id: "24-25.v.dars", type: "vocabulary", fa: "درس", pin: "dars", en: "lesson", notes: "د-ر-س",
      examples: [
        { fa: "من در دانشگاه درس میخونم", pin: "man dar dāneshgāh dars mikhoonam", en: "I study at university", source: "phrase:24-25" },
        { fa: "اون داره توی کتابخونه درس می‌خونه", pin: "oon dāreh tooye ketābkhooneh dars mikhooneh", en: "He/she is studying in the library", source: "phrase:31" },
      ] },
    { id: "24-25.v.asr", type: "vocabulary", fa: "عصر", pin: "asr", en: "evening, late afternoon", notes: "ع-ص-ر" },
    { id: "24-25.v.restoran", type: "vocabulary", fa: "رستوران", pin: "restorān", en: "restaurant", notes: "ر-س-ت-و-ر-ا-ن",
      examples: [
        { fa: "ما همیشه در رستورانمون غذای سنتی درست میکنیم", pin: "mā hamishe dar restorān-emoon ghazā-ye sonnati dorost mikonim", en: "We always make traditional food in our restaurant", source: "phrase:24-25" },
        { fa: "اون یه رستوران سنتی داره.", pin: "Oon ye restorān-e sonnati dāreh.", en: "She has a traditional restaurant.", source: "story:st-2425-1" },
        { fa: "رستوران امروز خیلی شلوغ هست", pin: "restorān emrooz kheili sholugh hast", en: "The restaurant is very busy today", source: "phrase:24-25" },
        { fa: "رستوران مریم همیشه شلوغه.", pin: "Restorān-e Maryam hamisheh sholugh-eh.", en: "Maryam's restaurant is always busy.", source: "story:st-2425-1" },
      ] },
    { id: "24-25.v.chand-ta", type: "vocabulary", fa: "چند تا", pin: "chand tā", en: "a few, several", notes: "چند (how many/some) + تا (counter)" },
    // Grammar
    { id: "24-25.g.bekhand", type: "grammar", fa: "بخند", pin: "bekhand", en: "Laugh! (singular imperative)", notes: "بِ + خند (present stem of خندیدن)" },
    { id: "24-25.g.bekhandid", type: "grammar", fa: "بخندید", pin: "bekhandid", en: "Laugh! (formal/plural imperative)", notes: "بِ + خند + ید" },
    { id: "24-25.g.nakhand", type: "grammar", fa: "نخند", pin: "nakhand", en: "Don't laugh! (negative imperative)", notes: "نَ + خند" },
    { id: "24-25.g.befarmayid-bokhorid", type: "grammar", fa: "بفرمایید بخورید", pin: "befarmāyid bokhorid", en: "Please eat! (formal polite)", notes: "بفرمایید + بخورید" },
    { id: "24-25.g.befarmayid-beshinid", type: "grammar", fa: "بفرمایید بشینید", pin: "befarmāyid beshinid", en: "Please sit down! (formal polite)", notes: "بفرمایید + بشینید" },
    // Phrases
    { id: "24-25.p.salam-beresoon", type: "phrases", fa: "سلام برسون!", pin: "salām beresoon!", en: "Send my regards!", notes: "سلام (regards) + برسون (send/deliver)" },
    { id: "24-25.p.be-maryam-salam-beresoon", type: "phrases", fa: "به مریم سلام برسون!", pin: "be Maryam salām beresoon!", en: "Say hi to Maryam!", notes: "به (to) + مریم + سلام + برسون" },
    { id: "24-25.p.mamanam-salam-miresooneh", type: "phrases", fa: "مامانم سلام میرسونه", pin: "māmānam salām miresooneh", en: "My mom is sending regards", notes: "مامانم + سلام + میرسونه (delivers)" },
    { id: "24-25.p.be-man-begoo", type: "phrases", fa: "به من بگو", pin: "be man begoo", en: "Tell me!", notes: "به (to) + من (me) + بگو (tell)" },
    { id: "24-25.p.be-oon-begoo", type: "phrases", fa: "به اون بگو", pin: "be oon begoo", en: "Tell her/him!", notes: "به (to) + اون (her/him) + بگو (tell)" },
    { id: "24-25.p.be-man-bedeh", type: "phrases", fa: "به من بده", pin: "be man bedeh", en: "Give me!", notes: "به (to) + من (me) + بده (give)" },
    { id: "24-25.p.in-ro-bekhoon", type: "phrases", fa: "این رو بخون", pin: "in ro bekhoon", en: "Read this!", notes: "این (this) + رو (object marker) + بخون (read)" },
    { id: "24-25.p.saram-sholugh-e", type: "phrases", fa: "سرم شلوغه", pin: "saram sholugh-e", en: "I'm busy", notes: "سرم (my head) + شلوغه (is busy)" },
    { id: "24-25.p.emrooz-saret-sholugh-e", type: "phrases", fa: "امروز سرت شلوغه؟", pin: "emrooz saret sholugh-e?", en: "Are you busy today?", notes: "امروز (today) + سرت (your head) + شلوغه" },
    { id: "24-25.p.in-hafte-vaght-nadaram", type: "phrases", fa: "این هفته وقت ندارم", pin: "in hafte vaght nadāram", en: "I don't have time this week", notes: "این هفته + وقت (time) + ندارم" },
    { id: "24-25.p.emrooz-vaght-daram", type: "phrases", fa: "امروز وقت دارم", pin: "emrooz vaght dāram", en: "I have time today", notes: "امروز + وقت + دارم (have)" },
    { id: "24-25.p.man-hamishe-bastani-sefaresh", type: "phrases", fa: "من همیشه بستنی سفارش میدم", pin: "man hamishe bastani sefāresh midam", en: "I always order ice cream", notes: "همیشه (always) + سفارش میدم (I order)" },
    { id: "24-25.p.oon-hamishe-mikhandeh", type: "phrases", fa: "اون همیشه میخنده", pin: "oon hamishe mikhandeh", en: "He/She always laughs", notes: "اون + همیشه + میخنده (laughs)" },
    { id: "24-25.p.man-hich-vaght-be-sagam-biscuit", type: "phrases", fa: "من هیچ‌وقت به سگم بیسکویت نمیدم", pin: "man hich-vaght be sagam biscuit nemidam", en: "I never give my dog biscuits", notes: "هیچ‌وقت (never) + نمیدم (don't give)" },
    { id: "24-25.p.man-asheghet-hastam", type: "phrases", fa: "من عاشقت هستم", pin: "man āsheghet hastam", en: "I am in love with you / I love you", notes: "من + عاشقت (in love with you) + هستم (am)" },
    { id: "24-25.p.man-ashegh-e-in-ahang-hastam", type: "phrases", fa: "من عاشق این آهنگ هستم", pin: "man āshegh-e in āhang hastam", en: "I love this song", notes: "عاشق (in love) + این آهنگ (this song)" },
    { id: "24-25.p.man-ashegh-e-in-shahr-hastam", type: "phrases", fa: "من عاشق این شهر هستم", pin: "man āshegh-e in shahr hastam", en: "I'm in love with this city", notes: "عاشق + این شهر (this city)" },
    { id: "24-25.p.mamanam-ashegh-e-safar-kardan", type: "phrases", fa: "مامانم عاشق سفر کردن هست", pin: "māmānam āshegh-e safar kardan hast", en: "My mom loves traveling", notes: "عاشق + سفر کردن (traveling)" },
    { id: "24-25.p.oon-ashegh-e-shokolat-hast", type: "phrases", fa: "اون عاشق شکلات هست", pin: "oon āshegh-e shokolāt hast", en: "He/She loves chocolate", notes: "عاشق + شکلات" },
    { id: "24-25.p.maman-bozorgesh-torshi-dorost", type: "phrases", fa: "مامان‌بزرگش ترشی درست میکنه", pin: "māmān-bozorgesh torshi dorost mikoneh", en: "His/her grandma makes pickles", notes: "مامان‌بزرگش + ترشی + درست میکنه" },
    { id: "24-25.p.man-ashegh-e-khoonevade-am", type: "phrases", fa: "من عاشق خانواده‌ام هستم", pin: "man āshegh-e khoonevāde-am hastam", en: "I love my family", notes: "عاشق + خانواده‌ام (my family)" },
    { id: "24-25.p.ma-dar-shahr-e-yazd-zendegi", type: "phrases", fa: "ما در شهر یزد زندگی میکنیم", pin: "mā dar shahr-e Yazd zendegi mikonim", en: "We live in the city of Yazd", notes: "زندگی میکنیم (we live)" },
    { id: "24-25.p.ma-hamishe-dar-restoran-emoon", type: "phrases", fa: "ما همیشه در رستورانمون غذای سنتی درست میکنیم", pin: "mā hamishe dar restorān-emoon ghazā-ye sonnati dorost mikonim", en: "We always make traditional food in our restaurant", notes: "رستورانمون = our restaurant (Tehran)" },
    { id: "24-25.p.man-dar-daneshgah-dars-mikhoonam", type: "phrases", fa: "من در دانشگاه درس میخونم", pin: "man dar dāneshgāh dars mikhoonam", en: "I study at university", notes: "درس میخونم (I study)" },
    { id: "24-25.p.man-hichvaght-ashpazi-nemikonam", type: "phrases", fa: "من هیچ‌وقت آشپزی نمیکنم", pin: "man hichvaght āshpazi nemikonam", en: "I never cook", notes: "هیچ‌وقت + آشپزی نمیکنم" },
    { id: "24-25.p.restoran-emrooz-kheili-sholugh", type: "phrases", fa: "رستوران امروز خیلی شلوغ هست", pin: "restorān emrooz kheili sholugh hast", en: "The restaurant is very busy today", notes: "شلوغ (busy/crowded)" },
    { id: "24-25.p.khorosht-e-bademjoon-khorosht-e", type: "phrases", fa: "خورشت بادمجون خورشت مورد علاقم هست", pin: "khorosht-e bādemjoon khorosht-e mored-e alāgham hast", en: "Aubergine stew is my favourite stew", notes: "مورد علاقم (my favourite)" },
  ],
});
