// Session 26.
// Item ids are permanent. Never change or reuse one; add new items with new ids.
F.lesson({
  id: "26",
  label: "Session 26",
  title: "Telling the time, numbers and meals",
  notes: "ALEX-SESSION-26_formatted.md",
  items: [
    // Vocabulary
    // To know
    { id: "26.v.danestan-dunestan", type: "vocabulary", fa: "دانستن", pin: "dānestan / dunestan", en: "to know", notes: "د-ا-ن-س-ت-ن",
      examples: [
        { fa: "تو این رو میدونی؟", pin: "to in ro midooni?", en: "Do you know this?", source: "phrase:26" },
        { fa: "رضا می‌گه: «نمی‌دونم!»", pin: "Rezā migeh: \"Nemidoonam!\"", en: "Reza says: \"I don't know!\"", source: "story:st-26-1" },
        { fa: "تو میدونی اون کجاست؟", pin: "to midooni oon kojāst?", en: "Do you know where he/she is?", source: "phrase:26" },
        { fa: "تو میدونی این یعنی چی؟", pin: "to midooni in yani chi?", en: "Do you know what this means?", source: "phrase:26" },
      ] },
    { id: "26.v.danesh", type: "vocabulary", fa: "دانش", pin: "dānesh", en: "knowledge", notes: "د-ا-ن-ش" },
    { id: "26.v.kojast", type: "vocabulary", fa: "کجاست", pin: "kojāst", en: "where is?", notes: "کجا (where) + ست (is)",
      examples: [
        { fa: "تو میدونی اون کجاست؟", pin: "to midooni oon kojāst?", en: "Do you know where he/she is?", source: "phrase:26" },
        { fa: "سارا می‌گه: «کلاس کجاست؟»", pin: "Sārā migeh: \"Kelās kojāst?\"", en: "Sara says: \"Where is the class?\"", source: "story:st-26-1" },
        { fa: "نمی‌دونم کلیدت کجاست!", pin: "Nemidoonam kelidet kojāst!", en: "I don't know where your key is!", source: "phrase:35" },
        { fa: "علی می‌گه: «سارا! تو می‌دونی کلیدم کجاست؟»", pin: "Ali migeh: \"Sārā! To midooni kelidam kojāst?\"", en: "Ali says: \"Sara! Do you know where my key is?\"", source: "story:st-35-1" },
      ] },
    { id: "26.v.yani", type: "vocabulary", fa: "یعنی", pin: "yani", en: "means, i.e.", notes: "ی-ع-ن-ی",
      examples: [
        { fa: "تو میدونی این یعنی چی؟", pin: "to midooni in yani chi?", en: "Do you know what this means?", source: "phrase:26" },
      ] },
    { id: "26.v.chi", type: "vocabulary", fa: "چی", pin: "chi", en: "what", notes: "چ-ی",
      examples: [
        { fa: "تو میدونی این یعنی چی؟", pin: "to midooni in yani chi?", en: "Do you know what this means?", source: "phrase:26" },
        { fa: "علی می‌گه: «نه، من فردا کار نمی‌کنم. تو چی؟»", pin: "Ali migeh: \"Na, man fardā kār nemikonam. To chi?\"", en: "Ali says: \"No, I'm not working tomorrow. What about you?\"", source: "story:st-28-1" },
        { fa: "سارا می‌گه: «توی کیفت چی؟»", pin: "Sārā migeh: \"Tuye kifet chi?\"", en: "Sara says: \"What about in your bag?\"", source: "story:st-35-1" },
        { fa: "دیگه چی؟", pin: "dige chi?", en: "What else?", source: "phrase:28" },
      ] },
    { id: "26.v.chi-e", type: "vocabulary", fa: "چیه", pin: "chi-e", en: "what is it?", notes: "چی (what) + ه (is)",
      examples: [
        { fa: "تو میدونی این چیه؟", pin: "to midooni in chi-e?", en: "Do you know what this is?", source: "phrase:26" },
        { fa: "ساز مورد علاقه‌ی تو چیه؟", pin: "sāz-e mored-e alāghe-ye to chi-e?", en: "What's your favourite instrument?", source: "phrase:33" },
        { fa: "تو میدونی اسمش چیه؟", pin: "to midooni esmesh chi-e?", en: "Do you know what his name is?", source: "phrase:26" },
      ] },
    // Math
    { id: "26.v.riazi", type: "vocabulary", fa: "ریاضی", pin: "riāzi", en: "mathematics", notes: "ر-ی-ا-ض-ی",
      examples: [
        { fa: "ساعت نه کلاس ریاضی داره.", pin: "Sāat-e noh kelās-e riāzi dāreh.", en: "At nine she has a maths class.", source: "story:st-26-1" },
      ] },
    { id: "26.v.kelas", type: "vocabulary", fa: "کلاس", pin: "kelās", en: "class", notes: "ک-ل-ا-س",
      examples: [
        { fa: "ساعت نه کلاس ریاضی داره.", pin: "Sāat-e noh kelās-e riāzi dāreh.", en: "At nine she has a maths class.", source: "story:st-26-1" },
        { fa: "رضا می‌گه: «من ساعت دو و نیم کلاس دارم!»", pin: "Rezā migeh: \"Man sāat-e do-o nim kelās dāram!\"", en: "Reza says: \"I have a class at half past two!\"", source: "story:st-26-1" },
        { fa: "سارا می‌گه: «کلاس کجاست؟»", pin: "Sārā migeh: \"Kelās kojāst?\"", en: "Sara says: \"Where is the class?\"", source: "story:st-26-1" },
        { fa: "من خوشحالم چون امشب کلاس فارسی دارم", pin: "man khoshhālam chon emshab kelās-e Fārsi dāram", en: "I'm happy because I have Farsi class tonight", source: "phrase:27" },
      ] },
    // Time
    { id: "26.v.saat", type: "vocabulary", fa: "ساعت", pin: "sā’at", en: "clock, watch, hour, time", notes: "س-ا-ع-ت",
      examples: [
        { fa: "الان ساعت چنده؟", pin: "alān sā’at chand-e?", en: "What time is it now?", source: "phrase:26" },
        { fa: "اون هر روز ساعت هفت صبحونه می‌خوره.", pin: "Oon har rooz sāat-e haft sobhooneh mikhoreh.", en: "Every day she has breakfast at seven.", source: "story:st-26-1" },
        { fa: "ببخشید، ساعت چنده؟", pin: "bebakhshid, sā’at chand-e?", en: "Excuse me, what time is it?", source: "phrase:26" },
        { fa: "ساعت ده و نیمه", pin: "sā’at dah-o nim-e", en: "It's 10:30", source: "phrase:26" },
      ] },
    { id: "26.v.nim", type: "vocabulary", fa: "نیم", pin: "nim", en: "half", notes: "ن-ی-م",
      examples: [
        { fa: "ساعت ده و نیمه", pin: "sā’at dah-o nim-e", en: "It's 10:30", source: "phrase:26" },
        { fa: "رضا می‌گه: «من ساعت دو و نیم کلاس دارم!»", pin: "Rezā migeh: \"Man sāat-e do-o nim kelās dāram!\"", en: "Reza says: \"I have a class at half past two!\"", source: "story:st-26-1" },
        { fa: "سعید ساعت هفت و نیم میاد خونه.", pin: "Saeed sāat-e haft-o nim miād khooneh.", en: "Saeed comes home at half past seven.", source: "story:32" },
        { fa: "الان ساعت هشت و نیمه.", pin: "Alān sāat hasht-o nim-eh.", en: "It's half past eight now.", source: "story:st-35-1" },
      ] },
    { id: "26.v.rob", type: "vocabulary", fa: "ربع", pin: "rob", en: "quarter", notes: "ر-ب-ع",
      examples: [
        { fa: "ساعت هفت و ربعه", pin: "sā’at haft-o rob-e", en: "It's 7:15", source: "phrase:26" },
        { fa: "ساعت یک ربع به نهه", pin: "sā’at yek rob be noh-e", en: "It's a quarter to 9 (8:45)", source: "phrase:26" },
        { fa: "سارا می‌گه: «ساعت دو و ربعه.»", pin: "Sārā migeh: \"Sāat do-o rob'-eh.\"", en: "Sara says: \"It's a quarter past two.\"", source: "story:st-26-1" },
        { fa: "من ساعت نه و ربع می‌خوابم", pin: "man sāat-e noh-o rob mikhābam", en: "I go to bed at quarter past nine", source: "phrase:32" },
      ] },
    { id: "26.v.daghighe", type: "vocabulary", fa: "دقیقه", pin: "daghighe", en: "minute", notes: "د-ق-ی-ق-ه",
      examples: [
        { fa: "من پنج دقیقه دیگه می‌رسم", pin: "man panj daghighe-ye dige miresam", en: "I'll arrive in 5 minutes", source: "phrase:29" },
        { fa: "پنج دقیقه بعد، علی می‌رسه و می‌گه: «ببخشید دیر شد!»", pin: "Panj daghigheh ba'd, Ali mireseh va migeh: \"Bebakhshid dir shod!\"", en: "Five minutes later, Ali arrives and says: \"Sorry I'm late!\"", source: "story:st-29-1" },
      ] },
    { id: "26.v.sanieh", type: "vocabulary", fa: "ثانیه", pin: "sānieh", en: "second", notes: "ث-ا-ن-ی-ه" },
    { id: "26.v.lahzeh", type: "vocabulary", fa: "لحظه", pin: "lahzeh", en: "moment", notes: "ل-ح-ظ-ه",
      examples: [
        { fa: "یه لحظه صبر کن", pin: "ye lahze sabr kon", en: "Just a moment, please", source: "phrase:26" },
      ] },
    { id: "26.v.sabr", type: "vocabulary", fa: "صبر", pin: "sabr", en: "patience", notes: "ص-ب-ر",
      examples: [
        { fa: "یه لحظه صبر کن", pin: "ye lahze sabr kon", en: "Just a moment, please", source: "phrase:26" },
      ] },
    { id: "26.v.bebakhshid", type: "vocabulary", fa: "ببخشید", pin: "bebakhshid", en: "excuse me", notes: "ب-ب-خ-ش-ی-د",
      examples: [
        { fa: "ببخشید، ساعت چنده؟", pin: "bebakhshid, sā’at chand-e?", en: "Excuse me, what time is it?", source: "phrase:26" },
        { fa: "امروز رضا می‌گه: «ببخشید، الان ساعت چنده؟»", pin: "Emrooz Rezā migeh: \"Bebakhshid, alān sāat chand-eh?\"", en: "Today Reza says: \"Excuse me, what time is it now?\"", source: "story:st-26-1" },
        { fa: "ببخشید دیر شد!", pin: "bebakhshid dir shod!", en: "Sorry I'm late! (it got late)", source: "phrase:29" },
        { fa: "ببخشید آقا! ایستگاه اتوبوس به اینجا نزدیکه؟", pin: "bebakhshid āghā! istgāh-e otobus be injā nazdik-e?", en: "Excuse me, sir! Is the bus stop near here?", source: "phrase:31" },
      ] },
    // Numbers 1-10
    { id: "26.v.yek", type: "vocabulary", fa: "یک", pin: "yek", en: "one (1)", notes: "ی-ک",
      examples: [
        { fa: "ساعت یک ربع به نهه", pin: "sā’at yek rob be noh-e", en: "It's a quarter to 9 (8:45)", source: "phrase:26" },
        { fa: "ساعت یک، سارا با همکارش، رضا، ناهار می‌خوره.", pin: "Sāat-e yek, Sārā bā hamkāresh, Rezā, nāhār mikhoreh.", en: "At one, Sara has lunch with her colleague Reza.", source: "story:st-26-1" },
        { fa: "من یکی دیگه می‌خوام", pin: "man yeki dige mikhām", en: "I want another one / one more", source: "phrase:28" },
        { fa: "و سعید و میترا یک ساعت تلویزیون تماشا می‌کنن و ساعت ده می‌خوابن.", pin: "va Saeed-o Mitrā yek sāat televizion tamāshā mikonan va sāat-e dah mikhāban.", en: "And Saeed and Mitra watch TV for an hour and go to bed at ten.", source: "story:32" },
      ] },
    { id: "26.v.do", type: "vocabulary", fa: "دو", pin: "do", en: "two (2)", notes: "د-و",
      examples: [
        { fa: "من ساعت دو ناهار میخورم", pin: "man sā’at-e do nāhār mikhoram", en: "I eat lunch at 2", source: "phrase:26" },
        { fa: "سارا سی و دو سالشه.", pin: "Sārā si-o do sālesh-eh.", en: "Sara is thirty-two.", source: "story:st-26-1" },
        { fa: "من هر دو رو دوست دارم", pin: "man har do ro doost dāram", en: "I like both", source: "phrase:23" },
        { fa: "سارا می‌گه: «ساعت دو و ربعه.»", pin: "Sārā migeh: \"Sāat do-o rob'-eh.\"", en: "Sara says: \"It's a quarter past two.\"", source: "story:st-26-1" },
      ] },
    { id: "26.v.seh", type: "vocabulary", fa: "سه", pin: "seh", en: "three (3)", notes: "س-ه",
      examples: [
        { fa: "من سی و سه سالمه", pin: "man si-o seh sālam-e", en: "I am 33 years old", source: "phrase:26" },
        { fa: "علی هفته‌ای سه بار باشگاه هم می‌ره.", pin: "Ali hafte-i seh bār bāshgāh ham mireh.", en: "Ali also goes to the gym three times a week.", source: "story:st-30-1" },
        { fa: "اونها زن و شوهرن و سه تا بچه دارن.", pin: "oonhā zan-o shohar-an va se tā bache dāran.", en: "They are husband and wife and have three children.", source: "story:32" },
        { fa: "من روزی سه بار غذا می‌خورم", pin: "man roozi seh bār ghazā mikhoram", en: "I eat three times a day", source: "phrase:30" },
      ] },
    { id: "26.v.chahar", type: "vocabulary", fa: "چهار", pin: "chahār", en: "four (4)", notes: "چ-ه-ا-ر",
      examples: [
        { fa: "من از ساعت دو تا چهار خونه هستم", pin: "man az sāat-e do tā chahār khoone hastam", en: "I'm at home from 2 to 4", source: "phrase:30" },
        { fa: "میترا ساعت چهار بعد از خرید میاد خونه و یه غذای گرم درست می‌کنه.", pin: "Mitrā sāat-e chahār baad az kharid miād khooneh va ye ghazā-ye garm dorost mikoneh.", en: "Mitra comes home at four after shopping and cooks a warm meal.", source: "story:32" },
      ] },
    { id: "26.v.panj", type: "vocabulary", fa: "پنج", pin: "panj", en: "five (5)", notes: "پ-ن-ج",
      examples: [
        { fa: "ساعت پنجه", pin: "sā’at panj-e", en: "It is 5 o'clock", source: "phrase:26" },
        { fa: "امروز کلاس فارسی ساعت پنج هست.", pin: "Emrooz kelās-e Fārsi sāat-e panj hast.", en: "Today the Persian class is at five.", source: "story:st-29-1" },
        { fa: "من سه‌شنبه از پنج تا هفت وقت دارم", pin: "man seshanbe az panj tā haft vaght dāram", en: "I'm free on Tuesday from 5 to 7", source: "phrase:30" },
        { fa: "من پنج دقیقه دیگه می‌رسم", pin: "man panj daghighe-ye dige miresam", en: "I'll arrive in 5 minutes", source: "phrase:29" },
      ] },
    { id: "26.v.shish", type: "vocabulary", fa: "شش", pin: "shish", en: "six (6)", notes: "ش-ش",
      examples: [
        { fa: "ساعت شش صبح، اون با تاکسی به ایستگاه قطار می‌ره.", pin: "Sāat-e shish-e sobh, oon bā tāksi be istgāh-e ghatār mireh.", en: "At six in the morning, she takes a taxi to the railway station.", source: "story:st-31-2" },
        { fa: "اون از ساعت نه تا ده صبح و از ساعت پنج تا شش بعد از ظهر راه می‌ره.", pin: "Oon az sāat-e noh tā dah-e sobh va az sāat-e panj tā shish-e ba'd az zohr rāh mireh.", en: "She walks from nine to ten in the morning and from five to six in the afternoon.", source: "story:st-30-2" },
      ] },
    { id: "26.v.haft", type: "vocabulary", fa: "هفت", pin: "haft", en: "seven (7)", notes: "ه-ف-ت",
      examples: [
        { fa: "ساعت هفت و ربعه", pin: "sā’at haft-o rob-e", en: "It's 7:15", source: "phrase:26" },
        { fa: "اون هر روز ساعت هفت صبحونه می‌خوره.", pin: "Oon har rooz sāat-e haft sobhooneh mikhoreh.", en: "Every day she has breakfast at seven.", source: "story:st-26-1" },
        { fa: "من ساعت هفت صبحانه میخورم", pin: "man sā’at-e haft sobhāneh mikhoram", en: "I eat breakfast at 7", source: "phrase:26" },
        { fa: "بچه‌ها تا ساعت هفت با همدیگه بازی می‌کنن.", pin: "bache-hā tā sāat-e haft bā hamdige bāzi mikonan.", en: "The children play with each other until seven.", source: "story:32" },
      ] },
    { id: "26.v.hasht", type: "vocabulary", fa: "هشت", pin: "hasht", en: "eight (8)", notes: "ه-ش-ت",
      examples: [
        { fa: "اونها ساعت هشت صبح باز می‌کنن", pin: "oonhā sāat-e hasht-e sobh bāz mikonan", en: "They open at 8 AM", source: "phrase:32" },
        { fa: "ساعت هشت، یکی زنگ در رو می‌زنه.", pin: "Sāat-e hasht, yeki zang-e dar ro mizaneh.", en: "At eight, someone rings the doorbell.", source: "story:st-33-2" },
        { fa: "خانواده ساعت هشت تو آشپزخونه شام می‌خورن.", pin: "khānevādeh sāat-e hasht too āshpazkhooneh shām mikhoran.", en: "The family eats dinner in the kitchen at eight.", source: "story:32" },
        { fa: "الان ساعت هشت و نیمه.", pin: "Alān sāat hasht-o nim-eh.", en: "It's half past eight now.", source: "story:st-35-1" },
      ] },
    { id: "26.v.noh", type: "vocabulary", fa: "نه", pin: "noh", en: "nine (9)", notes: "ن-ه",
      examples: [
        { fa: "ساعت یک ربع به نهه", pin: "sā’at yek rob be noh-e", en: "It's a quarter to 9 (8:45)", source: "phrase:26" },
        { fa: "سارا: «نه، ممنون. من مشروب نمی‌خورم. من چای سبز می‌خورم.»", pin: "Sārā: \"Na, mamnoon. Man mashroob nemikhoram. Man chāy-e sabz mikhoram.\"", en: "Sara: \"No, thanks. I don't drink alcohol. I'll have green tea.\"", source: "story:st-23-1" },
        { fa: "ساعت نه کلاس ریاضی داره.", pin: "Sāat-e noh kelās-e riāzi dāreh.", en: "At nine she has a maths class.", source: "story:st-26-1" },
        { fa: "سارا: «نه، بدون شکر، لطفاً.»", pin: "Sārā: \"Na, bedoon-e shekar, lotfan.\"", en: "Sara: \"No, without sugar, please.\"", source: "story:st-23-1" },
      ] },
    { id: "26.v.dah", type: "vocabulary", fa: "ده", pin: "dah", en: "ten (10)", notes: "د-ه",
      examples: [
        { fa: "ساعت ده و نیمه", pin: "sā’at dah-o nim-e", en: "It's 10:30", source: "phrase:26" },
        { fa: "و سعید و میترا یک ساعت تلویزیون تماشا می‌کنن و ساعت ده می‌خوابن.", pin: "va Saeed-o Mitrā yek sāat televizion tamāshā mikonan va sāat-e dah mikhāban.", en: "And Saeed and Mitra watch TV for an hour and go to bed at ten.", source: "story:32" },
        { fa: "دیشب سعید و میترا ساعت ده نخوابیدن.", pin: "Dishab Saeed o Mitrā sāat-e dah nakhābidan.", en: "Last night Saeed and Mitra didn't go to bed at ten.", source: "story:st-32-1" },
        { fa: "من ساعت ده شب می‌خوابم", pin: "man sāat-e dah-e shab mikhābam", en: "I go to bed at 10 PM", source: "phrase:32" },
      ] },
    // Numbers 11-20
    { id: "26.v.yazdah", type: "vocabulary", fa: "یازده", pin: "yāzdah", en: "eleven (11)", notes: "ی-ا-ز-د-ه",
      examples: [
        { fa: "برادرم ساعت یازده می‌خوابه", pin: "barādaram sāat-e yāzdah mikhābeh", en: "My brother goes to bed at eleven", source: "phrase:32" },
        { fa: "ساعت یازده، بچه‌ها هم بیدار شدن.", pin: "Sāat-e yāzdah, bacheh hā ham bidār shodan.", en: "At eleven, the children woke up too.", source: "story:st-32-1" },
      ] },
    { id: "26.v.davazdah", type: "vocabulary", fa: "دوازده", pin: "davāzdah", en: "twelve (12)", notes: "د-و-ا-ز-د-ه",
      examples: [
        { fa: "ساعت دوازده، همسایه اومد.", pin: "Sāat-e davāzdah, hamsāyeh oomad.", en: "At twelve, the neighbour came over.", source: "story:st-32-1" },
      ] },
    { id: "26.v.sizdah", type: "vocabulary", fa: "سیزده", pin: "sizdah", en: "thirteen (13)", notes: "س-ی-ز-د-ه" },
    { id: "26.v.chahardah", type: "vocabulary", fa: "چهارده", pin: "chahārdah", en: "fourteen (14)", notes: "چ-ه-ا-ر-د-ه" },
    { id: "26.v.panzdah-punzdah", type: "vocabulary", fa: "پانزده", pin: "pānzdah / punzdah", en: "fifteen (15)", notes: "پ-ا-ن-ز-د-ه" },
    { id: "26.v.shanzdah-shunzdah", type: "vocabulary", fa: "شانزده", pin: "shānzdah / shunzdah", en: "sixteen (16)", notes: "ش-ا-ن-ز-د-ه" },
    { id: "26.v.hefdah-hifdah", type: "vocabulary", fa: "هفده", pin: "hefdah / hifdah", en: "seventeen (17)", notes: "ه-ف-د-ه" },
    { id: "26.v.hejdah-hijdah", type: "vocabulary", fa: "هجده", pin: "hejdah / hijdah", en: "eighteen (18)", notes: "ه-ج-د-ه" },
    { id: "26.v.noozdah", type: "vocabulary", fa: "نوزده", pin: "noozdah", en: "nineteen (19)", notes: "ن-و-ز-د-ه" },
    { id: "26.v.bist", type: "vocabulary", fa: "بیست", pin: "bist", en: "twenty (20)", notes: "ب-ی-س-ت" },
    // Tens
    { id: "26.v.si", type: "vocabulary", fa: "سی", pin: "si", en: "thirty (30)", notes: "س-ی",
      examples: [
        { fa: "من سی و سه سالمه", pin: "man si-o seh sālam-e", en: "I am 33 years old", source: "phrase:26" },
        { fa: "سارا سی و دو سالشه.", pin: "Sārā si-o do sālesh-eh.", en: "Sara is thirty-two.", source: "story:st-26-1" },
        { fa: "ایران سی و یک استان دارد.", pin: "Irān si-o-yek ostān dārad.", en: "Iran has thirty-one provinces.", source: "phrase:35" },
      ] },
    { id: "26.v.chehel", type: "vocabulary", fa: "چهل", pin: "chehel", en: "forty (40)", notes: "چ-ه-ل" },
    { id: "26.v.panjah", type: "vocabulary", fa: "پنجاه", pin: "panjāh", en: "fifty (50)", notes: "پ-ن-ج-ا-ه" },
    { id: "26.v.shast", type: "vocabulary", fa: "شصت", pin: "shast", en: "sixty (60)", notes: "ش-ص-ت" },
    { id: "26.v.haftad", type: "vocabulary", fa: "هفتاد", pin: "haftād", en: "seventy (70)", notes: "ه-ف-ت-ا-د" },
    { id: "26.v.hashtad", type: "vocabulary", fa: "هشتاد", pin: "hashtād", en: "eighty (80)", notes: "ه-ش-ت-ا-د",
      examples: [
        { fa: "مامان‌بزرگ سارا هشتاد و پنج سالشه.", pin: "Māmānbozorg-e Sārā hashtād-o panj sālesh-eh.", en: "Sara's grandma is eighty-five.", source: "story:st-30-2" },
      ] },
    { id: "26.v.navad", type: "vocabulary", fa: "نود", pin: "navad", en: "ninety (90)", notes: "ن-و-د" },
    { id: "26.v.sad", type: "vocabulary", fa: "صد", pin: "sad", en: "one hundred (100)", notes: "ص-د" },
    { id: "26.v.hezar", type: "vocabulary", fa: "هزار", pin: "hezār", en: "one thousand (1000)", notes: "ه-ز-ا-ر",
      examples: [
        { fa: "من هزار بار می‌گم عاشقتم", pin: "man hezār bār migam āsheghetam", en: "I say a thousand times, I love you", source: "phrase:30" },
      ] },
    // Year / age
    { id: "26.v.sal", type: "vocabulary", fa: "سال", pin: "sāl", en: "year", notes: "س-ا-ل",
      examples: [
        { fa: "تو چند سال داری؟", pin: "to chand sāl dāri?", en: "How old are you?", source: "phrase:26" },
        { fa: "سارا سی و دو سالشه.", pin: "Sārā si-o do sālesh-eh.", en: "Sara is thirty-two.", source: "story:st-26-1" },
        { fa: "تو چند سالته؟", pin: "to chand sālet-e?", en: "How old are you? (short form)", source: "phrase:26" },
        { fa: "شما چند سالتونه؟", pin: "shomā chand sāletoon-e?", en: "How old are you? (formal)", source: "phrase:26" },
      ] },
    { id: "26.v.emsal", type: "vocabulary", fa: "امسال", pin: "emsāl", en: "this year", notes: "ام (this) + سال (year)",
      examples: [
        { fa: "بابام امسال ماشینش رو می‌فروشه", pin: "bābām emsāl māshinesh ro miforousheh", en: "My dad is selling his car this year", source: "phrase:31" },
        { fa: "امسال از پارسال سردتره.", pin: "Emsāl az pārsāl sardtar-eh.", en: "This year is colder than last year.", source: "phrase:34" },
      ] },
    { id: "26.v.chand", type: "vocabulary", fa: "چند", pin: "chand", en: "how many", notes: "چ-ن-د",
      examples: [
        { fa: "الان ساعت چنده؟", pin: "alān sā’at chand-e?", en: "What time is it now?", source: "phrase:26" },
        { fa: "تو چند سال داری؟", pin: "to chand sāl dāri?", en: "How old are you?", source: "phrase:26" },
        { fa: "امروز رضا می‌گه: «ببخشید، الان ساعت چنده؟»", pin: "Emrooz Rezā migeh: \"Bebakhshid, alān sāat chand-eh?\"", en: "Today Reza says: \"Excuse me, what time is it now?\"", source: "story:st-26-1" },
        { fa: "ببخشید، ساعت چنده؟", pin: "bebakhshid, sā’at chand-e?", en: "Excuse me, what time is it?", source: "phrase:26" },
      ] },
    { id: "26.v.foat-kardan", type: "vocabulary", fa: "فوت کردن", pin: "foat kardan", en: "to pass away, to die", notes: "فوت (death) + کردن (to do)",
      examples: [
        { fa: "بابابزرگم فوت کرده", pin: "bābā-bozorgam foat kardeh", en: "My grandpa has passed away", source: "phrase:26" },
      ] },
    // Meals
    { id: "26.v.sobhooneh-sobhaneh", type: "vocabulary", fa: "صبحونه / صبحانه", pin: "sobhooneh / sobhāneh", en: "breakfast", notes: "صبح (morning) + انه",
      examples: [
        { fa: "تو کی صبحونه میخوری؟", pin: "to kay sobhooneh mikhori?", en: "When do you eat breakfast?", source: "phrase:26" },
        { fa: "من ساعت هفت صبحانه میخورم", pin: "man sā’at-e haft sobhāneh mikhoram", en: "I eat breakfast at 7", source: "phrase:26" },
        { fa: "اون هر روز ساعت هفت صبحونه می‌خوره.", pin: "Oon har rooz sāat-e haft sobhooneh mikhoreh.", en: "Every day she has breakfast at seven.", source: "story:st-26-1" },
        { fa: "خواهرم امروز با دوست‌هاش صبحونه میخوره", pin: "khāharam emrooz bā doost-hāsh sobhooneh mikhoreh", en: "My sister is having breakfast with her friends today", source: "phrase:26" },
      ] },
    { id: "26.v.nahar", type: "vocabulary", fa: "ناهار", pin: "nāhār", en: "lunch", notes: "ن-ا-ه-ا-ر",
      examples: [
        { fa: "من ساعت دو ناهار میخورم", pin: "man sā’at-e do nāhār mikhoram", en: "I eat lunch at 2", source: "phrase:26" },
        { fa: "ساعت یک، سارا با همکارش، رضا، ناهار می‌خوره.", pin: "Sāat-e yek, Sārā bā hamkāresh, Rezā, nāhār mikhoreh.", en: "At one, Sara has lunch with her colleague Reza.", source: "story:st-26-1" },
        { fa: "من امروز با خونواده‌ام ناهار میخورم", pin: "man emrooz bā khoonevādam nāhār mikhoram", en: "Today I'm having lunch with my family", source: "phrase:26" },
        { fa: "من و شوهرم امروز با هم ناهار میخوریم", pin: "man va shoharam emrooz bā ham nāhār mikhorim", en: "My husband and I are having lunch together today", source: "phrase:26" },
      ] },
    { id: "26.v.sham", type: "vocabulary", fa: "شام", pin: "shām", en: "dinner", notes: "ش-ا-م",
      examples: [
        { fa: "من شام درست میکنم", pin: "man shām dorost mikonam", en: "I cook dinner", source: "phrase:26" },
        { fa: "شب، سارا با شوهرش شام می‌خوره.", pin: "Shab, Sārā bā shoharesh shām mikhoreh.", en: "In the evening, Sara has dinner with her husband.", source: "story:st-26-1" },
        { fa: "تو امشب شام درست میکنی؟", pin: "to emshab shām dorost mikoni?", en: "Will you cook dinner tonight?", source: "phrase:26" },
        { fa: "من امروز با همکارم شام میخورم", pin: "man emrooz bā hamkāram shām mikhoram", en: "I'm having dinner with my colleague today", source: "phrase:26" },
      ] },
    { id: "26.v.kay", type: "vocabulary", fa: "کی", pin: "kay", en: "when", notes: "ک-ی",
      examples: [
        { fa: "تو کی صبحونه میخوری؟", pin: "to kay sobhooneh mikhori?", en: "When do you eat breakfast?", source: "phrase:26" },
        { fa: "سارا می‌گه: «این خودکار مال کیه؟»", pin: "Sārā migeh: \"In khodkār māl-e ki-eh?\"", en: "Sara says: \"Whose pen is this, then?\"", source: "story:st-29-1" },
        { fa: "شما کی از خواب بیدار می‌شید؟", pin: "shomā key az khāb bidār mishid?", en: "What time do you wake up?", source: "phrase:32" },
        { fa: "تو کی هستی؟", pin: "to ki hasti?", en: "Who are you?", source: "phrase:29" },
      ] },
    { id: "26.v.emshab", type: "vocabulary", fa: "امشب", pin: "emshab", en: "tonight", notes: "ام (this) + شب (night)",
      examples: [
        { fa: "تو امشب شام درست میکنی؟", pin: "to emshab shām dorost mikoni?", en: "Will you cook dinner tonight?", source: "phrase:26" },
        { fa: "شوهرش امشب شام درست می‌کنه.", pin: "Shoharesh emshab shām dorost mikoneh.", en: "Her husband is cooking dinner tonight.", source: "story:st-26-1" },
        { fa: "من خوشحالم چون امشب کلاس فارسی دارم", pin: "man khoshhālam chon emshab kelās-e Fārsi dāram", en: "I'm happy because I have Farsi class tonight", source: "phrase:27" },
        { fa: "امشب ما با همدیگه شام می‌خوریم", pin: "emshab mā bā hamdige shām mikhorim", en: "Tonight we'll eat dinner together", source: "phrase:28" },
      ] },
    { id: "26.v.sobh", type: "vocabulary", fa: "صبح", pin: "sobh", en: "morning", notes: "ص-ب-ح",
      examples: [
        { fa: "سارا می‌گه: «من فردا صبح سر کار می‌رم، ولی بعد از ظهر وقت دارم.»", pin: "Sārā migeh: \"Man fardā sobh sar-e kār miram, vali ba'd az zohr vaght dāram.\"", en: "Sara says: \"I'm going to work tomorrow morning, but I'm free in the afternoon.\"", source: "story:st-28-1" },
        { fa: "من امروز از ساعت هفت صبح تا ساعت دو شب کار می‌کنم", pin: "man emrooz az sāat-e haft-e sobh tā sāat-e do-e shab kār mikonam", en: "I work from 7 AM to 2 AM today", source: "phrase:30" },
        { fa: "صُبحِ زود بیدار میشم و صُبحانه دُرُست می‌کنم.", pin: "Sobh-e zood bidār misham va sobhāneh dorost mikonam.", en: "I wake up early and make breakfast.", source: "story:34" },
        { fa: "صبح، اون با دوچرخه به نونوایی می‌ره و نون می‌خره.", pin: "Sobh, oon bā docharkheh be noonvāyi mireh va noon mikhareh.", en: "In the morning, he goes to the bakery by bike and buys bread.", source: "story:st-31-1" },
      ] },
    { id: "26.v.zohr", type: "vocabulary", fa: "ظهر", pin: "zohr", en: "noon", notes: "ظ-ه-ر",
      examples: [
        { fa: "سارا می‌گه: «من فردا صبح سر کار می‌رم، ولی بعد از ظهر وقت دارم.»", pin: "Sārā migeh: \"Man fardā sobh sar-e kār miram, vali ba'd az zohr vaght dāram.\"", en: "Sara says: \"I'm going to work tomorrow morning, but I'm free in the afternoon.\"", source: "story:st-28-1" },
        { fa: "اون هر روز از ساعت هفت صبح تا ساعت دو بعد از ظهر کار می‌کنه", pin: "oon har rooz az sāat-e haft-e sobh tā sāat-e do baad az zohr kār mikoneh", en: "She works from 7 AM to 2 PM every day", source: "phrase:30" },
        { fa: "علی تا ساعت سه بعد از ظهر خوابید.", pin: "Ali tā sāat-e seh ba'd az zohr khābid.", en: "Ali slept until three in the afternoon.", source: "story:st-32-2" },
        { fa: "علی می‌گه: «فردا بعد از ظهر با همدیگه می‌ریم سینما؟»", pin: "Ali migeh: \"Fardā ba'd az zohr bā hamdige mirim cinemā?\"", en: "Ali says: \"Shall we go to the cinema together tomorrow afternoon?\"", source: "story:st-28-1" },
      ] },
    // With
    { id: "26.v.shohar", type: "vocabulary", fa: "شوهر", pin: "shohar", en: "husband", notes: "ش-و-ه-ر",
      examples: [
        { fa: "من و شوهرم امروز با هم ناهار میخوریم", pin: "man va shoharam emrooz bā ham nāhār mikhorim", en: "My husband and I are having lunch together today", source: "phrase:26" },
        { fa: "شب، سارا با شوهرش شام می‌خوره.", pin: "Shab, Sārā bā shoharesh shām mikhoreh.", en: "In the evening, Sara has dinner with her husband.", source: "story:st-26-1" },
        { fa: "اونها زن و شوهرن و سه تا بچه دارن.", pin: "oonhā zan-o shohar-an va se tā bache dāran.", en: "They are husband and wife and have three children.", source: "story:32" },
        { fa: "شوهرش امشب شام درست می‌کنه.", pin: "Shoharesh emshab shām dorost mikoneh.", en: "Her husband is cooking dinner tonight.", source: "story:st-26-1" },
      ] },
    { id: "26.v.ba-ham", type: "vocabulary", fa: "با هم", pin: "bā ham", en: "together", notes: "با (with) + هم (each other)",
      examples: [
        { fa: "من و شوهرم امروز با هم ناهار میخوریم", pin: "man va shoharam emrooz bā ham nāhār mikhorim", en: "My husband and I are having lunch together today", source: "phrase:26" },
        { fa: "بچّه‌ها بیدار هستند و با هم بازی می‌کنند.", pin: "Bachcheh hā bidār hastand va bā ham bāzi mikonand.", en: "The children are awake and playing together.", source: "story:st-34-2" },
        { fa: "ما با هم قرار داریم.", pin: "Mā bā ham gharār dārim.", en: "We're meeting. / We have a date.", source: "phrase:35" },
      ] },
    { id: "26.v.hamkar", type: "vocabulary", fa: "همکار", pin: "hamkār", en: "colleague", notes: "هم (together) + کار (work)",
      examples: [
        { fa: "من امروز با همکارم شام میخورم", pin: "man emrooz bā hamkāram shām mikhoram", en: "I'm having dinner with my colleague today", source: "phrase:26" },
        { fa: "ساعت یک، سارا با همکارش، رضا، ناهار می‌خوره.", pin: "Sāat-e yek, Sārā bā hamkāresh, Rezā, nāhār mikhoreh.", en: "At one, Sara has lunch with her colleague Reza.", source: "story:st-26-1" },
      ] },
    { id: "26.v.hamkelasi", type: "vocabulary", fa: "همکلاسی", pin: "hamkelāsi", en: "classmate", notes: "هم (together) + کلاسی (class)" },
    { id: "26.v.khahar", type: "vocabulary", fa: "خواهر", pin: "khāhar", en: "sister", notes: "خ-و-ا-ه-ر",
      examples: [
        { fa: "خواهرم امروز با دوست‌هاش صبحونه میخوره", pin: "khāharam emrooz bā doost-hāsh sobhooneh mikhoreh", en: "My sister is having breakfast with her friends today", source: "phrase:26" },
        { fa: "خواهرم از من جوون‌تر هست.", pin: "Khāharam az man javoontar hast.", en: "My sister is younger than me.", source: "phrase:34" },
      ] },
    { id: "26.v.hamsar", type: "vocabulary", fa: "همسر", pin: "hamsar", en: "spouse", notes: "هم (together) + سر (head)" },
    { id: "26.v.mashin", type: "vocabulary", fa: "ماشین", pin: "māshin", en: "car", notes: "م-ا-ش-ی-ن",
      examples: [
        { fa: "من سوار ماشینم", pin: "man savār-e māshinam", en: "I'm in the car", source: "phrase:31" },
        { fa: "همسایه‌ست! بچه‌ها هر روز با ماشین همسایه به مدرسه می‌رن.", pin: "Hamsāyeh-st! Bacheh hā har rooz bā māshin-e hamsāyeh be madreseh miran.", en: "It's the neighbour! Every day the children go to school in the neighbour's car.", source: "story:st-33-2" },
        { fa: "بابام امسال ماشینش رو می‌فروشه", pin: "bābām emsāl māshinesh ro miforousheh", en: "My dad is selling his car this year", source: "phrase:31" },
        { fa: "ماشینت رو به من می‌فروشی؟", pin: "māshinet ro be man miforushi?", en: "Will you sell your car to me?", source: "phrase:31" },
      ] },
    { id: "26.v.jadid-no", type: "vocabulary", fa: "جدید / نو", pin: "jadid / no", en: "new", notes: "ج-د-ی-د" },
    // Grammar
    // midoonam conjugation
    { id: "26.g.midoonam", type: "grammar", fa: "میدونم", pin: "midoonam", en: "I know", notes: "می + دون + م" },
    { id: "26.g.midooni", type: "grammar", fa: "میدونی", pin: "midooni", en: "you know", notes: "می + دون + ی" },
    { id: "26.g.midooneh", type: "grammar", fa: "میدونه", pin: "midooneh", en: "he/she knows", notes: "می + دون + ه" },
    { id: "26.g.midoonim", type: "grammar", fa: "میدونیم", pin: "midoonim", en: "we know", notes: "می + دون + یم" },
    { id: "26.g.midoonid", type: "grammar", fa: "میدونید", pin: "midoonid", en: "you know (formal)", notes: "می + دون + ید" },
    { id: "26.g.midoonand", type: "grammar", fa: "میدونند", pin: "midoonand", en: "they know", notes: "می + دون + ند" },
    // negative
    { id: "26.g.nemidoonam", type: "grammar", fa: "نمیدونم", pin: "nemidoonam", en: "I don't know", notes: "نمی + دون + م" },
    { id: "26.g.nemidooni", type: "grammar", fa: "نمیدونی", pin: "nemidooni", en: "you don't know", notes: "نمی + دون + ی" },
    // Phrases
    // Knowing
    { id: "26.p.to-in-ro-midooni", type: "phrases", fa: "تو این رو میدونی؟", pin: "to in ro midooni?", en: "Do you know this?", notes: "تو + این رو (this, obj.) + میدونی" },
    { id: "26.p.to-midooni-oon-kojast", type: "phrases", fa: "تو میدونی اون کجاست؟", pin: "to midooni oon kojāst?", en: "Do you know where he/she is?", notes: "میدونی + کجاست (where is)" },
    { id: "26.p.to-midooni-in-yani-chi", type: "phrases", fa: "تو میدونی این یعنی چی؟", pin: "to midooni in yani chi?", en: "Do you know what this means?", notes: "یعنی (means) + چی (what)" },
    { id: "26.p.to-midooni-in-chi-e", type: "phrases", fa: "تو میدونی این چیه؟", pin: "to midooni in chi-e?", en: "Do you know what this is?", notes: "چیه = what is it" },
    // Time
    { id: "26.p.saat-chand-e", type: "phrases", fa: "ساعت چنده؟", pin: "sā’at chand-e?", en: "What time is it?", notes: "ساعت (time) + چنده (how much is)" },
    { id: "26.p.alan-saat-chand-e", type: "phrases", fa: "الان ساعت چنده؟", pin: "alān sā’at chand-e?", en: "What time is it now?", notes: "الان (now) + ساعت چنده" },
    { id: "26.p.bebakhshid-saat-chand-e", type: "phrases", fa: "ببخشید، ساعت چنده؟", pin: "bebakhshid, sā’at chand-e?", en: "Excuse me, what time is it?", notes: "ببخشید (excuse me)" },
    { id: "26.p.saat-panj-e", type: "phrases", fa: "ساعت پنجه", pin: "sā’at panj-e", en: "It is 5 o'clock", notes: "ساعت + number + ه (is)" },
    { id: "26.p.saat-dah-o-nim-e", type: "phrases", fa: "ساعت ده و نیمه", pin: "sā’at dah-o nim-e", en: "It's 10:30", notes: "نیم = half" },
    { id: "26.p.saat-haft-o-rob-e", type: "phrases", fa: "ساعت هفت و ربعه", pin: "sā’at haft-o rob-e", en: "It's 7:15", notes: "ربع = quarter" },
    { id: "26.p.saat-yek-rob-be-noh-e", type: "phrases", fa: "ساعت یک ربع به نهه", pin: "sā’at yek rob be noh-e", en: "It's a quarter to 9 (8:45)", notes: "یک ربع به = a quarter to" },
    { id: "26.p.ye-lahze-sabr-kon", type: "phrases", fa: "یه لحظه صبر کن", pin: "ye lahze sabr kon", en: "Just a moment, please", notes: "یه لحظه (one moment) + صبر کن (wait)" },
    // Year / age
    { id: "26.p.to-chand-sal-dari", type: "phrases", fa: "تو چند سال داری؟", pin: "to chand sāl dāri?", en: "How old are you?", notes: "چند سال داری = how many years do you have" },
    { id: "26.p.to-chand-salet-e", type: "phrases", fa: "تو چند سالته؟", pin: "to chand sālet-e?", en: "How old are you? (short form)", notes: "سالته = your years is" },
    { id: "26.p.shoma-chand-saletoon-e", type: "phrases", fa: "شما چند سالتونه؟", pin: "shomā chand sāletoon-e?", en: "How old are you? (formal)", notes: "سالتونه = your (formal) years is" },
    { id: "26.p.man-si-o-seh-salam-e", type: "phrases", fa: "من سی و سه سالمه", pin: "man si-o seh sālam-e", en: "I am 33 years old", notes: "سالمه = my years is" },
    { id: "26.p.oon-chand-salesh-e", type: "phrases", fa: "اون چند سالشه؟", pin: "oon chand sālesh-e?", en: "How old is he/she?", notes: "سالشه = his/her years is" },
    { id: "26.p.baba-bozorgam-foat-kardeh", type: "phrases", fa: "بابابزرگم فوت کرده", pin: "bābā-bozorgam foat kardeh", en: "My grandpa has passed away", notes: "فوت کرده = has died (past participle)" },
    // Meals
    { id: "26.p.to-kay-sobhooneh-mikhori", type: "phrases", fa: "تو کی صبحونه میخوری؟", pin: "to kay sobhooneh mikhori?", en: "When do you eat breakfast?", notes: "کی (when) + صبحونه + میخوری" },
    { id: "26.p.man-saat-e-haft-sobhaneh", type: "phrases", fa: "من ساعت هفت صبحانه میخورم", pin: "man sā’at-e haft sobhāneh mikhoram", en: "I eat breakfast at 7", notes: "ساعتِ = at (time)" },
    { id: "26.p.man-saat-e-do-nahar-mikhoram", type: "phrases", fa: "من ساعت دو ناهار میخورم", pin: "man sā’at-e do nāhār mikhoram", en: "I eat lunch at 2", notes: "ساعتِ دو" },
    { id: "26.p.man-sham-dorost-mikonam", type: "phrases", fa: "من شام درست میکنم", pin: "man shām dorost mikonam", en: "I cook dinner", notes: "شام + درست میکنم (I make)" },
    { id: "26.p.to-emshab-sham-dorost-mikoni", type: "phrases", fa: "تو امشب شام درست میکنی؟", pin: "to emshab shām dorost mikoni?", en: "Will you cook dinner tonight?", notes: "امشب (tonight)" },
    // With family/friends
    { id: "26.p.man-emrooz-ba-khoonevadam-nahar", type: "phrases", fa: "من امروز با خونواده‌ام ناهار میخورم", pin: "man emrooz bā khoonevādam nāhār mikhoram", en: "Today I'm having lunch with my family", notes: "با خونواده‌ام = with my family" },
    { id: "26.p.man-va-shoharam-emrooz-ba-ham", type: "phrases", fa: "من و شوهرم امروز با هم ناهار میخوریم", pin: "man va shoharam emrooz bā ham nāhār mikhorim", en: "My husband and I are having lunch together today", notes: "با هم = together" },
    { id: "26.p.khaharam-emrooz-ba-doost-hash", type: "phrases", fa: "خواهرم امروز با دوست‌هاش صبحونه میخوره", pin: "khāharam emrooz bā doost-hāsh sobhooneh mikhoreh", en: "My sister is having breakfast with her friends today", notes: "با دوست‌هاش = with her friends" },
    { id: "26.p.man-emrooz-ba-hamkaram-sham", type: "phrases", fa: "من امروز با همکارم شام میخورم", pin: "man emrooz bā hamkāram shām mikhoram", en: "I'm having dinner with my colleague today", notes: "با همکارم = with my colleague" },
    // Do you know (age/name/work)
    { id: "26.p.to-midooni-oon-chand-salesh-e", type: "phrases", fa: "تو میدونی اون چند سالشه؟", pin: "to midooni oon chand sālesh-e?", en: "Do you know how old she is?", notes: "میدونی + چند سالشه" },
    { id: "26.p.nemidoonam-chand-salesh-e", type: "phrases", fa: "نمیدونم چند سالشه", pin: "nemidoonam chand sālesh-e", en: "I don't know how old she is", notes: "نمیدونم + چند سالشه" },
    { id: "26.p.to-midooni-esmesh-chi-e", type: "phrases", fa: "تو میدونی اسمش چیه؟", pin: "to midooni esmesh chi-e?", en: "Do you know what his name is?", notes: "اسمش (his name) + چیه (what is)" },
    { id: "26.p.to-midooni-koja-kar-mikoneh", type: "phrases", fa: "تو میدونی کجا کار میکنه؟", pin: "to midooni kojā kār mikoneh?", en: "Do you know where she works?", notes: "کجا (where) + کار میکنه (works)" },
  ],
});
