// Session 27.
// Item ids are permanent. Never change or reuse one; add new items with new ids.
F.lesson({
  id: "27",
  label: "Session 27",
  summary: "moods, feelings (sardam-e...), weather, infinitives as nouns, because/why",
  items: [
    // Vocabulary
    { id: "27.v.khoshhal", type: "vocabulary", fa: "خوشحال", pin: "khoshhāl", en: "happy", notes: "خوش (pleasant) + حال (state)",
      examples: [
        { fa: "من خوشحالم چون امشب کلاس فارسی دارم", pin: "man khoshhālam chon emshab kelās-e Fārsi dāram", en: "I'm happy because I have Farsi class tonight", source: "phrase:27" },
        { fa: "الان سارا خوشحاله.", pin: "Alān Sārā khoshhāl-eh.", en: "Now Sara is happy.", source: "story:st-27-1" },
        { fa: "یه خانواده‌ی خوشحال", pin: "ye khānevāde-ye khoshhāl", en: "A happy family", source: "story:32" },
        { fa: "مَن خیلی خوشحالَم چون جُمعه‌ها کِلاسِ رَقص دارَم.", pin: "Man kheili khoshhālam chun jom'e hā kelās-e raghs dāram.", en: "I am very happy because on Fridays I have a dance class.", source: "story:34" },
      ] },
    { id: "27.v.shad", type: "vocabulary", fa: "شاد", pin: "shād", en: "joyful", notes: "ش-ا-د" },
    { id: "27.v.narahat", type: "vocabulary", fa: "ناراحت", pin: "nārāhat", en: "upset, sad", notes: "نا (not) + راحت (comfortable)",
      examples: [
        { fa: "از دست من ناراحتی؟", pin: "az dast-e man nārāhati?", en: "Are you upset with me?", source: "phrase:27" },
        { fa: "سارا خیلی ناراحته.", pin: "Sārā kheili nārāhat-eh.", en: "Sara is very upset.", source: "story:st-27-1" },
        { fa: "اون از دست من خیلی ناراحته", pin: "oon az dast-e man kheili nārāhat-e", en: "She/he is really upset with me", source: "phrase:27" },
        { fa: "علی می‌گه: «سارا، چرا ناراحتی؟»", pin: "Ali migeh: \"Sārā, cherā nārāhati?\"", en: "Ali says: \"Sara, why are you upset?\"", source: "story:st-27-1" },
      ] },
    { id: "27.v.ghamgin", type: "vocabulary", fa: "غمگین", pin: "ghamgin", en: "sad", notes: "غم (sorrow) + گین",
      examples: [
        { fa: "من غمگینم چون هوا این هفته ابریه", pin: "man ghamginam chon havā in hafte abri-e", en: "I'm sad because the weather is cloudy this week", source: "phrase:27" },
        { fa: "چرا غمگینی؟", pin: "cherā ghamgini?", en: "Why are you sad?", source: "phrase:27" },
      ] },
    { id: "27.v.asabani", type: "vocabulary", fa: "عصبانی", pin: "asabāni", en: "angry", notes: "ع-ص-ب-ا-ن-ی",
      examples: [
        { fa: "از دست من عصبانی هستی؟", pin: "az dast-e man asabāni hasti?", en: "Are you angry with me?", source: "phrase:27" },
      ] },
    { id: "27.v.asabi", type: "vocabulary", fa: "عصبی", pin: "asabi", en: "nervous, tense", notes: "ع-ص-ب-ی" },
    { id: "27.v.negaran", type: "vocabulary", fa: "نگران", pin: "negarān", en: "worried, anxious", notes: "ن-گ-ر-ا-ن",
      examples: [
        { fa: "مامانم همیشه نگرانه", pin: "māmānam hamishe negarān-e", en: "My mom is always worried", source: "phrase:27" },
        { fa: "علی می‌گه: «نگران نباش! من چای درست می‌کنم.»", pin: "Ali migeh: \"Negarān nabāsh! Man chāy dorost mikonam.\"", en: "Ali says: \"Don't worry! I'll make tea.\"", source: "story:st-27-1" },
        { fa: "مامانم همیشه نگران منه", pin: "māmānam hamishe negarān-e man-e", en: "My mom is always worried about me", source: "phrase:27" },
        { fa: "من نگرانتم", pin: "man negarānetam", en: "I'm worried about you", source: "phrase:27" },
      ] },
    { id: "27.v.rahat", type: "vocabulary", fa: "راحت", pin: "rāhat", en: "comfortable, at ease", notes: "ر-ا-ح-ت",
      examples: [
        { fa: "من اینجا راحت نیستم", pin: "man injā rāhat nistam", en: "I'm not comfortable here", source: "phrase:27" },
        { fa: "اون برای سارا یه چای شیرین درست می‌کنه و می‌گه: «راحت باش!»", pin: "Oon barāye Sārā ye chāy-e shirin dorost mikoneh va migeh: \"Rāhat bāsh!\"", en: "He makes Sara a sweet tea and says: \"Make yourself comfortable!\"", source: "story:st-27-1" },
        { fa: "راحت باشید!", pin: "rāhat bāshid!", en: "Make yourself comfortable! Relax!", source: "phrase:27" },
        { fa: "اینجا خونه‌ی خودته! راحت باش!", pin: "injā khoone-ye khodet-e! rāhat bāsh!", en: "This is your home! Make yourself comfortable!", source: "phrase:29" },
      ] },
    { id: "27.v.baran-baroon", type: "vocabulary", fa: "باران / بارون", pin: "bārān / bāroon", en: "rain", notes: "ب-ا-ر-ا-ن" },
    { id: "27.v.barooni", type: "vocabulary", fa: "بارونی", pin: "bārooni", en: "rainy", notes: "بارون (rain) + ی",
      examples: [
        { fa: "امروز هوا بارونیه", pin: "emrooz havā bārooni-e", en: "The weather is rainy today", source: "phrase:27" },
        { fa: "سارا می‌گه: «چون هوا بارونیه و من سردمه.»", pin: "Sārā migeh: \"Chon havā bārooni-eh va man sardam-eh.\"", en: "Sara says: \"Because it's rainy and I'm cold.\"", source: "story:st-27-1" },
      ] },
    { id: "27.v.mehman-navazi", type: "vocabulary", fa: "مهمان‌نوازی", pin: "mehmān-navāzi", en: "hospitality", notes: "مهمان (guest) + نوازی (treating kindly)" },
    { id: "27.v.mehman-navaz", type: "vocabulary", fa: "مهمان‌نواز", pin: "mehmān-navāz", en: "hospitable", notes: "مهمان (guest) + نواز",
      examples: [
        { fa: "علی خیلی مهمان‌نوازه.", pin: "Ali kheili mehmān-navāz-eh.", en: "Ali is very hospitable.", source: "story:st-27-1" },
      ] },
    { id: "27.v.sakht", type: "vocabulary", fa: "سخت", pin: "sakht", en: "hard, difficult", notes: "س-خ-ت",
      examples: [
        { fa: "زندگی کردن در ایران الان خیلی سخته", pin: "zendegi kardan dar Irān alān kheili sakht-e", en: "Living in Iran is very hard right now", source: "phrase:27" },
        { fa: "سگ داشتن خیلی سخته ولی شیرین هم هست", pin: "sag dāshtan kheili sakht-e vali shirin ham hast", en: "Having a dog is hard, but it's also sweet", source: "phrase:27" },
        { fa: "خونه اجاره کردن تو لندن خیلی سخته", pin: "khoone ejāre kardan too London kheili sakht-e", en: "Renting a house in London is very hard", source: "phrase:27" },
        { fa: "سارا می‌گه: «پیاده‌روی برای من سخته.»", pin: "Sārā migeh: \"Piāderavi barāye man sakht-eh.\"", en: "Sara says: \"Walking is hard for me.\"", source: "story:st-30-1" },
      ] },
    { id: "27.v.shirin", type: "vocabulary", fa: "شیرین", pin: "shirin", en: "sweet", notes: "ش-ی-ر-ی-ن",
      examples: [
        { fa: "سگ داشتن خیلی سخته ولی شیرین هم هست", pin: "sag dāshtan kheili sakht-e vali shirin ham hast", en: "Having a dog is hard, but it's also sweet", source: "phrase:27" },
        { fa: "اون برای سارا یه چای شیرین درست می‌کنه و می‌گه: «راحت باش!»", pin: "Oon barāye Sārā ye chāy-e shirin dorost mikoneh va migeh: \"Rāhat bāsh!\"", en: "He makes Sara a sweet tea and says: \"Make yourself comfortable!\"", source: "story:st-27-1" },
        { fa: "و ساعت هفت صبح تو آشپزخونه صبحونه می‌خورن: نون خانگی، پنیر، مربا، تخم مرغ و چای شیرین.", pin: "va sāat-e haft-e sobh too āshpazkhooneh sobhooneh mikhoran: noon-e khānegi, panir, morabbā, tokhm-e morgh va chāy-e shirin.", en: "And at seven in the morning they have breakfast in the kitchen: homemade bread, cheese, jam, eggs and sweet tea.", source: "story:32" },
      ] },
    { id: "27.v.mohem", type: "vocabulary", fa: "مهم", pin: "mohem", en: "important", notes: "م-ه-م",
      examples: [
        { fa: "پول داشتن برای من مهم نیست", pin: "pool dāshtan barāye man mohem nist", en: "Having money is not important to me", source: "phrase:27" },
        { fa: "ورزش کردن برای من خیلی مهمه", pin: "varzesh kardan barāye man kheili mohem-e", en: "Exercising is very important to me", source: "phrase:27" },
        { fa: "داشتن یه دوست خوب خیلی مهمه", pin: "dāshtan-e ye doost-e khoob kheili mohem-e", en: "Having a good friend is very important", source: "phrase:27" },
        { fa: "جایگاه مادر در خانواده بسیار مهم است", pin: "jāygāh-e mādar dar khānevādeh besyār mohem ast", en: "The mother's role in a family is very important", source: "phrase:31" },
      ] },
    { id: "27.v.pooldar", type: "vocabulary", fa: "پولدار", pin: "pooldār", en: "rich", notes: "پول (money) + دار (having)" },
    { id: "27.v.ke", type: "vocabulary", fa: "که", pin: "ke", en: "that (connector)", notes: "ک-ه" },
    { id: "27.v.chon", type: "vocabulary", fa: "چون", pin: "chon", en: "because, since", notes: "چ-و-ن",
      examples: [
        { fa: "من خوشحالم چون امشب کلاس فارسی دارم", pin: "man khoshhālam chon emshab kelās-e Fārsi dāram", en: "I'm happy because I have Farsi class tonight", source: "phrase:27" },
        { fa: "سارا می‌گه: «چون هوا بارونیه و من سردمه.»", pin: "Sārā migeh: \"Chon havā bārooni-eh va man sardam-eh.\"", en: "Sara says: \"Because it's rainy and I'm cold.\"", source: "story:st-27-1" },
        { fa: "من غمگینم چون هوا این هفته ابریه", pin: "man ghamginam chon havā in hafte abri-e", en: "I'm sad because the weather is cloudy this week", source: "phrase:27" },
        { fa: "مَن خیلی خوشحالَم چون جُمعه‌ها کِلاسِ رَقص دارَم.", pin: "Man kheili khoshhālam chun jom'e hā kelās-e raghs dāram.", en: "I am very happy because on Fridays I have a dance class.", source: "story:34" },
      ] },
    { id: "27.v.baraye-inke", type: "vocabulary", fa: "برای اینکه", pin: "barāye inke", en: "because", notes: "برای (for) + اینکه (that)" },
    { id: "27.v.chera", type: "vocabulary", fa: "چرا", pin: "cherā", en: "why", notes: "چ-ر-ا",
      examples: [
        { fa: "علی می‌گه: «سارا، چرا ناراحتی؟»", pin: "Ali migeh: \"Sārā, cherā nārāhati?\"", en: "Ali says: \"Sara, why are you upset?\"", source: "story:st-27-1" },
        { fa: "چرا غمگینی؟", pin: "cherā ghamgini?", en: "Why are you sad?", source: "phrase:27" },
      ] },
    { id: "27.v.baraye-chi", type: "vocabulary", fa: "برای چی", pin: "barāye chi", en: "why, for what", notes: "برای (for) + چی (what)" },
    { id: "27.v.tamiz-kardan", type: "vocabulary", fa: "تمیز کردن", pin: "tamiz kardan", en: "to clean", notes: "تمیز (clean) + کردن (to do)",
      examples: [
        { fa: "گربه‌ام هر روز خودش رو تمیز می‌کنه", pin: "gorbe-am har rooz khodesh ro tamiz mikoneh", en: "My cat cleans itself every day", source: "phrase:29" },
      ] },
    { id: "27.v.shostan", type: "vocabulary", fa: "شستن", pin: "shostan", en: "to wash", notes: "present stem: شور (shoor)",
      examples: [
        { fa: "من هر روز خودم رو می‌شورم", pin: "man har rooz khodam ro mishooram", en: "I wash myself every day", source: "phrase:29" },
      ] },
    { id: "27.v.amade-kardan", type: "vocabulary", fa: "آماده کردن", pin: "āmāde kardan", en: "to prepare, to make ready", notes: "آماده (ready) + کردن" },
    { id: "27.v.ejare-kardan", type: "vocabulary", fa: "اجاره کردن", pin: "ejāre kardan", en: "to rent", notes: "اجاره (rent) + کردن",
      examples: [
        { fa: "خونه اجاره کردن تو لندن خیلی سخته", pin: "khoone ejāre kardan too London kheili sakht-e", en: "Renting a house in London is very hard", source: "phrase:27" },
        { fa: "در شیراز، سارا یه اتاق در یه مهمون‌خونه‌ی قدیمی اجاره می‌کنه.", pin: "Dar Shirāz, Sārā ye otāgh dar ye mehmoon-khoone-ye ghadimi ejāreh mikoneh.", en: "In Shiraz, Sara rents a room in an old guesthouse.", source: "story:st-31-2" },
      ] },
    { id: "27.v.pokhtan", type: "vocabulary", fa: "پختن", pin: "pokhtan", en: "to cook, to bake", notes: "present stem: پز (paz)" },
    { id: "27.v.mordan", type: "vocabulary", fa: "مردن", pin: "mordan", en: "to die", notes: "present stem: میر (mir)" },
    { id: "27.v.ashegh-boodan", type: "vocabulary", fa: "عاشق بودن", pin: "āshegh boodan", en: "to be in love", notes: "عاشق (in love) + بودن (to be)",
      examples: [
        { fa: "من عاشقت هستم", pin: "man āsheghet hastam", en: "I am in love with you / I love you", source: "phrase:24-25" },
      ] },
    { id: "27.v.pooldar-boodan", type: "vocabulary", fa: "پولدار بودن", pin: "pooldār boodan", en: "to be rich", notes: "پولدار (rich) + بودن" },
    // Grammar
    { id: "27.g.man-sardam-e", type: "grammar", fa: "من سردمه", pin: "man sardam-e", en: "I'm cold (I feel cold)", notes: "سرد (cold) + م (my) + ه (is)" },
    { id: "27.g.man-sardam-nist", type: "grammar", fa: "من سردم نیست", pin: "man sardam nist", en: "I'm not cold", notes: "سردم + نیست (is not)" },
    { id: "27.g.man-garmam-e", type: "grammar", fa: "من گرممه", pin: "man garmam-e", en: "I'm hot (I feel hot)", notes: "گرم (hot) + م + ه" },
    { id: "27.g.to-sardet-e", type: "grammar", fa: "تو سردته؟", pin: "to sardet-e?", en: "Are you cold?", notes: "سرد + ت (your) + ه" },
    { id: "27.g.oon-sardesh-e", type: "grammar", fa: "اون سردشه", pin: "oon sardesh-e", en: "He/she is cold", notes: "سرد + ش (his/her) + ه" },
    { id: "27.g.ma-sardemoon-e", type: "grammar", fa: "ما سردمونه", pin: "mā sardemoon-e", en: "We are cold", notes: "سرد + مون (our) + ه" },
    { id: "27.g.shoma-garmetoon-e", type: "grammar", fa: "شما گرمتونه؟", pin: "shomā garmetoon-e?", en: "Are you (pl) hot?", notes: "گرم + تون (your pl) + ه" },
    { id: "27.g.goshnam-e", type: "grammar", fa: "گشنمه", pin: "goshnam-e", en: "I'm hungry", notes: "گشنه (hungry) + م + ه" },
    { id: "27.g.teshnam-e", type: "grammar", fa: "تشنمه", pin: "teshnam-e", en: "I'm thirsty", notes: "تشنه (thirsty) + م + ه" },
    // Phrases
    { id: "27.p.zendegi-kardan-dar-iran-alan", type: "phrases", fa: "زندگی کردن در ایران الان خیلی سخته", pin: "zendegi kardan dar Irān alān kheili sakht-e", en: "Living in Iran is very hard right now", notes: "infinitive used as a noun (subject)" },
    { id: "27.p.sag-dashtan-kheili-sakht-e-vali", type: "phrases", fa: "سگ داشتن خیلی سخته ولی شیرین هم هست", pin: "sag dāshtan kheili sakht-e vali shirin ham hast", en: "Having a dog is hard, but it's also sweet", notes: "ولی (but) + هم (also)" },
    { id: "27.p.pool-dashtan-baraye-man-mohem", type: "phrases", fa: "پول داشتن برای من مهم نیست", pin: "pool dāshtan barāye man mohem nist", en: "Having money is not important to me", notes: "برای من (for me) + مهم نیست" },
    { id: "27.p.varzesh-kardan-baraye-man-kheili", type: "phrases", fa: "ورزش کردن برای من خیلی مهمه", pin: "varzesh kardan barāye man kheili mohem-e", en: "Exercising is very important to me", notes: "infinitive as noun + مهمه (is important)" },
    { id: "27.p.khoone-ejare-kardan-too-london", type: "phrases", fa: "خونه اجاره کردن تو لندن خیلی سخته", pin: "khoone ejāre kardan too London kheili sakht-e", en: "Renting a house in London is very hard", notes: "تو (in, colloquial)" },
    { id: "27.p.dashtan-e-ye-doost-e-khoob", type: "phrases", fa: "داشتن یه دوست خوب خیلی مهمه", pin: "dāshtan-e ye doost-e khoob kheili mohem-e", en: "Having a good friend is very important", notes: "داشتنِ + ezāfe" },
    { id: "27.p.emrooz-hava-barooni-e", type: "phrases", fa: "امروز هوا بارونیه", pin: "emrooz havā bārooni-e", en: "The weather is rainy today", notes: "هوا (weather) + بارونی (rainy) + ه (is)" },
    { id: "27.p.az-dast-e-man-narahati", type: "phrases", fa: "از دست من ناراحتی؟", pin: "az dast-e man nārāhati?", en: "Are you upset with me?", notes: "از دستِ (from the hand of = with)" },
    { id: "27.p.oon-az-dast-e-man-kheili-narahat", type: "phrases", fa: "اون از دست من خیلی ناراحته", pin: "oon az dast-e man kheili nārāhat-e", en: "She/he is really upset with me", notes: "ناراحت + ه (is)" },
    { id: "27.p.az-dast-e-man-asabani-hasti", type: "phrases", fa: "از دست من عصبانی هستی؟", pin: "az dast-e man asabāni hasti?", en: "Are you angry with me?", notes: "عصبانی (angry) + هستی (you are)" },
    { id: "27.p.mamanam-hamishe-negaran-e", type: "phrases", fa: "مامانم همیشه نگرانه", pin: "māmānam hamishe negarān-e", en: "My mom is always worried", notes: "نگران + ه (is)" },
    { id: "27.p.mamanam-hamishe-negaran-e-man-e", type: "phrases", fa: "مامانم همیشه نگران منه", pin: "māmānam hamishe negarān-e man-e", en: "My mom is always worried about me", notes: "نگرانِ من (worried about me)" },
    { id: "27.p.man-negaranetam", type: "phrases", fa: "من نگرانتم", pin: "man negarānetam", en: "I'm worried about you", notes: "نگران + ت (you) + م (I am)" },
    { id: "27.p.negaran-nabash", type: "phrases", fa: "نگران نباش!", pin: "negarān nabāsh!", en: "Don't worry!", notes: "نباش = negative imperative of بودن" },
    { id: "27.p.rahat-bashid", type: "phrases", fa: "راحت باشید!", pin: "rāhat bāshid!", en: "Make yourself comfortable! Relax!", notes: "راحت (comfortable) + باشید (be, pl)" },
    { id: "27.p.man-inja-rahat-nistam", type: "phrases", fa: "من اینجا راحت نیستم", pin: "man injā rāhat nistam", en: "I'm not comfortable here", notes: "نیستم (I am not)" },
    { id: "27.p.chera-ghamgini", type: "phrases", fa: "چرا غمگینی؟", pin: "cherā ghamgini?", en: "Why are you sad?", notes: "چرا (why) + غمگین + ی (you are)" },
    { id: "27.p.man-khoshhalam-chon-emshab-kelas", type: "phrases", fa: "من خوشحالم چون امشب کلاس فارسی دارم", pin: "man khoshhālam chon emshab kelās-e Fārsi dāram", en: "I'm happy because I have Farsi class tonight", notes: "چون (because)" },
    { id: "27.p.man-ghamginam-chon-hava-in-hafte", type: "phrases", fa: "من غمگینم چون هوا این هفته ابریه", pin: "man ghamginam chon havā in hafte abri-e", en: "I'm sad because the weather is cloudy this week", notes: "ابری (cloudy) + ه" },
  ],
});
