// Session 28.
// Item ids are permanent. Never change or reuse one; add new items with new ids.
F.lesson({
  id: "28",
  label: "Session 28",
  summary: "demonstratives, present continuous, dige, hamdige, future time, raftan + be",
  items: [
    // Vocabulary
    { id: "28.v.inha-ina", type: "vocabulary", fa: "اینها / اینا", pin: "inhā / inā", en: "these", notes: "این (this) + ها (plural)" },
    { id: "28.v.anha-oona", type: "vocabulary", fa: "آنها / اونا", pin: "ānhā / oonā", en: "those, they", notes: "آن (that) + ها",
      examples: [
        { fa: "اونا با همدیگه زندگی می‌کنن.", pin: "Oonā bā hamdige zendegi mikonan.", en: "They live together.", source: "story:st-28-1" },
        { fa: "مامان: «اونا خوبن. بد نیستن.»", pin: "Māmān: \"Oonā khooban. Bad nistan.\"", en: "Mom: \"They're well. Not bad.\"", source: "story:st-22-1" },
      ] },
    { id: "28.v.digar-dige", type: "vocabulary", fa: "دیگر / دیگه", pin: "digar / dige", en: "other, another, else, anymore", notes: "د-ی-گ-ر",
      examples: [
        { fa: "یه سوال دیگه دارم", pin: "ye soāl-e dige dāram", en: "I have another question", source: "phrase:28" },
        { fa: "علی می‌گه: «و سال دیگه با همدیگه به ایران سفر می‌کنیم!»", pin: "Ali migeh: \"Va sāl-e dige bā hamdige be Irān safar mikonim!\"", en: "Ali says: \"And next year we'll travel to Iran together!\"", source: "story:st-28-1" },
        { fa: "یه بستنی دیگه می‌خوای؟", pin: "ye bastani-e dige mikhāy?", en: "Do you want another ice cream?", source: "phrase:28" },
        { fa: "من یکی دیگه می‌خوام", pin: "man yeki dige mikhām", en: "I want another one / one more", source: "phrase:28" },
      ] },
    { id: "28.v.hamdigar-hamdige", type: "vocabulary", fa: "همدیگر / همدیگه", pin: "hamdigar / hamdige", en: "each other, one another", notes: "هم (same) + دیگه (other)",
      examples: [
        { fa: "ما همدیگه رو دوست داریم", pin: "mā hamdige ro doost dārim", en: "We love each other", source: "phrase:28" },
        { fa: "علی و سارا همدیگه رو خیلی دوست دارن.", pin: "Ali o Sārā hamdige ro kheili doost dāran.", en: "Ali and Sara love each other very much.", source: "story:st-28-1" },
        { fa: "ما با همدیگه زندگی می‌کنیم", pin: "mā bā hamdige zendegi mikonim", en: "We live together", source: "phrase:28" },
        { fa: "امشب ما با همدیگه شام می‌خوریم", pin: "emshab mā bā hamdige shām mikhorim", en: "Tonight we'll eat dinner together", source: "phrase:28" },
      ] },
    { id: "28.v.farda", type: "vocabulary", fa: "فردا", pin: "fardā", en: "tomorrow", notes: "ف-ر-د-ا",
      examples: [
        { fa: "فردا من و دوستم با همدیگه ناهار می‌خوریم", pin: "fardā man o doostam bā hamdige nāhār mikhorim", en: "Tomorrow my friend and I are having lunch together", source: "phrase:28" },
        { fa: "سارا می‌گه: «علی، فردا سر کار می‌ری؟»", pin: "Sārā migeh: \"Ali, fardā sar-e kār miri?\"", en: "Sara says: \"Ali, are you going to work tomorrow?\"", source: "story:st-28-1" },
        { fa: "من فردا کار نمی‌کنم", pin: "man fardā kār nemikonam", en: "I'm not working tomorrow", source: "phrase:28" },
        { fa: "علی می‌گه: «نه، من فردا کار نمی‌کنم. تو چی؟»", pin: "Ali migeh: \"Na, man fardā kār nemikonam. To chi?\"", en: "Ali says: \"No, I'm not working tomorrow. What about you?\"", source: "story:st-28-1" },
      ] },
    { id: "28.v.pas-farda", type: "vocabulary", fa: "پس‌فردا", pin: "pas-fardā", en: "the day after tomorrow", notes: "پس (after) + فردا" },
    { id: "28.v.farda-sobh", type: "vocabulary", fa: "فردا صبح", pin: "fardā sobh", en: "tomorrow morning", notes: "فردا + صبح (morning)",
      examples: [
        { fa: "سارا می‌گه: «من فردا صبح سر کار می‌رم، ولی بعد از ظهر وقت دارم.»", pin: "Sārā migeh: \"Man fardā sobh sar-e kār miram, vali ba'd az zohr vaght dāram.\"", en: "Sara says: \"I'm going to work tomorrow morning, but I'm free in the afternoon.\"", source: "story:st-28-1" },
      ] },
    { id: "28.v.farda-shab", type: "vocabulary", fa: "فردا شب", pin: "fardā shab", en: "tomorrow night", notes: "فردا + شب (night)",
      examples: [
        { fa: "علی می‌گه: «خوب، فردا شب شام خونه‌ی مامان تو!»", pin: "Ali migeh: \"Khob, fardā shab shām khoone-ye māmān-e to!\"", en: "Ali says: \"OK then, tomorrow night it's dinner at your mom's!\"", source: "story:st-34-1" },
      ] },
    { id: "28.v.ayande", type: "vocabulary", fa: "آینده", pin: "āyande", en: "future", notes: "آ-ی-ن-د-ه",
      examples: [
        { fa: "در آینده ما اینجا نیستیم", pin: "dar āyande mā injā nistim", en: "In the future, we won't be here", source: "phrase:28" },
      ] },
    { id: "28.v.dar-ayande", type: "vocabulary", fa: "در آینده", pin: "dar āyande", en: "in the future", notes: "در (in) + آینده",
      examples: [
        { fa: "در آینده ما اینجا نیستیم", pin: "dar āyande mā injā nistim", en: "In the future, we won't be here", source: "phrase:28" },
      ] },
    { id: "28.v.hafte-ye-ayande", type: "vocabulary", fa: "هفته‌ی آینده", pin: "hafte-ye āyande", en: "next week", notes: "هفته (week) + آینده" },
    { id: "28.v.sal-e-ayande", type: "vocabulary", fa: "سال آینده", pin: "sāl-e āyande", en: "next year", notes: "سال (year) + آینده" },
    { id: "28.v.mah-e-ayande", type: "vocabulary", fa: "ماه آینده", pin: "māh-e āyande", en: "next month", notes: "ماه (month) + آینده" },
    { id: "28.v.hafte-ye-baad", type: "vocabulary", fa: "هفته‌ی بعد", pin: "hafte-ye baad", en: "next week (neutral/formal)", notes: "بعد (after/next)" },
    { id: "28.v.hafte-ye-dige", type: "vocabulary", fa: "هفته‌ی دیگه", pin: "hafte-ye dige", en: "next week (colloquial)", notes: "دیگه as 'next'",
      examples: [
        { fa: "هفته‌ی دیگه می‌بینمت", pin: "hafte-ye dige mibinamet", en: "I'll see you next week", source: "phrase:30" },
        { fa: "ساعت هفت، سارا می‌گه: «هفته‌ی دیگه دوباره می‌بینمت!»", pin: "Sāat-e haft, Sārā migeh: \"Hafte-ye dige dobāreh mibinamet!\"", en: "At seven, Sara says: \"See you again next week!\"", source: "story:st-30-2" },
        { fa: "هفته‌ی دیگه همدیگه رو می‌بینیم", pin: "hafte-ye dige hamdige ro mibinim", en: "We'll see each other next week", source: "phrase:30" },
      ] },
    { id: "28.v.do-rooz-e-dige", type: "vocabulary", fa: "دو روز دیگه", pin: "do rooz-e dige", en: "in two days", notes: "دو (two) + روز (day) + دیگه" },
    { id: "28.v.do-saat-e-dige", type: "vocabulary", fa: "دو ساعت دیگه", pin: "do sāat-e dige", en: "in two hours", notes: "ساعت (hour) + دیگه" },
    { id: "28.v.sal-e-dige", type: "vocabulary", fa: "سال دیگه", pin: "sāl-e dige", en: "next year (colloquial)", notes: "سال + دیگه",
      examples: [
        { fa: "سال دیگه به ایران سفر می‌کنم", pin: "sāl-e dige be Irān safar mikonam", en: "I'll travel to Iran next year", source: "phrase:28" },
        { fa: "علی می‌گه: «و سال دیگه با همدیگه به ایران سفر می‌کنیم!»", pin: "Ali migeh: \"Va sāl-e dige bā hamdige be Irān safar mikonim!\"", en: "Ali says: \"And next year we'll travel to Iran together!\"", source: "story:st-28-1" },
      ] },
    { id: "28.v.madrese", type: "vocabulary", fa: "مدرسه", pin: "madrese", en: "school", notes: "م-د-ر-س-ه",
      examples: [
        { fa: "من به مدرسه نمی‌رم", pin: "man be madrese nemiram", en: "I don't go to school", source: "phrase:28" },
        { fa: "بعد بچه‌ها می‌رن مدرسه و پدر و مادر می‌رن سر کار.", pin: "baad bache-hā miran madreseh va pedar-o mādar miran sar-e kār.", en: "Then the children go to school and the parents go to work.", source: "story:32" },
        { fa: "همسایه‌ست! بچه‌ها هر روز با ماشین همسایه به مدرسه می‌رن.", pin: "Hamsāyeh-st! Bacheh hā har rooz bā māshin-e hamsāyeh be madreseh miran.", en: "It's the neighbour! Every day the children go to school in the neighbour's car.", source: "story:st-33-2" },
        { fa: "علی به مامانش چشمک می‌زنه و می‌گه: «بعد از مدرسه بهت زنگ می‌زنم!»", pin: "Ali be māmānesh cheshmak mizaneh va migeh: \"Ba'd az madreseh behet zang mizanam!\"", en: "Ali winks at his mom and says: \"I'll call you after school!\"", source: "story:st-33-2" },
      ] },
    { id: "28.v.sar-e-kar", type: "vocabulary", fa: "سر کار", pin: "sar-e kār", en: "(to/at) work", notes: "سر (head) + کار (work)",
      examples: [
        { fa: "امروز نرو سر کار!", pin: "emrooz naro sar-e kār!", en: "Don't go to work today!", source: "phrase:28" },
        { fa: "سارا می‌گه: «علی، فردا سر کار می‌ری؟»", pin: "Sārā migeh: \"Ali, fardā sar-e kār miri?\"", en: "Sara says: \"Ali, are you going to work tomorrow?\"", source: "story:st-28-1" },
        { fa: "لطفاً برید سر کار!", pin: "lotfan berid sar-e kār!", en: "Please go to work! (pl)", source: "phrase:28" },
        { fa: "سارا می‌گه: «من فردا صبح سر کار می‌رم، ولی بعد از ظهر وقت دارم.»", pin: "Sārā migeh: \"Man fardā sobh sar-e kār miram, vali ba'd az zohr vaght dāram.\"", en: "Sara says: \"I'm going to work tomorrow morning, but I'm free in the afternoon.\"", source: "story:st-28-1" },
      ] },
    { id: "28.v.ranandegi-kardan", type: "vocabulary", fa: "رانندگی کردن", pin: "rānandegi kardan", en: "to drive", notes: "رانندگی (driving) + کردن",
      examples: [
        { fa: "اون داره رانندگی می‌کنه", pin: "oon dāreh rānandegi mikoneh", en: "He/she is driving", source: "phrase:28" },
        { fa: "من الان دارم رانندگی می‌کنم", pin: "man alān dāram rānandegi mikonam", en: "I'm driving right now", source: "phrase:30" },
        { fa: "ولی سارا از خونه تا سر کار رانندگی می‌کنه.", pin: "Vali Sārā az khooneh tā sar-e kār rānandegi mikoneh.", en: "But Sara drives from home to work.", source: "story:st-30-1" },
        { fa: "اون از خونه‌ی خودش تا خونه‌ی مامان‌بزرگ رانندگی می‌کنه.", pin: "Oon az khoone-ye khodesh tā khoone-ye māmānbozorg rānandegi mikoneh.", en: "She drives from her own home to Grandma's house.", source: "story:st-30-2" },
      ] },
    { id: "28.v.be", type: "vocabulary", fa: "به", pin: "be", en: "to, toward", notes: "preposition, comes before the noun",
      examples: [
        { fa: "سال دیگه به ایران سفر می‌کنم", pin: "sāl-e dige be Irān safar mikonam", en: "I'll travel to Iran next year", source: "phrase:28" },
        { fa: "امروز من و دوستم به رستوران مریم می‌ریم.", pin: "Emrooz man o doostam be restorān-e Maryam mirim.", en: "Today my friend and I are going to Maryam's restaurant.", source: "story:st-2425-1" },
        { fa: "ساعت یک ربع به نهه", pin: "sā’at yek rob be noh-e", en: "It's a quarter to 9 (8:45)", source: "phrase:26" },
        { fa: "علی: «به سلامتی!»", pin: "Ali: \"Be salāmati!\"", en: "Ali: \"Cheers!\"", source: "story:st-23-1" },
      ] },
    // Grammar
    { id: "28.g.miram", type: "grammar", fa: "می‌رم", pin: "miram", en: "I go", notes: "می + ر + م" },
    { id: "28.g.miri", type: "grammar", fa: "می‌ری", pin: "miri", en: "you go", notes: "می + ر + ی" },
    { id: "28.g.mireh", type: "grammar", fa: "می‌ره", pin: "mireh", en: "he/she goes", notes: "می + ر + ه" },
    { id: "28.g.mirim", type: "grammar", fa: "می‌ریم", pin: "mirim", en: "we go", notes: "می + ر + یم" },
    { id: "28.g.mirid", type: "grammar", fa: "می‌رید", pin: "mirid", en: "you (pl) go", notes: "می + ر + ید" },
    { id: "28.g.miran", type: "grammar", fa: "می‌رن", pin: "miran", en: "they go", notes: "می + ر + ن" },
    { id: "28.g.nemiram", type: "grammar", fa: "نمی‌رم", pin: "nemiram", en: "I don't go", notes: "نمی + ر + م" },
    { id: "28.g.daram-mikhoram", type: "grammar", fa: "دارم می‌خورم", pin: "dāram mikhoram", en: "I am eating (right now)", notes: "دارم (I have) + می‌خورم — present continuous" },
    { id: "28.g.dari-mikhori", type: "grammar", fa: "داری می‌خوری", pin: "dāri mikhori", en: "you are eating", notes: "داری + می‌خوری" },
    { id: "28.g.dareh-mikhoreh", type: "grammar", fa: "داره می‌خوره", pin: "dāreh mikhoreh", en: "he/she is eating", notes: "داره + می‌خوره" },
    { id: "28.g.darim-mikhorim", type: "grammar", fa: "داریم می‌خوریم", pin: "dārim mikhorim", en: "we are eating", notes: "داریم + می‌خوریم" },
    { id: "28.g.daran-mikhoran", type: "grammar", fa: "دارن می‌خورن", pin: "dāran mikhoran", en: "they are eating", notes: "دارن + می‌خورن" },
    // Phrases
    { id: "28.p.man-alan-daram-ketab-mikhoonam", type: "phrases", fa: "من الان دارم کتاب می‌خونم", pin: "man alān dāram ketāb mikhoonam", en: "I'm reading a book right now", notes: "الان (now) + present continuous" },
    { id: "28.p.oon-alan-dareh-ghaza-mikhoreh", type: "phrases", fa: "اون الان داره غذا می‌خوره", pin: "oon alān dāreh ghazā mikhoreh", en: "He/she is eating right now", notes: "داره + می‌خوره" },
    { id: "28.p.to-alan-dari-ghaza-mikhori", type: "phrases", fa: "تو الان داری غذا می‌خوری؟", pin: "to alān dāri ghazā mikhori?", en: "Are you eating right now?", notes: "داری + می‌خوری" },
    { id: "28.p.oon-dareh-ranandegi-mikoneh", type: "phrases", fa: "اون داره رانندگی می‌کنه", pin: "oon dāreh rānandegi mikoneh", en: "He/she is driving", notes: "داره + رانندگی می‌کنه" },
    { id: "28.p.ye-soal-e-dige-daram", type: "phrases", fa: "یه سوال دیگه دارم", pin: "ye soāl-e dige dāram", en: "I have another question", notes: "سوالِ دیگه (another question)" },
    { id: "28.p.ye-bastani-e-dige-mikhay", type: "phrases", fa: "یه بستنی دیگه می‌خوای؟", pin: "ye bastani-e dige mikhāy?", en: "Do you want another ice cream?", notes: "دیگه (another) + می‌خوای (you want)" },
    { id: "28.p.man-yeki-dige-mikham", type: "phrases", fa: "من یکی دیگه می‌خوام", pin: "man yeki dige mikhām", en: "I want another one / one more", notes: "یکی (one) + دیگه" },
    { id: "28.p.man-ye-chiz-e-dige-mikham", type: "phrases", fa: "من یه چیز دیگه می‌خوام", pin: "man ye chiz-e dige mikhām", en: "I want something else", notes: "چیزِ دیگه (another thing)" },
    { id: "28.p.dige-chi", type: "phrases", fa: "دیگه چی؟", pin: "dige chi?", en: "What else?", notes: "دیگه (else) + چی (what)" },
    { id: "28.p.ma-hamdige-ro-doost-darim", type: "phrases", fa: "ما همدیگه رو دوست داریم", pin: "mā hamdige ro doost dārim", en: "We love each other", notes: "همدیگه (each other) + رو (object marker)" },
    { id: "28.p.ma-ba-hamdige-zendegi-mikonim", type: "phrases", fa: "ما با همدیگه زندگی می‌کنیم", pin: "mā bā hamdige zendegi mikonim", en: "We live together", notes: "با همدیگه (with each other)" },
    { id: "28.p.emshab-ma-ba-hamdige-sham", type: "phrases", fa: "امشب ما با همدیگه شام می‌خوریم", pin: "emshab mā bā hamdige shām mikhorim", en: "Tonight we'll eat dinner together", notes: "present tense used for future" },
    { id: "28.p.farda-man-o-doostam-ba-hamdige", type: "phrases", fa: "فردا من و دوستم با همدیگه ناهار می‌خوریم", pin: "fardā man o doostam bā hamdige nāhār mikhorim", en: "Tomorrow my friend and I are having lunch together", notes: "present-for-future (planned)" },
    { id: "28.p.man-farda-kar-nemikonam", type: "phrases", fa: "من فردا کار نمی‌کنم", pin: "man fardā kār nemikonam", en: "I'm not working tomorrow", notes: "فردا + نمی‌کنم" },
    { id: "28.p.dar-ayande-ma-inja-nistim", type: "phrases", fa: "در آینده ما اینجا نیستیم", pin: "dar āyande mā injā nistim", en: "In the future, we won't be here", notes: "در آینده (in the future)" },
    { id: "28.p.sal-e-dige-be-iran-safar-mikonam", type: "phrases", fa: "سال دیگه به ایران سفر می‌کنم", pin: "sāl-e dige be Irān safar mikonam", en: "I'll travel to Iran next year", notes: "سال دیگه + سفر می‌کنم" },
    { id: "28.p.man-be-cinema-miram", type: "phrases", fa: "من به سینما می‌رم", pin: "man be cinemā miram", en: "I'm going to the cinema", notes: "به (to) + می‌رم" },
    { id: "28.p.man-be-madrese-nemiram", type: "phrases", fa: "من به مدرسه نمی‌رم", pin: "man be madrese nemiram", en: "I don't go to school", notes: "به + نمی‌رم" },
    { id: "28.p.ma-emrooz-be-ketab-khoone-mirim", type: "phrases", fa: "ما امروز به کتابخونه می‌ریم", pin: "mā emrooz be ketāb-khoone mirim", en: "Today we're going to the library", notes: "کتابخونه (library)" },
    { id: "28.p.boro-khoone", type: "phrases", fa: "برو خونه!", pin: "boro khoone!", en: "Go home!", notes: "برو = imperative of رفتن" },
    { id: "28.p.emrooz-naro-sar-e-kar", type: "phrases", fa: "امروز نرو سر کار!", pin: "emrooz naro sar-e kār!", en: "Don't go to work today!", notes: "نرو = negative imperative" },
    { id: "28.p.lotfan-berid-sar-e-kar", type: "phrases", fa: "لطفاً برید سر کار!", pin: "lotfan berid sar-e kār!", en: "Please go to work! (pl)", notes: "برید = plural imperative" },
    { id: "28.p.in-ketab-ha-ro-nemikham", type: "phrases", fa: "این کتاب‌ها رو نمی‌خوام", pin: "in ketāb-hā ro nemikhām", en: "I don't want these books", notes: "این ... ها (these) + رو" },
    { id: "28.p.in-rooz-ha-kheili-khasta-am", type: "phrases", fa: "این روزها خیلی خسته‌ام", pin: "in rooz-hā kheili khasta-am", en: "I'm very tired these days", notes: "این روزها (these days)" },
  ],
});
