// Session 29.
// Item ids are permanent. Never change or reuse one; add new items with new ids.
F.lesson({
  id: "29",
  label: "Session 29",
  summary: "residan, ki/che kasi, māl-e possessives, reflexives, morāgheb",
  items: [
    // Vocabulary
    { id: "29.v.residan", type: "vocabulary", fa: "رسیدن", pin: "residan", en: "to arrive", notes: "present stem: رس (res)",
      examples: [
        { fa: "ببخشید، من کمی دیر می‌رسم", pin: "bebakhshid, man kami dir miresam", en: "Sorry, I'm running a bit late", source: "phrase:29" },
        { fa: "سارا همیشه زود می‌رسه، ولی علی همیشه دیر می‌رسه.", pin: "Sārā hamisheh zood mireseh, vali Ali hamisheh dir mireseh.", en: "Sara always arrives early, but Ali always arrives late.", source: "story:st-29-1" },
        { fa: "من سر وقت نمی‌رسم", pin: "man sar-e vaght nemiresam", en: "I won't arrive on time", source: "phrase:29" },
        { fa: "ساعت چند می‌رسی؟", pin: "sāat-e chand miresi?", en: "What time do you arrive?", source: "phrase:29" },
      ] },
    { id: "29.v.dir", type: "vocabulary", fa: "دیر", pin: "dir", en: "late", notes: "د-ی-ر",
      examples: [
        { fa: "ببخشید دیر شد!", pin: "bebakhshid dir shod!", en: "Sorry I'm late! (it got late)", source: "phrase:29" },
        { fa: "سارا همیشه زود می‌رسه، ولی علی همیشه دیر می‌رسه.", pin: "Sārā hamisheh zood mireseh, vali Ali hamisheh dir mireseh.", en: "Sara always arrives early, but Ali always arrives late.", source: "story:st-29-1" },
        { fa: "ببخشید، من کمی دیر می‌رسم", pin: "bebakhshid, man kami dir miresam", en: "Sorry, I'm running a bit late", source: "phrase:29" },
        { fa: "پنج دقیقه بعد، علی می‌رسه و می‌گه: «ببخشید دیر شد!»", pin: "Panj daghigheh ba'd, Ali mireseh va migeh: \"Bebakhshid dir shod!\"", en: "Five minutes later, Ali arrives and says: \"Sorry I'm late!\"", source: "story:st-29-1" },
      ] },
    { id: "29.v.zood", type: "vocabulary", fa: "زود", pin: "zood", en: "early, soon, quick", notes: "ز-و-د",
      examples: [
        { fa: "من همیشه زود می‌رسم", pin: "man hamishe zood miresam", en: "I always arrive early", source: "phrase:29" },
        { fa: "سارا همیشه زود می‌رسه، ولی علی همیشه دیر می‌رسه.", pin: "Sārā hamisheh zood mireseh, vali Ali hamisheh dir mireseh.", en: "Sara always arrives early, but Ali always arrives late.", source: "story:st-29-1" },
        { fa: "صُبحِ زود بیدار میشم و صُبحانه دُرُست می‌کنم.", pin: "Sobh-e zood bidār misham va sobhāneh dorost mikonam.", en: "I wake up early and make breakfast.", source: "story:34" },
        { fa: "زود باش!", pin: "zood bāsh!", en: "Hurry up! Be quick!", source: "phrase:29" },
      ] },
    { id: "29.v.sar-e-vaght", type: "vocabulary", fa: "سر وقت", pin: "sar-e vaght", en: "on time", notes: "سر (head) + وقت (time)",
      examples: [
        { fa: "من سر وقت نمی‌رسم", pin: "man sar-e vaght nemiresam", en: "I won't arrive on time", source: "phrase:29" },
        { fa: "سارا سر وقت به کلاس می‌رسه.", pin: "Sārā sar-e vaght be kelās mireseh.", en: "Sara arrives at the class on time.", source: "story:st-29-1" },
      ] },
    { id: "29.v.ki", type: "vocabulary", fa: "کی", pin: "ki", en: "who (informal)", notes: "ک-ی — careful: kay = when!",
      examples: [
        { fa: "تو کی هستی؟", pin: "to ki hasti?", en: "Who are you?", source: "phrase:29" },
        { fa: "سارا می‌گه: «این خودکار مال کیه؟»", pin: "Sārā migeh: \"In khodkār māl-e ki-eh?\"", en: "Sara says: \"Whose pen is this, then?\"", source: "story:st-29-1" },
        { fa: "تو کی صبحونه میخوری؟", pin: "to kay sobhooneh mikhori?", en: "When do you eat breakfast?", source: "phrase:26" },
        { fa: "کی اینجا زندگی می‌کنه؟", pin: "ki injā zendegi mikoneh?", en: "Who lives here?", source: "phrase:29" },
      ] },
    { id: "29.v.che-kasi", type: "vocabulary", fa: "چه کسی", pin: "che kasi", en: "who (formal)", notes: "چه (what) + کسی (person)" },
    { id: "29.v.kas", type: "vocabulary", fa: "کس", pin: "kas", en: "person", notes: "ک-س" },
    { id: "29.v.kasi", type: "vocabulary", fa: "کسی", pin: "kasi", en: "someone, anyone", notes: "کس + ی",
      examples: [
        { fa: "کسی اینجا هست؟", pin: "kasi injā hast?", en: "Is there anyone here?", source: "phrase:29" },
        { fa: "کسی اینجا نیست، ولی یه خودکار و یه مداد اینجا هست.", pin: "Kasi injā nist, vali ye khodkār o ye medād injā hast.", en: "No one is here, but there's a pen and a pencil here.", source: "story:st-29-1" },
        { fa: "اون می‌گه: «کسی اینجا هست؟»", pin: "Oon migeh: \"Kasi injā hast?\"", en: "She says: \"Is anyone here?\"", source: "story:st-29-1" },
      ] },
    { id: "29.v.har-kas", type: "vocabulary", fa: "هر کس", pin: "har kas", en: "everyone, anyone, whoever", notes: "هر (every) + کس" },
    { id: "29.v.mal", type: "vocabulary", fa: "مال", pin: "māl", en: "property, belonging", notes: "م-ا-ل",
      examples: [
        { fa: "این کتاب مال منه", pin: "in ketāb māl-e man-e", en: "This book is mine", source: "phrase:29" },
        { fa: "سارا می‌گه: «این خودکار مال توئه؟»", pin: "Sārā migeh: \"In khodkār māl-e to-eh?\"", en: "Sara says: \"Is this pen yours?\"", source: "story:st-29-1" },
        { fa: "این کیف مال اونه", pin: "in kif māl-e oon-e", en: "This bag is hers/his", source: "phrase:29" },
        { fa: "این مال من نیست", pin: "in māl-e man nist", en: "This is not mine", source: "phrase:29" },
      ] },
    { id: "29.v.mal-e-man", type: "vocabulary", fa: "مال من", pin: "māl-e man", en: "mine", notes: "'property of me'",
      examples: [
        { fa: "این کتاب مال منه", pin: "in ketāb māl-e man-e", en: "This book is mine", source: "phrase:29" },
        { fa: "علی می‌گه: «نه، مال من نیست. این مداد مال منه.»", pin: "Ali migeh: \"Na, māl-e man nist. In medād māl-e man-eh.\"", en: "Ali says: \"No, it's not mine. This pencil is mine.\"", source: "story:st-29-1" },
        { fa: "این مال من نیست", pin: "in māl-e man nist", en: "This is not mine", source: "phrase:29" },
        { fa: "بعد مریم می‌رسه و می‌گه: «اون خودکار مال منه!»", pin: "Ba'd Maryam mireseh va migeh: \"Oon khodkār māl-e man-eh!\"", en: "Then Maryam arrives and says: \"That pen is mine!\"", source: "story:st-29-1" },
      ] },
    { id: "29.v.mal-e-to", type: "vocabulary", fa: "مال تو", pin: "māl-e to", en: "yours", notes: "مال + تو" },
    { id: "29.v.mal-e-oon", type: "vocabulary", fa: "مال اون", pin: "māl-e oon", en: "his, hers", notes: "مال + اون",
      examples: [
        { fa: "این کیف مال اونه", pin: "in kif māl-e oon-e", en: "This bag is hers/his", source: "phrase:29" },
      ] },
    { id: "29.v.mal-e-ma", type: "vocabulary", fa: "مال ما", pin: "māl-e mā", en: "ours", notes: "مال + ما" },
    { id: "29.v.mal-e-shoma", type: "vocabulary", fa: "مال شما", pin: "māl-e shomā", en: "yours (pl/formal)", notes: "مال + شما" },
    { id: "29.v.mal-e-oonha", type: "vocabulary", fa: "مال اونها", pin: "māl-e oonhā", en: "theirs", notes: "مال + اونها" },
    { id: "29.v.medad", type: "vocabulary", fa: "مداد", pin: "medād", en: "pencil", notes: "م-د-ا-د",
      examples: [
        { fa: "کسی اینجا نیست، ولی یه خودکار و یه مداد اینجا هست.", pin: "Kasi injā nist, vali ye khodkār o ye medād injā hast.", en: "No one is here, but there's a pen and a pencil here.", source: "story:st-29-1" },
        { fa: "علی می‌گه: «نه، مال من نیست. این مداد مال منه.»", pin: "Ali migeh: \"Na, māl-e man nist. In medād māl-e man-eh.\"", en: "Ali says: \"No, it's not mine. This pencil is mine.\"", source: "story:st-29-1" },
      ] },
    { id: "29.v.ghalam", type: "vocabulary", fa: "قلم", pin: "ghalam", en: "pen, writing instrument (general)", notes: "ق-ل-م" },
    { id: "29.v.ahl-e-ghalam", type: "vocabulary", fa: "اهل قلم", pin: "ahl-e ghalam", en: "writer, person of letters", notes: "اهل (people of) + قلم" },
    { id: "29.v.khod", type: "vocabulary", fa: "خود", pin: "khod", en: "self", notes: "خ-و-د" },
    { id: "29.v.khodam", type: "vocabulary", fa: "خودم", pin: "khodam", en: "myself", notes: "خود + م",
      examples: [
        { fa: "من هر روز خودم رو می‌شورم", pin: "man har rooz khodam ro mishooram", en: "I wash myself every day", source: "phrase:29" },
        { fa: "من خودم شام درست می‌کنم", pin: "man khodam shām dorost mikonam", en: "I cook dinner myself", source: "phrase:29" },
        { fa: "من مراقب خودم هستم", pin: "man morāgheb-e khodam hastam", en: "I look after myself", source: "phrase:29" },
      ] },
    { id: "29.v.khodet", type: "vocabulary", fa: "خودت", pin: "khodet", en: "yourself", notes: "خود + ت",
      examples: [
        { fa: "مراقب خودت باش!", pin: "morāgheb-e khodet bāsh!", en: "Take care of yourself!", source: "phrase:29" },
        { fa: "اینجا خونه‌ی خودته! راحت باش!", pin: "injā khoone-ye khodet-e! rāhat bāsh!", en: "This is your home! Make yourself comfortable!", source: "phrase:29" },
        { fa: "مامان‌بزرگ می‌گه: «مراقب خودت باش!»", pin: "Māmānbozorg migeh: \"Morāgheb-e khodet bāsh!\"", en: "Grandma says: \"Take care of yourself!\"", source: "story:st-30-2" },
        { fa: "مامان گفت: «مراقب خودت باش!»", pin: "Māmān goft: \"Morāgheb-e khodet bāsh!\"", en: "Mom said: \"Take care of yourself!\"", source: "story:st-32-2" },
      ] },
    { id: "29.v.khodesh", type: "vocabulary", fa: "خودش", pin: "khodesh", en: "himself, herself, itself", notes: "خود + ش",
      examples: [
        { fa: "گربه‌ام هر روز خودش رو تمیز می‌کنه", pin: "gorbe-am har rooz khodesh ro tamiz mikoneh", en: "My cat cleans itself every day", source: "phrase:29" },
        { fa: "اون از خونه‌ی خودش تا خونه‌ی مامان‌بزرگ رانندگی می‌کنه.", pin: "Oon az khoone-ye khodesh tā khoone-ye māmānbozorg rānandegi mikoneh.", en: "She drives from her own home to Grandma's house.", source: "story:st-30-2" },
      ] },
    { id: "29.v.khodemoon", type: "vocabulary", fa: "خودمون", pin: "khodemoon", en: "ourselves", notes: "خود + مون" },
    { id: "29.v.khodetoon", type: "vocabulary", fa: "خودتون", pin: "khodetoon", en: "yourselves", notes: "خود + تون",
      examples: [
        { fa: "مراقب خودتون باشید!", pin: "morāgheb-e khodetoon bāshid!", en: "Take care of yourselves! (pl/formal)", source: "phrase:29" },
      ] },
    { id: "29.v.khodeshoon", type: "vocabulary", fa: "خودشون", pin: "khodeshoon", en: "themselves", notes: "خود + شون" },
    { id: "29.v.moragheb", type: "vocabulary", fa: "مراقب", pin: "morāgheb", en: "careful, watchful", notes: "م-ر-ا-ق-ب",
      examples: [
        { fa: "مراقب خودت باش!", pin: "morāgheb-e khodet bāsh!", en: "Take care of yourself!", source: "phrase:29" },
        { fa: "علی می‌خنده و می‌گه: «مراقب خودکارت باش!»", pin: "Ali mikhandeh va migeh: \"Morāgheb-e khodkāret bāsh!\"", en: "Ali laughs and says: \"Look after your pen!\"", source: "story:st-29-1" },
        { fa: "مراقب خودتون باشید!", pin: "morāgheb-e khodetoon bāshid!", en: "Take care of yourselves! (pl/formal)", source: "phrase:29" },
        { fa: "من مراقب خودم هستم", pin: "man morāgheb-e khodam hastam", en: "I look after myself", source: "phrase:29" },
      ] },
    // Grammar
    { id: "29.g.miresam", type: "grammar", fa: "می‌رسم", pin: "miresam", en: "I arrive", notes: "می + رس + م" },
    { id: "29.g.miresi", type: "grammar", fa: "می‌رسی", pin: "miresi", en: "you arrive", notes: "می + رس + ی" },
    { id: "29.g.mireseh", type: "grammar", fa: "می‌رسه", pin: "mireseh", en: "he/she arrives", notes: "می + رس + ه" },
    { id: "29.g.miresim", type: "grammar", fa: "می‌رسیم", pin: "miresim", en: "we arrive", notes: "می + رس + یم" },
    { id: "29.g.miresid", type: "grammar", fa: "می‌رسید", pin: "miresid", en: "you (pl) arrive", notes: "می + رس + ید" },
    { id: "29.g.miresan", type: "grammar", fa: "می‌رسن", pin: "miresan", en: "they arrive", notes: "می + رس + ن" },
    { id: "29.g.nemiresam", type: "grammar", fa: "نمی‌رسم", pin: "nemiresam", en: "I won't make it / I don't arrive", notes: "نمی + رس + م" },
    // Phrases
    { id: "29.p.bebakhshid-dir-shod", type: "phrases", fa: "ببخشید دیر شد!", pin: "bebakhshid dir shod!", en: "Sorry I'm late! (it got late)", notes: "دیر (late) + شد (became)" },
    { id: "29.p.bebakhshid-man-kami-dir-miresam", type: "phrases", fa: "ببخشید، من کمی دیر می‌رسم", pin: "bebakhshid, man kami dir miresam", en: "Sorry, I'm running a bit late", notes: "کمی (a bit) + دیر می‌رسم" },
    { id: "29.p.oon-alan-mireseh", type: "phrases", fa: "اون الان می‌رسه", pin: "oon alān mireseh", en: "He/she is arriving now", notes: "الان (now)" },
    { id: "29.p.man-sar-e-vaght-nemiresam", type: "phrases", fa: "من سر وقت نمی‌رسم", pin: "man sar-e vaght nemiresam", en: "I won't arrive on time", notes: "سر وقت (on time)" },
    { id: "29.p.kay-miresi", type: "phrases", fa: "کی می‌رسی؟", pin: "kay miresi?", en: "When do you arrive?", notes: "کی here = when (kay)" },
    { id: "29.p.saat-e-chand-miresi", type: "phrases", fa: "ساعت چند می‌رسی؟", pin: "sāat-e chand miresi?", en: "What time do you arrive?", notes: "ساعت چند (what time)" },
    { id: "29.p.man-hamishe-zood-miresam", type: "phrases", fa: "من همیشه زود می‌رسم", pin: "man hamishe zood miresam", en: "I always arrive early", notes: "همیشه (always) + زود (early)" },
    { id: "29.p.man-panj-daghighe-ye-dige", type: "phrases", fa: "من پنج دقیقه دیگه می‌رسم", pin: "man panj daghighe-ye dige miresam", en: "I'll arrive in 5 minutes", notes: "پنج دقیقه دیگه (in 5 minutes)" },
    { id: "29.p.zood-bash", type: "phrases", fa: "زود باش!", pin: "zood bāsh!", en: "Hurry up! Be quick!", notes: "زود (quick) + باش (be)" },
    { id: "29.p.to-ki-hasti", type: "phrases", fa: "تو کی هستی؟", pin: "to ki hasti?", en: "Who are you?", notes: "کی (who) + هستی" },
    { id: "29.p.ki-e", type: "phrases", fa: "کیه؟", pin: "ki-e?", en: "Who is it?", notes: "کی + ه (is)" },
    { id: "29.p.ki-inja-zendegi-mikoneh", type: "phrases", fa: "کی اینجا زندگی می‌کنه؟", pin: "ki injā zendegi mikoneh?", en: "Who lives here?", notes: "کی (who) + زندگی می‌کنه" },
    { id: "29.p.ki-chay-mikhad", type: "phrases", fa: "کی چای می‌خواد؟", pin: "ki chāy mikhād?", en: "Who wants tea?", notes: "می‌خواد (wants)" },
    { id: "29.p.shoma-ba-ki-zendegi-mikonid", type: "phrases", fa: "شما با کی زندگی می‌کنید؟", pin: "shomā bā ki zendegi mikonid?", en: "Who do you live with?", notes: "با کی (with whom)" },
    { id: "29.p.ki-morgh-sefaresh-mideh", type: "phrases", fa: "کی مرغ سفارش می‌ده؟", pin: "ki morgh sefāresh mideh?", en: "Who is ordering chicken?", notes: "سفارش می‌ده (orders)" },
    { id: "29.p.kasi-inja-hast", type: "phrases", fa: "کسی اینجا هست؟", pin: "kasi injā hast?", en: "Is there anyone here?", notes: "کسی (anyone) + هست" },
    { id: "29.p.in-ketab-mal-e-man-e", type: "phrases", fa: "این کتاب مال منه", pin: "in ketāb māl-e man-e", en: "This book is mine", notes: "مال من + ه (is)" },
    { id: "29.p.in-kif-mal-e-oon-e", type: "phrases", fa: "این کیف مال اونه", pin: "in kif māl-e oon-e", en: "This bag is hers/his", notes: "کیف (bag)" },
    { id: "29.p.in-khodkar-mal-e-to-e", type: "phrases", fa: "این خودکار مال توئه؟", pin: "in khodkār māl-e to-e?", en: "Is this pen yours?", notes: "مال تو + ئه (is)" },
    { id: "29.p.in-mal-e-man-nist", type: "phrases", fa: "این مال من نیست", pin: "in māl-e man nist", en: "This is not mine", notes: "نیست (is not)" },
    { id: "29.p.in-mal-e-ki-e", type: "phrases", fa: "این مال کیه؟", pin: "in māl-e ki-e?", en: "Whose is this?", notes: "مال کی (whose) + ه" },
    { id: "29.p.man-har-rooz-khodam-ro-mishooram", type: "phrases", fa: "من هر روز خودم رو می‌شورم", pin: "man har rooz khodam ro mishooram", en: "I wash myself every day", notes: "خودم رو (myself) + می‌شورم" },
    { id: "29.p.gorbe-am-har-rooz-khodesh-ro", type: "phrases", fa: "گربه‌ام هر روز خودش رو تمیز می‌کنه", pin: "gorbe-am har rooz khodesh ro tamiz mikoneh", en: "My cat cleans itself every day", notes: "خودش رو (itself)" },
    { id: "29.p.man-khodam-sham-dorost-mikonam", type: "phrases", fa: "من خودم شام درست می‌کنم", pin: "man khodam shām dorost mikonam", en: "I cook dinner myself", notes: "خودم emphasizes 'myself'" },
    { id: "29.p.moragheb-bash", type: "phrases", fa: "مراقب باش!", pin: "morāgheb bāsh!", en: "Watch out! Be careful!", notes: "مراقب (watchful) + باش" },
    { id: "29.p.moragheb-e-khodet-bash", type: "phrases", fa: "مراقب خودت باش!", pin: "morāgheb-e khodet bāsh!", en: "Take care of yourself!", notes: "مراقبِ خودت (of yourself)" },
    { id: "29.p.moragheb-e-khodetoon-bashid", type: "phrases", fa: "مراقب خودتون باشید!", pin: "morāgheb-e khodetoon bāshid!", en: "Take care of yourselves! (pl/formal)", notes: "باشید (be, pl)" },
    { id: "29.p.inja-khoone-ye-khodet-e-rahat", type: "phrases", fa: "اینجا خونه‌ی خودته! راحت باش!", pin: "injā khoone-ye khodet-e! rāhat bāsh!", en: "This is your home! Make yourself comfortable!", notes: "خونه‌ی خودت (your own home)" },
    { id: "29.p.man-moragheb-e-khodam-hastam", type: "phrases", fa: "من مراقب خودم هستم", pin: "man morāgheb-e khodam hastam", en: "I look after myself", notes: "مراقبِ خودم" },
  ],
});
