// Session 30.
// Item ids are permanent. Never change or reuse one; add new items with new ids.
F.lesson({
  id: "30",
  label: "Session 30",
  summary: "counting times (bār), \"per\" suffix (-i), didan, prepositions, az...tā, walking & driving",
  items: [
    // Vocabulary
    { id: "30.v.dobareh", type: "vocabulary", fa: "دوباره", pin: "dobāreh", en: "again", notes: "د-و-باره",
      examples: [
        { fa: "من دوباره برگر سفارش می‌دم", pin: "man dobāreh burger sefāresh midam", en: "I'll order a burger again", source: "phrase:30" },
        { fa: "راننده می‌خنده و می‌گه: «فردا دوباره می‌بینمت!»", pin: "Rānandeh mikhandeh va migeh: \"Fardā dobāreh mibinamet!\"", en: "The driver laughs and says: \"See you again tomorrow!\"", source: "story:st-30-1" },
        { fa: "ساعت هفت، سارا می‌گه: «هفته‌ی دیگه دوباره می‌بینمت!»", pin: "Sāat-e haft, Sārā migeh: \"Hafte-ye dige dobāreh mibinamet!\"", en: "At seven, Sara says: \"See you again next week!\"", source: "story:st-30-2" },
        { fa: "علی می‌خنده و دوباره می‌ره خرید.", pin: "Ali mikhandeh va dobāreh mireh kharid.", en: "Ali laughs and goes shopping again.", source: "story:st-31-1" },
      ] },
    { id: "30.v.bar", type: "vocabulary", fa: "بار", pin: "bār", en: "time, instance (countable)", notes: "ب-ا-ر",
      examples: [
        { fa: "من هزار بار می‌گم عاشقتم", pin: "man hezār bār migam āsheghetam", en: "I say a thousand times, I love you", source: "phrase:30" },
        { fa: "علی هفته‌ای سه بار باشگاه هم می‌ره.", pin: "Ali hafte-i seh bār bāshgāh ham mireh.", en: "Ali also goes to the gym three times a week.", source: "story:st-30-1" },
        { fa: "من دو بار در هفته می‌رم باشگاه", pin: "man do bār dar hafte miram bāshgāh", en: "I go to the gym twice a week", source: "phrase:30" },
        { fa: "من روزی سه بار غذا می‌خورم", pin: "man roozi seh bār ghazā mikhoram", en: "I eat three times a day", source: "phrase:30" },
      ] },
    { id: "30.v.do-bar", type: "vocabulary", fa: "دو بار", pin: "do bār", en: "twice, two times", notes: "دو (two) + بار",
      examples: [
        { fa: "من دو بار در هفته می‌رم باشگاه", pin: "man do bār dar hafte miram bāshgāh", en: "I go to the gym twice a week", source: "phrase:30" },
        { fa: "مامان‌بزرگ خیلی پیر هست، ولی روزی دو بار پیاده‌روی می‌کنه.", pin: "Māmānbozorg kheili pir hast, vali roozi do bār piāderavi mikoneh.", en: "Grandma is very old, but she goes for a walk twice a day.", source: "story:st-30-2" },
        { fa: "من هفته‌ای دو بار می‌رم باشگاه", pin: "man hafte-yi do bār miram bāshgāh", en: "I go to the gym twice a week", source: "phrase:30" },
      ] },
    { id: "30.v.seh-bar", type: "vocabulary", fa: "سه بار", pin: "seh bār", en: "three times", notes: "سه (three) + بار",
      examples: [
        { fa: "من روزی سه بار غذا می‌خورم", pin: "man roozi seh bār ghazā mikhoram", en: "I eat three times a day", source: "phrase:30" },
        { fa: "علی هفته‌ای سه بار باشگاه هم می‌ره.", pin: "Ali hafte-i seh bār bāshgāh ham mireh.", en: "Ali also goes to the gym three times a week.", source: "story:st-30-1" },
        { fa: "من ماهی سه بار مامانم رو می‌بینم", pin: "man māhi seh bār māmānam ro mibinam", en: "I see my mom three times a month", source: "phrase:30" },
        { fa: "سارا ماهی سه بار مامان‌بزرگش رو می‌بینه.", pin: "Sārā māhi seh bār māmānbozorgesh ro mibineh.", en: "Sara sees her grandma three times a month.", source: "story:st-30-2" },
      ] },
    { id: "30.v.dah-bar", type: "vocabulary", fa: "ده بار", pin: "dah bār", en: "ten times", notes: "ده (ten) + بار" },
    { id: "30.v.sad-bar", type: "vocabulary", fa: "صد بار", pin: "sad bār", en: "a hundred times", notes: "صد (hundred) + بار" },
    { id: "30.v.hezar-bar", type: "vocabulary", fa: "هزار بار", pin: "hezār bār", en: "a thousand times", notes: "هزار (thousand) + بار",
      examples: [
        { fa: "من هزار بار می‌گم عاشقتم", pin: "man hezār bār migam āsheghetam", en: "I say a thousand times, I love you", source: "phrase:30" },
      ] },
    { id: "30.v.roozi", type: "vocabulary", fa: "روزی", pin: "roozi", en: "per day, a day", notes: "روز (day) + ی (per)",
      examples: [
        { fa: "من روزی سه بار غذا می‌خورم", pin: "man roozi seh bār ghazā mikhoram", en: "I eat three times a day", source: "phrase:30" },
        { fa: "مامان‌بزرگ خیلی پیر هست، ولی روزی دو بار پیاده‌روی می‌کنه.", pin: "Māmānbozorg kheili pir hast, vali roozi do bār piāderavi mikoneh.", en: "Grandma is very old, but she goes for a walk twice a day.", source: "story:st-30-2" },
      ] },
    { id: "30.v.hafte-yi", type: "vocabulary", fa: "هفته‌ای", pin: "hafte-yi", en: "per week, a week", notes: "هفته (week) + ای (per)",
      examples: [
        { fa: "من هفته‌ای دو بار می‌رم باشگاه", pin: "man hafte-yi do bār miram bāshgāh", en: "I go to the gym twice a week", source: "phrase:30" },
        { fa: "علی هفته‌ای سه بار باشگاه هم می‌ره.", pin: "Ali hafte-i seh bār bāshgāh ham mireh.", en: "Ali also goes to the gym three times a week.", source: "story:st-30-1" },
        { fa: "سارا می‌گه: «مامان‌بزرگ، من هفته‌ای یه بار هم پیاده‌روی نمی‌کنم!»", pin: "Sārā migeh: \"Māmānbozorg, man hafte-i ye bār ham piāderavi nemikonam!\"", en: "Sara says: \"Grandma, I don't even go for a walk once a week!\"", source: "story:st-30-2" },
      ] },
    { id: "30.v.mahi", type: "vocabulary", fa: "ماهی", pin: "māhi", en: "per month, a month", notes: "ماه (month) + ی (per)",
      examples: [
        { fa: "من ماهی سه بار مامانم رو می‌بینم", pin: "man māhi seh bār māmānam ro mibinam", en: "I see my mom three times a month", source: "phrase:30" },
        { fa: "اون گوشت و ماهی نمی‌خوره.", pin: "Oon goosht o māhi nemikhoreh.", en: "She doesn't eat meat or fish.", source: "story:st-23-1" },
        { fa: "سارا ماهی یه بار باشگاه می‌ره!", pin: "Sārā māhi ye bār bāshgāh mireh!", en: "Sara goes to the gym once a month!", source: "story:st-30-1" },
        { fa: "سارا ماهی سه بار مامان‌بزرگش رو می‌بینه.", pin: "Sārā māhi seh bār māmānbozorgesh ro mibineh.", en: "Sara sees her grandma three times a month.", source: "story:st-30-2" },
      ] },
    { id: "30.v.sali", type: "vocabulary", fa: "سالی", pin: "sāli", en: "per year, a year", notes: "سال (year) + ی (per)" },
    { id: "30.v.didan", type: "vocabulary", fa: "دیدن", pin: "didan", en: "to see", notes: "present stem: بین (bin)",
      examples: [
        { fa: "من ماهی سه بار مامانم رو می‌بینم", pin: "man māhi seh bār māmānam ro mibinam", en: "I see my mom three times a month", source: "phrase:30" },
        { fa: "هر روز صبح، علی تو راه یه راننده‌ی تاکسی رو می‌بینه.", pin: "Har rooz sobh, Ali too rāh ye rānande-ye tāksi ro mibineh.", en: "Every morning, Ali sees a taxi driver on the way.", source: "story:st-30-1" },
        { fa: "هفته‌ی دیگه همدیگه رو می‌بینیم", pin: "hafte-ye dige hamdige ro mibinim", en: "We'll see each other next week", source: "phrase:30" },
        { fa: "من فردا تو رو نمی‌بینم", pin: "man fardā to ro nemibinam", en: "I won't see you tomorrow", source: "phrase:30" },
      ] },
    { id: "30.v.va", type: "vocabulary", fa: "و", pin: "va", en: "and", notes: "connector",
      examples: [
        { fa: "راننده می‌خنده و می‌گه: «فردا دوباره می‌بینمت!»", pin: "Rānandeh mikhandeh va migeh: \"Fardā dobāreh mibinamet!\"", en: "The driver laughs and says: \"See you again tomorrow!\"", source: "story:st-30-1" },
        { fa: "فردا من و دوستم با همدیگه ناهار می‌خوریم", pin: "fardā man o doostam bā hamdige nāhār mikhorim", en: "Tomorrow my friend and I are having lunch together", source: "phrase:28" },
        { fa: "کسی اینجا نیست، ولی یه خودکار و یه مداد اینجا هست.", pin: "Kasi injā nist, vali ye khodkār o ye medād injā hast.", en: "No one is here, but there's a pen and a pencil here.", source: "story:st-29-1" },
        { fa: "سارا می‌گه: «چون هوا بارونیه و من سردمه.»", pin: "Sārā migeh: \"Chon havā bārooni-eh va man sardam-eh.\"", en: "Sara says: \"Because it's rainy and I'm cold.\"", source: "story:st-27-1" },
      ] },
    { id: "30.v.ba", type: "vocabulary", fa: "با", pin: "bā", en: "with, by", notes: "preposition",
      examples: [
        { fa: "شما با کی زندگی می‌کنید؟", pin: "shomā bā ki zendegi mikonid?", en: "Who do you live with?", source: "phrase:29" },
        { fa: "اونا با همدیگه زندگی می‌کنن.", pin: "Oonā bā hamdige zendegi mikonan.", en: "They live together.", source: "story:st-28-1" },
        { fa: "من امروز با خونواده‌ام ناهار میخورم", pin: "man emrooz bā khoonevādam nāhār mikhoram", en: "Today I'm having lunch with my family", source: "phrase:26" },
        { fa: "سبزی پلو با ماهی", pin: "sabzi polo bā māhi", en: "herb rice with fish (Nowruz dish)", source: "phrase:23" },
      ] },
    { id: "30.v.ya", type: "vocabulary", fa: "یا", pin: "yā", en: "or", notes: "connector",
      examples: [
        { fa: "بودن یا نبودن، مسئله این است!", pin: "boodan yā naboodan, mas'ale in ast!", en: "To be or not to be, that is the question!", source: "phrase:32" },
      ] },
    { id: "30.v.be", type: "vocabulary", fa: "به", pin: "be", en: "to, toward", notes: "preposition",
      examples: [
        { fa: "من به پیاده‌روی می‌رم", pin: "man be piāderavi miram", en: "I'm heading out for a walk", source: "phrase:30" },
        { fa: "سارا سر وقت به کلاس می‌رسه.", pin: "Sārā sar-e vaght be kelās mireseh.", en: "Sara arrives at the class on time.", source: "story:st-29-1" },
        { fa: "سال دیگه به ایران سفر می‌کنم", pin: "sāl-e dige be Irān safar mikonam", en: "I'll travel to Iran next year", source: "phrase:28" },
        { fa: "ساعت یک ربع به نهه", pin: "sā’at yek rob be noh-e", en: "It's a quarter to 9 (8:45)", source: "phrase:26" },
      ] },
    { id: "30.v.az", type: "vocabulary", fa: "از", pin: "az", en: "from, of", notes: "preposition",
      examples: [
        { fa: "من از ساعت دو تا چهار خونه هستم", pin: "man az sāat-e do tā chahār khoone hastam", en: "I'm at home from 2 to 4", source: "phrase:30" },
        { fa: "سارا می‌گه: «من فردا صبح سر کار می‌رم، ولی بعد از ظهر وقت دارم.»", pin: "Sārā migeh: \"Man fardā sobh sar-e kār miram, vali ba'd az zohr vaght dāram.\"", en: "Sara says: \"I'm going to work tomorrow morning, but I'm free in the afternoon.\"", source: "story:st-28-1" },
        { fa: "از دست من ناراحتی؟", pin: "az dast-e man nārāhati?", en: "Are you upset with me?", source: "phrase:27" },
        { fa: "بعد از غذا، ما دسر و چای می‌خوریم.", pin: "Ba'd az ghazā, mā deser o chāy mikhorim.", en: "After the meal, we have dessert and tea.", source: "story:st-2425-1" },
      ] },
    { id: "30.v.ta", type: "vocabulary", fa: "تا", pin: "tā", en: "until, up to, to", notes: "preposition",
      examples: [
        { fa: "من از ساعت دو تا چهار خونه هستم", pin: "man az sāat-e do tā chahār khoone hastam", en: "I'm at home from 2 to 4", source: "phrase:30" },
        { fa: "علی هر روز از خونه تا سر کار راه می‌ره.", pin: "Ali har rooz az khooneh tā sar-e kār rāh mireh.", en: "Every day Ali walks from home to work.", source: "story:st-30-1" },
        { fa: "من از دوشنبه تا جمعه کار می‌کنم", pin: "man az doshanbe tā jome kār mikonam", en: "I work from Monday to Friday", source: "phrase:30" },
        { fa: "من سه‌شنبه از پنج تا هفت وقت دارم", pin: "man seshanbe az panj tā haft vaght dāram", en: "I'm free on Tuesday from 5 to 7", source: "phrase:30" },
      ] },
    { id: "30.v.rah", type: "vocabulary", fa: "راه", pin: "rāh", en: "road, way, path", notes: "ر-ا-ه",
      examples: [
        { fa: "من از خونه تا سر کار راه می‌رم", pin: "man az khoone tā sar-e kār rāh miram", en: "I walk from home to work", source: "phrase:30" },
        { fa: "علی هر روز از خونه تا سر کار راه می‌ره.", pin: "Ali har rooz az khooneh tā sar-e kār rāh mireh.", en: "Every day Ali walks from home to work.", source: "story:st-30-1" },
        { fa: "هر روز صبح، علی تو راه یه راننده‌ی تاکسی رو می‌بینه.", pin: "Har rooz sobh, Ali too rāh ye rānande-ye tāksi ro mibineh.", en: "Every morning, Ali sees a taxi driver on the way.", source: "story:st-30-1" },
        { fa: "اون از ساعت نه تا ده صبح و از ساعت پنج تا شش بعد از ظهر راه می‌ره.", pin: "Oon az sāat-e noh tā dah-e sobh va az sāat-e panj tā shish-e ba'd az zohr rāh mireh.", en: "She walks from nine to ten in the morning and from five to six in the afternoon.", source: "story:st-30-2" },
      ] },
    { id: "30.v.rah-raftan", type: "vocabulary", fa: "راه رفتن", pin: "rāh raftan", en: "to walk", notes: "راه (way) + رفتن (to go)",
      examples: [
        { fa: "من از خونه تا سر کار راه می‌رم", pin: "man az khoone tā sar-e kār rāh miram", en: "I walk from home to work", source: "phrase:30" },
        { fa: "علی هر روز از خونه تا سر کار راه می‌ره.", pin: "Ali har rooz az khooneh tā sar-e kār rāh mireh.", en: "Every day Ali walks from home to work.", source: "story:st-30-1" },
        { fa: "اون از ساعت نه تا ده صبح و از ساعت پنج تا شش بعد از ظهر راه می‌ره.", pin: "Oon az sāat-e noh tā dah-e sobh va az sāat-e panj tā shish-e ba'd az zohr rāh mireh.", en: "She walks from nine to ten in the morning and from five to six in the afternoon.", source: "story:st-30-2" },
      ] },
    { id: "30.v.piadeh", type: "vocabulary", fa: "پیاده", pin: "piādeh", en: "on foot", notes: "پ-ی-ا-د-ه",
      examples: [
        { fa: "هوا خوبه، من پیاده می‌رم", pin: "havā khoobeh, man piādeh miram", en: "The weather's good, I'm walking", source: "phrase:30" },
        { fa: "راننده می‌گه: «سلام! امروز هم پیاده‌ای؟»", pin: "Rānandeh migeh: \"Salām! Emrooz ham piāde-i?\"", en: "The driver says: \"Hi! On foot again today?\"", source: "story:st-30-1" },
        { fa: "من پیاده‌ام", pin: "man piādeh-am", en: "I'm on foot", source: "phrase:30" },
        { fa: "علی می‌گه: «آره! هوا خوبه، من پیاده می‌رم.»", pin: "Ali migeh: \"Āreh! Havā khoob-eh, man piādeh miram.\"", en: "Ali says: \"Yes! The weather's nice, I'm walking.\"", source: "story:st-30-1" },
      ] },
    { id: "30.v.piadeh-ro", type: "vocabulary", fa: "پیاده‌رو", pin: "piādeh-ro", en: "sidewalk", notes: "پیاده (on foot) + رو" },
    { id: "30.v.piaderavi", type: "vocabulary", fa: "پیاده‌روی", pin: "piāderavi", en: "a walk, walking (for exercise)", notes: "پیاده + روی",
      examples: [
        { fa: "من به پیاده‌روی می‌رم", pin: "man be piāderavi miram", en: "I'm heading out for a walk", source: "phrase:30" },
        { fa: "اون پیاده‌روی رو خیلی دوست داره.", pin: "Oon piāderavi ro kheili doost dāreh.", en: "He really loves walking.", source: "story:st-30-1" },
        { fa: "من هر روز یک ساعت پیاده‌روی می‌کنم", pin: "man har rooz yek sāat piāderavi mikonam", en: "I walk for an hour every day", source: "phrase:30" },
        { fa: "سارا می‌گه: «پیاده‌روی برای من سخته.»", pin: "Sārā migeh: \"Piāderavi barāye man sakht-eh.\"", en: "Sara says: \"Walking is hard for me.\"", source: "story:st-30-1" },
      ] },
    { id: "30.v.piaderavi-kardan", type: "vocabulary", fa: "پیاده‌روی کردن", pin: "piāderavi kardan", en: "to walk (for exercise/leisure)", notes: "پیاده‌روی + کردن",
      examples: [
        { fa: "من هر روز یک ساعت پیاده‌روی می‌کنم", pin: "man har rooz yek sāat piāderavi mikonam", en: "I walk for an hour every day", source: "phrase:30" },
        { fa: "مامان‌بزرگ خیلی پیر هست، ولی روزی دو بار پیاده‌روی می‌کنه.", pin: "Māmānbozorg kheili pir hast, vali roozi do bār piāderavi mikoneh.", en: "Grandma is very old, but she goes for a walk twice a day.", source: "story:st-30-2" },
        { fa: "سارا می‌گه: «مامان‌بزرگ، من هفته‌ای یه بار هم پیاده‌روی نمی‌کنم!»", pin: "Sārā migeh: \"Māmānbozorg, man hafte-i ye bār ham piāderavi nemikonam!\"", en: "Sara says: \"Grandma, I don't even go for a walk once a week!\"", source: "story:st-30-2" },
      ] },
    { id: "30.v.ranande", type: "vocabulary", fa: "راننده", pin: "rānande", en: "driver", notes: "ران (drive) + نده (-er)",
      examples: [
        { fa: "هر روز صبح، علی تو راه یه راننده‌ی تاکسی رو می‌بینه.", pin: "Har rooz sobh, Ali too rāh ye rānande-ye tāksi ro mibineh.", en: "Every morning, Ali sees a taxi driver on the way.", source: "story:st-30-1" },
        { fa: "راننده می‌گه: «سلام! امروز هم پیاده‌ای؟»", pin: "Rānandeh migeh: \"Salām! Emrooz ham piāde-i?\"", en: "The driver says: \"Hi! On foot again today?\"", source: "story:st-30-1" },
        { fa: "راننده می‌خنده و می‌گه: «فردا دوباره می‌بینمت!»", pin: "Rānandeh mikhandeh va migeh: \"Fardā dobāreh mibinamet!\"", en: "The driver laughs and says: \"See you again tomorrow!\"", source: "story:st-30-1" },
      ] },
    { id: "30.v.ranande-ye-taxi", type: "vocabulary", fa: "راننده‌ی تاکسی", pin: "rānande-ye taxi", en: "taxi driver", notes: "راننده + تاکسی",
      examples: [
        { fa: "هر روز صبح، علی تو راه یه راننده‌ی تاکسی رو می‌بینه.", pin: "Har rooz sobh, Ali too rāh ye rānande-ye tāksi ro mibineh.", en: "Every morning, Ali sees a taxi driver on the way.", source: "story:st-30-1" },
      ] },
    { id: "30.v.ranandegi", type: "vocabulary", fa: "رانندگی", pin: "rānandegi", en: "driving", notes: "راننده + گی",
      examples: [
        { fa: "من الان دارم رانندگی می‌کنم", pin: "man alān dāram rānandegi mikonam", en: "I'm driving right now", source: "phrase:30" },
        { fa: "ولی سارا از خونه تا سر کار رانندگی می‌کنه.", pin: "Vali Sārā az khooneh tā sar-e kār rānandegi mikoneh.", en: "But Sara drives from home to work.", source: "story:st-30-1" },
        { fa: "اون داره رانندگی می‌کنه", pin: "oon dāreh rānandegi mikoneh", en: "He/she is driving", source: "phrase:28" },
        { fa: "تو رانندگی رو دوست داری؟", pin: "to rānandegi ro doost dāri?", en: "Do you like driving?", source: "phrase:30" },
      ] },
    { id: "30.v.ranandegi-kardan", type: "vocabulary", fa: "رانندگی کردن", pin: "rānandegi kardan", en: "to drive", notes: "رانندگی (driving) + کردن",
      examples: [
        { fa: "من الان دارم رانندگی می‌کنم", pin: "man alān dāram rānandegi mikonam", en: "I'm driving right now", source: "phrase:30" },
        { fa: "ولی سارا از خونه تا سر کار رانندگی می‌کنه.", pin: "Vali Sārā az khooneh tā sar-e kār rānandegi mikoneh.", en: "But Sara drives from home to work.", source: "story:st-30-1" },
        { fa: "اون داره رانندگی می‌کنه", pin: "oon dāreh rānandegi mikoneh", en: "He/she is driving", source: "phrase:28" },
        { fa: "اون از خونه‌ی خودش تا خونه‌ی مامان‌بزرگ رانندگی می‌کنه.", pin: "Oon az khoone-ye khodesh tā khoone-ye māmānbozorg rānandegi mikoneh.", en: "She drives from her own home to Grandma's house.", source: "story:st-30-2" },
      ] },
    // Grammar
    { id: "30.g.mibinam", type: "grammar", fa: "می‌بینم", pin: "mibinam", en: "I see", notes: "می + بین + م" },
    { id: "30.g.mibini", type: "grammar", fa: "می‌بینی", pin: "mibini", en: "you see", notes: "می + بین + ی" },
    { id: "30.g.mibineh", type: "grammar", fa: "می‌بینه", pin: "mibineh", en: "he/she sees", notes: "می + بین + ه" },
    { id: "30.g.mibinim", type: "grammar", fa: "می‌بینیم", pin: "mibinim", en: "we see", notes: "می + بین + یم" },
    { id: "30.g.mibinid", type: "grammar", fa: "می‌بینید", pin: "mibinid", en: "you (pl) see", notes: "می + بین + ید" },
    { id: "30.g.mibinan", type: "grammar", fa: "می‌بینن", pin: "mibinan", en: "they see", notes: "می + بین + ن" },
    { id: "30.g.nemibinam", type: "grammar", fa: "نمی‌بینم", pin: "nemibinam", en: "I don't see", notes: "نمی + بین + م" },
    { id: "30.g.mibinamet", type: "grammar", fa: "می‌بینمت", pin: "mibinamet", en: "I see you / I'll see you", notes: "می‌بینم + ت (you, object)" },
    { id: "30.g.rah-miram", type: "grammar", fa: "راه می‌رم", pin: "rāh miram", en: "I walk", notes: "راه + می‌رم" },
    // Phrases
    { id: "30.p.man-dobareh-burger-sefaresh", type: "phrases", fa: "من دوباره برگر سفارش می‌دم", pin: "man dobāreh burger sefāresh midam", en: "I'll order a burger again", notes: "دوباره (again) + سفارش می‌دم" },
    { id: "30.p.man-hezar-bar-migam-asheghetam", type: "phrases", fa: "من هزار بار می‌گم عاشقتم", pin: "man hezār bār migam āsheghetam", en: "I say a thousand times, I love you", notes: "هزار بار + عاشقتم" },
    { id: "30.p.man-do-bar-dar-hafte-miram", type: "phrases", fa: "من دو بار در هفته می‌رم باشگاه", pin: "man do bār dar hafte miram bāshgāh", en: "I go to the gym twice a week", notes: "دو بار در هفته" },
    { id: "30.p.man-hafte-yi-do-bar-miram", type: "phrases", fa: "من هفته‌ای دو بار می‌رم باشگاه", pin: "man hafte-yi do bār miram bāshgāh", en: "I go to the gym twice a week", notes: "هفته‌ای (per week)" },
    { id: "30.p.man-roozi-seh-bar-ghaza-mikhoram", type: "phrases", fa: "من روزی سه بار غذا می‌خورم", pin: "man roozi seh bār ghazā mikhoram", en: "I eat three times a day", notes: "روزی (per day) + سه بار" },
    { id: "30.p.man-mahi-seh-bar-mamanam-ro", type: "phrases", fa: "من ماهی سه بار مامانم رو می‌بینم", pin: "man māhi seh bār māmānam ro mibinam", en: "I see my mom three times a month", notes: "ماهی (per month)" },
    { id: "30.p.bebin", type: "phrases", fa: "ببین!", pin: "bebin!", en: "Look!", notes: "imperative of دیدن" },
    { id: "30.p.hafte-ye-dige-mibinamet", type: "phrases", fa: "هفته‌ی دیگه می‌بینمت", pin: "hafte-ye dige mibinamet", en: "I'll see you next week", notes: "می‌بینمت (I'll see you)" },
    { id: "30.p.hafte-ye-dige-hamdige-ro-mibinim", type: "phrases", fa: "هفته‌ی دیگه همدیگه رو می‌بینیم", pin: "hafte-ye dige hamdige ro mibinim", en: "We'll see each other next week", notes: "همدیگه رو + می‌بینیم" },
    { id: "30.p.man-farda-to-ro-nemibinam", type: "phrases", fa: "من فردا تو رو نمی‌بینم", pin: "man fardā to ro nemibinam", en: "I won't see you tomorrow", notes: "نمی‌بینم (won't see)" },
    { id: "30.p.man-farda-shoma-ro-mibinam", type: "phrases", fa: "من فردا شما رو می‌بینم", pin: "man fardā shomā ro mibinam", en: "I'll see you (formal) tomorrow", notes: "شما رو + می‌بینم" },
    { id: "30.p.man-ro-mibini", type: "phrases", fa: "من رو می‌بینی؟", pin: "man ro mibini?", en: "Do you see me?", notes: "من رو (me) + می‌بینی" },
    { id: "30.p.man-az-saat-e-do-ta-chahar", type: "phrases", fa: "من از ساعت دو تا چهار خونه هستم", pin: "man az sāat-e do tā chahār khoone hastam", en: "I'm at home from 2 to 4", notes: "از ... تا ... (from...to...)" },
    { id: "30.p.man-az-doshanbe-ta-jome-kar", type: "phrases", fa: "من از دوشنبه تا جمعه کار می‌کنم", pin: "man az doshanbe tā jome kār mikonam", en: "I work from Monday to Friday", notes: "از دوشنبه تا جمعه" },
    { id: "30.p.man-seshanbe-az-panj-ta-haft", type: "phrases", fa: "من سه‌شنبه از پنج تا هفت وقت دارم", pin: "man seshanbe az panj tā haft vaght dāram", en: "I'm free on Tuesday from 5 to 7", notes: "وقت دارم (have time / am free)" },
    { id: "30.p.man-emrooz-az-saat-e-haft-e-sobh", type: "phrases", fa: "من امروز از ساعت هفت صبح تا ساعت دو شب کار می‌کنم", pin: "man emrooz az sāat-e haft-e sobh tā sāat-e do-e shab kār mikonam", en: "I work from 7 AM to 2 AM today", notes: "صبح (AM) ... شب (night)" },
    { id: "30.p.oon-har-rooz-az-saat-e-haft-e", type: "phrases", fa: "اون هر روز از ساعت هفت صبح تا ساعت دو بعد از ظهر کار می‌کنه", pin: "oon har rooz az sāat-e haft-e sobh tā sāat-e do baad az zohr kār mikoneh", en: "She works from 7 AM to 2 PM every day", notes: "بعد از ظهر (afternoon / PM)" },
    { id: "30.p.man-az-doshanbe-ta-jome", type: "phrases", fa: "من از دوشنبه تا جمعه دانشگاه هستم", pin: "man az doshanbe tā jome dāneshgāh hastam", en: "From Monday to Friday I'm at university", notes: "دانشگاه (university)" },
    { id: "30.p.man-az-khoone-ta-sar-e-kar-rah", type: "phrases", fa: "من از خونه تا سر کار راه می‌رم", pin: "man az khoone tā sar-e kār rāh miram", en: "I walk from home to work", notes: "راه می‌رم (I walk)" },
    { id: "30.p.man-piadeh-am", type: "phrases", fa: "من پیاده‌ام", pin: "man piādeh-am", en: "I'm on foot", notes: "پیاده + ام (I am)" },
    { id: "30.p.hava-khoobeh-man-piadeh-miram", type: "phrases", fa: "هوا خوبه، من پیاده می‌رم", pin: "havā khoobeh, man piādeh miram", en: "The weather's good, I'm walking", notes: "پیاده می‌رم (going on foot)" },
    { id: "30.p.man-be-piaderavi-miram", type: "phrases", fa: "من به پیاده‌روی می‌رم", pin: "man be piāderavi miram", en: "I'm heading out for a walk", notes: "به پیاده‌روی (for a walk)" },
    { id: "30.p.man-har-rooz-yek-saat-piaderavi", type: "phrases", fa: "من هر روز یک ساعت پیاده‌روی می‌کنم", pin: "man har rooz yek sāat piāderavi mikonam", en: "I walk for an hour every day", notes: "پیاده‌روی می‌کنم" },
    { id: "30.p.man-alan-daram-ranandegi-mikonam", type: "phrases", fa: "من الان دارم رانندگی می‌کنم", pin: "man alān dāram rānandegi mikonam", en: "I'm driving right now", notes: "present continuous" },
    { id: "30.p.to-ranandegi-ro-doost-dari", type: "phrases", fa: "تو رانندگی رو دوست داری؟", pin: "to rānandegi ro doost dāri?", en: "Do you like driving?", notes: "رانندگی (driving) as a noun" },
    { id: "30.p.man-az-khoone-ta-sar-e-kar", type: "phrases", fa: "من از خونه تا سر کار رانندگی می‌کنم", pin: "man az khoone tā sar-e kār rānandegi mikonam", en: "I drive from home to work", notes: "از ... تا ... + رانندگی می‌کنم" },
  ],
});
