// Session 31.
// Item ids are permanent. Never change or reuse one; add new items with new ids.
F.lesson({
  id: "31",
  label: "Session 31",
  summary: "transport & savār, place names (-gāh / -khooneh), makeup & ahl-e, buying & selling, -forushi shops, travel, near & far",
  items: [
    // Vocabulary
    { id: "31.v.docharkheh", type: "vocabulary", fa: "دوچرخه", pin: "docharkheh", en: "bicycle, bike", notes: "د-و-چرخه (چرخ = wheel)" },
    { id: "31.v.motorsiklet", type: "vocabulary", fa: "موتورسیکلت", pin: "motorsiklet", en: "motorcycle", notes: "usually shortened to موتور" },
    { id: "31.v.motor", type: "vocabulary", fa: "موتور", pin: "motor", en: "motorbike (colloquial)", notes: "short for موتورسیکلت" },
    { id: "31.v.ghatar", type: "vocabulary", fa: "قطار", pin: "ghatār", en: "train", notes: "ق-ط-ا-ر" },
    { id: "31.v.otobus", type: "vocabulary", fa: "اتوبوس", pin: "otobus", en: "bus", notes: "ا-ت-و-ب-و-س" },
    { id: "31.v.havapeyma", type: "vocabulary", fa: "هواپیما", pin: "havāpeymā", en: "airplane", notes: "هوا (air) + پیما (traverser)" },
    { id: "31.v.savar", type: "vocabulary", fa: "سوار", pin: "savār", en: "mounted, riding, on top of", notes: "سوارِ چیزی = on/riding something" },
    { id: "31.v.docharkheh-savari-kardan", type: "vocabulary", fa: "دوچرخه‌سواری کردن", pin: "docharkheh savāri kardan", en: "to ride a bike, to cycle", notes: "دوچرخه + سواری + کردن" },
    { id: "31.v.asb-savari-kardan", type: "vocabulary", fa: "اسب‌سواری کردن", pin: "asb savāri kardan", en: "to ride a horse", notes: "اسب (horse) + سواری + کردن" },
    { id: "31.v.karkhooneh", type: "vocabulary", fa: "کارخونه", pin: "kārkhooneh", en: "factory", notes: "کار (work) + خونه (house)" },
    { id: "31.v.ashpazkhooneh", type: "vocabulary", fa: "آشپزخونه", pin: "āshpazkhooneh", en: "kitchen", notes: "آشپز (cook) + خونه" },
    { id: "31.v.ketabkhooneh", type: "vocabulary", fa: "کتابخونه", pin: "ketābkhooneh", en: "library", notes: "کتاب (book) + خونه" },
    { id: "31.v.darookhooneh", type: "vocabulary", fa: "داروخونه", pin: "dārookhooneh", en: "pharmacy, chemist's", notes: "دارو (medicine) + خونه" },
    { id: "31.v.golkhooneh", type: "vocabulary", fa: "گلخونه", pin: "golkhooneh", en: "greenhouse", notes: "گل (flower) + خونه" },
    { id: "31.v.bashgah", type: "vocabulary", fa: "باشگاه", pin: "bāshgāh", en: "gym, club", notes: "also باشگاه ورزشی (sports club)" },
    { id: "31.v.foroudgah", type: "vocabulary", fa: "فرودگاه", pin: "foroudgāh", en: "airport", notes: "فرود (landing) + گاه (place)" },
    { id: "31.v.varzeshgah", type: "vocabulary", fa: "ورزشگاه", pin: "varzeshgāh", en: "stadium", notes: "ورزش (sport) + گاه" },
    { id: "31.v.arayeshgah", type: "vocabulary", fa: "آرایشگاه", pin: "ārāyeshgāh", en: "hair salon, barbershop", notes: "آرایش (grooming) + گاه" },
    { id: "31.v.istgah-e-polis", type: "vocabulary", fa: "ایستگاه پلیس", pin: "istgāh-e polis", en: "police station", notes: "ایست (stop) + گاه" },
    { id: "31.v.istgah-e-ghatar", type: "vocabulary", fa: "ایستگاه قطار", pin: "istgāh-e ghatār", en: "railway station", notes: "ایستگاه + قطار" },
    { id: "31.v.istgah-e-otobus", type: "vocabulary", fa: "ایستگاه اتوبوس", pin: "istgāh-e otobus", en: "bus station, bus stop", notes: "ایستگاه + اتوبوس" },
    { id: "31.v.tamirgah", type: "vocabulary", fa: "تعمیرگاه", pin: "tamirgāh", en: "repair shop, garage", notes: "تعمیر (repair) + گاه" },
    { id: "31.v.kargah", type: "vocabulary", fa: "کارگاه", pin: "kārgāh", en: "workshop", notes: "کار (work) + گاه" },
    { id: "31.v.jaygah", type: "vocabulary", fa: "جایگاه", pin: "jāygāh", en: "position, place; status, rank, role", notes: "جای (place) + گاه" },
    { id: "31.v.pomp-e-benzin", type: "vocabulary", fa: "پمپ بنزین", pin: "pomp-e benzin", en: "gas station, petrol station", notes: "also جایگاه سوخت (jāygāh-e sookht)" },
    { id: "31.v.parking", type: "vocabulary", fa: "پارکینگ", pin: "pārking", en: "car park, parking lot", notes: "loanword" },
    { id: "31.v.madreseh", type: "vocabulary", fa: "مدرسه", pin: "madreseh", en: "school", notes: "م-د-ر-س-ه" },
    { id: "31.v.maghazeh", type: "vocabulary", fa: "مغازه", pin: "maghāzeh", en: "shop", notes: "م-غ-ا-ز-ه" },
    { id: "31.v.matab-e-doktor", type: "vocabulary", fa: "مطب دکتر", pin: "matab-e doktor", en: "doctor's office, practice", notes: "مطب (practice) + دکتر" },
    { id: "31.v.mazraeh", type: "vocabulary", fa: "مزرعه", pin: "mazra'eh", en: "farm", notes: "م-ز-ر-ع-ه" },
    { id: "31.v.arayesh", type: "vocabulary", fa: "آرایش", pin: "ārāyesh", en: "makeup", notes: "آ-ر-ا-ی-ش" },
    { id: "31.v.arayeshgar", type: "vocabulary", fa: "آرایشگر", pin: "ārāyeshgar", en: "barber, hairdresser", notes: "آرایش + گر (-er, doer)" },
    { id: "31.v.ahl-e", type: "vocabulary", fa: "اهل", pin: "ahl-e", en: "into (something), a fan of", notes: "اهلِ ورزش = into sports" },
    { id: "31.v.istadan", type: "vocabulary", fa: "ایستادن", pin: "istādan", en: "to stand, to stop", notes: "ا-ی-س-ت-ا-د-ن" },
    { id: "31.v.tamir-kardan", type: "vocabulary", fa: "تعمیر کردن", pin: "tamir kardan", en: "to repair, to service", notes: "تعمیر (repair) + کردن" },
    { id: "31.v.daftar", type: "vocabulary", fa: "دفتر", pin: "daftar", en: "notebook; office; bureau", notes: "دفترچه = small notebook" },
    { id: "31.v.daftar-e-mashgh", type: "vocabulary", fa: "دفتر مشق", pin: "daftar-e mashgh", en: "exercise book", notes: "دفتر + مشق (homework)" },
    { id: "31.v.daftar-e-kar", type: "vocabulary", fa: "دفتر کار", pin: "daftar-e kār", en: "office", notes: "دفتر + کار" },
    { id: "31.v.daftardar", type: "vocabulary", fa: "دفتردار", pin: "daftardār", en: "clerk", notes: "دفتر + دار (keeper)" },
    { id: "31.v.dandoon-pezeshk", type: "vocabulary", fa: "دندون‌پزشک", pin: "dandoon pezeshk", en: "dentist", notes: "دندون (tooth) + پزشک (doctor)" },
    { id: "31.v.dandoon-pezeshki", type: "vocabulary", fa: "دندون‌پزشکی", pin: "dandoon pezeshki", en: "dental clinic, dentistry", notes: "دندون‌پزشک + ی" },
    { id: "31.v.kharid", type: "vocabulary", fa: "خرید", pin: "kharid", en: "shopping, a purchase", notes: "from خریدن" },
    { id: "31.v.kharidar", type: "vocabulary", fa: "خریدار", pin: "kharidār", en: "buyer, purchaser", notes: "خرید + ار" },
    { id: "31.v.kharidan", type: "vocabulary", fa: "خریدن", pin: "kharidan", en: "to buy", notes: "present stem: خر (khar)" },
    { id: "31.v.kharid-kardan", type: "vocabulary", fa: "خرید کردن", pin: "kharid kardan", en: "to shop", notes: "خرید + کردن" },
    { id: "31.v.forukhtan", type: "vocabulary", fa: "فروختن", pin: "forukhtan", en: "to sell", notes: "present stem: فروش (foroosh)" },
    { id: "31.v.foroush", type: "vocabulary", fa: "فروش", pin: "foroush", en: "sale", notes: "from فروختن" },
    { id: "31.v.forushi", type: "vocabulary", fa: "فروشی", pin: "forushi", en: "for sale", notes: "فروش + ی" },
    { id: "31.v.forushgah", type: "vocabulary", fa: "فروشگاه", pin: "forushgāh", en: "store, shop", notes: "فروش + گاه" },
    { id: "31.v.forushande", type: "vocabulary", fa: "فروشنده", pin: "forushande", en: "shop assistant, seller", notes: "فروش + نده (-er)" },
    { id: "31.v.ketab-foroush", type: "vocabulary", fa: "کتاب‌فروش", pin: "ketāb-foroush", en: "bookseller", notes: "noun + فروش = seller of that thing" },
    { id: "31.v.shir-foroush", type: "vocabulary", fa: "شیرفروش", pin: "shir-foroush", en: "milkman, milk seller", notes: "شیر (milk) + فروش" },
    { id: "31.v.miveh-foroush", type: "vocabulary", fa: "میوه‌فروش", pin: "miveh-foroush", en: "greengrocer, fruit seller", notes: "میوه (fruit) + فروش" },
    { id: "31.v.noonvayi", type: "vocabulary", fa: "نونوایی", pin: "noonvāyi", en: "bakery, baker's", notes: "نون (bread) + وایی" },
    { id: "31.v.shirini-forushi", type: "vocabulary", fa: "شیرینی‌فروشی", pin: "shirini-forushi", en: "patisserie, cake shop", notes: "also قنادی (ghannādi)" },
    { id: "31.v.lebas-forushi", type: "vocabulary", fa: "لباس‌فروشی", pin: "lebās-forushi", en: "clothing store", notes: "لباس (clothes) + فروشی" },
    { id: "31.v.ketab-forushi", type: "vocabulary", fa: "کتاب‌فروشی", pin: "ketāb-forushi", en: "bookshop", notes: "کتاب + فروشی" },
    { id: "31.v.miveh-forushi", type: "vocabulary", fa: "میوه‌فروشی", pin: "miveh-forushi", en: "fruit shop, greengrocer's", notes: "also سبزی‌فروشی (sabzi-forushi)" },
    { id: "31.v.goosht-forushi", type: "vocabulary", fa: "گوشت‌فروشی", pin: "goosht-forushi", en: "butcher's", notes: "also قصابی (ghassābi)" },
    { id: "31.v.mahi-forushi", type: "vocabulary", fa: "ماهی‌فروشی", pin: "māhi-forushi", en: "fish market, fishmonger's", notes: "ماهی (fish) + فروشی" },
    { id: "31.v.gol-forushi", type: "vocabulary", fa: "گل‌فروشی", pin: "gol-forushi", en: "flower shop, florist's", notes: "گل (flower) + فروشی" },
    { id: "31.v.kafsh-forushi", type: "vocabulary", fa: "کفش‌فروشی", pin: "kafsh-forushi", en: "shoe store", notes: "کفش (shoe) + فروشی" },
    { id: "31.v.saat-forushi", type: "vocabulary", fa: "ساعت‌فروشی", pin: "sāat-forushi", en: "watchmaker's, watch shop", notes: "ساعت (watch) + فروشی" },
    { id: "31.v.bastani-forushi", type: "vocabulary", fa: "بستنی‌فروشی", pin: "bastani-forushi", en: "ice cream shop", notes: "بستنی (ice cream) + فروشی" },
    { id: "31.v.mosaferat", type: "vocabulary", fa: "مسافرت", pin: "mosāferat", en: "trip", notes: "به مسافرت رفتن = to go on a trip" },
    { id: "31.v.safar", type: "vocabulary", fa: "سفر", pin: "safar", en: "travel, journey", notes: "به سفر رفتن = to go on a trip" },
    { id: "31.v.safar-e-kari", type: "vocabulary", fa: "سفر کاری", pin: "safar-e kāri", en: "work trip, business trip", notes: "سفر + کاری" },
    { id: "31.v.mosafer", type: "vocabulary", fa: "مسافر", pin: "mosāfer", en: "passenger, traveler", notes: "م-س-ا-ف-ر" },
    { id: "31.v.mehmoon-khooneh", type: "vocabulary", fa: "مهمون‌خونه", pin: "mehmoon khooneh", en: "guesthouse, hotel", notes: "مهمون (guest) + خونه" },
    { id: "31.v.mosafer-khooneh", type: "vocabulary", fa: "مسافرخونه", pin: "mosāfer khooneh", en: "motel, hostel", notes: "مسافر + خونه" },
    { id: "31.v.nazdik", type: "vocabulary", fa: "نزدیک", pin: "nazdik", en: "close, near", notes: "ن-ز-د-ی-ک" },
    { id: "31.v.dour", type: "vocabulary", fa: "دور", pin: "dour", en: "far, away", notes: "د-و-ر" },
    // Grammar
    { id: "31.g.mikharam", type: "grammar", fa: "می‌خرم", pin: "mikharam", en: "I buy", notes: "می + خر + م" },
    { id: "31.g.mikhari", type: "grammar", fa: "می‌خری", pin: "mikhari", en: "you buy", notes: "می + خر + ی" },
    { id: "31.g.mikhareh", type: "grammar", fa: "می‌خره", pin: "mikhareh", en: "he/she buys", notes: "می + خر + ه" },
    { id: "31.g.mikharim", type: "grammar", fa: "می‌خریم", pin: "mikharim", en: "we buy", notes: "می + خر + یم" },
    { id: "31.g.mikharid", type: "grammar", fa: "می‌خرید", pin: "mikharid", en: "you (pl) buy", notes: "می + خر + ید" },
    { id: "31.g.mikharan", type: "grammar", fa: "می‌خرن", pin: "mikharan", en: "they buy", notes: "می + خر + ن" },
    { id: "31.g.nemikharam", type: "grammar", fa: "نمی‌خرم", pin: "nemikharam", en: "I don't buy / won't buy", notes: "نمی + خر + م" },
    { id: "31.g.bekhar", type: "grammar", fa: "بخر", pin: "bekhar", en: "buy! (command)", notes: "ب + خر" },
    { id: "31.g.miforusham", type: "grammar", fa: "می‌فروشم", pin: "miforusham", en: "I sell", notes: "می + فروش + م" },
    { id: "31.g.miforushi", type: "grammar", fa: "می‌فروشی", pin: "miforushi", en: "you sell", notes: "می + فروش + ی" },
    { id: "31.g.miforousheh", type: "grammar", fa: "می‌فروشه", pin: "miforousheh", en: "he/she sells", notes: "می + فروش + ه" },
    { id: "31.g.nemiforusham", type: "grammar", fa: "نمی‌فروشم", pin: "nemiforusham", en: "I don't sell", notes: "نمی + فروش + م" },
    { id: "31.g.beforoush", type: "grammar", fa: "بفروش", pin: "beforoush", en: "sell! (command)", notes: "ب + فروش" },
    { id: "31.g.savar-e-hastam", type: "grammar", fa: "سوارِ ... هستم", pin: "savār-e ... hastam", en: "I am on/riding ... (vehicle/animal)", notes: "سوار + ezāfe + vehicle" },
    { id: "31.g.ba-vehicle", type: "grammar", fa: "با + vehicle", pin: "bā + vehicle", en: "by (train, bus, car...)", notes: "با قطار = by train" },
    // Phrases
    { id: "31.p.man-az-khoone-ta-daneshgah", type: "phrases", fa: "من از خونه تا دانشگاه دوچرخه‌سواری می‌کنم", pin: "man az khoone tā dāneshgāh docharkheh savāri mikonam", en: "I ride a bicycle from home to university", notes: "از ... تا ... + دوچرخه‌سواری" },
    { id: "31.p.man-alan-savar-e-ghatar-be-samt", type: "phrases", fa: "من الان سوار قطار به سمت لندن هستم", pin: "man alān savār-e ghatār be samt-e London hastam", en: "I'm on the train to London right now", notes: "به سمتِ (toward) — also به طرفِ (be taraf-e)" },
    { id: "31.p.man-savar-e-otobusam", type: "phrases", fa: "من سوار اتوبوسم", pin: "man savār-e otobusam", en: "I'm on the bus", notes: "سوارِ + اتوبوس + م (am)" },
    { id: "31.p.man-savar-e-ghataram", type: "phrases", fa: "من سوار قطارم", pin: "man savār-e ghatāram", en: "I'm on the train", notes: "سوارِ + قطار" },
    { id: "31.p.man-savar-e-havapeyma-hastam", type: "phrases", fa: "من سوار هواپیما هستم", pin: "man savār-e havāpeymā hastam", en: "I'm on the plane", notes: "سوارِ + هواپیما" },
    { id: "31.p.man-savar-e-asbam", type: "phrases", fa: "من سوار اسبم", pin: "man savār-e asbam", en: "I'm on a horse", notes: "سوارِ + اسب" },
    { id: "31.p.man-asb-savari-mikonam", type: "phrases", fa: "من اسب‌سواری می‌کنم", pin: "man asb savāri mikonam", en: "I ride a horse / I'm horseriding", notes: "اسب‌سواری می‌کنم" },
    { id: "31.p.daram-docharkheh-savari-mikonam", type: "phrases", fa: "دارم دوچرخه‌سواری می‌کنم", pin: "dāram docharkheh savāri mikonam", en: "I'm riding a bike right now", notes: "present continuous" },
    { id: "31.p.man-savar-e-mashinam", type: "phrases", fa: "من سوار ماشینم", pin: "man savār-e māshinam", en: "I'm in the car", notes: "سوارِ + ماشین" },
    { id: "31.p.man-savar-e-taksi-am", type: "phrases", fa: "من سوار تاکسی‌ام", pin: "man savār-e tāksi-am", en: "I'm in a taxi", notes: "سوارِ + تاکسی" },
    { id: "31.p.man-ba-ghatar-be-daneshgah-miram", type: "phrases", fa: "من با قطار به دانشگاه می‌رم", pin: "man bā ghatār be dāneshgāh miram", en: "I go to the university by train", notes: "با (by) + قطار" },
    { id: "31.p.man-ba-otobus-miram", type: "phrases", fa: "من با اتوبوس می‌رم", pin: "man bā otobus miram", en: "I go by bus", notes: "با + اتوبوس" },
    { id: "31.p.man-ba-mashin-miram", type: "phrases", fa: "من با ماشین می‌رم", pin: "man bā māshin miram", en: "I go by car", notes: "با + ماشین" },
    { id: "31.p.oon-tooye-karkhooneh-kar-mikoneh", type: "phrases", fa: "اون توی کارخونه کار می‌کنه", pin: "oon tooye kārkhooneh kār mikoneh", en: "He/she works in a factory", notes: "توی (in) + کارخونه" },
    { id: "31.p.oon-dareh-tooye-ketabkhooneh", type: "phrases", fa: "اون داره توی کتابخونه درس می‌خونه", pin: "oon dāreh tooye ketābkhooneh dars mikhooneh", en: "He/she is studying in the library", notes: "داره ... می‌خونه (continuous)" },
    { id: "31.p.oon-dareh-too-ashpazkhooneh", type: "phrases", fa: "اون داره تو آشپزخونه غذا درست می‌کنه", pin: "oon dāreh too āshpazkhooneh ghazā dorost mikoneh", en: "He/she is cooking in the kitchen", notes: "غذا درست می‌کنه = آشپزی می‌کنه" },
    { id: "31.p.man-har-mah-be-arayeshgah-miram", type: "phrases", fa: "من هر ماه به آرایشگاه می‌رم", pin: "man har māh be ārāyeshgāh miram", en: "I go to the hairdresser's every month", notes: "هر ماه (every month)" },
    { id: "31.p.man-daram-be-istgah-e-ghatar", type: "phrases", fa: "من دارم به ایستگاه قطار می‌رسم", pin: "man dāram be istgāh-e ghatār miresam", en: "I'm just arriving at the railway station", notes: "دارم می‌رسم (arriving now)" },
    { id: "31.p.ghatar-dareh-mireseh", type: "phrases", fa: "قطار داره می‌رسه", pin: "ghatār dāreh mireseh", en: "The train is arriving", notes: "داره می‌رسه" },
    { id: "31.p.man-tooye-parking-hastam", type: "phrases", fa: "من توی پارکینگ هستم", pin: "man tooye pārking hastam", en: "I'm in the car park", notes: "توی + پارکینگ" },
    { id: "31.p.jaygah-e-madar-dar-khanevadeh", type: "phrases", fa: "جایگاه مادر در خانواده بسیار مهم است", pin: "jāygāh-e mādar dar khānevādeh besyār mohem ast", en: "The mother's role in a family is very important", notes: "جایگاه = role/status here" },
    { id: "31.p.man-arayesh-nadaram", type: "phrases", fa: "من آرایش ندارم", pin: "man ārāyesh nadāram", en: "I have no makeup on", notes: "آرایش + ندارم" },
    { id: "31.p.man-har-rooz-yek-kam-arayesh", type: "phrases", fa: "من هر روز یک کم آرایش می‌کنم", pin: "man har rooz yek kam ārāyesh mikonam", en: "I wear a little makeup every day", notes: "یک کم (a little)" },
    { id: "31.p.man-aslan-arayesh-nemikonam", type: "phrases", fa: "من اصلا آرایش نمی‌کنم", pin: "man aslan ārāyesh nemikonam", en: "I don't wear makeup at all", notes: "اصلا (at all)" },
    { id: "31.p.oon-ahl-e-arayesh-nist", type: "phrases", fa: "اون اهل آرایش نیست", pin: "oon ahl-e ārāyesh nist", en: "She's not really into makeup", notes: "اهلِ + نیست" },
    { id: "31.p.oon-ahl-e-varzesh-hast", type: "phrases", fa: "اون اهل ورزش هست", pin: "oon ahl-e varzesh hast", en: "He/she is into sports", notes: "اهلِ ورزش" },
    { id: "31.p.oon-ahl-e-ketab-hast", type: "phrases", fa: "اون اهل کتاب هست", pin: "oon ahl-e ketāb hast", en: "He/she is into books", notes: "اهلِ کتاب" },
    { id: "31.p.arayeshgaram-saresh-sholough-e", type: "phrases", fa: "آرایشگرم سرش شلوغه", pin: "ārāyeshgaram saresh sholough-e", en: "My hairdresser/barber is busy", notes: "سرش شلوغه (lit: their head is busy)" },
    { id: "31.p.man-alan-too-daftaram-hastam", type: "phrases", fa: "من الان تو دفترم هستم", pin: "man alān too daftaram hastam", en: "I'm in my office right now", notes: "دفتر + م (my)" },
    { id: "31.p.pedaram-mazrae-ye-piaz-dareh", type: "phrases", fa: "پدرم مزرعه‌ی پیاز داره!", pin: "pedaram mazra'e-ye piāz dāreh!", en: "My dad has an onion farm!", notes: "مزرعه‌ی + پیاز (onion)" },
    { id: "31.p.man-matab-e-dandoon-pezeshk", type: "phrases", fa: "من مطب دندون‌پزشک هستم", pin: "man matab-e dandoon pezeshk hastam", en: "I'm in the dental clinic", notes: "مطب + دندون‌پزشک" },
    { id: "31.p.man-miram-kharid", type: "phrases", fa: "من می‌رم خرید", pin: "man miram kharid", en: "I'm going shopping", notes: "می‌رم + خرید" },
    { id: "31.p.man-noon-mikharam", type: "phrases", fa: "من نون می‌خرم", pin: "man noon mikharam", en: "I buy bread", notes: "نون + می‌خرم" },
    { id: "31.p.man-in-ro-nemikharam", type: "phrases", fa: "من این رو نمی‌خرم", pin: "man in ro nemikharam", en: "I'm not buying this one", notes: "این رو + نمی‌خرم" },
    { id: "31.p.shir-bekhar", type: "phrases", fa: "شیر بخر", pin: "shir bekhar", en: "Buy some milk", notes: "بخر (imperative)" },
    { id: "31.p.lotfan-noon-bekharid", type: "phrases", fa: "لطفا نون بخرید", pin: "lotfan noon bekharid", en: "Please buy some bread", notes: "بخرید (imperative, pl/formal)" },
    { id: "31.p.man-az-in-maghazeh-kharid", type: "phrases", fa: "من از این مغازه خرید می‌کنم", pin: "man az in maghāzeh kharid mikonam", en: "I shop from this store", notes: "از (from) + خرید می‌کنم" },
    { id: "31.p.noon-nadarim-lotfan-noon-bekhar", type: "phrases", fa: "نون نداریم، لطفا نون بخر!", pin: "noon nadārim, lotfan noon bekhar!", en: "We don't have bread, please buy some bread!", notes: "نداریم (we don't have)" },
    { id: "31.p.ma-dige-shir-nadarim-lotfan-shir", type: "phrases", fa: "ما دیگه شیر نداریم، لطفا شیر می‌خری؟", pin: "mā dige shir nadārim, lotfan shir mikhari?", en: "We're out of milk, will you buy milk please?", notes: "دیگه ... نداریم (no more...)" },
    { id: "31.p.babam-emsal-mashinesh-ro", type: "phrases", fa: "بابام امسال ماشینش رو می‌فروشه", pin: "bābām emsāl māshinesh ro miforousheh", en: "My dad is selling his car this year", notes: "امسال (this year) + ماشینش" },
    { id: "31.p.mashinet-ro-be-man-miforushi", type: "phrases", fa: "ماشینت رو به من می‌فروشی؟", pin: "māshinet ro be man miforushi?", en: "Will you sell your car to me?", notes: "ماشینت رو + به من" },
    { id: "31.p.mashinet-ro-beforoush", type: "phrases", fa: "ماشینت رو بفروش", pin: "māshinet ro beforoush", en: "Sell your car", notes: "بفروش (imperative)" },
    { id: "31.p.man-in-hafteh-be-mosaferat-miram", type: "phrases", fa: "من این هفته به مسافرت می‌رم", pin: "man in hafteh be mosāferat miram", en: "I'm going on a trip this week", notes: "به مسافرت (سفر) می‌رم" },
    { id: "31.p.bebakhshid-agha-istgah-e-otobus", type: "phrases", fa: "ببخشید آقا! ایستگاه اتوبوس به اینجا نزدیکه؟", pin: "bebakhshid āghā! istgāh-e otobus be injā nazdik-e?", en: "Excuse me, sir! Is the bus stop near here?", notes: "نزدیک + ه (is)" },
    { id: "31.p.na-istgah-e-otobus-az-inja", type: "phrases", fa: "نه، ایستگاه اتوبوس از اینجا خیلی دوره", pin: "na, istgāh-e otobus az injā kheili dour-e", en: "No, the bus stop is very far from here", notes: "از اینجا (from here) + دور" },
    { id: "31.p.bashgaham-nazdik-e-khooneh-hast", type: "phrases", fa: "باشگاهم نزدیک خونه هست", pin: "bāshgāham nazdik-e khooneh hast", en: "My gym is near the house", notes: "نزدیکِ + خونه" },
    { id: "31.p.kheili-dour-kheili-nazdik", type: "phrases", fa: "خیلی دور، خیلی نزدیک", pin: "kheili dour, kheili nazdik", en: "So far, so close (Iranian film, 2005)", notes: "Reza Mirkarimi film title" },
  ],
});
