// Session 32.
// Item ids are permanent. Never change or reuse one; add new items with new ids.
F.lesson({
  id: "32",
  label: "Session 32",
  summary: "komak, oomadan, THE PAST TENSE, bāz/baste/band, dard + body parts, bidār shodan, khābidan, delam tang shodeh",
  items: [
    // Vocabulary
    { id: "32.v.komak", type: "vocabulary", fa: "کمک", pin: "komak", en: "help", notes: "ک-م-ک",
      examples: [
        { fa: "من کمک لازم دارم", pin: "man komak lāzem dāram", en: "I need help", source: "phrase:32" },
        { fa: "همسایه گفت: «ببخشید! کمک لازم دارید؟»", pin: "Hamsāyeh goft: \"Bebakhshid! Komak lāzem dārid?\"", en: "The neighbour said: \"Excuse me! Do you need help?\"", source: "story:st-32-1" },
        { fa: "من کمک می‌خوام", pin: "man komak mikhām", en: "I want help", source: "phrase:32" },
        { fa: "تو کمک می‌خوای؟", pin: "to komak mikhāy?", en: "Do you want help?", source: "phrase:32" },
      ] },
    { id: "32.v.lazem", type: "vocabulary", fa: "لازم", pin: "lāzem", en: "necessary, needed", notes: "لازم داشتن = to need",
      examples: [
        { fa: "من کمک لازم دارم", pin: "man komak lāzem dāram", en: "I need help", source: "phrase:32" },
        { fa: "همسایه گفت: «ببخشید! کمک لازم دارید؟»", pin: "Hamsāyeh goft: \"Bebakhshid! Komak lāzem dārid?\"", en: "The neighbour said: \"Excuse me! Do you need help?\"", source: "story:st-32-1" },
      ] },
    { id: "32.v.oomadan", type: "vocabulary", fa: "اومدن", pin: "oomadan", en: "to come", notes: "formal: آمدن (āmadan) — present: میام (miām)",
      examples: [
        { fa: "من دارم میام", pin: "man dāram miām", en: "I'm coming", source: "phrase:32" },
        { fa: "میترا ساعت چهار بعد از خرید میاد خونه و یه غذای گرم درست می‌کنه.", pin: "Mitrā sāat-e chahār baad az kharid miād khooneh va ye ghazā-ye garm dorost mikoneh.", en: "Mitra comes home at four after shopping and cooks a warm meal.", source: "story:32" },
        { fa: "ساعت دوازده، همسایه اومد.", pin: "Sāat-e davāzdah, hamsāyeh oomad.", en: "At twelve, the neighbour came over.", source: "story:st-32-1" },
        { fa: "تو داری میای؟", pin: "to dāri miāy?", en: "Are you coming?", source: "phrase:32" },
      ] },
    { id: "32.v.amadeh", type: "vocabulary", fa: "آماده", pin: "āmādeh", en: "ready", notes: "آ-م-ا-د-ه",
      examples: [
        { fa: "بعد از صبحونه، مامان می‌گه: «زود باشید! همه‌چیز آماده‌ست؟»", pin: "Ba'd az sobhooneh, māmān migeh: \"Zood bāshid! Hameh-chiz āmādeh-st?\"", en: "After breakfast, Mom says: \"Hurry up! Is everything ready?\"", source: "story:st-33-2" },
        { fa: "کَم کَم برایِ رفتن آماده می‌شَوَم.", pin: "Kam kam barāye raftan āmādeh mishavam.", en: "Little by little I get ready to leave.", source: "story:34" },
      ] },
    { id: "32.v.hamsayeh", type: "vocabulary", fa: "همسایه", pin: "hamsāyeh", en: "neighbour", notes: "هم (co-) + سایه (shade)",
      examples: [
        { fa: "اون همسایه‌ی ماست", pin: "oon hamsāye-ye māst", en: "He/she is our neighbour", source: "phrase:32" },
        { fa: "سعید و میترا همسایه‌های ما هستن.", pin: "Saeed-o Mitrā hamsāye-hā-ye mā hastan.", en: "Saeed and Mitra are our neighbours.", source: "story:32" },
        { fa: "ساعت دوازده، همسایه اومد.", pin: "Sāat-e davāzdah, hamsāyeh oomad.", en: "At twelve, the neighbour came over.", source: "story:st-32-1" },
        { fa: "همسایه گفت: «ببخشید! کمک لازم دارید؟»", pin: "Hamsāyeh goft: \"Bebakhshid! Komak lāzem dārid?\"", en: "The neighbour said: \"Excuse me! Do you need help?\"", source: "story:st-32-1" },
      ] },
    { id: "32.v.tamasha-kardan", type: "vocabulary", fa: "تماشا کردن", pin: "tamāshā kardan", en: "to watch", notes: "تماشا + کردن — used for TV, films, matches",
      examples: [
        { fa: "اونها دارن تلویزیون تماشا می‌کنن", pin: "oonhā dāran televizion tamāshā mikonan", en: "They're watching TV", source: "phrase:32" },
        { fa: "و سعید و میترا یک ساعت تلویزیون تماشا می‌کنن و ساعت ده می‌خوابن.", pin: "va Saeed-o Mitrā yek sāat televizion tamāshā mikonan va sāat-e dah mikhāban.", en: "And Saeed and Mitra watch TV for an hour and go to bed at ten.", source: "story:32" },
      ] },
    { id: "32.v.vaghei", type: "vocabulary", fa: "واقعی", pin: "vāghe'i", en: "real (adj)", notes: "و-ا-ق-ع-ی" },
    { id: "32.v.vaghean", type: "vocabulary", fa: "واقعاً", pin: "vāghean", en: "really (adv)", notes: "واقعی + اً (adverb ending)",
      examples: [
        { fa: "اون واقعاً باهوشه", pin: "oon vāghean bāhoosh-e", en: "He/she is really smart", source: "phrase:32" },
        { fa: "من گفتم: «واقعاً؟ پیانو؟»", pin: "Man goftam: \"Vāghean? Piāno?\"", en: "I said: \"Really? The piano?\"", source: "story:st-33-1" },
      ] },
    { id: "32.v.bahoosh", type: "vocabulary", fa: "باهوش", pin: "bāhoosh", en: "smart, clever (people)", notes: "با (with) + هوش (intelligence)",
      examples: [
        { fa: "اون واقعاً باهوشه", pin: "oon vāghean bāhoosh-e", en: "He/she is really smart", source: "phrase:32" },
        { fa: "رضا خیلی باهوشه، ولی ساعت نداره.", pin: "Rezā kheili bāhoosh-eh, vali sāat nadāreh.", en: "Reza is very smart, but he doesn't have a watch.", source: "story:st-26-1" },
        { fa: "علی ایرانی هست و خیلی باهوشه.", pin: "Ali irāni hast va kheili bāhoosh-eh.", en: "Ali is Iranian and very smart.", source: "story:st-22-1" },
        { fa: "سارا خیلی خوب و باهوشه.", pin: "Sārā kheili khoob o bāhoosh-eh.", en: "Sara is very nice and smart.", source: "story:st-22-1" },
      ] },
    { id: "32.v.hooshmand", type: "vocabulary", fa: "هوشمند", pin: "hooshmand", en: "smart, intelligent (devices)", notes: "هوش + مند — گوشی هوشمند = smartphone" },
    { id: "32.v.gooshi", type: "vocabulary", fa: "گوشی", pin: "gooshi", en: "phone, mobile, handset; headphones", notes: "گوش (ear) + ی",
      examples: [
        { fa: "گوشیم کجاست؟", pin: "gooshim kojāst?", en: "Where's my phone?", source: "phrase:32" },
      ] },
    { id: "32.v.morabba", type: "vocabulary", fa: "مربا", pin: "morabbā", en: "jam", notes: "م-ر-ب-ا",
      examples: [
        { fa: "و ساعت هفت صبح تو آشپزخونه صبحونه می‌خورن: نون خانگی، پنیر، مربا، تخم مرغ و چای شیرین.", pin: "va sāat-e haft-e sobh too āshpazkhooneh sobhooneh mikhoran: noon-e khānegi, panir, morabbā, tokhm-e morgh va chāy-e shirin.", en: "And at seven in the morning they have breakfast in the kitchen: homemade bread, cheese, jam, eggs and sweet tea.", source: "story:32" },
      ] },
    { id: "32.v.khanegi", type: "vocabulary", fa: "خانگی", pin: "khānegi", en: "homemade, domestic", notes: "خانه (home) + گی",
      examples: [
        { fa: "و ساعت هفت صبح تو آشپزخونه صبحونه می‌خورن: نون خانگی، پنیر، مربا، تخم مرغ و چای شیرین.", pin: "va sāat-e haft-e sobh too āshpazkhooneh sobhooneh mikhoran: noon-e khānegi, panir, morabbā, tokhm-e morgh va chāy-e shirin.", en: "And at seven in the morning they have breakfast in the kitchen: homemade bread, cheese, jam, eggs and sweet tea.", source: "story:32" },
      ] },
    { id: "32.v.heyvan-e-khanegi", type: "vocabulary", fa: "حیوان خانگی", pin: "heyvān-e khānegi", en: "pet", notes: "حیوان (animal) + خانگی (domestic)" },
    { id: "32.v.televizion", type: "vocabulary", fa: "تلویزیون", pin: "televizion", en: "television", notes: "loanword",
      examples: [
        { fa: "اونها دارن تلویزیون تماشا می‌کنن", pin: "oonhā dāran televizion tamāshā mikonan", en: "They're watching TV", source: "phrase:32" },
        { fa: "و سعید و میترا یک ساعت تلویزیون تماشا می‌کنن و ساعت ده می‌خوابن.", pin: "va Saeed-o Mitrā yek sāat televizion tamāshā mikonan va sāat-e dah mikhāban.", en: "And Saeed and Mitra watch TV for an hour and go to bed at ten.", source: "story:32" },
      ] },
    { id: "32.v.khanevadeh", type: "vocabulary", fa: "خانواده", pin: "khānevādeh", en: "family", notes: "خ-ا-ن-و-ا-د-ه",
      examples: [
        { fa: "یه خانواده‌ی خوشحال", pin: "ye khānevāde-ye khoshhāl", en: "A happy family", source: "story:32" },
        { fa: "جایگاه مادر در خانواده بسیار مهم است", pin: "jāygāh-e mādar dar khānevādeh besyār mohem ast", en: "The mother's role in a family is very important", source: "phrase:31" },
        { fa: "من عاشق خانواده‌ام هستم", pin: "man āshegh-e khoonevāde-am hastam", en: "I love my family", source: "phrase:24-25" },
        { fa: "خانواده ساعت هشت تو آشپزخونه شام می‌خورن.", pin: "khānevādeh sāat-e hasht too āshpazkhooneh shām mikhoran.", en: "The family eats dinner in the kitchen at eight.", source: "story:32" },
      ] },
    { id: "32.v.zan-o-shohar", type: "vocabulary", fa: "زن و شوهر", pin: "zan-o shohar", en: "husband and wife, married couple", notes: "زن (woman/wife) + شوهر (husband)",
      examples: [
        { fa: "اونها زن و شوهرن و سه تا بچه دارن.", pin: "oonhā zan-o shohar-an va se tā bache dāran.", en: "They are husband and wife and have three children.", source: "story:32" },
      ] },
    { id: "32.v.sobhooneh", type: "vocabulary", fa: "صبحونه", pin: "sobhooneh", en: "breakfast", notes: "from صبح (morning) — formal: صبحانه",
      examples: [
        { fa: "تو ساعت چند صبحونه می‌خوری؟", pin: "to sāat-e chand sobhooneh mikhori?", en: "What time do you eat breakfast?", source: "phrase:32" },
        { fa: "اون هر روز ساعت هفت صبحونه می‌خوره.", pin: "Oon har rooz sāat-e haft sobhooneh mikhoreh.", en: "Every day she has breakfast at seven.", source: "story:st-26-1" },
        { fa: "و ساعت هفت صبح تو آشپزخونه صبحونه می‌خورن: نون خانگی، پنیر، مربا، تخم مرغ و چای شیرین.", pin: "va sāat-e haft-e sobh too āshpazkhooneh sobhooneh mikhoran: noon-e khānegi, panir, morabbā, tokhm-e morgh va chāy-e shirin.", en: "And at seven in the morning they have breakfast in the kitchen: homemade bread, cheese, jam, eggs and sweet tea.", source: "story:32" },
        { fa: "ولی بچه‌ها ساعت شیش بیدار شدن و گفتن: «ما صبحونه می‌خوایم!»", pin: "Vali bacheh hā sāat-e shish bidār shodan va goftan: \"Mā sobhooneh mikhāym!\"", en: "But the children woke up at six and said: \"We want breakfast!\"", source: "story:st-32-1" },
      ] },
    { id: "32.v.nahar", type: "vocabulary", fa: "ناهار", pin: "nāhār", en: "lunch", notes: "ن-ا-ه-ا-ر",
      examples: [
        { fa: "تو ساعت چند ناهار می‌خوری؟", pin: "to sāat-e chand nāhār mikhori?", en: "What time do you eat lunch?", source: "phrase:32" },
        { fa: "ساعت یک، سارا با همکارش، رضا، ناهار می‌خوره.", pin: "Sāat-e yek, Sārā bā hamkāresh, Rezā, nāhār mikhoreh.", en: "At one, Sara has lunch with her colleague Reza.", source: "story:st-26-1" },
        { fa: "فردا من و دوستم با همدیگه ناهار می‌خوریم", pin: "fardā man o doostam bā hamdige nāhār mikhorim", en: "Tomorrow my friend and I are having lunch together", source: "phrase:28" },
        { fa: "من ساعت دو ناهار میخورم", pin: "man sā’at-e do nāhār mikhoram", en: "I eat lunch at 2", source: "phrase:26" },
      ] },
    { id: "32.v.panir", type: "vocabulary", fa: "پنیر", pin: "panir", en: "cheese", notes: "پ-ن-ی-ر",
      examples: [
        { fa: "من پنیر دوست نداشتم، اما الان پنیر خیلی دوست دارم", pin: "man panir doost nadāshtam, ammā alān panir kheili doost dāram", en: "I didn't like cheese, but now I like cheese a lot", source: "phrase:32" },
        { fa: "بعد اون نون و پنیر و چای خورد.", pin: "Ba'd oon noon o panir o chāy khord.", en: "Then he had bread, cheese and tea.", source: "story:st-32-2" },
        { fa: "و ساعت هفت صبح تو آشپزخونه صبحونه می‌خورن: نون خانگی، پنیر، مربا، تخم مرغ و چای شیرین.", pin: "va sāat-e haft-e sobh too āshpazkhooneh sobhooneh mikhoran: noon-e khānegi, panir, morabbā, tokhm-e morgh va chāy-e shirin.", en: "And at seven in the morning they have breakfast in the kitchen: homemade bread, cheese, jam, eggs and sweet tea.", source: "story:32" },
      ] },
    { id: "32.v.tokhm-e-morgh", type: "vocabulary", fa: "تخم مرغ", pin: "tokhm-e morgh", en: "egg", notes: "تخم (seed/egg) + مرغ (hen)",
      examples: [
        { fa: "و ساعت هفت صبح تو آشپزخونه صبحونه می‌خورن: نون خانگی، پنیر، مربا، تخم مرغ و چای شیرین.", pin: "va sāat-e haft-e sobh too āshpazkhooneh sobhooneh mikhoran: noon-e khānegi, panir, morabbā, tokhm-e morgh va chāy-e shirin.", en: "And at seven in the morning they have breakfast in the kitchen: homemade bread, cheese, jam, eggs and sweet tea.", source: "story:32" },
        { fa: "تخم مرغ‌ها توی یخچال نیستند.", pin: "Tokhm-e morgh hā tuye yakhchāl nistand.", en: "The eggs are not in the fridge.", source: "phrase:35" },
        { fa: "بعد مامانم تخم مرغ‌ها رو از یخچال برمی‌داره.", pin: "Ba'd māmānam tokhm-e morgh hā ro az yakhchāl barmidāreh.", en: "Then my mom takes the eggs out of the fridge.", source: "story:st-35-2" },
      ] },
    { id: "32.v.diruz", type: "vocabulary", fa: "دیروز", pin: "diruz", en: "yesterday", notes: "دی (past) + روز (day)",
      examples: [
        { fa: "من دیروز خونه بودم", pin: "man diruz khoone boodam", en: "I was at home yesterday", source: "phrase:32" },
        { fa: "دیروز علی ساعت هفت از خواب بیدار شد.", pin: "Dirooz Ali sāat-e haft az khāb bidār shod.", en: "Yesterday Ali woke up at seven.", source: "story:st-32-2" },
        { fa: "هَوا خیلی بِهتَر از دیروز است.", pin: "Havā kheili behtar az dirooz ast.", en: "The weather is much better than yesterday.", source: "story:34" },
        { fa: "دیروز من رفتم خونه‌ی مامانم.", pin: "Dirooz man raftam khoone-ye māmānam.", en: "Yesterday I went to my mom's house.", source: "story:st-33-1" },
      ] },
    { id: "32.v.dishab", type: "vocabulary", fa: "دیشب", pin: "dishab", en: "last night", notes: "دی + شب (night)",
      examples: [
        { fa: "دیشب کجا بودی؟", pin: "dishab kojā boodi?", en: "Where were you last night?", source: "phrase:32" },
        { fa: "دیشب سعید و میترا ساعت ده نخوابیدن.", pin: "Dishab Saeed o Mitrā sāat-e dah nakhābidan.", en: "Last night Saeed and Mitra didn't go to bed at ten.", source: "story:st-32-1" },
        { fa: "ولی دیشب...", pin: "vali dishab...", en: "But last night...", source: "story:32" },
        { fa: "امشب از دیشب گرم‌تره.", pin: "Emshab az dishab garmtar-eh.", en: "Tonight is warmer than last night.", source: "phrase:34" },
      ] },
    { id: "32.v.pish", type: "vocabulary", fa: "پیش", pin: "pish", en: "ago, before", notes: "دو سال پیش = two years ago",
      examples: [
        { fa: "ما سال پیش گربه نداشتیم ولی الان دو تا گربه داریم", pin: "mā sāl-e pish gorbeh nadāshtim vali alān do tā gorbeh dārim", en: "Last year we didn't have a cat but now we have two cats", source: "phrase:32" },
        { fa: "سام دو سال پیش ماشین داشت ولی الان ماشین نداره", pin: "Sam do sāl-e pish māshin dāsht vali alān māshin nadāreh", en: "Two years ago Sam had a car but now he doesn't", source: "phrase:32" },
        { fa: "ولی هفته‌ی پیش زنگ نزد.", pin: "Vali hafte-ye pish zang nazad.", en: "But last week she didn't call.", source: "story:st-33-1" },
        { fa: "امروز بهتر از هفته‌ی پیش رقصیدم.", pin: "Emrooz behtar az hafte-ye pish raghsidam.", en: "Today I danced better than last week.", source: "story:st-34-2" },
      ] },
    { id: "32.v.sal-e-pish", type: "vocabulary", fa: "سال پیش", pin: "sāl-e pish", en: "last year", notes: "سال + پیش",
      examples: [
        { fa: "ما سال پیش گربه نداشتیم ولی الان دو تا گربه داریم", pin: "mā sāl-e pish gorbeh nadāshtim vali alān do tā gorbeh dārim", en: "Last year we didn't have a cat but now we have two cats", source: "phrase:32" },
        { fa: "سام دو سال پیش ماشین داشت ولی الان ماشین نداره", pin: "Sam do sāl-e pish māshin dāsht vali alān māshin nadāreh", en: "Two years ago Sam had a car but now he doesn't", source: "phrase:32" },
      ] },
    { id: "32.v.baz", type: "vocabulary", fa: "باز", pin: "bāz", en: "open", notes: "ب-ا-ز",
      examples: [
        { fa: "در باز هست", pin: "dar bāz hast", en: "The door is open", source: "phrase:32" },
        { fa: "سعید در رو باز کرد.", pin: "Saeed dar ro bāz kard.", en: "Saeed opened the door.", source: "story:st-32-1" },
        { fa: "اونها ساعت هشت صبح باز می‌کنن", pin: "oonhā sāat-e hasht-e sobh bāz mikonan", en: "They open at 8 AM", source: "phrase:32" },
        { fa: "لطفاً در رو باز کن!", pin: "lotfan dar ro bāz kon!", en: "Open the door please!", source: "phrase:32" },
      ] },
    { id: "32.v.dar", type: "vocabulary", fa: "در", pin: "dar", en: "door", notes: "also means 'in' — context tells you which",
      examples: [
        { fa: "من دو سال در آلمان زندگی کردم", pin: "man do sāl dar Ālmān zendegi kardam", en: "I lived in Germany for two years", source: "phrase:32" },
        { fa: "در شیراز، سارا یه اتاق در یه مهمون‌خونه‌ی قدیمی اجاره می‌کنه.", pin: "Dar Shirāz, Sārā ye otāgh dar ye mehmoon-khoone-ye ghadimi ejāreh mikoneh.", en: "In Shiraz, Sara rents a room in an old guesthouse.", source: "story:st-31-2" },
        { fa: "من دو بار در هفته می‌رم باشگاه", pin: "man do bār dar hafte miram bāshgāh", en: "I go to the gym twice a week", source: "phrase:30" },
        { fa: "در آینده ما اینجا نیستیم", pin: "dar āyande mā injā nistim", en: "In the future, we won't be here", source: "phrase:28" },
      ] },
    { id: "32.v.baz-kardan", type: "vocabulary", fa: "باز کردن", pin: "bāz kardan", en: "to open", notes: "باز + کردن",
      examples: [
        { fa: "اونها ساعت هشت صبح باز می‌کنن", pin: "oonhā sāat-e hasht-e sobh bāz mikonan", en: "They open at 8 AM", source: "phrase:32" },
        { fa: "سعید در رو باز کرد.", pin: "Saeed dar ro bāz kard.", en: "Saeed opened the door.", source: "story:st-32-1" },
        { fa: "لطفاً در رو باز کن!", pin: "lotfan dar ro bāz kon!", en: "Open the door please!", source: "phrase:32" },
        { fa: "لطفاً در رو باز نکن!", pin: "lotfan dar ro bāz nakon!", en: "Don't open the door please!", source: "phrase:32" },
      ] },
    { id: "32.v.baste", type: "vocabulary", fa: "بسته", pin: "baste", en: "closed, shut, locked; a package, a pack", notes: "one word both ways — a 'closed up' thing. From بستن",
      examples: [
        { fa: "در بسته هست", pin: "dar baste hast", en: "The door is closed", source: "phrase:32" },
        { fa: "یک بسته‌ی شکلات", pin: "yek baste-ye shokolāt", en: "a packet of chocolates", source: "phrase:32" },
        { fa: "یک بسته سیگار", pin: "yek baste sigār", en: "a pack of cigarettes", source: "phrase:32" },
      ] },
    { id: "32.v.bastan", type: "vocabulary", fa: "بستن", pin: "bastan", en: "to close, to shut; to tie, to fasten", notes: "present stem: بند (band)",
      examples: [
        { fa: "در رو ببند!", pin: "dar ro beband!", en: "Close the door!", source: "phrase:32" },
        { fa: "بعد در رو بست.", pin: "Ba'd dar ro bast.", en: "Then he closed the door.", source: "story:st-32-1" },
        { fa: "من در رو می‌بندم", pin: "man dar ro mibandam", en: "I'll close the door", source: "phrase:32" },
      ] },
    { id: "32.v.baste-ye-posti", type: "vocabulary", fa: "بسته‌ی پستی", pin: "baste-ye posti", en: "parcel, postal package", notes: "بسته + پستی (postal)" },
    { id: "32.v.pakat", type: "vocabulary", fa: "پاکت", pin: "pākat", en: "packet, envelope", notes: "پاکت سیگار = pack of cigarettes" },
    { id: "32.v.bastegi-dashtan", type: "vocabulary", fa: "بستگی داشتن", pin: "bastegi dāshtan", en: "to depend on", notes: "from بستن — 'to be tied to'",
      examples: [
        { fa: "بستگی داره!", pin: "bastegi dāreh!", en: "It depends!", source: "phrase:32" },
      ] },
    { id: "32.v.band", type: "vocabulary", fa: "بند", pin: "band", en: "string, cord, rope, strap", notes: "physical ties — from بستن" },
    { id: "32.v.band-e-kafsh", type: "vocabulary", fa: "بند کفش", pin: "band-e kafsh", en: "shoelace", notes: "بند + کفش (shoe)" },
    { id: "32.v.band-e-saat", type: "vocabulary", fa: "بند ساعت", pin: "band-e sāat", en: "watch strap", notes: "بند + ساعت (watch)" },
    { id: "32.v.dard", type: "vocabulary", fa: "درد", pin: "dard", en: "pain, ache", notes: "د-ر-د",
      examples: [
        { fa: "من درد دارم", pin: "man dard dāram", en: "I'm in pain", source: "phrase:32" },
        { fa: "مامان گفت: «علی، کجات درد می‌کنه؟»", pin: "Māmān goft: \"Ali, kojāt dard mikoneh?\"", en: "Mom said: \"Ali, where does it hurt?\"", source: "story:st-32-2" },
        { fa: "سرم درد می‌کنه", pin: "saram dard mikoneh", en: "My head hurts", source: "phrase:32" },
        { fa: "پام درد می‌کنه", pin: "pām dard mikoneh", en: "My leg hurts", source: "phrase:32" },
      ] },
    { id: "32.v.sar-dard", type: "vocabulary", fa: "سردرد", pin: "sar-dard", en: "headache", notes: "سر (head) + درد",
      examples: [
        { fa: "من سردرد دارم", pin: "man sar-dard dāram", en: "I have a headache", source: "phrase:32" },
        { fa: "سعید سردرد داشت و میترا دل‌درد داشت.", pin: "Saeed sar-dard dāsht va Mitrā del-dard dāsht.", en: "Saeed had a headache and Mitra had a stomachache.", source: "story:st-32-1" },
        { fa: "اون خیلی سردرد داشت.", pin: "Oon kheili sar-dard dāsht.", en: "He had a bad headache.", source: "story:st-32-2" },
      ] },
    { id: "32.v.del-dard", type: "vocabulary", fa: "دل‌درد", pin: "del-dard", en: "stomachache", notes: "دل (stomach) + درد",
      examples: [
        { fa: "من دل‌درد دارم", pin: "man del-dard dāram", en: "I have a stomachache", source: "phrase:32" },
        { fa: "سعید سردرد داشت و میترا دل‌درد داشت.", pin: "Saeed sar-dard dāsht va Mitrā del-dard dāsht.", en: "Saeed had a headache and Mitra had a stomachache.", source: "story:st-32-1" },
      ] },
    { id: "32.v.sar", type: "vocabulary", fa: "سر", pin: "sar", en: "head", notes: "س-ر",
      examples: [
        { fa: "سرم درد می‌کنه", pin: "saram dard mikoneh", en: "My head hurts", source: "phrase:32" },
        { fa: "امروز علی سرش خیلی شلوغه.", pin: "Emrooz Ali saresh kheili sholugh-eh.", en: "Ali is very busy today.", source: "story:st-31-1" },
        { fa: "بعد بچه‌ها می‌رن مدرسه و پدر و مادر می‌رن سر کار.", pin: "baad bache-hā miran madreseh va pedar-o mādar miran sar-e kār.", en: "Then the children go to school and the parents go to work.", source: "story:32" },
        { fa: "امروز سرت شلوغه؟", pin: "emrooz saret sholugh-e?", en: "Are you busy today?", source: "phrase:24-25" },
      ] },
    { id: "32.v.del", type: "vocabulary", fa: "دل", pin: "del", en: "heart (emotions); stomach (physical)", notes: "دلم تنگ شده = I miss / دلم درد می‌کنه = my stomach hurts",
      examples: [
        { fa: "دلم درد می‌کنه", pin: "delam dard mikoneh", en: "My stomach hurts", source: "phrase:32" },
        { fa: "دلم برای تو تنگ شده!", pin: "delam barāye to tang shodeh!", en: "I miss you!", source: "phrase:32" },
        { fa: "دلم برات خیلی تنگ شده!", pin: "delam barāt kheili tang shodeh!", en: "I miss you so much!", source: "phrase:32" },
        { fa: "من هم دلم برات تنگ شده!", pin: "man ham delam barāt tang shodeh!", en: "I miss you too!", source: "phrase:32" },
      ] },
    { id: "32.v.pa", type: "vocabulary", fa: "پا", pin: "pā", en: "leg, foot", notes: "پ-ا",
      examples: [
        { fa: "پام درد می‌کنه", pin: "pām dard mikoneh", en: "My leg hurts", source: "phrase:32" },
      ] },
    { id: "32.v.paha", type: "vocabulary", fa: "پاها", pin: "pāhā", en: "legs, feet", notes: "پا + ها (plural)",
      examples: [
        { fa: "پاهام درد می‌کنه", pin: "pāhām dard mikoneh", en: "My legs hurt", source: "phrase:32" },
      ] },
    { id: "32.v.dast", type: "vocabulary", fa: "دست", pin: "dast", en: "hand", notes: "د-س-ت",
      examples: [
        { fa: "دستم درد می‌کنه", pin: "dastam dard mikoneh", en: "My hand hurts", source: "phrase:32" },
        { fa: "شب، علی گفت: «مامان، دستت درد نکنه! الان خوبم.»", pin: "Shab, Ali goft: \"Māmān, dastet dard nakoneh! Alān khoobam.\"", en: "In the evening, Ali said: \"Mom, thank you! I'm fine now.\"", source: "story:st-32-2" },
        { fa: "از دست من ناراحتی؟", pin: "az dast-e man nārāhati?", en: "Are you upset with me?", source: "phrase:27" },
        { fa: "دستت درد نکنه!", pin: "dastet dard nakoneh!", en: "Thank you! (lit. may your hand not hurt)", source: "phrase:32" },
      ] },
    { id: "32.v.dastha", type: "vocabulary", fa: "دست‌ها", pin: "dasthā", en: "hands", notes: "دست + ها (plural)" },
    { id: "32.v.shooneh", type: "vocabulary", fa: "شونه", pin: "shooneh", en: "shoulder", notes: "formal: شانه (shāneh)",
      examples: [
        { fa: "شونه‌ام درد می‌کنه", pin: "shoone-am dard mikoneh", en: "My shoulder hurts", source: "phrase:32" },
        { fa: "سارا موهاش رو شونه می‌زنه.", pin: "Sārā moo hāsh ro shooneh mizaneh.", en: "Sara combs her hair.", source: "story:st-33-2" },
        { fa: "موها رو شونه بزن", pin: "moo-hā ro shooneh bezan", en: "Comb your hair", source: "phrase:33" },
      ] },
    { id: "32.v.posht", type: "vocabulary", fa: "پشت", pin: "posht", en: "back", notes: "پ-ش-ت",
      examples: [
        { fa: "پشتم درد می‌کنه", pin: "poshtam dard mikoneh", en: "My back hurts", source: "phrase:32" },
      ] },
    { id: "32.v.kamar", type: "vocabulary", fa: "کمر", pin: "kamar", en: "lower back, waist", notes: "ک-م-ر",
      examples: [
        { fa: "کمرم درد می‌کنه", pin: "kamaram dard mikoneh", en: "My lower back hurts", source: "phrase:32" },
        { fa: "علی گفت: «سرم درد می‌کنه، گوشم درد می‌کنه، کمرم هم درد می‌کنه!»", pin: "Ali goft: \"Saram dard mikoneh, goosham dard mikoneh, kamaram ham dard mikoneh!\"", en: "Ali said: \"My head hurts, my ear hurts, and my back hurts too!\"", source: "story:st-32-2" },
      ] },
    { id: "32.v.goosh", type: "vocabulary", fa: "گوش", pin: "goosh", en: "ear", notes: "گ-و-ش",
      examples: [
        { fa: "گوشم درد می‌کنه", pin: "goosham dard mikoneh", en: "My ear hurts", source: "phrase:32" },
        { fa: "علی گفت: «سرم درد می‌کنه، گوشم درد می‌کنه، کمرم هم درد می‌کنه!»", pin: "Ali goft: \"Saram dard mikoneh, goosham dard mikoneh, kamaram ham dard mikoneh!\"", en: "Ali said: \"My head hurts, my ear hurts, and my back hurts too!\"", source: "story:st-32-2" },
      ] },
    { id: "32.v.dandoon", type: "vocabulary", fa: "دندون", pin: "dandoon", en: "tooth", notes: "formal: دندان (dandān)",
      examples: [
        { fa: "دندونم درد می‌کنه", pin: "dandoonam dard mikoneh", en: "My tooth hurts", source: "phrase:32" },
        { fa: "قبل از صبحونه، بچه‌ها دندون‌هاشون رو مسواک می‌زنن.", pin: "Ghabl az sobhooneh, bacheh hā dandoon hāshoon ro mesvāk mizanan.", en: "Before breakfast, the children brush their teeth.", source: "story:st-33-2" },
        { fa: "دندون‌ها رو مسواک بزن", pin: "dandoon-hā ro mesvāk bezan", en: "Brush your teeth", source: "phrase:33" },
      ] },
    { id: "32.v.bidar", type: "vocabulary", fa: "بیدار", pin: "bidār", en: "awake", notes: "ب-ی-د-ا-ر",
      examples: [
        { fa: "من بیدار هستم", pin: "man bidār hastam", en: "I am awake", source: "phrase:32" },
        { fa: "اونها ساعت شیش از خواب بیدار می‌شن.", pin: "oonhā sāat-e shish az khāb bidār mishan.", en: "They wake up at six o'clock.", source: "story:32" },
        { fa: "ساعت یازده، بچه‌ها هم بیدار شدن.", pin: "Sāat-e yāzdah, bacheh hā ham bidār shodan.", en: "At eleven, the children woke up too.", source: "story:st-32-1" },
        { fa: "من هر روز ساعت شیش از خواب بیدار می‌شم", pin: "man har rooz sāat-e shish az khāb bidār misham", en: "I wake up at six every day", source: "phrase:32" },
      ] },
    { id: "32.v.bidar-shodan", type: "vocabulary", fa: "بیدار شدن", pin: "bidār shodan", en: "to wake up", notes: "بیدار (awake) + شدن (to become)",
      examples: [
        { fa: "من هر روز ساعت شیش از خواب بیدار می‌شم", pin: "man har rooz sāat-e shish az khāb bidār misham", en: "I wake up at six every day", source: "phrase:32" },
        { fa: "اونها ساعت شیش از خواب بیدار می‌شن.", pin: "oonhā sāat-e shish az khāb bidār mishan.", en: "They wake up at six o'clock.", source: "story:32" },
        { fa: "ساعت یازده، بچه‌ها هم بیدار شدن.", pin: "Sāat-e yāzdah, bacheh hā ham bidār shodan.", en: "At eleven, the children woke up too.", source: "story:st-32-1" },
        { fa: "شما کی از خواب بیدار می‌شید؟", pin: "shomā key az khāb bidār mishid?", en: "What time do you wake up?", source: "phrase:32" },
      ] },
    { id: "32.v.shodan", type: "vocabulary", fa: "شدن", pin: "shodan", en: "to become, to get", notes: "present stem: ش (sh) — می‌شم (misham)",
      examples: [
        { fa: "من هر روز ساعت شیش از خواب بیدار می‌شم", pin: "man har rooz sāat-e shish az khāb bidār misham", en: "I wake up at six every day", source: "phrase:32" },
        { fa: "پنج دقیقه بعد، علی می‌رسه و می‌گه: «ببخشید دیر شد!»", pin: "Panj daghigheh ba'd, Ali mireseh va migeh: \"Bebakhshid dir shod!\"", en: "Five minutes later, Ali arrives and says: \"Sorry I'm late!\"", source: "story:st-29-1" },
        { fa: "اونها ساعت شیش از خواب بیدار می‌شن.", pin: "oonhā sāat-e shish az khāb bidār mishan.", en: "They wake up at six o'clock.", source: "story:32" },
        { fa: "شما کی از خواب بیدار می‌شید؟", pin: "shomā key az khāb bidār mishid?", en: "What time do you wake up?", source: "phrase:32" },
      ] },
    { id: "32.v.khab", type: "vocabulary", fa: "خواب", pin: "khāb", en: "sleep, dream", notes: "خ-و-ا-ب",
      examples: [
        { fa: "من هر روز ساعت شیش از خواب بیدار می‌شم", pin: "man har rooz sāat-e shish az khāb bidār misham", en: "I wake up at six every day", source: "phrase:32" },
        { fa: "اونها ساعت شیش از خواب بیدار می‌شن.", pin: "oonhā sāat-e shish az khāb bidār mishan.", en: "They wake up at six o'clock.", source: "story:32" },
        { fa: "دیروز علی ساعت هفت از خواب بیدار شد.", pin: "Dirooz Ali sāat-e haft az khāb bidār shod.", en: "Yesterday Ali woke up at seven.", source: "story:st-32-2" },
        { fa: "شما کی از خواب بیدار می‌شید؟", pin: "shomā key az khāb bidār mishid?", en: "What time do you wake up?", source: "phrase:32" },
      ] },
    { id: "32.v.khabidan", type: "vocabulary", fa: "خوابیدن", pin: "khābidan", en: "to sleep", notes: "present stem: خواب (khāb)",
      examples: [
        { fa: "تو کی می‌خوابی؟", pin: "to key mikhābi?", en: "What time do you go to sleep?", source: "phrase:32" },
        { fa: "بچه‌ها ساعت نه می‌خوابن.", pin: "bache-hā sāat-e noh mikhāban.", en: "The children go to bed at nine.", source: "story:32" },
        { fa: "دیشب سعید و میترا ساعت ده نخوابیدن.", pin: "Dishab Saeed o Mitrā sāat-e dah nakhābidan.", en: "Last night Saeed and Mitra didn't go to bed at ten.", source: "story:st-32-1" },
        { fa: "من ساعت ده شب می‌خوابم", pin: "man sāat-e dah-e shab mikhābam", en: "I go to bed at 10 PM", source: "phrase:32" },
      ] },
    { id: "32.v.takht-e-khab", type: "vocabulary", fa: "تخت خواب", pin: "takht-e khāb", en: "bed", notes: "تخت (platform) + خواب" },
    { id: "32.v.cheragh-e-khab", type: "vocabulary", fa: "چراغ خواب", pin: "cherāgh-e khāb", en: "bedside lamp, night light", notes: "چراغ (lamp) + خواب" },
    { id: "32.v.otagh-e-khab", type: "vocabulary", fa: "اتاق خواب", pin: "otāgh-e khāb", en: "bedroom", notes: "اتاق (room) + خواب" },
    { id: "32.v.saat-e-chand", type: "vocabulary", fa: "ساعت چند", pin: "sāat-e chand", en: "what time", notes: "ساعت (hour) + چند (how many)",
      examples: [
        { fa: "تو ساعت چند صبحونه می‌خوری؟", pin: "to sāat-e chand sobhooneh mikhori?", en: "What time do you eat breakfast?", source: "phrase:32" },
        { fa: "امروز رضا می‌گه: «ببخشید، الان ساعت چنده؟»", pin: "Emrooz Rezā migeh: \"Bebakhshid, alān sāat chand-eh?\"", en: "Today Reza says: \"Excuse me, what time is it now?\"", source: "story:st-26-1" },
        { fa: "ساعت چند می‌رسی؟", pin: "sāat-e chand miresi?", en: "What time do you arrive?", source: "phrase:29" },
        { fa: "تو هر شب ساعت چند می‌خوابی؟", pin: "to har shab sāat-e chand mikhābi?", en: "What time do you go to sleep every night?", source: "phrase:32" },
      ] },
    { id: "32.v.che-saati", type: "vocabulary", fa: "چه ساعتی", pin: "che sāati", en: "what time (formal)", notes: "چه (what) + ساعتی" },
    { id: "32.v.tang", type: "vocabulary", fa: "تنگ", pin: "tang", en: "tight, narrow", notes: "دلم تنگ شده = my heart has become tight",
      examples: [
        { fa: "دلم برای تو تنگ شده!", pin: "delam barāye to tang shodeh!", en: "I miss you!", source: "phrase:32" },
        { fa: "دلم برات خیلی تنگ شده!", pin: "delam barāt kheili tang shodeh!", en: "I miss you so much!", source: "phrase:32" },
        { fa: "من هم دلم برات تنگ شده!", pin: "man ham delam barāt tang shodeh!", en: "I miss you too!", source: "phrase:32" },
      ] },
    // Grammar
    { id: "32.g.past-stem-infinitive", type: "grammar", fa: "گذشته‌ی ساده", pin: "past stem = infinitive − ن", en: "THE SIMPLE PAST: drop the final ن, add the endings", notes: "رفتن → رفت / دیدن → دید / کردن → کرد" },
    { id: "32.g.am-i-im-id-an", type: "grammar", fa: "ـم، ـی، ـ، ـیم، ـید، ـن", pin: "-am, -i, —, -im, -id, -an", en: "past endings (3rd person singular takes NO ending)", notes: "رفتم، رفتی، رفت، رفتیم، رفتید، رفتن" },
    { id: "32.g.boodam", type: "grammar", fa: "بودم", pin: "boodam", en: "I was", notes: "بود + م" },
    { id: "32.g.boodi", type: "grammar", fa: "بودی", pin: "boodi", en: "you were", notes: "بود + ی" },
    { id: "32.g.bood", type: "grammar", fa: "بود", pin: "bood", en: "he/she was", notes: "bare past stem — no ending" },
    { id: "32.g.boodim", type: "grammar", fa: "بودیم", pin: "boodim", en: "we were", notes: "بود + یم" },
    { id: "32.g.boodid", type: "grammar", fa: "بودید", pin: "boodid", en: "you (pl) were", notes: "بود + ید" },
    { id: "32.g.boodand-boodan", type: "grammar", fa: "بودند", pin: "boodand / boodan", en: "they were", notes: "formal بودند, colloquial بودن" },
    { id: "32.g.naboodam", type: "grammar", fa: "نبودم", pin: "naboodam", en: "I wasn't", notes: "نـ (not) + بودم" },
    { id: "32.g.nabood", type: "grammar", fa: "نبود", pin: "nabood", en: "he/she wasn't", notes: "نـ + بود" },
    { id: "32.g.dashtam", type: "grammar", fa: "داشتم", pin: "dāshtam", en: "I had", notes: "داشت + م" },
    { id: "32.g.dasht", type: "grammar", fa: "داشت", pin: "dāsht", en: "he/she had", notes: "bare past stem" },
    { id: "32.g.dashtim", type: "grammar", fa: "داشتیم", pin: "dāshtim", en: "we had", notes: "داشت + یم" },
    { id: "32.g.nadashtam", type: "grammar", fa: "نداشتم", pin: "nadāshtam", en: "I didn't have", notes: "نـ + داشتم" },
    { id: "32.g.doost-dashtam", type: "grammar", fa: "دوست داشتم", pin: "doost dāshtam", en: "I liked, I loved", notes: "دوست + داشتم" },
    { id: "32.g.doost-nadashtam", type: "grammar", fa: "دوست نداشتم", pin: "doost nadāshtam", en: "I didn't like", notes: "دوست + نداشتم" },
    { id: "32.g.kardam", type: "grammar", fa: "کردم", pin: "kardam", en: "I did", notes: "کرد + م" },
    { id: "32.g.raftam", type: "grammar", fa: "رفتم", pin: "raftam", en: "I went", notes: "رفت + م" },
    { id: "32.g.khordam", type: "grammar", fa: "خوردم", pin: "khordam", en: "I ate, I drank", notes: "خورد + م" },
    { id: "32.g.didam", type: "grammar", fa: "دیدم", pin: "didam", en: "I saw", notes: "دید + م" },
    { id: "32.g.oomadam", type: "grammar", fa: "اومدم", pin: "oomadam", en: "I came", notes: "اومد + م" },
    { id: "32.g.shodam", type: "grammar", fa: "شدم", pin: "shodam", en: "I became, I got", notes: "شد + م" },
    { id: "32.g.khabidam", type: "grammar", fa: "خوابیدم", pin: "khābidam", en: "I slept", notes: "خوابید + م" },
    { id: "32.g.zendegi-kardam", type: "grammar", fa: "زندگی کردم", pin: "zendegi kardam", en: "I lived", notes: "زندگی + کردم — compare زندگی می‌کنم (I live)" },
    { id: "32.g.mikham", type: "grammar", fa: "می‌خوام", pin: "mikhām", en: "I want", notes: "colloquial of می‌خواهم" },
    { id: "32.g.mikhay", type: "grammar", fa: "می‌خوای", pin: "mikhāy", en: "you want", notes: "می + خوا + ی" },
    { id: "32.g.mikhad", type: "grammar", fa: "می‌خواد", pin: "mikhād", en: "he/she wants", notes: "می + خوا + د" },
    { id: "32.g.mikhaym", type: "grammar", fa: "می‌خوایم", pin: "mikhāym", en: "we want", notes: "می + خوا + یم" },
    { id: "32.g.mikhayd", type: "grammar", fa: "می‌خواید", pin: "mikhāyd", en: "you (pl) want", notes: "می + خوا + ید" },
    { id: "32.g.mikhan", type: "grammar", fa: "می‌خوان", pin: "mikhān", en: "they want", notes: "می + خوا + ن" },
    { id: "32.g.miam", type: "grammar", fa: "میام", pin: "miām", en: "I come", notes: "می + ا + م (stem of اومدن)" },
    { id: "32.g.miay", type: "grammar", fa: "میای", pin: "miāy", en: "you come", notes: "می + ا + ی" },
    { id: "32.g.miad", type: "grammar", fa: "میاد", pin: "miād", en: "he/she comes", notes: "می + ا + د" },
    { id: "32.g.miaym", type: "grammar", fa: "میایم", pin: "miāym", en: "we come", notes: "می + ا + یم" },
    { id: "32.g.miayd", type: "grammar", fa: "میاید", pin: "miāyd", en: "you (pl) come", notes: "می + ا + ید" },
    { id: "32.g.mian", type: "grammar", fa: "میان", pin: "miān", en: "they come", notes: "می + ا + ن" },
    { id: "32.g.nemiam", type: "grammar", fa: "نمیام", pin: "nemiām", en: "I don't come", notes: "نمی + ام" },
    { id: "32.g.daram-miam", type: "grammar", fa: "دارم میام", pin: "dāram miām", en: "I'm coming (right now)", notes: "دارم + میام" },
    { id: "32.g.bia", type: "grammar", fa: "بیا", pin: "biā", en: "come! (imperative)", notes: "imperative of اومدن" },
    { id: "32.g.misham", type: "grammar", fa: "می‌شم", pin: "misham", en: "I become, I get", notes: "می + ش + م" },
    { id: "32.g.misheh", type: "grammar", fa: "می‌شه", pin: "misheh", en: "he/she/it becomes, gets", notes: "می + ش + ه" },
    { id: "32.g.bidar-misham", type: "grammar", fa: "بیدار می‌شم", pin: "bidār misham", en: "I wake up", notes: "بیدار + می‌شم — formal: بیدار می‌شوم" },
    { id: "32.g.bidar-sho", type: "grammar", fa: "بیدار شو", pin: "bidār sho", en: "wake up! (imperative)", notes: "بیدار + شو" },
    { id: "32.g.mikhabam", type: "grammar", fa: "می‌خوابم", pin: "mikhābam", en: "I sleep, I go to bed", notes: "می + خواب + م" },
    { id: "32.g.mibandam", type: "grammar", fa: "می‌بندم", pin: "mibandam", en: "I close, I'll close", notes: "می + بند + م (stem of بستن)" },
    { id: "32.g.beband", type: "grammar", fa: "ببند", pin: "beband", en: "close it! (imperative)", notes: "ب + بند" },
    { id: "32.g.baz-kon", type: "grammar", fa: "باز کن", pin: "bāz kon", en: "open it! (imperative)", notes: "باز + کن" },
    { id: "32.g.baz-nakon", type: "grammar", fa: "باز نکن", pin: "bāz nakon", en: "don't open it!", notes: "باز + نکن" },
    // Phrases
    { id: "32.p.man-komak-lazem-daram", type: "phrases", fa: "من کمک لازم دارم", pin: "man komak lāzem dāram", en: "I need help", notes: "کمک + لازم دارم" },
    { id: "32.p.man-komak-mikham", type: "phrases", fa: "من کمک می‌خوام", pin: "man komak mikhām", en: "I want help", notes: "کمک + می‌خوام" },
    { id: "32.p.to-komak-mikhay", type: "phrases", fa: "تو کمک می‌خوای؟", pin: "to komak mikhāy?", en: "Do you want help?", notes: "کمک + می‌خوای" },
    { id: "32.p.man-daram-miam", type: "phrases", fa: "من دارم میام", pin: "man dāram miām", en: "I'm coming", notes: "present continuous of اومدن" },
    { id: "32.p.to-dari-miay", type: "phrases", fa: "تو داری میای؟", pin: "to dāri miāy?", en: "Are you coming?", notes: "داری + میای" },
    { id: "32.p.oon-dareh-miad", type: "phrases", fa: "اون داره میاد", pin: "oon dāreh miād", en: "He/she is coming", notes: "داره + میاد" },
    { id: "32.p.man-ye-sib-mikham", type: "phrases", fa: "من یه سیب می‌خوام", pin: "man ye sib mikhām", en: "I want an apple", notes: "یه سیب (an apple)" },
    { id: "32.p.man-nemiam", type: "phrases", fa: "من نمیام", pin: "man nemiām", en: "I'm not coming", notes: "نمیام (negative)" },
    { id: "32.p.oon-hamsaye-ye-mast", type: "phrases", fa: "اون همسایه‌ی ماست", pin: "oon hamsāye-ye māst", en: "He/she is our neighbour", notes: "همسایه + ی + ما + ست" },
    { id: "32.p.oonha-daran-televizion-tamasha", type: "phrases", fa: "اونها دارن تلویزیون تماشا می‌کنن", pin: "oonhā dāran televizion tamāshā mikonan", en: "They're watching TV", notes: "تماشا کردن for TV" },
    { id: "32.p.oon-vaghean-bahoosh-e", type: "phrases", fa: "اون واقعاً باهوشه", pin: "oon vāghean bāhoosh-e", en: "He/she is really smart", notes: "واقعاً (really) + باهوش + ه" },
    { id: "32.p.gooshim-kojast", type: "phrases", fa: "گوشیم کجاست؟", pin: "gooshim kojāst?", en: "Where's my phone?", notes: "گوشی + م (my) + کجاست" },
    { id: "32.p.boodan-ya-naboodan-masale-in-ast", type: "phrases", fa: "بودن یا نبودن، مسئله این است!", pin: "boodan yā naboodan, mas'ale in ast!", en: "To be or not to be, that is the question!", notes: "the two infinitives contrasted" },
    { id: "32.p.man-diruz-khoone-boodam", type: "phrases", fa: "من دیروز خونه بودم", pin: "man diruz khoone boodam", en: "I was at home yesterday", notes: "دیروز + بودم (past of بودن)" },
    { id: "32.p.dishab-koja-boodi", type: "phrases", fa: "دیشب کجا بودی؟", pin: "dishab kojā boodi?", en: "Where were you last night?", notes: "دیشب + کجا + بودی" },
    { id: "32.p.ma-sal-e-pish-gorbeh-nadashtim", type: "phrases", fa: "ما سال پیش گربه نداشتیم ولی الان دو تا گربه داریم", pin: "mā sāl-e pish gorbeh nadāshtim vali alān do tā gorbeh dārim", en: "Last year we didn't have a cat but now we have two cats", notes: "نداشتیم (past) vs داریم (present)" },
    { id: "32.p.sam-do-sal-e-pish-mashin-dasht", type: "phrases", fa: "سام دو سال پیش ماشین داشت ولی الان ماشین نداره", pin: "Sam do sāl-e pish māshin dāsht vali alān māshin nadāreh", en: "Two years ago Sam had a car but now he doesn't", notes: "داشت (past) vs نداره (present)" },
    { id: "32.p.man-mahi-doost-nadashtam-vali", type: "phrases", fa: "من ماهی دوست نداشتم ولی الان دوست دارم", pin: "man māhi doost nadāshtam vali alān doost dāram", en: "I didn't like fish but now I do", notes: "دوست نداشتم → دوست دارم" },
    { id: "32.p.man-sag-ha-ro-doost-nadashtam", type: "phrases", fa: "من سگ‌ها رو دوست نداشتم ولی الان سگ‌ها رو دوست دارم", pin: "man sag-hā ro doost nadāshtam vali alān sag-hā ro doost dāram", en: "I didn't like dogs but now I like dogs", notes: "سگ‌ها رو (dogs, object)" },
    { id: "32.p.man-panir-doost-nadashtam-amma", type: "phrases", fa: "من پنیر دوست نداشتم، اما الان پنیر خیلی دوست دارم", pin: "man panir doost nadāshtam, ammā alān panir kheili doost dāram", en: "I didn't like cheese, but now I like cheese a lot", notes: "اما (but) = ولی" },
    { id: "32.p.man-do-sal-dar-alman-zendegi", type: "phrases", fa: "من دو سال در آلمان زندگی کردم", pin: "man do sāl dar Ālmān zendegi kardam", en: "I lived in Germany for two years", notes: "زندگی کردم (past)" },
    { id: "32.p.man-alan-dar-manchester-zendegi", type: "phrases", fa: "من الان در منچستر زندگی می‌کنم", pin: "man alān dar Manchester zendegi mikonam", en: "I live in Manchester now", notes: "زندگی می‌کنم (present)" },
    { id: "32.p.dar-baz-hast", type: "phrases", fa: "در باز هست", pin: "dar bāz hast", en: "The door is open", notes: "در (door) + باز (open)" },
    { id: "32.p.oonha-saat-e-hasht-e-sobh-baz", type: "phrases", fa: "اونها ساعت هشت صبح باز می‌کنن", pin: "oonhā sāat-e hasht-e sobh bāz mikonan", en: "They open at 8 AM", notes: "باز می‌کنن (they open something)" },
    { id: "32.p.oonha-saat-e-hasht-e-sobh-baz-2", type: "phrases", fa: "اونها ساعت هشت صبح باز هستن", pin: "oonhā sāat-e hasht-e sobh bāz hastan", en: "They are open at 8 AM", notes: "باز هستن (they are open)" },
    { id: "32.p.lotfan-dar-ro-baz-kon", type: "phrases", fa: "لطفاً در رو باز کن!", pin: "lotfan dar ro bāz kon!", en: "Open the door please!", notes: "در رو + باز کن" },
    { id: "32.p.lotfan-dar-ro-baz-nakon", type: "phrases", fa: "لطفاً در رو باز نکن!", pin: "lotfan dar ro bāz nakon!", en: "Don't open the door please!", notes: "باز نکن (negative imperative)" },
    { id: "32.p.emrooz-baz-hastid", type: "phrases", fa: "امروز باز هستید؟", pin: "emrooz bāz hastid?", en: "Are you open today?", notes: "باز هستید (formal/plural)" },
    { id: "32.p.dar-baste-hast", type: "phrases", fa: "در بسته هست", pin: "dar baste hast", en: "The door is closed", notes: "بسته (closed)" },
    { id: "32.p.yek-baste-sigar", type: "phrases", fa: "یک بسته سیگار", pin: "yek baste sigār", en: "a pack of cigarettes", notes: "also یک پاکت سیگار" },
    { id: "32.p.yek-baste-ye-shokolat", type: "phrases", fa: "یک بسته‌ی شکلات", pin: "yek baste-ye shokolāt", en: "a packet of chocolates", notes: "بسته‌ی + شکلات" },
    { id: "32.p.bastegi-dareh", type: "phrases", fa: "بستگی داره!", pin: "bastegi dāreh!", en: "It depends!", notes: "lit. 'it has a tie to it'" },
    { id: "32.p.dar-ro-beband", type: "phrases", fa: "در رو ببند!", pin: "dar ro beband!", en: "Close the door!", notes: "ببند (imperative of بستن)" },
    { id: "32.p.man-dar-ro-mibandam", type: "phrases", fa: "من در رو می‌بندم", pin: "man dar ro mibandam", en: "I'll close the door", notes: "می‌بندم (present = near future)" },
    { id: "32.p.man-dard-daram", type: "phrases", fa: "من درد دارم", pin: "man dard dāram", en: "I'm in pain", notes: "درد + دارم" },
    { id: "32.p.man-sar-dard-daram", type: "phrases", fa: "من سردرد دارم", pin: "man sar-dard dāram", en: "I have a headache", notes: "سردرد + دارم" },
    { id: "32.p.man-del-dard-daram", type: "phrases", fa: "من دل‌درد دارم", pin: "man del-dard dāram", en: "I have a stomachache", notes: "دل‌درد + دارم" },
    { id: "32.p.saram-dard-mikoneh", type: "phrases", fa: "سرم درد می‌کنه", pin: "saram dard mikoneh", en: "My head hurts", notes: "سر + م (my) + درد می‌کنه" },
    { id: "32.p.pam-dard-mikoneh", type: "phrases", fa: "پام درد می‌کنه", pin: "pām dard mikoneh", en: "My leg hurts", notes: "پا + م (my)" },
    { id: "32.p.paham-dard-mikoneh", type: "phrases", fa: "پاهام درد می‌کنه", pin: "pāhām dard mikoneh", en: "My legs hurt", notes: "پاها + م (my)" },
    { id: "32.p.dastam-dard-mikoneh", type: "phrases", fa: "دستم درد می‌کنه", pin: "dastam dard mikoneh", en: "My hand hurts", notes: "دست + م (my)" },
    { id: "32.p.delam-dard-mikoneh", type: "phrases", fa: "دلم درد می‌کنه", pin: "delam dard mikoneh", en: "My stomach hurts", notes: "دل + م (my)" },
    { id: "32.p.kheili-dard-mikoneh", type: "phrases", fa: "خیلی درد می‌کنه", pin: "kheili dard mikoneh", en: "It really hurts", notes: "خیلی (very) + درد می‌کنه" },
    { id: "32.p.shoone-am-dard-mikoneh", type: "phrases", fa: "شونه‌ام درد می‌کنه", pin: "shoone-am dard mikoneh", en: "My shoulder hurts", notes: "شونه + ام (my)" },
    { id: "32.p.poshtam-dard-mikoneh", type: "phrases", fa: "پشتم درد می‌کنه", pin: "poshtam dard mikoneh", en: "My back hurts", notes: "پشت + م (my)" },
    { id: "32.p.kamaram-dard-mikoneh", type: "phrases", fa: "کمرم درد می‌کنه", pin: "kamaram dard mikoneh", en: "My lower back hurts", notes: "کمر + م (my)" },
    { id: "32.p.goosham-dard-mikoneh", type: "phrases", fa: "گوشم درد می‌کنه", pin: "goosham dard mikoneh", en: "My ear hurts", notes: "گوش + م (my)" },
    { id: "32.p.dandoonam-dard-mikoneh", type: "phrases", fa: "دندونم درد می‌کنه", pin: "dandoonam dard mikoneh", en: "My tooth hurts", notes: "دندون + م (my)" },
    { id: "32.p.dastet-dard-nakoneh", type: "phrases", fa: "دستت درد نکنه!", pin: "dastet dard nakoneh!", en: "Thank you! (lit. may your hand not hurt)", notes: "a wish that your effort cost you no pain" },
    { id: "32.p.man-bidar-hastam", type: "phrases", fa: "من بیدار هستم", pin: "man bidār hastam", en: "I am awake", notes: "بیدار + هستم" },
    { id: "32.p.bidar-sho", type: "phrases", fa: "بیدار شو!", pin: "bidār sho!", en: "Wake up!", notes: "بیدار + شو (imperative)" },
    { id: "32.p.man-har-rooz-saat-e-shish-az", type: "phrases", fa: "من هر روز ساعت شیش از خواب بیدار می‌شم", pin: "man har rooz sāat-e shish az khāb bidār misham", en: "I wake up at six every day", notes: "از خواب بیدار شدن = to wake from sleep" },
    { id: "32.p.shoma-key-az-khab-bidar-mishid", type: "phrases", fa: "شما کی از خواب بیدار می‌شید؟", pin: "shomā key az khāb bidār mishid?", en: "What time do you wake up?", notes: "کی (when) + بیدار می‌شید" },
    { id: "32.p.hava-dareh-sard-misheh", type: "phrases", fa: "هوا داره سرد می‌شه", pin: "havā dāreh sard misheh", en: "The weather is getting cold", notes: "داره + سرد می‌شه (becoming)" },
    { id: "32.p.hava-dareh-kheili-garm-misheh", type: "phrases", fa: "هوا داره خیلی گرم می‌شه", pin: "havā dāreh kheili garm misheh", en: "The weather is getting very hot", notes: "گرم می‌شه (getting hot)" },
    { id: "32.p.oon-khab-e", type: "phrases", fa: "اون خوابه", pin: "oon khāb-e", en: "He/she is asleep", notes: "خواب + ه — also اون خوابیده" },
    { id: "32.p.to-key-mikhabi", type: "phrases", fa: "تو کی می‌خوابی؟", pin: "to key mikhābi?", en: "What time do you go to sleep?", notes: "کی (when) + می‌خوابی" },
    { id: "32.p.man-saat-e-dah-e-shab-mikhabam", type: "phrases", fa: "من ساعت ده شب می‌خوابم", pin: "man sāat-e dah-e shab mikhābam", en: "I go to bed at 10 PM", notes: "ساعت ده شب + می‌خوابم" },
    { id: "32.p.baradaram-saat-e-yazdah-mikhabeh", type: "phrases", fa: "برادرم ساعت یازده می‌خوابه", pin: "barādaram sāat-e yāzdah mikhābeh", en: "My brother goes to bed at eleven", notes: "برادرم (my brother)" },
    { id: "32.p.man-saat-e-noh-o-rob-mikhabam", type: "phrases", fa: "من ساعت نه و ربع می‌خوابم", pin: "man sāat-e noh-o rob mikhābam", en: "I go to bed at quarter past nine", notes: "نه و ربع (9:15)" },
    { id: "32.p.to-saat-e-chand-sobhooneh", type: "phrases", fa: "تو ساعت چند صبحونه می‌خوری؟", pin: "to sāat-e chand sobhooneh mikhori?", en: "What time do you eat breakfast?", notes: "ساعت چند (what time)" },
    { id: "32.p.to-saat-e-chand-nahar-mikhori", type: "phrases", fa: "تو ساعت چند ناهار می‌خوری؟", pin: "to sāat-e chand nāhār mikhori?", en: "What time do you eat lunch?", notes: "ناهار (lunch)" },
    { id: "32.p.to-har-shab-saat-e-chand-mikhabi", type: "phrases", fa: "تو هر شب ساعت چند می‌خوابی؟", pin: "to har shab sāat-e chand mikhābi?", en: "What time do you go to sleep every night?", notes: "هر شب (every night)" },
    { id: "32.p.to-saat-e-chand-be-bashgah-miri", type: "phrases", fa: "تو ساعت چند به باشگاه می‌ری؟", pin: "to sāat-e chand be bāshgāh miri?", en: "What time do you go to the gym?", notes: "به باشگاه می‌ری" },
    { id: "32.p.delam-baraye-to-tang-shodeh", type: "phrases", fa: "دلم برای تو تنگ شده!", pin: "delam barāye to tang shodeh!", en: "I miss you!", notes: "lit. my heart has become tight for you" },
    { id: "32.p.delam-barat-kheili-tang-shodeh", type: "phrases", fa: "دلم برات خیلی تنگ شده!", pin: "delam barāt kheili tang shodeh!", en: "I miss you so much!", notes: "برات = برای تو" },
    { id: "32.p.man-ham-delam-barat-tang-shodeh", type: "phrases", fa: "من هم دلم برات تنگ شده!", pin: "man ham delam barāt tang shodeh!", en: "I miss you too!", notes: "من هم (me too)" },
    { id: "32.p.man-ham-hamintor", type: "phrases", fa: "من هم همین‌طور!", pin: "man ham hamintor!", en: "Me too! Same here!", notes: "همین‌طور (likewise)" },
    // Story
    { id: "32.s.ye-khanevade-ye-khoshhal", type: "story", fa: "یه خانواده‌ی خوشحال", pin: "ye khānevāde-ye khoshhāl", en: "A happy family", notes: "خانواده + ی + خوشحال (ezāfe)" },
    { id: "32.s.saeed-o-mitra-hamsaye-ha-ye-ma", type: "story", fa: "سعید و میترا همسایه‌های ما هستن.", pin: "Saeed-o Mitrā hamsāye-hā-ye mā hastan.", en: "Saeed and Mitra are our neighbours.", notes: "همسایه‌ها + ی + ما" },
    { id: "32.s.oonha-zan-o-shohar-an-va-se-ta", type: "story", fa: "اونها زن و شوهرن و سه تا بچه دارن.", pin: "oonhā zan-o shohar-an va se tā bache dāran.", en: "They are husband and wife and have three children.", notes: "سه تا بچه (three children)" },
    { id: "32.s.oonha-saat-e-shish-az-khab-bidar", type: "story", fa: "اونها ساعت شیش از خواب بیدار می‌شن.", pin: "oonhā sāat-e shish az khāb bidār mishan.", en: "They wake up at six o'clock.", notes: "بیدار می‌شن (they wake up)" },
    { id: "32.s.va-saat-e-haft-e-sobh-too", type: "story", fa: "و ساعت هفت صبح تو آشپزخونه صبحونه می‌خورن: نون خانگی، پنیر، مربا، تخم مرغ و چای شیرین.", pin: "va sāat-e haft-e sobh too āshpazkhooneh sobhooneh mikhoran: noon-e khānegi, panir, morabbā, tokhm-e morgh va chāy-e shirin.", en: "And at seven in the morning they have breakfast in the kitchen: homemade bread, cheese, jam, eggs and sweet tea.", notes: "صبحونه خوردن = to have breakfast" },
    { id: "32.s.baad-bache-ha-miran-madreseh-va", type: "story", fa: "بعد بچه‌ها می‌رن مدرسه و پدر و مادر می‌رن سر کار.", pin: "baad bache-hā miran madreseh va pedar-o mādar miran sar-e kār.", en: "Then the children go to school and the parents go to work.", notes: "سر کار (to work)" },
    { id: "32.s.saeed-too-ye-maghazeh-kar", type: "story", fa: "سعید تو یه مغازه کار می‌کنه و میترا تو یه آرایشگاه کار می‌کنه.", pin: "Saeed too ye maghāzeh kār mikoneh va Mitrā too ye ārāyeshgāh kār mikoneh.", en: "Saeed works at a shop and Mitra works at a hair salon.", notes: "مغازه / آرایشگاه (session 31)" },
    { id: "32.s.oon-arayeshgar-e", type: "story", fa: "اون آرایشگره.", pin: "oon ārāyeshgar-e.", en: "She is a hairdresser.", notes: "آرایشگر + ه (is)" },
    { id: "32.s.mitra-saat-e-chahar-baad-az", type: "story", fa: "میترا ساعت چهار بعد از خرید میاد خونه و یه غذای گرم درست می‌کنه.", pin: "Mitrā sāat-e chahār baad az kharid miād khooneh va ye ghazā-ye garm dorost mikoneh.", en: "Mitra comes home at four after shopping and cooks a warm meal.", notes: "میاد خونه (comes home)" },
    { id: "32.s.bache-ha-ta-saat-e-haft-ba", type: "story", fa: "بچه‌ها تا ساعت هفت با همدیگه بازی می‌کنن.", pin: "bache-hā tā sāat-e haft bā hamdige bāzi mikonan.", en: "The children play with each other until seven.", notes: "تا (until) + با همدیگه (with each other)" },
    { id: "32.s.saeed-saat-e-haft-o-nim-miad", type: "story", fa: "سعید ساعت هفت و نیم میاد خونه.", pin: "Saeed sāat-e haft-o nim miād khooneh.", en: "Saeed comes home at half past seven.", notes: "هفت و نیم (7:30)" },
    { id: "32.s.khanevadeh-saat-e-hasht-too", type: "story", fa: "خانواده ساعت هشت تو آشپزخونه شام می‌خورن.", pin: "khānevādeh sāat-e hasht too āshpazkhooneh shām mikhoran.", en: "The family eats dinner in the kitchen at eight.", notes: "شام خوردن = to have dinner" },
    { id: "32.s.bache-ha-saat-e-noh-mikhaban", type: "story", fa: "بچه‌ها ساعت نه می‌خوابن.", pin: "bache-hā sāat-e noh mikhāban.", en: "The children go to bed at nine.", notes: "می‌خوابن (they sleep)" },
    { id: "32.s.va-saeed-o-mitra-yek-saat", type: "story", fa: "و سعید و میترا یک ساعت تلویزیون تماشا می‌کنن و ساعت ده می‌خوابن.", pin: "va Saeed-o Mitrā yek sāat televizion tamāshā mikonan va sāat-e dah mikhāban.", en: "And Saeed and Mitra watch TV for an hour and go to bed at ten.", notes: "یک ساعت (for one hour)" },
    { id: "32.s.vali-dishab", type: "story", fa: "ولی دیشب...", pin: "vali dishab...", en: "But last night...", notes: "دیشب (last night) — the past tense is coming!" },
  ],
});
