// Session 33.
// Item ids are permanent. Never change or reuse one; add new items with new ids.
F.lesson({
  id: "33",
  label: "Session 33",
  title: "Zadan and time ago",
  summary: "Cheshm / chashm, time ago (pish / ghabl), hame, zadan and its compounds.",
  items: [
    // Vocabulary
    { id: "33.v.cheshm-chashm", type: "vocabulary", fa: "چشم", pin: "cheshm / chashm", en: "eye; (as a reply) yes, gladly / as you wish", notes: "چشم = I'll do it, it's on my eyes. چَشم is more formal/poetic; چِشم is everyday",
      examples: [
        { fa: "بچه‌ها می‌گن: «چشم!»", pin: "Bacheh hā migan: \"Cheshm!\"", en: "The children say: \"Yes, Mom!\"", source: "story:st-33-2" },
      ] },
    { id: "33.v.pariruz", type: "vocabulary", fa: "پریروز", pin: "pariruz", en: "the day before yesterday", notes: "پری (before last) + روز" },
    { id: "33.v.parishab", type: "vocabulary", fa: "پریشب", pin: "parishab", en: "the night before last", notes: "پری + شب" },
    { id: "33.v.gozashteh", type: "vocabulary", fa: "گذشته", pin: "gozashteh", en: "last, past", notes: "هفته‌ی گذشته = last week" },
    { id: "33.v.ghabl", type: "vocabulary", fa: "قبل", pin: "ghabl", en: "previous, ago, before", notes: "قبل از = before",
      examples: [
        { fa: "قبل از ناهار", pin: "ghabl az nāhār", en: "before lunch", source: "phrase:33" },
        { fa: "قبل از شام، ما با همدیگه گپ زدیم.", pin: "Ghabl az shām, mā bā hamdige gap zadim.", en: "Before dinner, we chatted.", source: "story:st-33-1" },
        { fa: "قبل از صبحونه، بچه‌ها دندون‌هاشون رو مسواک می‌زنن.", pin: "Ghabl az sobhooneh, bacheh hā dandoon hāshoon ro mesvāk mizanan.", en: "Before breakfast, the children brush their teeth.", source: "story:st-33-2" },
      ] },
    { id: "33.v.baad-az", type: "vocabulary", fa: "بعد از", pin: "baad az", en: "after", notes: "also پس از (pas az) — a bit more formal",
      examples: [
        { fa: "بعد از شام", pin: "baad az shām", en: "after dinner", source: "phrase:33" },
        { fa: "میترا ساعت چهار بعد از خرید میاد خونه و یه غذای گرم درست می‌کنه.", pin: "Mitrā sāat-e chahār baad az kharid miād khooneh va ye ghazā-ye garm dorost mikoneh.", en: "Mitra comes home at four after shopping and cooks a warm meal.", source: "story:32" },
        { fa: "سارا می‌گه: «من فردا صبح سر کار می‌رم، ولی بعد از ظهر وقت دارم.»", pin: "Sārā migeh: \"Man fardā sobh sar-e kār miram, vali ba'd az zohr vaght dāram.\"", en: "Sara says: \"I'm going to work tomorrow morning, but I'm free in the afternoon.\"", source: "story:st-28-1" },
        { fa: "بعد از غذا، ما دسر و چای می‌خوریم.", pin: "Ba'd az ghazā, mā deser o chāy mikhorim.", en: "After the meal, we have dessert and tea.", source: "story:st-2425-1" },
      ] },
    { id: "33.v.pas-az", type: "vocabulary", fa: "پس از", pin: "pas az", en: "after (slightly formal)", notes: "پس + از" },
    { id: "33.v.ghabl-az", type: "vocabulary", fa: "قبل از", pin: "ghabl az", en: "before", notes: "قبل + از — also پیش از (pish az)",
      examples: [
        { fa: "قبل از ناهار", pin: "ghabl az nāhār", en: "before lunch", source: "phrase:33" },
        { fa: "قبل از شام، ما با همدیگه گپ زدیم.", pin: "Ghabl az shām, mā bā hamdige gap zadim.", en: "Before dinner, we chatted.", source: "story:st-33-1" },
        { fa: "قبل از صبحونه، بچه‌ها دندون‌هاشون رو مسواک می‌زنن.", pin: "Ghabl az sobhooneh, bacheh hā dandoon hāshoon ro mesvāk mizanan.", en: "Before breakfast, the children brush their teeth.", source: "story:st-33-2" },
      ] },
    { id: "33.v.pish-az", type: "vocabulary", fa: "پیش از", pin: "pish az", en: "before", notes: "پیش + از" },
    { id: "33.v.hameh", type: "vocabulary", fa: "همه", pin: "hameh", en: "all, every, everyone, everything", notes: "همه‌ی + noun = all the X; alone = everyone",
      examples: [
        { fa: "من همه‌ی ساندویچم رو می‌خورم", pin: "man hameh-ye sāndevich-am ro mikhoram", en: "I eat all of my sandwich", source: "phrase:33" },
        { fa: "شب، مامانم گفت: «به همه سلام برسون!»", pin: "Shab, māmānam goft: \"Be hameh salām beresoon!\"", en: "In the evening, my mom said: \"Say hello to everyone!\"", source: "story:st-33-1" },
        { fa: "همه‌ی دانشجوها اینجا هستن", pin: "hameh-ye dāneshjoo-hā injā hastan", en: "All the students are here", source: "phrase:33" },
        { fa: "همه‌ی خانواده اینجا بودن", pin: "hameh-ye khānevādeh injā boodan", en: "The whole family was here", source: "phrase:33" },
      ] },
    { id: "33.v.hameh-chiz", type: "vocabulary", fa: "همه‌چیز", pin: "hameh-chiz", en: "everything", notes: "همه + چیز (thing)",
      examples: [
        { fa: "همه‌چیز خوب بود", pin: "hameh-chiz khoob bood", en: "Everything was good", source: "phrase:33" },
        { fa: "همه‌چیز عالی بود!", pin: "Hameh-chiz āli bood!", en: "Everything was great!", source: "story:st-33-1" },
        { fa: "بعد از صبحونه، مامان می‌گه: «زود باشید! همه‌چیز آماده‌ست؟»", pin: "Ba'd az sobhooneh, māmān migeh: \"Zood bāshid! Hameh-chiz āmādeh-st?\"", en: "After breakfast, Mom says: \"Hurry up! Is everything ready?\"", source: "story:st-33-2" },
        { fa: "همه‌چیز خوبه", pin: "hameh-chiz khoob-e", en: "Everything is good", source: "phrase:33" },
      ] },
    { id: "33.v.hameh-ja", type: "vocabulary", fa: "همه‌جا", pin: "hameh-jā", en: "everywhere", notes: "همه + جا (place)" },
    { id: "33.v.zadan", type: "vocabulary", fa: "زدن", pin: "zadan", en: "to hit, to strike", notes: "present stem: زن (zan) — the base of a huge family of verbs",
      examples: [
        { fa: "من توپ رو می‌زنم", pin: "man toop ro mizanam", en: "I'll hit the ball", source: "phrase:33" },
        { fa: "مامانم هر هفته به من زنگ می‌زنه.", pin: "Māmānam har hafteh be man zang mizaneh.", en: "My mom calls me every week.", source: "story:st-33-1" },
        { fa: "من به کامپیوترت دست نمی‌زنم", pin: "man be kāmpiooteret dast nemizanam", en: "I'm not touching your computer", source: "phrase:33" },
        { fa: "ما داریم برات دست می‌زنیم", pin: "mā dārim barāt dast mizanim", en: "We're clapping for you", source: "phrase:33" },
      ] },
    { id: "33.v.toop", type: "vocabulary", fa: "توپ", pin: "toop", en: "ball", notes: "ت-و-پ",
      examples: [
        { fa: "من توپ رو می‌زنم", pin: "man toop ro mizanam", en: "I'll hit the ball", source: "phrase:33" },
        { fa: "من توپ رو زدم", pin: "man toop ro zadam", en: "I hit the ball", source: "phrase:33" },
      ] },
    { id: "33.v.dast-zadan-be", type: "vocabulary", fa: "دست زدن به", pin: "dast zadan be", en: "to touch", notes: "دست + زدن + به (to)",
      examples: [
        { fa: "من به کامپیوترت دست نمی‌زنم", pin: "man be kāmpiooteret dast nemizanam", en: "I'm not touching your computer", source: "phrase:33" },
        { fa: "بعد از شام، مامانم پیانو زد و من براش دست زدم.", pin: "Ba'd az shām, māmānam piāno zad va man barāsh dast zadam.", en: "After dinner, my mom played the piano and I clapped for her.", source: "story:st-33-1" },
        { fa: "ما داریم برات دست می‌زنیم", pin: "mā dārim barāt dast mizanim", en: "We're clapping for you", source: "phrase:33" },
        { fa: "من به غذا‌ت دست نمی‌زنم", pin: "man be ghazāt dast nemizanam", en: "I won't touch your food", source: "phrase:33" },
      ] },
    { id: "33.v.dast-zadan-baraye", type: "vocabulary", fa: "دست زدن برای", pin: "dast zadan barāye", en: "to clap for, to applaud", notes: "دست + زدن + برای (for)",
      examples: [
        { fa: "من به کامپیوترت دست نمی‌زنم", pin: "man be kāmpiooteret dast nemizanam", en: "I'm not touching your computer", source: "phrase:33" },
        { fa: "بعد از شام، مامانم پیانو زد و من براش دست زدم.", pin: "Ba'd az shām, māmānam piāno zad va man barāsh dast zadam.", en: "After dinner, my mom played the piano and I clapped for her.", source: "story:st-33-1" },
        { fa: "ما داریم برات دست می‌زنیم", pin: "mā dārim barāt dast mizanim", en: "We're clapping for you", source: "phrase:33" },
        { fa: "من به غذا‌ت دست نمی‌زنم", pin: "man be ghazāt dast nemizanam", en: "I won't touch your food", source: "phrase:33" },
      ] },
    { id: "33.v.baram", type: "vocabulary", fa: "برام", pin: "barām", en: "for me", notes: "short for برای من" },
    { id: "33.v.barat", type: "vocabulary", fa: "برات", pin: "barāt", en: "for you", notes: "short for برای تو",
      examples: [
        { fa: "ما داریم برات دست می‌زنیم", pin: "mā dārim barāt dast mizanim", en: "We're clapping for you", source: "phrase:33" },
        { fa: "مامانم گفت: «آره! فردا بیا خونه، برات پیانو می‌زنم.»", pin: "Māmānam goft: \"Āreh! Fardā biā khooneh, barāt piāno mizanam.\"", en: "My mom said: \"Yes! Come over tomorrow, I'll play the piano for you.\"", source: "story:st-33-1" },
        { fa: "دلم برات خیلی تنگ شده!", pin: "delam barāt kheili tang shodeh!", en: "I miss you so much!", source: "phrase:32" },
        { fa: "من هم دلم برات تنگ شده!", pin: "man ham delam barāt tang shodeh!", en: "I miss you too!", source: "phrase:32" },
      ] },
    { id: "33.v.barash", type: "vocabulary", fa: "براش", pin: "barāsh", en: "for him, for her", notes: "short for برای اون",
      examples: [
        { fa: "بعد از شام، مامانم پیانو زد و من براش دست زدم.", pin: "Ba'd az shām, māmānam piāno zad va man barāsh dast zadam.", en: "After dinner, my mom played the piano and I clapped for her.", source: "story:st-33-1" },
      ] },
    { id: "33.v.baramoon", type: "vocabulary", fa: "برامون", pin: "barāmoon", en: "for us", notes: "short for برای ما" },
    { id: "33.v.baratoon", type: "vocabulary", fa: "براتون", pin: "barātoon", en: "for you (pl/formal)", notes: "short for برای شما" },
    { id: "33.v.barashoon", type: "vocabulary", fa: "براشون", pin: "barāshoon", en: "for them", notes: "short for برای اونا" },
    { id: "33.v.baraye", type: "vocabulary", fa: "برای", pin: "barāye", en: "for", notes: "preposition — contracted as برام، برات، براش...",
      examples: [
        { fa: "ما داریم برای تو دست می‌زنیم", pin: "mā dārim barāye to dast mizanim", en: "We're applauding you", source: "phrase:33" },
        { fa: "سارا می‌گه: «پیاده‌روی برای من سخته.»", pin: "Sārā migeh: \"Piāderavi barāye man sakht-eh.\"", en: "Sara says: \"Walking is hard for me.\"", source: "story:st-30-1" },
        { fa: "دلم برای تو تنگ شده!", pin: "delam barāye to tang shodeh!", en: "I miss you!", source: "phrase:32" },
        { fa: "پول داشتن برای من مهم نیست", pin: "pool dāshtan barāye man mohem nist", en: "Having money is not important to me", source: "phrase:27" },
      ] },
    { id: "33.v.dar-zadan", type: "vocabulary", fa: "در زدن", pin: "dar zadan", en: "to knock (on the door)", notes: "در (door) + زدن",
      examples: [
        { fa: "زنگ در رو بزن", pin: "zang-e dar ro bezan", en: "Ring the doorbell", source: "phrase:33" },
        { fa: "ساعت هشت، یکی زنگ در رو می‌زنه.", pin: "Sāat-e hasht, yeki zang-e dar ro mizaneh.", en: "At eight, someone rings the doorbell.", source: "story:st-33-2" },
      ] },
    { id: "33.v.zang", type: "vocabulary", fa: "زنگ", pin: "zang", en: "bell", notes: "ز-ن-گ",
      examples: [
        { fa: "زنگ در رو بزن", pin: "zang-e dar ro bezan", en: "Ring the doorbell", source: "phrase:33" },
        { fa: "مامانم هر هفته به من زنگ می‌زنه.", pin: "Māmānam har hafteh be man zang mizaneh.", en: "My mom calls me every week.", source: "story:st-33-1" },
        { fa: "امروز به مامانم زنگ می‌زنم", pin: "emrooz be māmānam zang mizanam", en: "I'll call my mum today", source: "phrase:33" },
        { fa: "تلفن زنگ می‌زنه", pin: "telefon zang mizaneh", en: "The phone is ringing", source: "phrase:33" },
      ] },
    { id: "33.v.zang-e-dar", type: "vocabulary", fa: "زنگ در", pin: "zang-e dar", en: "doorbell", notes: "زنگ + در",
      examples: [
        { fa: "زنگ در رو بزن", pin: "zang-e dar ro bezan", en: "Ring the doorbell", source: "phrase:33" },
        { fa: "ساعت هشت، یکی زنگ در رو می‌زنه.", pin: "Sāat-e hasht, yeki zang-e dar ro mizaneh.", en: "At eight, someone rings the doorbell.", source: "story:st-33-2" },
      ] },
    { id: "33.v.zang-zadan", type: "vocabulary", fa: "زنگ زدن", pin: "zang zadan", en: "to call, to ring", notes: "زنگ + زدن — also تلفن زدن",
      examples: [
        { fa: "امروز به مامانم زنگ می‌زنم", pin: "emrooz be māmānam zang mizanam", en: "I'll call my mum today", source: "phrase:33" },
        { fa: "مامانم هر هفته به من زنگ می‌زنه.", pin: "Māmānam har hafteh be man zang mizaneh.", en: "My mom calls me every week.", source: "story:st-33-1" },
        { fa: "ولی هفته‌ی پیش زنگ نزد.", pin: "Vali hafte-ye pish zang nazad.", en: "But last week she didn't call.", source: "story:st-33-1" },
        { fa: "دو روز پیش، من بهش زنگ زدم.", pin: "Do rooz-e pish, man behesh zang zadam.", en: "Two days ago, I called her.", source: "story:st-33-1" },
      ] },
    { id: "33.v.telefon-zadan", type: "vocabulary", fa: "تلفن زدن", pin: "telefon zadan", en: "to call (on the phone)", notes: "تلفن + زدن + به (to someone)",
      examples: [
        { fa: "من به تو تلفن می‌زنم", pin: "man be to telefon mizanam", en: "I'll call you", source: "phrase:33" },
      ] },
    { id: "33.v.harf", type: "vocabulary", fa: "حرف", pin: "harf", en: "word, saying, speech", notes: "ح-ر-ف",
      examples: [
        { fa: "ما فردا حرف می‌زنیم", pin: "mā fardā harf mizanim", en: "We'll talk tomorrow", source: "phrase:33" },
        { fa: "اون با من حرف نمی‌زنه", pin: "oon bā man harf nemizaneh", en: "She doesn't talk to me", source: "phrase:33" },
        { fa: "علی و سارا با همدیگه حرف می‌زنن.", pin: "Ali o Sārā bā hamdige harf mizanan.", en: "Ali and Sara are talking.", source: "story:st-34-1" },
      ] },
    { id: "33.v.harf-zadan", type: "vocabulary", fa: "حرف زدن", pin: "harf zadan", en: "to talk", notes: "حرف + زدن + با (with) — also صحبت کردن",
      examples: [
        { fa: "ما فردا حرف می‌زنیم", pin: "mā fardā harf mizanim", en: "We'll talk tomorrow", source: "phrase:33" },
        { fa: "اون با من حرف نمی‌زنه", pin: "oon bā man harf nemizaneh", en: "She doesn't talk to me", source: "phrase:33" },
        { fa: "علی و سارا با همدیگه حرف می‌زنن.", pin: "Ali o Sārā bā hamdige harf mizanan.", en: "Ali and Sara are talking.", source: "story:st-34-1" },
      ] },
    { id: "33.v.sohbat-kardan", type: "vocabulary", fa: "صحبت کردن", pin: "sohbat kardan", en: "to talk, to speak", notes: "صحبت + کردن — synonym of حرف زدن" },
    { id: "33.v.saz", type: "vocabulary", fa: "ساز", pin: "sāz", en: "musical instrument", notes: "س-ا-ز",
      examples: [
        { fa: "ساز مورد علاقه‌ی تو چیه؟", pin: "sāz-e mored-e alāghe-ye to chi-e?", en: "What's your favourite instrument?", source: "phrase:33" },
        { fa: "ساز مورد علاقه‌ی من ویولن هست", pin: "sāz-e mored-e alāghe-ye man violon hast", en: "My favourite instrument is the violin", source: "phrase:33" },
      ] },
    { id: "33.v.saz-zadan", type: "vocabulary", fa: "ساز زدن", pin: "sāz zadan", en: "to play an instrument", notes: "ساز + زدن" },
    { id: "33.v.piano-zadan", type: "vocabulary", fa: "پیانو زدن", pin: "piāno zadan", en: "to play the piano", notes: "پیانو + زدن",
      examples: [
        { fa: "من یه کم پیانو می‌زنم", pin: "man ye kam piāno mizanam", en: "I play a little piano", source: "phrase:33" },
        { fa: "بعد از شام، مامانم پیانو زد و من براش دست زدم.", pin: "Ba'd az shām, māmānam piāno zad va man barāsh dast zadam.", en: "After dinner, my mom played the piano and I clapped for her.", source: "story:st-33-1" },
        { fa: "مامانم گفت: «ببخشید! سرم خیلی شلوغ بود. من الان هر روز پیانو می‌زنم!»", pin: "Māmānam goft: \"Bebakhshid! Saram kheili sholugh bood. Man alān har rooz piāno mizanam!\"", en: "My mom said: \"Sorry! I've been really busy. I play the piano every day now!\"", source: "story:st-33-1" },
        { fa: "مامانم گفت: «آره! فردا بیا خونه، برات پیانو می‌زنم.»", pin: "Māmānam goft: \"Āreh! Fardā biā khooneh, barāt piāno mizanam.\"", en: "My mom said: \"Yes! Come over tomorrow, I'll play the piano for you.\"", source: "story:st-33-1" },
      ] },
    { id: "33.v.kotak-zadan", type: "vocabulary", fa: "کتک زدن", pin: "kotak zadan", en: "to beat, to hit (a person)", notes: "کتک + زدن",
      examples: [
        { fa: "اون بچه‌ش رو کتک می‌زنه", pin: "oon bache-sh ro kotak mizaneh", en: "He/she hits their child", source: "phrase:33" },
      ] },
    { id: "33.v.cheshmak", type: "vocabulary", fa: "چشمک", pin: "cheshmak", en: "a wink", notes: "چشم + ک (diminutive)",
      examples: [
        { fa: "من به تو چشمک می‌زنم", pin: "man be to cheshmak mizanam", en: "I wink at you", source: "phrase:33" },
        { fa: "علی به مامانش چشمک می‌زنه و می‌گه: «بعد از مدرسه بهت زنگ می‌زنم!»", pin: "Ali be māmānesh cheshmak mizaneh va migeh: \"Ba'd az madreseh behet zang mizanam!\"", en: "Ali winks at his mom and says: \"I'll call you after school!\"", source: "story:st-33-2" },
      ] },
    { id: "33.v.cheshmak-zadan", type: "vocabulary", fa: "چشمک زدن", pin: "cheshmak zadan", en: "to wink", notes: "چشمک + زدن",
      examples: [
        { fa: "من به تو چشمک می‌زنم", pin: "man be to cheshmak mizanam", en: "I wink at you", source: "phrase:33" },
        { fa: "علی به مامانش چشمک می‌زنه و می‌گه: «بعد از مدرسه بهت زنگ می‌زنم!»", pin: "Ali be māmānesh cheshmak mizaneh va migeh: \"Ba'd az madreseh behet zang mizanam!\"", en: "Ali winks at his mom and says: \"I'll call you after school!\"", source: "story:st-33-2" },
      ] },
    { id: "33.v.khamir-e-dandoon", type: "vocabulary", fa: "خمیر دندون", pin: "khamir-e dandoon", en: "toothpaste", notes: "خمیر (paste) + دندون" },
    { id: "33.v.khalal-e-dandoon", type: "vocabulary", fa: "خلال دندون", pin: "khalāl-e dandoon", en: "toothpick", notes: "خلال + دندون" },
    { id: "33.v.mesvak-zadan", type: "vocabulary", fa: "مسواک زدن", pin: "mesvāk zadan", en: "to brush one's teeth", notes: "also مسواک کردن",
      examples: [
        { fa: "دندون‌ها رو مسواک بزن", pin: "dandoon-hā ro mesvāk bezan", en: "Brush your teeth", source: "phrase:33" },
        { fa: "قبل از صبحونه، بچه‌ها دندون‌هاشون رو مسواک می‌زنن.", pin: "Ghabl az sobhooneh, bacheh hā dandoon hāshoon ro mesvāk mizanan.", en: "Before breakfast, the children brush their teeth.", source: "story:st-33-2" },
      ] },
    { id: "33.v.moo", type: "vocabulary", fa: "مو", pin: "moo", en: "hair", notes: "م-و",
      examples: [
        { fa: "موها رو شونه بزن", pin: "moo-hā ro shooneh bezan", en: "Comb your hair", source: "phrase:33" },
        { fa: "سارا موهاش رو شونه می‌زنه.", pin: "Sārā moo hāsh ro shooneh mizaneh.", en: "Sara combs her hair.", source: "story:st-33-2" },
      ] },
    { id: "33.v.shooneh", type: "vocabulary", fa: "شونه", pin: "shooneh", en: "comb; shoulder", notes: "شانه زدن = to comb — same word as shoulder (session 32)",
      examples: [
        { fa: "موها رو شونه بزن", pin: "moo-hā ro shooneh bezan", en: "Comb your hair", source: "phrase:33" },
        { fa: "شونه‌ام درد می‌کنه", pin: "shoone-am dard mikoneh", en: "My shoulder hurts", source: "phrase:32" },
        { fa: "سارا موهاش رو شونه می‌زنه.", pin: "Sārā moo hāsh ro shooneh mizaneh.", en: "Sara combs her hair.", source: "story:st-33-2" },
      ] },
    { id: "33.v.shooneh-zadan", type: "vocabulary", fa: "شونه زدن", pin: "shooneh zadan", en: "to comb (hair)", notes: "شونه + زدن — also شونه کردن",
      examples: [
        { fa: "موها رو شونه بزن", pin: "moo-hā ro shooneh bezan", en: "Comb your hair", source: "phrase:33" },
        { fa: "سارا موهاش رو شونه می‌زنه.", pin: "Sārā moo hāsh ro shooneh mizaneh.", en: "Sara combs her hair.", source: "story:st-33-2" },
      ] },
    { id: "33.v.rang-zadan", type: "vocabulary", fa: "رنگ زدن", pin: "rang zadan", en: "to paint", notes: "رنگ + زدن — also رنگ کردن",
      examples: [
        { fa: "اتاق رو رنگ بزن", pin: "otāgh ro rang bezan", en: "Paint the room", source: "phrase:33" },
      ] },
    { id: "33.v.gap-zadan", type: "vocabulary", fa: "گپ زدن", pin: "gap zadan", en: "to chat", notes: "گپ + زدن",
      examples: [
        { fa: "قبل از شام، ما با همدیگه گپ زدیم.", pin: "Ghabl az shām, mā bā hamdige gap zadim.", en: "Before dinner, we chatted.", source: "story:st-33-1" },
      ] },
    { id: "33.v.seda-zadan", type: "vocabulary", fa: "صدا زدن", pin: "sedā zadan", en: "to call someone (by name or voice)", notes: "صدا + زدن — also صدا کردن",
      examples: [
        { fa: "ساعت هفت صبح، مامان بچه‌ها رو صدا می‌زنه: «بچه‌ها، بیدار بشید!»", pin: "Sāat-e haft-e sobh, māmān bacheh hā ro sedā mizaneh: \"Bacheh hā, bidār beshid!\"", en: "At seven in the morning, Mom calls the children: \"Kids, wake up!\"", source: "story:st-33-2" },
      ] },
    { id: "33.v.soot-zadan", type: "vocabulary", fa: "سوت زدن", pin: "soot zadan", en: "to whistle", notes: "سوت + زدن",
      examples: [
        { fa: "علی سوت می‌زنه و آواز می‌خونه.", pin: "Ali soot mizaneh va āvāz mikhooneh.", en: "Ali whistles and sings.", source: "story:st-33-2" },
      ] },
    // Grammar
    { id: "33.g.mizanam", type: "grammar", fa: "می‌زنم", pin: "mizanam", en: "I hit / I strike", notes: "می + زن + م — present of زدن" },
    { id: "33.g.mizani", type: "grammar", fa: "می‌زنی", pin: "mizani", en: "you hit", notes: "می + زن + ی" },
    { id: "33.g.mizaneh", type: "grammar", fa: "می‌زنه", pin: "mizaneh", en: "he/she hits", notes: "می + زن + ه" },
    { id: "33.g.mizanim", type: "grammar", fa: "می‌زنیم", pin: "mizanim", en: "we hit", notes: "می + زن + یم" },
    { id: "33.g.mizanid", type: "grammar", fa: "می‌زنید", pin: "mizanid", en: "you (pl) hit", notes: "می + زن + ید" },
    { id: "33.g.mizanan", type: "grammar", fa: "می‌زنن", pin: "mizanan", en: "they hit", notes: "می + زن + ن" },
    { id: "33.g.nemizanam", type: "grammar", fa: "نمی‌زنم", pin: "nemizanam", en: "I don't hit / I won't hit", notes: "نمی + زن + م" },
    { id: "33.g.zadam", type: "grammar", fa: "زدم", pin: "zadam", en: "I hit (past)", notes: "زد + م — past stem of زدن" },
    { id: "33.g.zadi", type: "grammar", fa: "زدی", pin: "zadi", en: "you hit (past)", notes: "زد + ی" },
    { id: "33.g.zad", type: "grammar", fa: "زد", pin: "zad", en: "he/she hit (past)", notes: "bare past stem — no ending" },
    { id: "33.g.zadim", type: "grammar", fa: "زدیم", pin: "zadim", en: "we hit (past)", notes: "زد + یم" },
    { id: "33.g.zadid", type: "grammar", fa: "زدید", pin: "zadid", en: "you (pl) hit (past)", notes: "زد + ید" },
    { id: "33.g.zadan", type: "grammar", fa: "زدن", pin: "zadan", en: "they hit (past)", notes: "زد + ن — same spelling as the infinitive" },
    { id: "33.g.bezan", type: "grammar", fa: "بزن", pin: "bezan", en: "hit! / do it! (imperative of زدن)", notes: "ب + زن" },
    { id: "33.g.nazan", type: "grammar", fa: "نزن", pin: "nazan", en: "don't hit!", notes: "ن + زن" },
    { id: "33.g.hameh-ye-noun", type: "grammar", fa: "همه‌ی + noun", pin: "hameh-ye + noun", en: "all the... / every...", notes: "همه + ezāfe + noun: همه‌ی پول = all the money" },
    { id: "33.g.time-pish", type: "grammar", fa: "[time] + پیش", pin: "[time] + pish", en: "[time] ago", notes: "یک ساعت پیش، دو روز پیش، هفته‌ی پیش" },
    // Phrases
    { id: "33.p.cheshm", type: "phrases", fa: "چشم!", pin: "cheshm!", en: "Yes, gladly! / As you wish!", notes: "polite, warm yes — 'it's on my eyes'" },
    { id: "33.p.yek-saat-e-pish", type: "phrases", fa: "یک ساعت پیش", pin: "yek sāat-e pish", en: "one hour ago", notes: "ساعت + پیش" },
    { id: "33.p.hafte-ye-pish", type: "phrases", fa: "هفته‌ی پیش", pin: "hafte-ye pish", en: "last week", notes: "also هفته‌ی گذشته" },
    { id: "33.p.sal-e-pish", type: "phrases", fa: "سال پیش", pin: "sāl-e pish", en: "last year", notes: "سال + پیش" },
    { id: "33.p.do-rooz-e-pish", type: "phrases", fa: "دو روز پیش", pin: "do rooz-e pish", en: "two days ago", notes: "دو روز + پیش" },
    { id: "33.p.baad-az-sham", type: "phrases", fa: "بعد از شام", pin: "baad az shām", en: "after dinner", notes: "بعد از / پس از" },
    { id: "33.p.ghabl-az-nahar", type: "phrases", fa: "قبل از ناهار", pin: "ghabl az nāhār", en: "before lunch", notes: "قبل از / پیش از" },
    { id: "33.p.hameh-ye-pool", type: "phrases", fa: "همه‌ی پول", pin: "hameh-ye pool", en: "all the money", notes: "همه + ی + پول" },
    { id: "33.p.hameh-ye-mardom", type: "phrases", fa: "همه‌ی مردم", pin: "hameh-ye mardom", en: "all the people", notes: "also همه‌ی آدم‌ها" },
    { id: "33.p.man-hameh-ye-sandevich-am-ro", type: "phrases", fa: "من همه‌ی ساندویچم رو می‌خورم", pin: "man hameh-ye sāndevich-am ro mikhoram", en: "I eat all of my sandwich", notes: "همه‌ی + ساندویچم رو" },
    { id: "33.p.hameh-ye-daneshjoo-ha-inja", type: "phrases", fa: "همه‌ی دانشجوها اینجا هستن", pin: "hameh-ye dāneshjoo-hā injā hastan", en: "All the students are here", notes: "همه‌ی + دانشجوها" },
    { id: "33.p.hameh-ye-khanevadeh-inja-boodan", type: "phrases", fa: "همه‌ی خانواده اینجا بودن", pin: "hameh-ye khānevādeh injā boodan", en: "The whole family was here", notes: "بودن (they were)" },
    { id: "33.p.hameh-midoonan", type: "phrases", fa: "همه می‌دونن", pin: "hameh midoonan", en: "Everyone knows", notes: "همه standing alone = everyone" },
    { id: "33.p.be-hameh-salam-beresoon", type: "phrases", fa: "به همه سلام برسون", pin: "be hameh salām beresoon", en: "Say hello to everyone!", notes: "به همه (to everyone)" },
    { id: "33.p.hameh-chiz-khoob-e", type: "phrases", fa: "همه‌چیز خوبه", pin: "hameh-chiz khoob-e", en: "Everything is good", notes: "همه‌چیز + ه" },
    { id: "33.p.hameh-chiz-khoob-bood", type: "phrases", fa: "همه‌چیز خوب بود", pin: "hameh-chiz khoob bood", en: "Everything was good", notes: "بود (was)" },
    { id: "33.p.hameh-chiz-ali-bood-kheili", type: "phrases", fa: "همه‌چیز عالی بود، خیلی ممنون!", pin: "hameh-chiz āli bood, kheili mamnoon!", en: "Everything was great! Thank you!", notes: "عالی (excellent)" },
    { id: "33.p.man-toop-ro-mizanam", type: "phrases", fa: "من توپ رو می‌زنم", pin: "man toop ro mizanam", en: "I'll hit the ball", notes: "توپ رو + می‌زنم" },
    { id: "33.p.man-toop-ro-zadam", type: "phrases", fa: "من توپ رو زدم", pin: "man toop ro zadam", en: "I hit the ball", notes: "زدم (past)" },
    { id: "33.p.man-be-kampiooteret-dast", type: "phrases", fa: "من به کامپیوترت دست نمی‌زنم", pin: "man be kāmpiooteret dast nemizanam", en: "I'm not touching your computer", notes: "دست زدن به = to touch" },
    { id: "33.p.man-be-ghazat-dast-nemizanam", type: "phrases", fa: "من به غذا‌ت دست نمی‌زنم", pin: "man be ghazāt dast nemizanam", en: "I won't touch your food", notes: "غذات (your food)" },
    { id: "33.p.ma-darim-barat-dast-mizanim", type: "phrases", fa: "ما داریم برات دست می‌زنیم", pin: "mā dārim barāt dast mizanim", en: "We're clapping for you", notes: "دست زدن برای = to applaud" },
    { id: "33.p.ma-darim-baraye-to-dast-mizanim", type: "phrases", fa: "ما داریم برای تو دست می‌زنیم", pin: "mā dārim barāye to dast mizanim", en: "We're applauding you", notes: "برای تو = برات" },
    { id: "33.p.dar-e-khoone-ro-bezan", type: "phrases", fa: "در خونه رو بزن", pin: "dar-e khoone ro bezan", en: "Knock on the door", notes: "در زدن" },
    { id: "33.p.zang-e-dar-ro-bezan", type: "phrases", fa: "زنگ در رو بزن", pin: "zang-e dar ro bezan", en: "Ring the doorbell", notes: "زنگ در + زدن" },
    { id: "33.p.emrooz-be-mamanam-zang-mizanam", type: "phrases", fa: "امروز به مامانم زنگ می‌زنم", pin: "emrooz be māmānam zang mizanam", en: "I'll call my mum today", notes: "زنگ زدن به = to call" },
    { id: "33.p.mamanam-har-hafteh-be-man-zang", type: "phrases", fa: "مامانم هر هفته به من زنگ نمی‌زنه", pin: "māmānam har hafteh be man zang nemizaneh", en: "My mum doesn't call me every week", notes: "زنگ نمی‌زنه" },
    { id: "33.p.man-be-to-telefon-mizanam", type: "phrases", fa: "من به تو تلفن می‌زنم", pin: "man be to telefon mizanam", en: "I'll call you", notes: "تلفن زدن به" },
    { id: "33.p.telefon-zang-mizaneh", type: "phrases", fa: "تلفن زنگ می‌زنه", pin: "telefon zang mizaneh", en: "The phone is ringing", notes: "زنگ می‌زنه = is ringing" },
    { id: "33.p.mobailet-zang-mizaneh", type: "phrases", fa: "موبایلت زنگ می‌زنه", pin: "mobāilet zang mizaneh", en: "Your mobile is ringing", notes: "موبایل + ت" },
    { id: "33.p.ma-farda-harf-mizanim", type: "phrases", fa: "ما فردا حرف می‌زنیم", pin: "mā fardā harf mizanim", en: "We'll talk tomorrow", notes: "حرف زدن" },
    { id: "33.p.oon-ba-man-harf-nemizaneh", type: "phrases", fa: "اون با من حرف نمی‌زنه", pin: "oon bā man harf nemizaneh", en: "She doesn't talk to me", notes: "حرف زدن با = to talk with" },
    { id: "33.p.man-ye-kam-piano-mizanam", type: "phrases", fa: "من یه کم پیانو می‌زنم", pin: "man ye kam piāno mizanam", en: "I play a little piano", notes: "ساز زدن = to play an instrument" },
    { id: "33.p.shoharam-ye-kam-gitar-mizaneh", type: "phrases", fa: "شوهرم یه کم گیتار می‌زنه", pin: "shoharam ye kam gitār mizaneh", en: "My husband plays a little guitar", notes: "گیتار + می‌زنه" },
    { id: "33.p.saz-e-mored-e-alaghe-ye-to-chi-e", type: "phrases", fa: "ساز مورد علاقه‌ی تو چیه؟", pin: "sāz-e mored-e alāghe-ye to chi-e?", en: "What's your favourite instrument?", notes: "مورد علاقه = favourite" },
    { id: "33.p.saz-e-mored-e-alaghe-ye-man", type: "phrases", fa: "ساز مورد علاقه‌ی من ویولن هست", pin: "sāz-e mored-e alāghe-ye man violon hast", en: "My favourite instrument is the violin", notes: "ویولن" },
    { id: "33.p.oon-bache-sh-ro-kotak-mizaneh", type: "phrases", fa: "اون بچه‌ش رو کتک می‌زنه", pin: "oon bache-sh ro kotak mizaneh", en: "He/she hits their child", notes: "کتک زدن — a harsh verb" },
    { id: "33.p.man-be-to-cheshmak-mizanam", type: "phrases", fa: "من به تو چشمک می‌زنم", pin: "man be to cheshmak mizanam", en: "I wink at you", notes: "چشمک زدن به" },
    { id: "33.p.dandoon-ha-ro-mesvak-bezan", type: "phrases", fa: "دندون‌ها رو مسواک بزن", pin: "dandoon-hā ro mesvāk bezan", en: "Brush your teeth", notes: "مسواک زدن / مسواک کردن" },
    { id: "33.p.moo-ha-ro-shooneh-bezan", type: "phrases", fa: "موها رو شونه بزن", pin: "moo-hā ro shooneh bezan", en: "Comb your hair", notes: "شونه زدن / شونه کردن" },
    { id: "33.p.otagh-ro-rang-bezan", type: "phrases", fa: "اتاق رو رنگ بزن", pin: "otāgh ro rang bezan", en: "Paint the room", notes: "رنگ زدن / رنگ کردن" },
  ],
});
