// Session 34: comparison.
// Item ids are permanent. Never change or reuse one; add new items with new ids.
F.lesson({
  id: "34",
  label: "Session 34",
  title: "Comparison",
  summary: "comparatives (-tar), superlatives (-tarin), adjective pairs, the یادداشت passage",
  notes: "ALEX-SESSION-34_formatted.md",
  items: [
    // Vocabulary
    { id: "34.v.nazar", type: "vocabulary", fa: "نظر", pin: "nazar", en: "opinion, view", notes: "ن-ظ-ر — به نظرِ من / از نظرِ من" },
    { id: "34.v.az", type: "vocabulary", fa: "از", pin: "az", en: "than; from", notes: "the same از does both jobs" },
    { id: "34.v.bozorg", type: "vocabulary", fa: "بزرگ", pin: "bozorg", en: "big; old (of a person)", notes: "ب-ز-ر-گ" },
    { id: "34.v.bozorgtar", type: "vocabulary", fa: "بزرگ‌تر", pin: "bozorgtar", en: "bigger; older", notes: "بزرگ + تر" },
    { id: "34.v.bozorgtarin", type: "vocabulary", fa: "بزرگ‌ترین", pin: "bozorgtarin", en: "the biggest", notes: "بزرگ + ترین" },
    { id: "34.v.koochak-koochik", type: "vocabulary", fa: "کوچک", pin: "koochak / koochik", en: "small; young (of a person)", notes: "ک-و-چ-ک" },
    { id: "34.v.koochaktar-koochiktar", type: "vocabulary", fa: "کوچک‌تر", pin: "koochaktar / koochiktar", en: "smaller; younger", notes: "کوچک + تر" },
    { id: "34.v.garm", type: "vocabulary", fa: "گرم", pin: "garm", en: "warm, hot", notes: "گ-ر-م" },
    { id: "34.v.garmtar", type: "vocabulary", fa: "گرم‌تر", pin: "garmtar", en: "warmer", notes: "گرم + تر" },
    { id: "34.v.sard", type: "vocabulary", fa: "سرد", pin: "sard", en: "cold", notes: "س-ر-د" },
    { id: "34.v.sardtar", type: "vocabulary", fa: "سردتر", pin: "sardtar", en: "colder", notes: "سرد + تر" },
    { id: "34.v.jaleb", type: "vocabulary", fa: "جالب", pin: "jāleb", en: "interesting", notes: "ج-ا-ل-ب" },
    { id: "34.v.jalebtar", type: "vocabulary", fa: "جالب‌تر", pin: "jālebtar", en: "more interesting", notes: "جالب + تر" },
    { id: "34.v.peer", type: "vocabulary", fa: "پیر", pin: "peer", en: "old (of a person)", notes: "پ-ی-ر" },
    { id: "34.v.peertar", type: "vocabulary", fa: "پیرتر", pin: "peertar", en: "older", notes: "پیر + تر — also بزرگ‌تر" },
    { id: "34.v.javan-javoon", type: "vocabulary", fa: "جوان", pin: "javān / javoon", en: "young", notes: "ج-و-ا-ن" },
    { id: "34.v.javoontar", type: "vocabulary", fa: "جوون‌تر", pin: "javoontar", en: "younger", notes: "جوون + تر" },
    { id: "34.v.khoshgel", type: "vocabulary", fa: "خوشگل", pin: "khoshgel", en: "pretty, good-looking", notes: "خوش (good) + گل (flower)" },
    { id: "34.v.khoshgeltar", type: "vocabulary", fa: "خوشگل‌تر", pin: "khoshgeltar", en: "prettier", notes: "خوشگل + تر" },
    { id: "34.v.ghadimi", type: "vocabulary", fa: "قدیمی", pin: "ghadimi", en: "old (of an object)", notes: "from قدیم (old times)" },
    { id: "34.v.ghadimitar", type: "vocabulary", fa: "قدیمی‌تر", pin: "ghadimitar", en: "older (of an object)", notes: "قدیمی + تر — not بزرگ‌تر for things" },
    { id: "34.v.khoob", type: "vocabulary", fa: "خوب", pin: "khoob", en: "good", notes: "خ-و-ب" },
    { id: "34.v.behtar", type: "vocabulary", fa: "بهتر", pin: "behtar", en: "better", notes: "irregular — not خوب‌تر" },
    { id: "34.v.behtarin", type: "vocabulary", fa: "بهترین", pin: "behtarin", en: "the best", notes: "irregular superlative of خوب" },
    { id: "34.v.bad", type: "vocabulary", fa: "بد", pin: "bad", en: "bad", notes: "ب-د" },
    { id: "34.v.badtar", type: "vocabulary", fa: "بدتر", pin: "badtar", en: "worse", notes: "بد + تر" },
    { id: "34.v.badtarin", type: "vocabulary", fa: "بدترین", pin: "badtarin", en: "the worst", notes: "بد + ترین" },
    { id: "34.v.ghashang", type: "vocabulary", fa: "قشنگ", pin: "ghashang", en: "beautiful, lovely", notes: "ق-ش-ن-گ" },
    { id: "34.v.ghashangtarin", type: "vocabulary", fa: "قشنگ‌ترین", pin: "ghashangtarin", en: "the most beautiful", notes: "قشنگ + ترین" },
    { id: "34.v.khoshmazze", type: "vocabulary", fa: "خوشمزه", pin: "khoshmazze", en: "tasty, delicious", notes: "خوش (good) + مزه (taste)" },
    { id: "34.v.khoshmazzetarin", type: "vocabulary", fa: "خوشمزه‌ترین", pin: "khoshmazzetarin", en: "the tastiest", notes: "خوشمزه + ترین" },
    { id: "34.v.fesenjoon", type: "vocabulary", fa: "فسنجون", pin: "fesenjoon", en: "fesenjoon (walnut & pomegranate stew)", notes: "a classic Iranian dish" },
    { id: "34.v.donya", type: "vocabulary", fa: "دنیا", pin: "donyā", en: "world; worldly life", notes: "everyday, material, emotional world" },
    { id: "34.v.jahan", type: "vocabulary", fa: "جهان", pin: "jahān", en: "world, universe", notes: "the whole of existence — scientific or poetic" },
    { id: "34.v.shahr", type: "vocabulary", fa: "شهر", pin: "shahr", en: "city", notes: "ش-ه-ر" },
    { id: "34.v.fil", type: "vocabulary", fa: "فیل", pin: "fil", en: "elephant", notes: "ف-ی-ل" },
    { id: "34.v.tuti", type: "vocabulary", fa: "طوطی", pin: "tuti", en: "parrot", notes: "ط-و-ط-ی" },
    { id: "34.v.sag", type: "vocabulary", fa: "سگ", pin: "sag", en: "dog", notes: "س-گ" },
    { id: "34.v.asb", type: "vocabulary", fa: "اسب", pin: "asb", en: "horse", notes: "ا-س-ب" },
    { id: "34.v.docharkheh", type: "vocabulary", fa: "دوچرخه", pin: "docharkheh", en: "bicycle", notes: "دو (two) + چرخ (wheel)" },
    { id: "34.v.shohar", type: "vocabulary", fa: "شوهر", pin: "shohar", en: "husband", notes: "ش-و-ه-ر — شوهرم = my husband" },
    { id: "34.v.khahar", type: "vocabulary", fa: "خواهر", pin: "khāhar", en: "sister", notes: "خ-و-ا-ه-ر — خواهرم = my sister" },
    { id: "34.v.emsal", type: "vocabulary", fa: "امسال", pin: "emsāl", en: "this year", notes: "این + سال" },
    { id: "34.v.parsal", type: "vocabulary", fa: "پارسال", pin: "pārsāl", en: "last year", notes: "پار + سال — also سالِ پیش" },
    { id: "34.v.emshab", type: "vocabulary", fa: "امشب", pin: "emshab", en: "tonight", notes: "این + شب" },
    { id: "34.v.dishab", type: "vocabulary", fa: "دیشب", pin: "dishab", en: "last night", notes: "دی + شب" },
    { id: "34.v.laghar", type: "vocabulary", fa: "لاغر", pin: "lāghar", en: "slim, thin", notes: "ل-ا-غ-ر" },
    { id: "34.v.chagh", type: "vocabulary", fa: "چاق", pin: "chāgh", en: "fat", notes: "چ-ا-ق" },
    { id: "34.v.kutah", type: "vocabulary", fa: "کوتاه", pin: "kutāh", en: "short; brief", notes: "opposite بلند (height) or طولانی (time)" },
    { id: "34.v.boland", type: "vocabulary", fa: "بلند", pin: "boland", en: "tall; long", notes: "ب-ل-ن-د" },
    { id: "34.v.sangin", type: "vocabulary", fa: "سنگین", pin: "sangin", en: "heavy", notes: "from سنگ (stone)" },
    { id: "34.v.sabok", type: "vocabulary", fa: "سبک", pin: "sabok", en: "light (in weight)", notes: "س-ب-ک" },
    { id: "34.v.kasif", type: "vocabulary", fa: "کثیف", pin: "kasif", en: "dirty", notes: "ک-ث-ی-ف" },
    { id: "34.v.tamiz", type: "vocabulary", fa: "تمیز", pin: "tamiz", en: "clean", notes: "ت-م-ی-ز" },
    { id: "34.v.kond", type: "vocabulary", fa: "کند", pin: "kond", en: "slow", notes: "ک-ن-د" },
    { id: "34.v.tond", type: "vocabulary", fa: "تند", pin: "tond", en: "fast; spicy", notes: "ت-ن-د" },
    { id: "34.v.bishtar", type: "vocabulary", fa: "بیشتر", pin: "bishtar", en: "more", notes: "بیش + تر" },
    { id: "34.v.kamtar", type: "vocabulary", fa: "کمتر", pin: "kamtar", en: "less", notes: "کم + تر" },
    { id: "34.v.tulani", type: "vocabulary", fa: "طولانی", pin: "tulāni", en: "long (in time)", notes: "from طول (length)" },
    { id: "34.v.por", type: "vocabulary", fa: "پر", pin: "por", en: "full", notes: "پ-ر" },
    { id: "34.v.khali", type: "vocabulary", fa: "خالی", pin: "khāli", en: "empty", notes: "خ-ا-ل-ی" },
    { id: "34.v.halim", type: "vocabulary", fa: "حلیم", pin: "halim", en: "halim (thick wheat & meat porridge)", notes: "a hearty breakfast dish" },
    { id: "34.v.yad-dasht", type: "vocabulary", fa: "یادداشت", pin: "yād dāsht", en: "note", notes: "یاد (memory) + داشت (had)" },
    { id: "34.v.yad-dasht-kardan", type: "vocabulary", fa: "یادداشت کردن", pin: "yād dāsht kardan", en: "to note down", notes: "یادداشت + کردن" },
    { id: "34.v.dagh", type: "vocabulary", fa: "داغ", pin: "dāgh", en: "extremely hot", notes: "د-ا-غ" },
    { id: "34.v.darchin", type: "vocabulary", fa: "دارچین", pin: "dārchin", en: "cinnamon", notes: "د-ا-ر-چ-ی-ن" },
    { id: "34.v.saket", type: "vocabulary", fa: "ساکت", pin: "sāket", en: "quiet, silent", notes: "س-ا-ک-ت" },
    { id: "34.v.hanooz", type: "vocabulary", fa: "هنوز", pin: "hanooz", en: "yet, still", notes: "ه-ن-و-ز" },
    { id: "34.v.kam-kam", type: "vocabulary", fa: "کم کم", pin: "kam kam", en: "gradually, little by little", notes: "کم (little) doubled" },
    { id: "34.v.amadeh", type: "vocabulary", fa: "آماده", pin: "āmādeh", en: "ready", notes: "آ-م-ا-د-ه" },
    { id: "34.v.amadeh-shodan", type: "vocabulary", fa: "آماده شدن", pin: "āmādeh shodan", en: "to get ready", notes: "آماده + شدن" },
    { id: "34.v.raghs", type: "vocabulary", fa: "رقص", pin: "raghs", en: "dance", notes: "ر-ق-ص" },
    { id: "34.v.raghsidan", type: "vocabulary", fa: "رقصیدن", pin: "raghsidan", en: "to dance", notes: "present stem: رقص" },
    { id: "34.v.kelas-e-raghs", type: "vocabulary", fa: "کلاس رقص", pin: "kelās-e raghs", en: "dance class", notes: "کلاس + ezāfe + رقص" },
    { id: "34.v.pichidan", type: "vocabulary", fa: "پیچیدن", pin: "pichidan", en: "to spread, to wind, to echo", notes: "present stem: پیچ" },
    { id: "34.v.jome", type: "vocabulary", fa: "جمعه", pin: "jom'e", en: "Friday", notes: "ج-م-ع-ه" },
    { id: "34.v.hava", type: "vocabulary", fa: "هوا", pin: "havā", en: "weather, air", notes: "ه-و-ا" },
    { id: "34.v.sobh-e-zood", type: "vocabulary", fa: "صبح زود", pin: "sobh-e zood", en: "early morning", notes: "صبح + زود (early)" },
    { id: "34.v.sobhaneh", type: "vocabulary", fa: "صبحانه", pin: "sobhāneh", en: "breakfast", notes: "from صبح (morning)" },
    { id: "34.v.nan-noon", type: "vocabulary", fa: "نان", pin: "nān / noon", en: "bread", notes: "نان written, نون spoken" },
    { id: "34.v.khab", type: "vocabulary", fa: "خواب", pin: "khāb", en: "asleep; sleep", notes: "خ-و-ا-ب" },
    { id: "34.v.khoshhal", type: "vocabulary", fa: "خوشحال", pin: "khoshhāl", en: "happy", notes: "خوش (good) + حال (state)" },
    { id: "34.v.chun", type: "vocabulary", fa: "چون", pin: "chun", en: "because", notes: "چ-و-ن" },
    { id: "34.v.hafteh", type: "vocabulary", fa: "هفته", pin: "hafteh", en: "week", notes: "ه-ف-ت-ه" },
    { id: "34.v.hamin", type: "vocabulary", fa: "همین", pin: "hamin", en: "that's it, just that", notes: "هم + این" },
    { id: "34.v.amma", type: "vocabulary", fa: "امّا", pin: "ammā", en: "but", notes: "ا-م-ا" },
    { id: "34.v.boo", type: "vocabulary", fa: "بو", pin: "boo", en: "smell, scent", notes: "ب-و" },
    { id: "34.v.seda", type: "vocabulary", fa: "صدا", pin: "sedā", en: "sound, voice", notes: "ص-د-ا" },
    // Grammar
    { id: "34.g.tar", type: "grammar", fa: "ـتر", pin: "-tar", en: "comparative suffix (more ...)", notes: "adjective + تر: بزرگ → بزرگ‌تر" },
    { id: "34.g.tarin", type: "grammar", fa: "ـترین", pin: "-tarin", en: "superlative suffix (the most ...)", notes: "adjective + ترین: بزرگ → بزرگ‌ترین" },
    { id: "34.g.az-tar", type: "grammar", fa: "از … ـتر", pin: "az ... -tar", en: "...er than ...", notes: "[A] از [B] [adj]تر — تهران از شیراز بزرگ‌تر هست" },
    { id: "34.g.khoob-behtar-behtarin", type: "grammar", fa: "خوب ← بهتر ← بهترین", pin: "khoob → behtar → behtarin", en: "good → better → the best", notes: "irregular: never خوب‌تر" },
    { id: "34.g.bad-badtar-badtarin", type: "grammar", fa: "بد ← بدتر ← بدترین", pin: "bad → badtar → badtarin", en: "bad → worse → the worst", notes: "regular endings, worth drilling as a set" },
    { id: "34.g.bozorgtarin-shahr-e-iran", type: "grammar", fa: "بزرگ‌ترین شهرِ ایران", pin: "bozorgtarin shahr-e Iran", en: "the biggest city in Iran", notes: "superlative + noun + ezāfe + group" },
    { id: "34.g.hast", type: "grammar", fa: "هست", pin: "hast", en: "is", notes: "singular — تهران ... بزرگ‌تر هست" },
    { id: "34.g.hastand", type: "grammar", fa: "هستند", pin: "hastand", en: "they are", notes: "plural — فیل‌ها ... بزرگ‌تر هستند" },
    { id: "34.g.bozorgtar", type: "grammar", fa: "بزرگ‌تر = older", pin: "bozorgtar", en: "older (of a person)", notes: "Persian says 'bigger' for older" },
    { id: "34.g.koochiktar", type: "grammar", fa: "کوچیک‌تر = younger", pin: "koochiktar", en: "younger (of a person)", notes: "Persian says 'smaller' for younger" },
    { id: "34.g.ghadimitar", type: "grammar", fa: "قدیمی‌تر = older (thing)", pin: "ghadimitar", en: "older (of an object)", notes: "use قدیمی‌تر for objects, not بزرگ‌تر" },
    { id: "34.g.ast", type: "grammar", fa: "است", pin: "ast", en: "is (formal, written)", notes: "the written form of the spoken ـه" },
    { id: "34.g.mishavam", type: "grammar", fa: "می‌شَوَم", pin: "mishavam", en: "I become (formal, written)", notes: "spoken: میشم" },
    { id: "34.g.mipichad", type: "grammar", fa: "می‌پیچَد", pin: "mipichad", en: "it spreads (formal, written)", notes: "spoken: می‌پیچه" },
    { id: "34.g.miraghsam", type: "grammar", fa: "می‌رقصم", pin: "miraghsam", en: "I dance", notes: "می + رقص + م" },
    { id: "34.g.baraye-raftan", type: "grammar", fa: "برای رفتن", pin: "barāye raftan", en: "for leaving, to go", notes: "برای + infinitive used as a noun" },
    // Phrases
    { id: "34.p.be-nazar-e-man", type: "phrases", fa: "به نظر من…", pin: "Be nazar-e man…", en: "In my opinion…", notes: "به + نظر + ezāfe + من" },
    { id: "34.p.az-nazar-e-man", type: "phrases", fa: "از نظر من…", pin: "Az nazar-e man…", en: "In my opinion… / From my point of view…", notes: "از + نظر + ezāfe + من" },
    { id: "34.p.emrooz-az-dirooz-garmtar-eh", type: "phrases", fa: "امروز از دیروز گرم‌تره.", pin: "Emrooz az dirooz garmtar-eh.", en: "Today is warmer than yesterday.", notes: "از = than" },
    { id: "34.p.emshab-az-dishab-garmtar-eh", type: "phrases", fa: "امشب از دیشب گرم‌تره.", pin: "Emshab az dishab garmtar-eh.", en: "Tonight is warmer than last night.", notes: "امشب / دیشب" },
    { id: "34.p.emsal-az-parsal-sardtar-eh", type: "phrases", fa: "امسال از پارسال سردتره.", pin: "Emsāl az pārsāl sardtar-eh.", en: "This year is colder than last year.", notes: "also از سالِ پیش" },
    { id: "34.p.tehran-az-shiraz-bozorgtar-hast", type: "phrases", fa: "تهران از شیراز بزرگ‌تر هست.", pin: "Tehran az Shirāz bozorgtar hast.", en: "Tehran is bigger than Shiraz.", notes: "[A] از [B] بزرگ‌تر" },
    { id: "34.p.shiraz-az-tehran-koochiktar-hast", type: "phrases", fa: "شیراز از تهران کوچیک‌تر هست.", pin: "Shirāz az Tehran koochiktar hast.", en: "Shiraz is smaller than Tehran.", notes: "the same frame reversed" },
    { id: "34.p.fil-ha-az-tuti-ha-bozorgtar", type: "phrases", fa: "فیل‌ها از طوطی‌ها بزرگ‌تر هستند.", pin: "Fil hā az tuti hā bozorgtar hastand.", en: "Elephants are bigger than parrots.", notes: "plural subject → هستند" },
    { id: "34.p.sag-az-asb-koochiktar-hast", type: "phrases", fa: "سگ از اسب کوچیک‌تر هست.", pin: "Sag az asb koochiktar hast.", en: "A dog is smaller than a horse.", notes: "singular → هست" },
    { id: "34.p.sag-ha-az-asb-ha-koochiktar", type: "phrases", fa: "سگ‌ها از اسب‌ها کوچیک‌تر هستند.", pin: "Sag hā az asb hā koochiktar hastand.", en: "Dogs are smaller than horses.", notes: "plural → هستند" },
    { id: "34.p.man-az-oon-koochiktar-hastam", type: "phrases", fa: "من از اون کوچیک‌تر هستم.", pin: "Man az oon koochiktar hastam.", en: "I am younger than her.", notes: "کوچیک‌تر = younger" },
    { id: "34.p.oon-az-man-bozorgtar-hast", type: "phrases", fa: "اون از من بزرگ‌تر هست.", pin: "Oon az man bozorgtar hast.", en: "He is older than me.", notes: "بزرگ‌تر = older" },
    { id: "34.p.shoharam-az-man-bozorgtar-hast", type: "phrases", fa: "شوهرم از من بزرگ‌تر هست.", pin: "Shoharam az man bozorgtar hast.", en: "My husband is older than me.", notes: "شوهر + م" },
    { id: "34.p.to-az-man-javoontar-koochiktar", type: "phrases", fa: "تو از من جوون‌تر، کوچیک‌تر هستی.", pin: "To az man javoontar, koochiktar hasti.", en: "You are younger, smaller than me.", notes: "two comparatives in one sentence" },
    { id: "34.p.docharkhe-ye-man-az-docharkhe-ye", type: "phrases", fa: "دوچرخه‌ی من از دوچرخه‌ی تو قدیمی‌تره.", pin: "Docharkhe-ye man az docharkhe-ye to ghadimitar-eh.", en: "My bicycle is older than yours.", notes: "قدیمی‌تر for objects" },
    { id: "34.p.ye-kam-behtaram", type: "phrases", fa: "یه کم بهترم!", pin: "Ye kam behtaram!", en: "I feel a bit better!", notes: "بهتر + م" },
    { id: "34.p.kheili-behtaram", type: "phrases", fa: "خیلی بهترم!", pin: "Kheili behtaram!", en: "I feel much better!", notes: "خیلی + بهترم" },
    { id: "34.p.to-az-man-bozorgtar-hasti", type: "phrases", fa: "تو از من بزرگ‌تر هستی.", pin: "To az man bozorgtar hasti.", en: "You are older than me.", notes: "هستی (you are)" },
    { id: "34.p.man-az-to-bozorgtar-hastam", type: "phrases", fa: "من از تو بزرگ‌تر هستم.", pin: "Man az to bozorgtar hastam.", en: "I am older than you.", notes: "هستم (I am)" },
    { id: "34.p.khaharam-az-man-javoontar-hast", type: "phrases", fa: "خواهرم از من جوون‌تر هست.", pin: "Khāharam az man javoontar hast.", en: "My sister is younger than me.", notes: "خواهر + م" },
    { id: "34.p.in-kafsh-khoshgeltar-eh", type: "phrases", fa: "این کفش خوشگل‌تره.", pin: "In kafsh khoshgeltar-eh.", en: "This shoe is prettier.", notes: "خوشگل + تر + ه" },
    { id: "34.p.in-behtar-eh", type: "phrases", fa: "این بهتره!", pin: "In behtar-eh!", en: "This one is better!", notes: "بهتر + ه" },
    { id: "34.p.tehran-bozorgtarin-shahr-e-iran", type: "phrases", fa: "تهران بزرگ‌ترین شهر ایران هست.", pin: "Tehran bozorgtarin shahr-e Iran hast.", en: "Tehran is the biggest city in Iran.", notes: "superlative + شهرِ ایران" },
    { id: "34.p.yazd-ghashangtarin-shahr-e-iran", type: "phrases", fa: "یزد قشنگ‌ترین شهر ایران هست.", pin: "Yazd ghashangtarin shahr-e Iran hast.", en: "Yazd is the most beautiful city in Iran.", notes: "قشنگ + ترین" },
    { id: "34.p.fesenjoon-khoshmazzetarin-ghaza", type: "phrases", fa: "فسنجون خوشمزه‌ترین غذای ایرانی هست.", pin: "Fesenjoon khoshmazzetarin ghazā-ye Irāni hast.", en: "Fesenjoon is the tastiest Iranian food.", notes: "خوشمزه + ترین + غذایِ ایرانی" },
    { id: "34.p.to-behtarin-maman-e-donya-hasti", type: "phrases", fa: "تو بهترین مامان دنیا هستی.", pin: "To behtarin māmān-e donyā hasti.", en: "You are the best mother in the world.", notes: "دنیا, not جهان — this is emotional" },
    { id: "34.p.sedaye-khandash-tu-saram", type: "phrases", fa: "صدای خنده‌اش تو سرم می‌پیچه.", pin: "Sedāye khandash tu saram mipicheh.", en: "The sound of her laughter echoes in my head.", notes: "the teacher's example of می‌پیچه" },
    // Story
    { id: "34.s.yad-dasht-haye-man", type: "story", fa: "یادداشت‌هایِ من", pin: "Yād dāsht hāye man", en: "My notes", notes: "یادداشت‌ها + ezāfe + من" },
    { id: "34.s.emrooz-jome-ast", type: "story", fa: "امروز جُمعه اَست.", pin: "Emrooz jom'e ast.", en: "Today is Friday.", notes: "است = written 'is'; spoken جمعه‌ست" },
    { id: "34.s.hava-kheili-behtar-az-dirooz-ast", type: "story", fa: "هَوا خیلی بِهتَر از دیروز است.", pin: "Havā kheili behtar az dirooz ast.", en: "The weather is much better than yesterday.", notes: "بهتر از = better than" },
    { id: "34.s.sobh-e-zood-bidar-misham-va", type: "story", fa: "صُبحِ زود بیدار میشم و صُبحانه دُرُست می‌کنم.", pin: "Sobh-e zood bidār misham va sobhāneh dorost mikonam.", en: "I wake up early and make breakfast.", notes: "بیدار شدن + درست کردن" },
    { id: "34.s.halim-nan-e-dagh-va-chay", type: "story", fa: "حَلیم، نانِ داغ و چای.", pin: "Halim, nān-e dāgh va chāy.", en: "Halim, hot bread and tea.", notes: "نانِ داغ = hot bread" },
    { id: "34.s.booye-halim-va-darchin-dar", type: "story", fa: "بویِ حَلیم و دارچین در خانه می‌پیچَد.", pin: "Booye halim va dārchin dar khāneh mipichad.", en: "The smell of halim and cinnamon fills the house.", notes: "بو می‌پیچه = the smell spreads" },
    { id: "34.s.amma-khaneh-saket-ast", type: "story", fa: "امّا خانه ساکِت اَست.", pin: "Ammā khāneh sāket ast.", en: "But the house is quiet.", notes: "امّا = but" },
    { id: "34.s.bachcheh-ha-hanooz-khab-hastand", type: "story", fa: "بَچّه‌ها هَنوز خواب هَستَند.", pin: "Bachcheh hā hanooz khāb hastand.", en: "The children are still asleep.", notes: "هنوز + خواب هستند" },
    { id: "34.s.siavash-ham", type: "story", fa: "سیاوَش هَم.", pin: "Siāvash ham.", en: "Siavash too.", notes: "هم = too, also" },
    { id: "34.s.kam-kam-baraye-raftan-amadeh", type: "story", fa: "کَم کَم برایِ رفتن آماده می‌شَوَم.", pin: "Kam kam barāye raftan āmādeh mishavam.", en: "Little by little I get ready to leave.", notes: "کم کم + برای رفتن + آماده شدن" },
    { id: "34.s.man-kheili-khoshhalam-chun-jome", type: "story", fa: "مَن خیلی خوشحالَم چون جُمعه‌ها کِلاسِ رَقص دارَم.", pin: "Man kheili khoshhālam chun jom'e hā kelās-e raghs dāram.", en: "I am very happy because on Fridays I have a dance class.", notes: "چون = because" },
    { id: "34.s.jome-behtarin-rooz-e-hafteh-ast", type: "story", fa: "جُمعه بِهتَرین روزِ هَفته اَست.", pin: "Jom'e behtarin rooz-e hafteh ast.", en: "Friday is the best day of the week.", notes: "بهترین + روزِ هفته" },
    { id: "34.s.hamin", type: "story", fa: "هَمین.", pin: "Hamin.", en: "That's it.", notes: "هم + این" },
  ],
});
