// Session 34: comparison.
// Item ids are permanent. Never change or reuse one; add new items with new ids.
F.lesson({
  id: "34",
  label: "Session 34",
  title: "Comparison",
  summary: "comparatives (-tar), superlatives (-tarin), adjective pairs, the یادداشت passage",
  notes: "ALEX-SESSION-34_formatted.md",
  items: [
    // Vocabulary
    { id: "34.v.nazar", type: "vocabulary", fa: "نظر", pin: "nazar", en: "opinion, view", notes: "ن-ظ-ر — به نظرِ من / از نظرِ من",
      examples: [
        { fa: "به نظر من…", pin: "Be nazar-e man…", en: "In my opinion…", source: "phrase:34" },
        { fa: "علی می‌گه: «به نظر من، تهران بهترین شهر ایرانه.»", pin: "Ali migeh: \"Be nazar-e man, Tehrān behtarin shahr-e Irān-eh.\"", en: "Ali says: \"In my opinion, Tehran is the best city in Iran.\"", source: "story:st-34-1" },
        { fa: "از نظر من…", pin: "Az nazar-e man…", en: "In my opinion… / From my point of view…", source: "phrase:34" },
      ] },
    { id: "34.v.az", type: "vocabulary", fa: "از", pin: "az", en: "than; from", notes: "the same از does both jobs",
      examples: [
        { fa: "از نظر من…", pin: "Az nazar-e man…", en: "In my opinion… / From my point of view…", source: "phrase:34" },
        { fa: "قبل از شام، ما با همدیگه گپ زدیم.", pin: "Ghabl az shām, mā bā hamdige gap zadim.", en: "Before dinner, we chatted.", source: "story:st-33-1" },
        { fa: "اونها ساعت شیش از خواب بیدار می‌شن.", pin: "oonhā sāat-e shish az khāb bidār mishan.", en: "They wake up at six o'clock.", source: "story:32" },
        { fa: "من از خونه تا دانشگاه دوچرخه‌سواری می‌کنم", pin: "man az khoone tā dāneshgāh docharkheh savāri mikonam", en: "I ride a bicycle from home to university", source: "phrase:31" },
      ] },
    { id: "34.v.bozorg", type: "vocabulary", fa: "بزرگ", pin: "bozorg", en: "big; old (of a person)", notes: "ب-ز-ر-گ",
      examples: [
        { fa: "تهران از شیراز بزرگ‌تر هست.", pin: "Tehran az Shirāz bozorgtar hast.", en: "Tehran is bigger than Shiraz.", source: "phrase:34" },
        { fa: "سارا می‌گه: «نه! تهران از شیراز بزرگ‌تره، ولی شیراز قشنگ‌تره.»", pin: "Sārā migeh: \"Na! Tehrān az Shirāz bozorgtar-eh, vali Shirāz ghashangtar-eh.\"", en: "Sara says: \"No! Tehran is bigger than Shiraz, but Shiraz is prettier.\"", source: "story:st-34-1" },
        { fa: "تهران بزرگ‌ترین شهر ایران هست.", pin: "Tehran bozorgtarin shahr-e Iran hast.", en: "Tehran is the biggest city in Iran.", source: "phrase:34" },
        { fa: "فیل‌ها از طوطی‌ها بزرگ‌تر هستند.", pin: "Fil hā az tuti hā bozorgtar hastand.", en: "Elephants are bigger than parrots.", source: "phrase:34" },
      ] },
    { id: "34.v.bozorgtar", type: "vocabulary", fa: "بزرگ‌تر", pin: "bozorgtar", en: "bigger; older", notes: "بزرگ + تر",
      examples: [
        { fa: "تهران از شیراز بزرگ‌تر هست.", pin: "Tehran az Shirāz bozorgtar hast.", en: "Tehran is bigger than Shiraz.", source: "phrase:34" },
        { fa: "سارا می‌گه: «نه! تهران از شیراز بزرگ‌تره، ولی شیراز قشنگ‌تره.»", pin: "Sārā migeh: \"Na! Tehrān az Shirāz bozorgtar-eh, vali Shirāz ghashangtar-eh.\"", en: "Sara says: \"No! Tehran is bigger than Shiraz, but Shiraz is prettier.\"", source: "story:st-34-1" },
        { fa: "فیل‌ها از طوطی‌ها بزرگ‌تر هستند.", pin: "Fil hā az tuti hā bozorgtar hastand.", en: "Elephants are bigger than parrots.", source: "phrase:34" },
        { fa: "اون از من بزرگ‌تر هست.", pin: "Oon az man bozorgtar hast.", en: "He is older than me.", source: "phrase:34" },
      ] },
    { id: "34.v.bozorgtarin", type: "vocabulary", fa: "بزرگ‌ترین", pin: "bozorgtarin", en: "the biggest", notes: "بزرگ + ترین",
      examples: [
        { fa: "تهران بزرگ‌ترین شهر ایران هست.", pin: "Tehran bozorgtarin shahr-e Iran hast.", en: "Tehran is the biggest city in Iran.", source: "phrase:34" },
      ] },
    { id: "34.v.koochak-koochik", type: "vocabulary", fa: "کوچک", pin: "koochak / koochik", en: "small; young (of a person)", notes: "ک-و-چ-ک" },
    { id: "34.v.koochaktar-koochiktar", type: "vocabulary", fa: "کوچک‌تر", pin: "koochaktar / koochiktar", en: "smaller; younger", notes: "کوچک + تر" },
    { id: "34.v.garm", type: "vocabulary", fa: "گرم", pin: "garm", en: "warm, hot", notes: "گ-ر-م",
      examples: [
        { fa: "امروز از دیروز گرم‌تره.", pin: "Emrooz az dirooz garmtar-eh.", en: "Today is warmer than yesterday.", source: "phrase:34" },
        { fa: "میترا ساعت چهار بعد از خرید میاد خونه و یه غذای گرم درست می‌کنه.", pin: "Mitrā sāat-e chahār baad az kharid miād khooneh va ye ghazā-ye garm dorost mikoneh.", en: "Mitra comes home at four after shopping and cooks a warm meal.", source: "story:32" },
        { fa: "امشب از دیشب گرم‌تره.", pin: "Emshab az dishab garmtar-eh.", en: "Tonight is warmer than last night.", source: "phrase:34" },
        { fa: "هوا داره خیلی گرم می‌شه", pin: "havā dāreh kheili garm misheh", en: "The weather is getting very hot", source: "phrase:32" },
      ] },
    { id: "34.v.garmtar", type: "vocabulary", fa: "گرم‌تر", pin: "garmtar", en: "warmer", notes: "گرم + تر",
      examples: [
        { fa: "امروز از دیروز گرم‌تره.", pin: "Emrooz az dirooz garmtar-eh.", en: "Today is warmer than yesterday.", source: "phrase:34" },
        { fa: "امشب از دیشب گرم‌تره.", pin: "Emshab az dishab garmtar-eh.", en: "Tonight is warmer than last night.", source: "phrase:34" },
      ] },
    { id: "34.v.sard", type: "vocabulary", fa: "سرد", pin: "sard", en: "cold", notes: "س-ر-د",
      examples: [
        { fa: "هوا داره سرد می‌شه", pin: "havā dāreh sard misheh", en: "The weather is getting cold", source: "phrase:32" },
        { fa: "سارا می‌گه: «چون هوا بارونیه و من سردمه.»", pin: "Sārā migeh: \"Chon havā bārooni-eh va man sardam-eh.\"", en: "Sara says: \"Because it's rainy and I'm cold.\"", source: "story:st-27-1" },
      ] },
    { id: "34.v.sardtar", type: "vocabulary", fa: "سردتر", pin: "sardtar", en: "colder", notes: "سرد + تر",
      examples: [
        { fa: "امسال از پارسال سردتره.", pin: "Emsāl az pārsāl sardtar-eh.", en: "This year is colder than last year.", source: "phrase:34" },
        { fa: "هوا امروز سردتر از دیروز بود.", pin: "Havā emrooz sardtar az dirooz bood.", en: "The weather today was colder than yesterday.", source: "story:st-34-2" },
      ] },
    { id: "34.v.jaleb", type: "vocabulary", fa: "جالب", pin: "jāleb", en: "interesting", notes: "ج-ا-ل-ب" },
    { id: "34.v.jalebtar", type: "vocabulary", fa: "جالب‌تر", pin: "jālebtar", en: "more interesting", notes: "جالب + تر" },
    { id: "34.v.peer", type: "vocabulary", fa: "پیر", pin: "peer", en: "old (of a person)", notes: "پ-ی-ر",
      examples: [
        { fa: "یه مسافر پیر می‌گه: «سفر کاری می‌رید؟»", pin: "Ye mosāfer-e pir migeh: \"Safar-e kāri mirid?\"", en: "An old passenger says: \"Are you going on a business trip?\"", source: "story:st-31-2" },
        { fa: "مامان‌بزرگ خیلی پیر هست، ولی روزی دو بار پیاده‌روی می‌کنه.", pin: "Māmānbozorg kheili pir hast, vali roozi do bār piāderavi mikoneh.", en: "Grandma is very old, but she goes for a walk twice a day.", source: "story:st-30-2" },
      ] },
    { id: "34.v.peertar", type: "vocabulary", fa: "پیرتر", pin: "peertar", en: "older", notes: "پیر + تر — also بزرگ‌تر" },
    { id: "34.v.javan-javoon", type: "vocabulary", fa: "جوان", pin: "javān / javoon", en: "young", notes: "ج-و-ا-ن" },
    { id: "34.v.javoontar", type: "vocabulary", fa: "جوون‌تر", pin: "javoontar", en: "younger", notes: "جوون + تر",
      examples: [
        { fa: "تو از من جوون‌تر، کوچیک‌تر هستی.", pin: "To az man javoontar, koochiktar hasti.", en: "You are younger, smaller than me.", source: "phrase:34" },
        { fa: "خواهرم از من جوون‌تر هست.", pin: "Khāharam az man javoontar hast.", en: "My sister is younger than me.", source: "phrase:34" },
      ] },
    { id: "34.v.khoshgel", type: "vocabulary", fa: "خوشگل", pin: "khoshgel", en: "pretty, good-looking", notes: "خوش (good) + گل (flower)",
      examples: [
        { fa: "این کفش خوشگل‌تره.", pin: "In kafsh khoshgeltar-eh.", en: "This shoe is prettier.", source: "phrase:34" },
      ] },
    { id: "34.v.khoshgeltar", type: "vocabulary", fa: "خوشگل‌تر", pin: "khoshgeltar", en: "prettier", notes: "خوشگل + تر",
      examples: [
        { fa: "این کفش خوشگل‌تره.", pin: "In kafsh khoshgeltar-eh.", en: "This shoe is prettier.", source: "phrase:34" },
      ] },
    { id: "34.v.ghadimi", type: "vocabulary", fa: "قدیمی", pin: "ghadimi", en: "old (of an object)", notes: "from قدیم (old times)",
      examples: [
        { fa: "دوچرخه‌ی من از دوچرخه‌ی تو قدیمی‌تره.", pin: "Docharkhe-ye man az docharkhe-ye to ghadimitar-eh.", en: "My bicycle is older than yours.", source: "phrase:34" },
        { fa: "در شیراز، سارا یه اتاق در یه مهمون‌خونه‌ی قدیمی اجاره می‌کنه.", pin: "Dar Shirāz, Sārā ye otāgh dar ye mehmoon-khoone-ye ghadimi ejāreh mikoneh.", en: "In Shiraz, Sara rents a room in an old guesthouse.", source: "story:st-31-2" },
      ] },
    { id: "34.v.ghadimitar", type: "vocabulary", fa: "قدیمی‌تر", pin: "ghadimitar", en: "older (of an object)", notes: "قدیمی + تر — not بزرگ‌تر for things",
      examples: [
        { fa: "دوچرخه‌ی من از دوچرخه‌ی تو قدیمی‌تره.", pin: "Docharkhe-ye man az docharkhe-ye to ghadimitar-eh.", en: "My bicycle is older than yours.", source: "phrase:34" },
      ] },
    { id: "34.v.khoob", type: "vocabulary", fa: "خوب", pin: "khoob", en: "good", notes: "خ-و-ب",
      examples: [
        { fa: "علی می‌گه: «خوب، فردا شب شام خونه‌ی مامان تو!»", pin: "Ali migeh: \"Khob, fardā shab shām khoone-ye māmān-e to!\"", en: "Ali says: \"OK then, tomorrow night it's dinner at your mom's!\"", source: "story:st-34-1" },
        { fa: "هوا خوبه، من پیاده می‌رم", pin: "havā khoobeh, man piādeh miram", en: "The weather's good, I'm walking", source: "phrase:30" },
        { fa: "سعید گفت: «نه، ممنون. ما خوبیم.»", pin: "Saeed goft: \"Na, mamnoon. Mā khoobim.\"", en: "Saeed said: \"No, thanks. We're fine.\"", source: "story:st-32-1" },
        { fa: "اون می‌گه: «تو دوست خیلی خوبی هستی.»", pin: "Oon migeh: \"To doost-e kheili khoobi hasti.\"", en: "She says: \"You're a really good friend.\"", source: "story:st-27-1" },
      ] },
    { id: "34.v.behtar", type: "vocabulary", fa: "بهتر", pin: "behtar", en: "better", notes: "irregular — not خوب‌تر",
      examples: [
        { fa: "یه کم بهترم!", pin: "Ye kam behtaram!", en: "I feel a bit better!", source: "phrase:34" },
        { fa: "هَوا خیلی بِهتَر از دیروز است.", pin: "Havā kheili behtar az dirooz ast.", en: "The weather is much better than yesterday.", source: "story:34" },
        { fa: "«هوای شیراز هم از هوای تهران بهتره.»", pin: "\"Havā-ye Shirāz ham az havā-ye Tehrān behtar-eh.\"", en: "\"And the weather in Shiraz is better than in Tehran.\"", source: "story:st-34-1" },
        { fa: "علی می‌خنده و می‌گه: «مامان تو از مامان من بهتر آشپزی می‌کنه؟»", pin: "Ali mikhandeh va migeh: \"Māmān-e to az māmān-e man behtar āshpazi mikoneh?\"", en: "Ali laughs and says: \"Your mom cooks better than my mom?\"", source: "story:st-34-1" },
      ] },
    { id: "34.v.behtarin", type: "vocabulary", fa: "بهترین", pin: "behtarin", en: "the best", notes: "irregular superlative of خوب",
      examples: [
        { fa: "تو بهترین مامان دنیا هستی.", pin: "To behtarin māmān-e donyā hasti.", en: "You are the best mother in the world.", source: "phrase:34" },
        { fa: "جُمعه بِهتَرین روزِ هَفته اَست.", pin: "Jom'e behtarin rooz-e hafteh ast.", en: "Friday is the best day of the week.", source: "story:34" },
        { fa: "علی می‌گه: «به نظر من، تهران بهترین شهر ایرانه.»", pin: "Ali migeh: \"Be nazar-e man, Tehrān behtarin shahr-e Irān-eh.\"", en: "Ali says: \"In my opinion, Tehran is the best city in Iran.\"", source: "story:st-34-1" },
        { fa: "«و مامان من بهترین فسنجون دنیا رو درست می‌کنه!»", pin: "\"Va māmān-e man behtarin fesenjoon-e donyā ro dorost mikoneh!\"", en: "\"And my mom makes the best fesenjoon in the world!\"", source: "story:st-34-1" },
      ] },
    { id: "34.v.bad", type: "vocabulary", fa: "بد", pin: "bad", en: "bad", notes: "ب-د",
      examples: [
        { fa: "مامان: «اونا خوبن. بد نیستن.»", pin: "Māmān: \"Oonā khooban. Bad nistan.\"", en: "Mom: \"They're well. Not bad.\"", source: "story:st-22-1" },
        { fa: "بد نیستند", pin: "bad nistand", en: "they're not bad", source: "phrase:22" },
      ] },
    { id: "34.v.badtar", type: "vocabulary", fa: "بدتر", pin: "badtar", en: "worse", notes: "بد + تر" },
    { id: "34.v.badtarin", type: "vocabulary", fa: "بدترین", pin: "badtarin", en: "the worst", notes: "بد + ترین" },
    { id: "34.v.ghashang", type: "vocabulary", fa: "قشنگ", pin: "ghashang", en: "beautiful, lovely", notes: "ق-ش-ن-گ",
      examples: [
        { fa: "یزد قشنگ‌ترین شهر ایران هست.", pin: "Yazd ghashangtarin shahr-e Iran hast.", en: "Yazd is the most beautiful city in Iran.", source: "phrase:34" },
        { fa: "سارا می‌گه: «نه! تهران از شیراز بزرگ‌تره، ولی شیراز قشنگ‌تره.»", pin: "Sārā migeh: \"Na! Tehrān az Shirāz bozorgtar-eh, vali Shirāz ghashangtar-eh.\"", en: "Sara says: \"No! Tehran is bigger than Shiraz, but Shiraz is prettier.\"", source: "story:st-34-1" },
      ] },
    { id: "34.v.ghashangtarin", type: "vocabulary", fa: "قشنگ‌ترین", pin: "ghashangtarin", en: "the most beautiful", notes: "قشنگ + ترین",
      examples: [
        { fa: "یزد قشنگ‌ترین شهر ایران هست.", pin: "Yazd ghashangtarin shahr-e Iran hast.", en: "Yazd is the most beautiful city in Iran.", source: "phrase:34" },
      ] },
    { id: "34.v.khoshmazze", type: "vocabulary", fa: "خوشمزه", pin: "khoshmazze", en: "tasty, delicious", notes: "خوش (good) + مزه (taste)",
      examples: [
        { fa: "فسنجون خوشمزه‌ترین غذای ایرانی هست.", pin: "Fesenjoon khoshmazzetarin ghazā-ye Irāni hast.", en: "Fesenjoon is the tastiest Iranian food.", source: "phrase:34" },
        { fa: "شام خیلی خوشمزه هست.", pin: "Shām kheili khoshmazeh hast.", en: "Dinner is very tasty.", source: "story:st-26-1" },
        { fa: "علی می‌گه: «ولی غذای تهران خوشمزه‌تره!»", pin: "Ali migeh: \"Vali ghazā-ye Tehrān khoshmazetar-eh!\"", en: "Ali says: \"But the food in Tehran is tastier!\"", source: "story:st-34-1" },
        { fa: "غذا خیلی خوشمزه و تازه هست.", pin: "Ghazā kheili khoshmazeh o tāzeh hast.", en: "The food is very tasty and fresh.", source: "story:st-2425-1" },
      ] },
    { id: "34.v.khoshmazzetarin", type: "vocabulary", fa: "خوشمزه‌ترین", pin: "khoshmazzetarin", en: "the tastiest", notes: "خوشمزه + ترین",
      examples: [
        { fa: "فسنجون خوشمزه‌ترین غذای ایرانی هست.", pin: "Fesenjoon khoshmazzetarin ghazā-ye Irāni hast.", en: "Fesenjoon is the tastiest Iranian food.", source: "phrase:34" },
        { fa: "سارا می‌گه: «خوشمزه‌ترین غذای ایرانی فسنجونه.»", pin: "Sārā migeh: \"Khoshmazetarin ghazā-ye irāni fesenjoon-eh.\"", en: "Sara says: \"The tastiest Iranian food is fesenjoon.\"", source: "story:st-34-1" },
      ] },
    { id: "34.v.fesenjoon", type: "vocabulary", fa: "فسنجون", pin: "fesenjoon", en: "fesenjoon (walnut & pomegranate stew)", notes: "a classic Iranian dish",
      examples: [
        { fa: "فسنجون خوشمزه‌ترین غذای ایرانی هست.", pin: "Fesenjoon khoshmazzetarin ghazā-ye Irāni hast.", en: "Fesenjoon is the tastiest Iranian food.", source: "phrase:34" },
        { fa: "سارا می‌گه: «خوشمزه‌ترین غذای ایرانی فسنجونه.»", pin: "Sārā migeh: \"Khoshmazetarin ghazā-ye irāni fesenjoon-eh.\"", en: "Sara says: \"The tastiest Iranian food is fesenjoon.\"", source: "story:st-34-1" },
        { fa: "«و مامان من بهترین فسنجون دنیا رو درست می‌کنه!»", pin: "\"Va māmān-e man behtarin fesenjoon-e donyā ro dorost mikoneh!\"", en: "\"And my mom makes the best fesenjoon in the world!\"", source: "story:st-34-1" },
        { fa: "سیاوش شام درست می‌کند: فسنجون و پلو.", pin: "Siāvash shām dorost mikonad: fesenjoon va polo.", en: "Siavash is making dinner: fesenjoon and rice.", source: "story:st-34-2" },
      ] },
    { id: "34.v.donya", type: "vocabulary", fa: "دنیا", pin: "donyā", en: "world; worldly life", notes: "everyday, material, emotional world",
      examples: [
        { fa: "تو بهترین مامان دنیا هستی.", pin: "To behtarin māmān-e donyā hasti.", en: "You are the best mother in the world.", source: "phrase:34" },
        { fa: "«و مامان من بهترین فسنجون دنیا رو درست می‌کنه!»", pin: "\"Va māmān-e man behtarin fesenjoon-e donyā ro dorost mikoneh!\"", en: "\"And my mom makes the best fesenjoon in the world!\"", source: "story:st-34-1" },
        { fa: "صبحونه‌ی مامانم بهترین صبحونه‌ی دنیاست!", pin: "Sobhoone-ye māmānam behtarin sobhoone-ye donyāst!", en: "My mom's breakfast is the best breakfast in the world!", source: "story:st-35-2" },
      ] },
    { id: "34.v.jahan", type: "vocabulary", fa: "جهان", pin: "jahān", en: "world, universe", notes: "the whole of existence — scientific or poetic" },
    { id: "34.v.shahr", type: "vocabulary", fa: "شهر", pin: "shahr", en: "city", notes: "ش-ه-ر",
      examples: [
        { fa: "تهران بزرگ‌ترین شهر ایران هست.", pin: "Tehran bozorgtarin shahr-e Iran hast.", en: "Tehran is the biggest city in Iran.", source: "phrase:34" },
        { fa: "مریم در شهر یزد زندگی می‌کنه.", pin: "Maryam dar shahr-e Yazd zendegi mikoneh.", en: "Maryam lives in the city of Yazd.", source: "story:st-2425-1" },
        { fa: "یزد قشنگ‌ترین شهر ایران هست.", pin: "Yazd ghashangtarin shahr-e Iran hast.", en: "Yazd is the most beautiful city in Iran.", source: "phrase:34" },
        { fa: "علی می‌گه: «به نظر من، تهران بهترین شهر ایرانه.»", pin: "Ali migeh: \"Be nazar-e man, Tehrān behtarin shahr-e Irān-eh.\"", en: "Ali says: \"In my opinion, Tehran is the best city in Iran.\"", source: "story:st-34-1" },
      ] },
    { id: "34.v.fil", type: "vocabulary", fa: "فیل", pin: "fil", en: "elephant", notes: "ف-ی-ل",
      examples: [
        { fa: "فیل‌ها از طوطی‌ها بزرگ‌تر هستند.", pin: "Fil hā az tuti hā bozorgtar hastand.", en: "Elephants are bigger than parrots.", source: "phrase:34" },
      ] },
    { id: "34.v.tuti", type: "vocabulary", fa: "طوطی", pin: "tuti", en: "parrot", notes: "ط-و-ط-ی",
      examples: [
        { fa: "فیل‌ها از طوطی‌ها بزرگ‌تر هستند.", pin: "Fil hā az tuti hā bozorgtar hastand.", en: "Elephants are bigger than parrots.", source: "phrase:34" },
      ] },
    { id: "34.v.sag", type: "vocabulary", fa: "سگ", pin: "sag", en: "dog", notes: "س-گ",
      examples: [
        { fa: "سگ از اسب کوچیک‌تر هست.", pin: "Sag az asb koochiktar hast.", en: "A dog is smaller than a horse.", source: "phrase:34" },
        { fa: "من سگ‌ها رو دوست نداشتم ولی الان سگ‌ها رو دوست دارم", pin: "man sag-hā ro doost nadāshtam vali alān sag-hā ro doost dāram", en: "I didn't like dogs but now I like dogs", source: "phrase:32" },
        { fa: "من هیچ‌وقت به سگم بیسکویت نمیدم", pin: "man hich-vaght be sagam biscuit nemidam", en: "I never give my dog biscuits", source: "phrase:24-25" },
        { fa: "سگ داشتن خیلی سخته ولی شیرین هم هست", pin: "sag dāshtan kheili sakht-e vali shirin ham hast", en: "Having a dog is hard, but it's also sweet", source: "phrase:27" },
      ] },
    { id: "34.v.asb", type: "vocabulary", fa: "اسب", pin: "asb", en: "horse", notes: "ا-س-ب",
      examples: [
        { fa: "سگ از اسب کوچیک‌تر هست.", pin: "Sag az asb koochiktar hast.", en: "A dog is smaller than a horse.", source: "phrase:34" },
        { fa: "من سوار اسبم", pin: "man savār-e asbam", en: "I'm on a horse", source: "phrase:31" },
        { fa: "سگ‌ها از اسب‌ها کوچیک‌تر هستند.", pin: "Sag hā az asb hā koochiktar hastand.", en: "Dogs are smaller than horses.", source: "phrase:34" },
      ] },
    { id: "34.v.docharkheh", type: "vocabulary", fa: "دوچرخه", pin: "docharkheh", en: "bicycle", notes: "دو (two) + چرخ (wheel)",
      examples: [
        { fa: "دوچرخه‌ی من از دوچرخه‌ی تو قدیمی‌تره.", pin: "Docharkhe-ye man az docharkhe-ye to ghadimitar-eh.", en: "My bicycle is older than yours.", source: "phrase:34" },
        { fa: "صبح، اون با دوچرخه به نونوایی می‌ره و نون می‌خره.", pin: "Sobh, oon bā docharkheh be noonvāyi mireh va noon mikhareh.", en: "In the morning, he goes to the bakery by bike and buys bread.", source: "story:st-31-1" },
      ] },
    { id: "34.v.shohar", type: "vocabulary", fa: "شوهر", pin: "shohar", en: "husband", notes: "ش-و-ه-ر — شوهرم = my husband",
      examples: [
        { fa: "شوهرم از من بزرگ‌تر هست.", pin: "Shoharam az man bozorgtar hast.", en: "My husband is older than me.", source: "phrase:34" },
        { fa: "اونها زن و شوهرن و سه تا بچه دارن.", pin: "oonhā zan-o shohar-an va se tā bache dāran.", en: "They are husband and wife and have three children.", source: "story:32" },
        { fa: "شب، سارا با شوهرش شام می‌خوره.", pin: "Shab, Sārā bā shoharesh shām mikhoreh.", en: "In the evening, Sara has dinner with her husband.", source: "story:st-26-1" },
        { fa: "شوهرم یه کم گیتار می‌زنه", pin: "shoharam ye kam gitār mizaneh", en: "My husband plays a little guitar", source: "phrase:33" },
      ] },
    { id: "34.v.khahar", type: "vocabulary", fa: "خواهر", pin: "khāhar", en: "sister", notes: "خ-و-ا-ه-ر — خواهرم = my sister",
      examples: [
        { fa: "خواهرم از من جوون‌تر هست.", pin: "Khāharam az man javoontar hast.", en: "My sister is younger than me.", source: "phrase:34" },
        { fa: "خواهرم امروز با دوست‌هاش صبحونه میخوره", pin: "khāharam emrooz bā doost-hāsh sobhooneh mikhoreh", en: "My sister is having breakfast with her friends today", source: "phrase:26" },
      ] },
    { id: "34.v.emsal", type: "vocabulary", fa: "امسال", pin: "emsāl", en: "this year", notes: "این + سال",
      examples: [
        { fa: "امسال از پارسال سردتره.", pin: "Emsāl az pārsāl sardtar-eh.", en: "This year is colder than last year.", source: "phrase:34" },
        { fa: "بابام امسال ماشینش رو می‌فروشه", pin: "bābām emsāl māshinesh ro miforousheh", en: "My dad is selling his car this year", source: "phrase:31" },
      ] },
    { id: "34.v.parsal", type: "vocabulary", fa: "پارسال", pin: "pārsāl", en: "last year", notes: "پار + سال — also سالِ پیش",
      examples: [
        { fa: "امسال از پارسال سردتره.", pin: "Emsāl az pārsāl sardtar-eh.", en: "This year is colder than last year.", source: "phrase:34" },
      ] },
    { id: "34.v.emshab", type: "vocabulary", fa: "امشب", pin: "emshab", en: "tonight", notes: "این + شب",
      examples: [
        { fa: "امشب از دیشب گرم‌تره.", pin: "Emshab az dishab garmtar-eh.", en: "Tonight is warmer than last night.", source: "phrase:34" },
        { fa: "شوهرش امشب شام درست می‌کنه.", pin: "Shoharesh emshab shām dorost mikoneh.", en: "Her husband is cooking dinner tonight.", source: "story:st-26-1" },
        { fa: "امشب ما با همدیگه شام می‌خوریم", pin: "emshab mā bā hamdige shām mikhorim", en: "Tonight we'll eat dinner together", source: "phrase:28" },
        { fa: "من خوشحالم چون امشب کلاس فارسی دارم", pin: "man khoshhālam chon emshab kelās-e Fārsi dāram", en: "I'm happy because I have Farsi class tonight", source: "phrase:27" },
      ] },
    { id: "34.v.dishab", type: "vocabulary", fa: "دیشب", pin: "dishab", en: "last night", notes: "دی + شب",
      examples: [
        { fa: "امشب از دیشب گرم‌تره.", pin: "Emshab az dishab garmtar-eh.", en: "Tonight is warmer than last night.", source: "phrase:34" },
        { fa: "دیشب سعید و میترا ساعت ده نخوابیدن.", pin: "Dishab Saeed o Mitrā sāat-e dah nakhābidan.", en: "Last night Saeed and Mitra didn't go to bed at ten.", source: "story:st-32-1" },
        { fa: "دیشب کجا بودی؟", pin: "dishab kojā boodi?", en: "Where were you last night?", source: "phrase:32" },
        { fa: "ولی دیشب...", pin: "vali dishab...", en: "But last night...", source: "story:32" },
      ] },
    { id: "34.v.laghar", type: "vocabulary", fa: "لاغر", pin: "lāghar", en: "slim, thin", notes: "ل-ا-غ-ر" },
    { id: "34.v.chagh", type: "vocabulary", fa: "چاق", pin: "chāgh", en: "fat", notes: "چ-ا-ق" },
    { id: "34.v.kutah", type: "vocabulary", fa: "کوتاه", pin: "kutāh", en: "short; brief", notes: "opposite بلند (height) or طولانی (time)" },
    { id: "34.v.boland", type: "vocabulary", fa: "بلند", pin: "boland", en: "tall; long", notes: "ب-ل-ن-د" },
    { id: "34.v.sangin", type: "vocabulary", fa: "سنگین", pin: "sangin", en: "heavy", notes: "from سنگ (stone)" },
    { id: "34.v.sabok", type: "vocabulary", fa: "سبک", pin: "sabok", en: "light (in weight)", notes: "س-ب-ک" },
    { id: "34.v.kasif", type: "vocabulary", fa: "کثیف", pin: "kasif", en: "dirty", notes: "ک-ث-ی-ف" },
    { id: "34.v.tamiz", type: "vocabulary", fa: "تمیز", pin: "tamiz", en: "clean", notes: "ت-م-ی-ز",
      examples: [
        { fa: "گربه‌ام هر روز خودش رو تمیز می‌کنه", pin: "gorbe-am har rooz khodesh ro tamiz mikoneh", en: "My cat cleans itself every day", source: "phrase:29" },
        { fa: "آشپزخونه‌ی مامانم کوچیکه، ولی خیلی تمیزه.", pin: "Āshpazkhoone-ye māmānam koochik-eh, vali kheili tamiz-eh.", en: "My mom's kitchen is small, but it's very clean.", source: "story:st-35-2" },
      ] },
    { id: "34.v.kond", type: "vocabulary", fa: "کند", pin: "kond", en: "slow", notes: "ک-ن-د" },
    { id: "34.v.tond", type: "vocabulary", fa: "تند", pin: "tond", en: "fast; spicy", notes: "ت-ن-د" },
    { id: "34.v.bishtar", type: "vocabulary", fa: "بیشتر", pin: "bishtar", en: "more", notes: "بیش + تر" },
    { id: "34.v.kamtar", type: "vocabulary", fa: "کمتر", pin: "kamtar", en: "less", notes: "کم + تر" },
    { id: "34.v.tulani", type: "vocabulary", fa: "طولانی", pin: "tulāni", en: "long (in time)", notes: "from طول (length)" },
    { id: "34.v.por", type: "vocabulary", fa: "پر", pin: "por", en: "full", notes: "پ-ر" },
    { id: "34.v.khali", type: "vocabulary", fa: "خالی", pin: "khāli", en: "empty", notes: "خ-ا-ل-ی" },
    { id: "34.v.halim", type: "vocabulary", fa: "حلیم", pin: "halim", en: "halim (thick wheat & meat porridge)", notes: "a hearty breakfast dish",
      examples: [
        { fa: "حَلیم، نانِ داغ و چای.", pin: "Halim, nān-e dāgh va chāy.", en: "Halim, hot bread and tea.", source: "story:34" },
        { fa: "سارا می‌گه: «آره! ولی مامان تو بهترین حلیم رو درست می‌کنه.»", pin: "Sārā migeh: \"Āreh! Vali māmān-e to behtarin halim ro dorost mikoneh.\"", en: "Sara says: \"Yes! But your mom makes the best halim.\"", source: "story:st-34-1" },
        { fa: "بویِ حَلیم و دارچین در خانه می‌پیچَد.", pin: "Booye halim va dārchin dar khāneh mipichad.", en: "The smell of halim and cinnamon fills the house.", source: "story:34" },
      ] },
    { id: "34.v.yad-dasht", type: "vocabulary", fa: "یادداشت", pin: "yād dāsht", en: "note", notes: "یاد (memory) + داشت (had)",
      examples: [
        { fa: "یادداشت‌هایِ من", pin: "Yād dāsht hāye man", en: "My notes", source: "story:34" },
      ] },
    { id: "34.v.yad-dasht-kardan", type: "vocabulary", fa: "یادداشت کردن", pin: "yād dāsht kardan", en: "to note down", notes: "یادداشت + کردن" },
    { id: "34.v.dagh", type: "vocabulary", fa: "داغ", pin: "dāgh", en: "extremely hot", notes: "د-ا-غ",
      examples: [
        { fa: "حَلیم، نانِ داغ و چای.", pin: "Halim, nān-e dāgh va chāy.", en: "Halim, hot bread and tea.", source: "story:34" },
      ] },
    { id: "34.v.darchin", type: "vocabulary", fa: "دارچین", pin: "dārchin", en: "cinnamon", notes: "د-ا-ر-چ-ی-ن",
      examples: [
        { fa: "بویِ حَلیم و دارچین در خانه می‌پیچَد.", pin: "Booye halim va dārchin dar khāneh mipichad.", en: "The smell of halim and cinnamon fills the house.", source: "story:34" },
      ] },
    { id: "34.v.saket", type: "vocabulary", fa: "ساکت", pin: "sāket", en: "quiet, silent", notes: "س-ا-ک-ت",
      examples: [
        { fa: "امّا خانه ساکِت اَست.", pin: "Ammā khāneh sāket ast.", en: "But the house is quiet.", source: "story:34" },
        { fa: "خانه دیگر ساکت نیست.", pin: "Khāneh digar sāket nist.", en: "The house isn't quiet anymore.", source: "story:st-34-2" },
      ] },
    { id: "34.v.hanooz", type: "vocabulary", fa: "هنوز", pin: "hanooz", en: "yet, still", notes: "ه-ن-و-ز",
      examples: [
        { fa: "بَچّه‌ها هَنوز خواب هَستَند.", pin: "Bachcheh hā hanooz khāb hastand.", en: "The children are still asleep.", source: "story:34" },
        { fa: "جمعه هنوز بهترین روز هفته است.", pin: "Jom'eh hanooz behtarin rooz-e hafteh ast.", en: "Friday is still the best day of the week.", source: "story:st-34-2" },
      ] },
    { id: "34.v.kam-kam", type: "vocabulary", fa: "کم کم", pin: "kam kam", en: "gradually, little by little", notes: "کم (little) doubled",
      examples: [
        { fa: "کَم کَم برایِ رفتن آماده می‌شَوَم.", pin: "Kam kam barāye raftan āmādeh mishavam.", en: "Little by little I get ready to leave.", source: "story:34" },
      ] },
    { id: "34.v.amadeh", type: "vocabulary", fa: "آماده", pin: "āmādeh", en: "ready", notes: "آ-م-ا-د-ه",
      examples: [
        { fa: "کَم کَم برایِ رفتن آماده می‌شَوَم.", pin: "Kam kam barāye raftan āmādeh mishavam.", en: "Little by little I get ready to leave.", source: "story:34" },
        { fa: "بعد از صبحونه، مامان می‌گه: «زود باشید! همه‌چیز آماده‌ست؟»", pin: "Ba'd az sobhooneh, māmān migeh: \"Zood bāshid! Hameh-chiz āmādeh-st?\"", en: "After breakfast, Mom says: \"Hurry up! Is everything ready?\"", source: "story:st-33-2" },
      ] },
    { id: "34.v.amadeh-shodan", type: "vocabulary", fa: "آماده شدن", pin: "āmādeh shodan", en: "to get ready", notes: "آماده + شدن" },
    { id: "34.v.raghs", type: "vocabulary", fa: "رقص", pin: "raghs", en: "dance", notes: "ر-ق-ص",
      examples: [
        { fa: "مَن خیلی خوشحالَم چون جُمعه‌ها کِلاسِ رَقص دارَم.", pin: "Man kheili khoshhālam chun jom'e hā kelās-e raghs dāram.", en: "I am very happy because on Fridays I have a dance class.", source: "story:34" },
        { fa: "کلاس رقص امروز خیلی خوب بود.", pin: "Kelās-e raghs emrooz kheili khoob bood.", en: "Dance class was very good today.", source: "story:st-34-2" },
        { fa: "من خسته هستم، امّا خیلی خوشحالم، چون رقص را خیلی دوست دارم.", pin: "Man khasteh hastam, ammā kheili khoshhālam, chun raghs rā kheili doost dāram.", en: "I'm tired, but I'm very happy, because I really love dancing.", source: "story:st-34-2" },
      ] },
    { id: "34.v.raghsidan", type: "vocabulary", fa: "رقصیدن", pin: "raghsidan", en: "to dance", notes: "present stem: رقص",
      examples: [
        { fa: "امروز بهتر از هفته‌ی پیش رقصیدم.", pin: "Emrooz behtar az hafte-ye pish raghsidam.", en: "Today I danced better than last week.", source: "story:st-34-2" },
      ] },
    { id: "34.v.kelas-e-raghs", type: "vocabulary", fa: "کلاس رقص", pin: "kelās-e raghs", en: "dance class", notes: "کلاس + ezāfe + رقص",
      examples: [
        { fa: "مَن خیلی خوشحالَم چون جُمعه‌ها کِلاسِ رَقص دارَم.", pin: "Man kheili khoshhālam chun jom'e hā kelās-e raghs dāram.", en: "I am very happy because on Fridays I have a dance class.", source: "story:34" },
        { fa: "کلاس رقص امروز خیلی خوب بود.", pin: "Kelās-e raghs emrooz kheili khoob bood.", en: "Dance class was very good today.", source: "story:st-34-2" },
      ] },
    { id: "34.v.pichidan", type: "vocabulary", fa: "پیچیدن", pin: "pichidan", en: "to spread, to wind, to echo", notes: "present stem: پیچ",
      examples: [
        { fa: "صدای خنده‌اش تو سرم می‌پیچه.", pin: "Sedāye khandash tu saram mipicheh.", en: "The sound of her laughter echoes in my head.", source: "phrase:34" },
        { fa: "بویِ حَلیم و دارچین در خانه می‌پیچَد.", pin: "Booye halim va dārchin dar khāneh mipichad.", en: "The smell of halim and cinnamon fills the house.", source: "story:34" },
        { fa: "بوی فسنجون در خانه می‌پیچد.", pin: "Booye fesenjoon dar khāneh mipichad.", en: "The smell of fesenjoon fills the house.", source: "story:st-34-2" },
      ] },
    { id: "34.v.jome", type: "vocabulary", fa: "جمعه", pin: "jom'e", en: "Friday", notes: "ج-م-ع-ه",
      examples: [
        { fa: "امروز جُمعه اَست.", pin: "Emrooz jom'e ast.", en: "Today is Friday.", source: "story:34" },
        { fa: "مَن خیلی خوشحالَم چون جُمعه‌ها کِلاسِ رَقص دارَم.", pin: "Man kheili khoshhālam chun jom'e hā kelās-e raghs dāram.", en: "I am very happy because on Fridays I have a dance class.", source: "story:34" },
        { fa: "من از دوشنبه تا جمعه کار می‌کنم", pin: "man az doshanbe tā jome kār mikonam", en: "I work from Monday to Friday", source: "phrase:30" },
        { fa: "جمعه هنوز بهترین روز هفته است.", pin: "Jom'eh hanooz behtarin rooz-e hafteh ast.", en: "Friday is still the best day of the week.", source: "story:st-34-2" },
      ] },
    { id: "34.v.hava", type: "vocabulary", fa: "هوا", pin: "havā", en: "weather, air", notes: "ه-و-ا",
      examples: [
        { fa: "هَوا خیلی بِهتَر از دیروز است.", pin: "Havā kheili behtar az dirooz ast.", en: "The weather is much better than yesterday.", source: "story:34" },
        { fa: "«هوای شیراز هم از هوای تهران بهتره.»", pin: "\"Havā-ye Shirāz ham az havā-ye Tehrān behtar-eh.\"", en: "\"And the weather in Shiraz is better than in Tehran.\"", source: "story:st-34-1" },
        { fa: "هوا داره سرد می‌شه", pin: "havā dāreh sard misheh", en: "The weather is getting cold", source: "phrase:32" },
        { fa: "هوا خوبه، من پیاده می‌رم", pin: "havā khoobeh, man piādeh miram", en: "The weather's good, I'm walking", source: "phrase:30" },
      ] },
    { id: "34.v.sobh-e-zood", type: "vocabulary", fa: "صبح زود", pin: "sobh-e zood", en: "early morning", notes: "صبح + زود (early)",
      examples: [
        { fa: "صُبحِ زود بیدار میشم و صُبحانه دُرُست می‌کنم.", pin: "Sobh-e zood bidār misham va sobhāneh dorost mikonam.", en: "I wake up early and make breakfast.", source: "story:34" },
      ] },
    { id: "34.v.sobhaneh", type: "vocabulary", fa: "صبحانه", pin: "sobhāneh", en: "breakfast", notes: "from صبح (morning)",
      examples: [
        { fa: "صُبحِ زود بیدار میشم و صُبحانه دُرُست می‌کنم.", pin: "Sobh-e zood bidār misham va sobhāneh dorost mikonam.", en: "I wake up early and make breakfast.", source: "story:34" },
        { fa: "من ساعت هفت صبحانه میخورم", pin: "man sā’at-e haft sobhāneh mikhoram", en: "I eat breakfast at 7", source: "phrase:26" },
      ] },
    { id: "34.v.nan-noon", type: "vocabulary", fa: "نان", pin: "nān / noon", en: "bread", notes: "نان written, نون spoken",
      examples: [
        { fa: "حَلیم، نانِ داغ و چای.", pin: "Halim, nān-e dāgh va chāy.", en: "Halim, hot bread and tea.", source: "story:34" },
      ] },
    { id: "34.v.khab", type: "vocabulary", fa: "خواب", pin: "khāb", en: "asleep; sleep", notes: "خ-و-ا-ب",
      examples: [
        { fa: "بَچّه‌ها هَنوز خواب هَستَند.", pin: "Bachcheh hā hanooz khāb hastand.", en: "The children are still asleep.", source: "story:34" },
        { fa: "من هر روز ساعت شیش از خواب بیدار می‌شم", pin: "man har rooz sāat-e shish az khāb bidār misham", en: "I wake up at six every day", source: "phrase:32" },
        { fa: "دیروز علی ساعت هفت از خواب بیدار شد.", pin: "Dirooz Ali sāat-e haft az khāb bidār shod.", en: "Yesterday Ali woke up at seven.", source: "story:st-32-2" },
        { fa: "شما کی از خواب بیدار می‌شید؟", pin: "shomā key az khāb bidār mishid?", en: "What time do you wake up?", source: "phrase:32" },
      ] },
    { id: "34.v.khoshhal", type: "vocabulary", fa: "خوشحال", pin: "khoshhāl", en: "happy", notes: "خوش (good) + حال (state)",
      examples: [
        { fa: "مَن خیلی خوشحالَم چون جُمعه‌ها کِلاسِ رَقص دارَم.", pin: "Man kheili khoshhālam chun jom'e hā kelās-e raghs dāram.", en: "I am very happy because on Fridays I have a dance class.", source: "story:34" },
        { fa: "الان سارا خوشحاله.", pin: "Alān Sārā khoshhāl-eh.", en: "Now Sara is happy.", source: "story:st-27-1" },
        { fa: "یه خانواده‌ی خوشحال", pin: "ye khānevāde-ye khoshhāl", en: "A happy family", source: "story:32" },
        { fa: "من خوشحالم چون امشب کلاس فارسی دارم", pin: "man khoshhālam chon emshab kelās-e Fārsi dāram", en: "I'm happy because I have Farsi class tonight", source: "phrase:27" },
      ] },
    { id: "34.v.chun", type: "vocabulary", fa: "چون", pin: "chun", en: "because", notes: "چ-و-ن",
      examples: [
        { fa: "مَن خیلی خوشحالَم چون جُمعه‌ها کِلاسِ رَقص دارَم.", pin: "Man kheili khoshhālam chun jom'e hā kelās-e raghs dāram.", en: "I am very happy because on Fridays I have a dance class.", source: "story:34" },
        { fa: "بعد علی با اتوبوس به داروخونه می‌ره، چون داروخونه از اینجا خیلی دوره.", pin: "Ba'd Ali bā otobus be dārookhooneh mireh, chon dārookhooneh az injā kheili dour-eh.", en: "Then Ali takes the bus to the pharmacy, because the pharmacy is very far from here.", source: "story:st-31-1" },
        { fa: "من خوشحالم چون امشب کلاس فارسی دارم", pin: "man khoshhālam chon emshab kelās-e Fārsi dāram", en: "I'm happy because I have Farsi class tonight", source: "phrase:27" },
        { fa: "من خسته هستم، امّا خیلی خوشحالم، چون رقص را خیلی دوست دارم.", pin: "Man khasteh hastam, ammā kheili khoshhālam, chun raghs rā kheili doost dāram.", en: "I'm tired, but I'm very happy, because I really love dancing.", source: "story:st-34-2" },
      ] },
    { id: "34.v.hafteh", type: "vocabulary", fa: "هفته", pin: "hafteh", en: "week", notes: "ه-ف-ت-ه",
      examples: [
        { fa: "جُمعه بِهتَرین روزِ هَفته اَست.", pin: "Jom'e behtarin rooz-e hafteh ast.", en: "Friday is the best day of the week.", source: "story:34" },
        { fa: "ولی هفته‌ی پیش زنگ نزد.", pin: "Vali hafte-ye pish zang nazad.", en: "But last week she didn't call.", source: "story:st-33-1" },
        { fa: "من هفته‌ای دو بار می‌رم باشگاه", pin: "man hafte-yi do bār miram bāshgāh", en: "I go to the gym twice a week", source: "phrase:30" },
        { fa: "من این هفته به مسافرت می‌رم", pin: "man in hafteh be mosāferat miram", en: "I'm going on a trip this week", source: "phrase:31" },
      ] },
    { id: "34.v.hamin", type: "vocabulary", fa: "همین", pin: "hamin", en: "that's it, just that", notes: "هم + این" },
    { id: "34.v.amma", type: "vocabulary", fa: "امّا", pin: "ammā", en: "but", notes: "ا-م-ا",
      examples: [
        { fa: "امّا خانه ساکِت اَست.", pin: "Ammā khāneh sāket ast.", en: "But the house is quiet.", source: "story:34" },
        { fa: "من پنیر دوست نداشتم، اما الان پنیر خیلی دوست دارم", pin: "man panir doost nadāshtam, ammā alān panir kheili doost dāram", en: "I didn't like cheese, but now I like cheese a lot", source: "phrase:32" },
        { fa: "من خسته هستم، امّا خیلی خوشحالم، چون رقص را خیلی دوست دارم.", pin: "Man khasteh hastam, ammā kheili khoshhālam, chun raghs rā kheili doost dāram.", en: "I'm tired, but I'm very happy, because I really love dancing.", source: "story:st-34-2" },
      ] },
    { id: "34.v.boo", type: "vocabulary", fa: "بو", pin: "boo", en: "smell, scent", notes: "ب-و",
      examples: [
        { fa: "بویِ حَلیم و دارچین در خانه می‌پیچَد.", pin: "Booye halim va dārchin dar khāneh mipichad.", en: "The smell of halim and cinnamon fills the house.", source: "story:34" },
        { fa: "بوی فسنجون در خانه می‌پیچد.", pin: "Booye fesenjoon dar khāneh mipichad.", en: "The smell of fesenjoon fills the house.", source: "story:st-34-2" },
      ] },
    { id: "34.v.seda", type: "vocabulary", fa: "صدا", pin: "sedā", en: "sound, voice", notes: "ص-د-ا",
      examples: [
        { fa: "ساعت هفت صبح، مامان بچه‌ها رو صدا می‌زنه: «بچه‌ها، بیدار بشید!»", pin: "Sāat-e haft-e sobh, māmān bacheh hā ro sedā mizaneh: \"Bacheh hā, bidār beshid!\"", en: "At seven in the morning, Mom calls the children: \"Kids, wake up!\"", source: "story:st-33-2" },
      ] },
    // Grammar
    { id: "34.g.tar", type: "grammar", fa: "ـتر", pin: "-tar", en: "comparative suffix (more ...)", notes: "adjective + تر: بزرگ → بزرگ‌تر" },
    { id: "34.g.tarin", type: "grammar", fa: "ـترین", pin: "-tarin", en: "superlative suffix (the most ...)", notes: "adjective + ترین: بزرگ → بزرگ‌ترین" },
    { id: "34.g.az-tar", type: "grammar", fa: "از … ـتر", pin: "az ... -tar", en: "...er than ...", notes: "[A] از [B] [adj]تر — تهران از شیراز بزرگ‌تر هست" },
    { id: "34.g.khoob-behtar-behtarin", type: "grammar", fa: "خوب ← بهتر ← بهترین", pin: "khoob → behtar → behtarin", en: "good → better → the best", notes: "irregular: never خوب‌تر" },
    { id: "34.g.bad-badtar-badtarin", type: "grammar", fa: "بد ← بدتر ← بدترین", pin: "bad → badtar → badtarin", en: "bad → worse → the worst", notes: "regular endings, worth drilling as a set" },
    { id: "34.g.bozorgtarin-shahr-e-iran", type: "grammar", fa: "بزرگ‌ترین شهرِ ایران", pin: "bozorgtarin shahr-e Iran", en: "the biggest city in Iran", notes: "superlative + noun + ezāfe + group" },
    { id: "34.g.hast", type: "grammar", fa: "هست", pin: "hast", en: "is", notes: "singular — تهران ... بزرگ‌تر هست" },
    { id: "34.g.hastand", type: "grammar", fa: "هستند", pin: "hastand", en: "they are", notes: "plural — فیل‌ها ... بزرگ‌تر هستند" },
    { id: "34.g.bozorgtar", type: "grammar", fa: "بزرگ‌تر = older", pin: "bozorgtar", en: "older (of a person)", notes: "Persian says 'bigger' for older" },
    { id: "34.g.koochiktar", type: "grammar", fa: "کوچیک‌تر = younger", pin: "koochiktar", en: "younger (of a person)", notes: "Persian says 'smaller' for younger" },
    { id: "34.g.ghadimitar", type: "grammar", fa: "قدیمی‌تر = older (thing)", pin: "ghadimitar", en: "older (of an object)", notes: "use قدیمی‌تر for objects, not بزرگ‌تر" },
    { id: "34.g.ast", type: "grammar", fa: "است", pin: "ast", en: "is (formal, written)", notes: "the written form of the spoken ـه" },
    { id: "34.g.mishavam", type: "grammar", fa: "می‌شَوَم", pin: "mishavam", en: "I become (formal, written)", notes: "spoken: میشم" },
    { id: "34.g.mipichad", type: "grammar", fa: "می‌پیچَد", pin: "mipichad", en: "it spreads (formal, written)", notes: "spoken: می‌پیچه" },
    { id: "34.g.miraghsam", type: "grammar", fa: "می‌رقصم", pin: "miraghsam", en: "I dance", notes: "می + رقص + م" },
    { id: "34.g.baraye-raftan", type: "grammar", fa: "برای رفتن", pin: "barāye raftan", en: "for leaving, to go", notes: "برای + infinitive used as a noun" },
    // Phrases
    { id: "34.p.be-nazar-e-man", type: "phrases", fa: "به نظر من…", pin: "Be nazar-e man…", en: "In my opinion…", notes: "به + نظر + ezāfe + من" },
    { id: "34.p.az-nazar-e-man", type: "phrases", fa: "از نظر من…", pin: "Az nazar-e man…", en: "In my opinion… / From my point of view…", notes: "از + نظر + ezāfe + من" },
    { id: "34.p.emrooz-az-dirooz-garmtar-eh", type: "phrases", fa: "امروز از دیروز گرم‌تره.", pin: "Emrooz az dirooz garmtar-eh.", en: "Today is warmer than yesterday.", notes: "از = than" },
    { id: "34.p.emshab-az-dishab-garmtar-eh", type: "phrases", fa: "امشب از دیشب گرم‌تره.", pin: "Emshab az dishab garmtar-eh.", en: "Tonight is warmer than last night.", notes: "امشب / دیشب" },
    { id: "34.p.emsal-az-parsal-sardtar-eh", type: "phrases", fa: "امسال از پارسال سردتره.", pin: "Emsāl az pārsāl sardtar-eh.", en: "This year is colder than last year.", notes: "also از سالِ پیش" },
    { id: "34.p.tehran-az-shiraz-bozorgtar-hast", type: "phrases", fa: "تهران از شیراز بزرگ‌تر هست.", pin: "Tehran az Shirāz bozorgtar hast.", en: "Tehran is bigger than Shiraz.", notes: "[A] از [B] بزرگ‌تر" },
    { id: "34.p.shiraz-az-tehran-koochiktar-hast", type: "phrases", fa: "شیراز از تهران کوچیک‌تر هست.", pin: "Shirāz az Tehran koochiktar hast.", en: "Shiraz is smaller than Tehran.", notes: "the same frame reversed" },
    { id: "34.p.fil-ha-az-tuti-ha-bozorgtar", type: "phrases", fa: "فیل‌ها از طوطی‌ها بزرگ‌تر هستند.", pin: "Fil hā az tuti hā bozorgtar hastand.", en: "Elephants are bigger than parrots.", notes: "plural subject → هستند" },
    { id: "34.p.sag-az-asb-koochiktar-hast", type: "phrases", fa: "سگ از اسب کوچیک‌تر هست.", pin: "Sag az asb koochiktar hast.", en: "A dog is smaller than a horse.", notes: "singular → هست" },
    { id: "34.p.sag-ha-az-asb-ha-koochiktar", type: "phrases", fa: "سگ‌ها از اسب‌ها کوچیک‌تر هستند.", pin: "Sag hā az asb hā koochiktar hastand.", en: "Dogs are smaller than horses.", notes: "plural → هستند" },
    { id: "34.p.man-az-oon-koochiktar-hastam", type: "phrases", fa: "من از اون کوچیک‌تر هستم.", pin: "Man az oon koochiktar hastam.", en: "I am younger than her.", notes: "کوچیک‌تر = younger" },
    { id: "34.p.oon-az-man-bozorgtar-hast", type: "phrases", fa: "اون از من بزرگ‌تر هست.", pin: "Oon az man bozorgtar hast.", en: "He is older than me.", notes: "بزرگ‌تر = older" },
    { id: "34.p.shoharam-az-man-bozorgtar-hast", type: "phrases", fa: "شوهرم از من بزرگ‌تر هست.", pin: "Shoharam az man bozorgtar hast.", en: "My husband is older than me.", notes: "شوهر + م" },
    { id: "34.p.to-az-man-javoontar-koochiktar", type: "phrases", fa: "تو از من جوون‌تر، کوچیک‌تر هستی.", pin: "To az man javoontar, koochiktar hasti.", en: "You are younger, smaller than me.", notes: "two comparatives in one sentence" },
    { id: "34.p.docharkhe-ye-man-az-docharkhe-ye", type: "phrases", fa: "دوچرخه‌ی من از دوچرخه‌ی تو قدیمی‌تره.", pin: "Docharkhe-ye man az docharkhe-ye to ghadimitar-eh.", en: "My bicycle is older than yours.", notes: "قدیمی‌تر for objects" },
    { id: "34.p.ye-kam-behtaram", type: "phrases", fa: "یه کم بهترم!", pin: "Ye kam behtaram!", en: "I feel a bit better!", notes: "بهتر + م" },
    { id: "34.p.kheili-behtaram", type: "phrases", fa: "خیلی بهترم!", pin: "Kheili behtaram!", en: "I feel much better!", notes: "خیلی + بهترم" },
    { id: "34.p.to-az-man-bozorgtar-hasti", type: "phrases", fa: "تو از من بزرگ‌تر هستی.", pin: "To az man bozorgtar hasti.", en: "You are older than me.", notes: "هستی (you are)" },
    { id: "34.p.man-az-to-bozorgtar-hastam", type: "phrases", fa: "من از تو بزرگ‌تر هستم.", pin: "Man az to bozorgtar hastam.", en: "I am older than you.", notes: "هستم (I am)" },
    { id: "34.p.khaharam-az-man-javoontar-hast", type: "phrases", fa: "خواهرم از من جوون‌تر هست.", pin: "Khāharam az man javoontar hast.", en: "My sister is younger than me.", notes: "خواهر + م" },
    { id: "34.p.in-kafsh-khoshgeltar-eh", type: "phrases", fa: "این کفش خوشگل‌تره.", pin: "In kafsh khoshgeltar-eh.", en: "This shoe is prettier.", notes: "خوشگل + تر + ه" },
    { id: "34.p.in-behtar-eh", type: "phrases", fa: "این بهتره!", pin: "In behtar-eh!", en: "This one is better!", notes: "بهتر + ه" },
    { id: "34.p.tehran-bozorgtarin-shahr-e-iran", type: "phrases", fa: "تهران بزرگ‌ترین شهر ایران هست.", pin: "Tehran bozorgtarin shahr-e Iran hast.", en: "Tehran is the biggest city in Iran.", notes: "superlative + شهرِ ایران" },
    { id: "34.p.yazd-ghashangtarin-shahr-e-iran", type: "phrases", fa: "یزد قشنگ‌ترین شهر ایران هست.", pin: "Yazd ghashangtarin shahr-e Iran hast.", en: "Yazd is the most beautiful city in Iran.", notes: "قشنگ + ترین" },
    { id: "34.p.fesenjoon-khoshmazzetarin-ghaza", type: "phrases", fa: "فسنجون خوشمزه‌ترین غذای ایرانی هست.", pin: "Fesenjoon khoshmazzetarin ghazā-ye Irāni hast.", en: "Fesenjoon is the tastiest Iranian food.", notes: "خوشمزه + ترین + غذایِ ایرانی" },
    { id: "34.p.to-behtarin-maman-e-donya-hasti", type: "phrases", fa: "تو بهترین مامان دنیا هستی.", pin: "To behtarin māmān-e donyā hasti.", en: "You are the best mother in the world.", notes: "دنیا, not جهان — this is emotional" },
    { id: "34.p.sedaye-khandash-tu-saram", type: "phrases", fa: "صدای خنده‌اش تو سرم می‌پیچه.", pin: "Sedāye khandash tu saram mipicheh.", en: "The sound of her laughter echoes in my head.", notes: "the teacher's example of می‌پیچه" },
    // Story
    { id: "34.s.yad-dasht-haye-man", type: "story", fa: "یادداشت‌هایِ من", pin: "Yād dāsht hāye man", en: "My notes", notes: "یادداشت‌ها + ezāfe + من" },
    { id: "34.s.emrooz-jome-ast", type: "story", fa: "امروز جُمعه اَست.", pin: "Emrooz jom'e ast.", en: "Today is Friday.", notes: "است = written 'is'; spoken جمعه‌ست" },
    { id: "34.s.hava-kheili-behtar-az-dirooz-ast", type: "story", fa: "هَوا خیلی بِهتَر از دیروز است.", pin: "Havā kheili behtar az dirooz ast.", en: "The weather is much better than yesterday.", notes: "بهتر از = better than" },
    { id: "34.s.sobh-e-zood-bidar-misham-va", type: "story", fa: "صُبحِ زود بیدار میشم و صُبحانه دُرُست می‌کنم.", pin: "Sobh-e zood bidār misham va sobhāneh dorost mikonam.", en: "I wake up early and make breakfast.", notes: "بیدار شدن + درست کردن" },
    { id: "34.s.halim-nan-e-dagh-va-chay", type: "story", fa: "حَلیم، نانِ داغ و چای.", pin: "Halim, nān-e dāgh va chāy.", en: "Halim, hot bread and tea.", notes: "نانِ داغ = hot bread" },
    { id: "34.s.booye-halim-va-darchin-dar", type: "story", fa: "بویِ حَلیم و دارچین در خانه می‌پیچَد.", pin: "Booye halim va dārchin dar khāneh mipichad.", en: "The smell of halim and cinnamon fills the house.", notes: "بو می‌پیچه = the smell spreads" },
    { id: "34.s.amma-khaneh-saket-ast", type: "story", fa: "امّا خانه ساکِت اَست.", pin: "Ammā khāneh sāket ast.", en: "But the house is quiet.", notes: "امّا = but" },
    { id: "34.s.bachcheh-ha-hanooz-khab-hastand", type: "story", fa: "بَچّه‌ها هَنوز خواب هَستَند.", pin: "Bachcheh hā hanooz khāb hastand.", en: "The children are still asleep.", notes: "هنوز + خواب هستند" },
    { id: "34.s.siavash-ham", type: "story", fa: "سیاوَش هَم.", pin: "Siāvash ham.", en: "Siavash too.", notes: "هم = too, also" },
    { id: "34.s.kam-kam-baraye-raftan-amadeh", type: "story", fa: "کَم کَم برایِ رفتن آماده می‌شَوَم.", pin: "Kam kam barāye raftan āmādeh mishavam.", en: "Little by little I get ready to leave.", notes: "کم کم + برای رفتن + آماده شدن" },
    { id: "34.s.man-kheili-khoshhalam-chun-jome", type: "story", fa: "مَن خیلی خوشحالَم چون جُمعه‌ها کِلاسِ رَقص دارَم.", pin: "Man kheili khoshhālam chun jom'e hā kelās-e raghs dāram.", en: "I am very happy because on Fridays I have a dance class.", notes: "چون = because" },
    { id: "34.s.jome-behtarin-rooz-e-hafteh-ast", type: "story", fa: "جُمعه بِهتَرین روزِ هَفته اَست.", pin: "Jom'e behtarin rooz-e hafteh ast.", en: "Friday is the best day of the week.", notes: "بهترین + روزِ هفته" },
    { id: "34.s.hamin", type: "story", fa: "هَمین.", pin: "Hamin.", en: "That's it.", notes: "هم + این" },
  ],
});
