// Session 35: where things are.
// Item ids are permanent. Never change or reuse one; add new items with new ids.
F.lesson({
  id: "35",
  label: "Session 35",
  title: "Where things are",
  summary: "where things are: prepositions of place, the kitchen, برداشتن / گذاشتن, directions, geography, قرار",
  notes: "ALEX-SESSION-35_formatted.md",
  items: [
    // Vocabulary
    { id: "35.v.bala", type: "vocabulary", fa: "بالا", pin: "bālā", en: "up", notes: "ب-ا-ل-ا",
      examples: [
        { fa: "زندگی بالا و پایین داره.", pin: "Zendegi bālā-o pāyin dāreh.", en: "Life has its ups and downs.", source: "phrase:35" },
      ] },
    { id: "35.v.payin", type: "vocabulary", fa: "پایین", pin: "pāyin", en: "down", notes: "پ-ا-ی-ی-ن",
      examples: [
        { fa: "زندگی بالا و پایین داره.", pin: "Zendegi bālā-o pāyin dāreh.", en: "Life has its ups and downs.", source: "phrase:35" },
      ] },
    { id: "35.v.rast", type: "vocabulary", fa: "راست", pin: "rāst", en: "right", notes: "ر-ا-س-ت — also means true, straight",
      examples: [
        { fa: "یخچال سمت راست در هست و اجاق کنار یخچاله.", pin: "Yakhchāl samt-e rāst-e dar hast va ojāgh kenār-e yakhchāl-eh.", en: "The fridge is on the right side of the door, and the stove is next to the fridge.", source: "story:st-35-2" },
      ] },
    { id: "35.v.chap", type: "vocabulary", fa: "چپ", pin: "chap", en: "left", notes: "چ-پ" },
    { id: "35.v.samt-e-chap", type: "vocabulary", fa: "سمتِ چپ", pin: "samt-e chap", en: "left side", notes: "سمت (side) + ezāfe + چپ" },
    { id: "35.v.samt-e-rast", type: "vocabulary", fa: "سمتِ راست", pin: "samt-e rāst", en: "right side", notes: "سمت (side) + ezāfe + راست",
      examples: [
        { fa: "یخچال سمت راست در هست و اجاق کنار یخچاله.", pin: "Yakhchāl samt-e rāst-e dar hast va ojāgh kenār-e yakhchāl-eh.", en: "The fridge is on the right side of the door, and the stove is next to the fridge.", source: "story:st-35-2" },
      ] },
    { id: "35.v.ghaza", type: "vocabulary", fa: "غذا", pin: "ghazā", en: "food", notes: "غ-ذ-ا",
      examples: [
        { fa: "غذا کجا هست؟", pin: "Ghazā kojā hast?", en: "Where is the food?", source: "phrase:35" },
        { fa: "من به غذا‌ت دست نمی‌زنم", pin: "man be ghazāt dast nemizanam", en: "I won't touch your food", source: "phrase:33" },
        { fa: "غذا خیلی خوشمزه و تازه هست.", pin: "Ghazā kheili khoshmazeh o tāzeh hast.", en: "The food is very tasty and fresh.", source: "story:st-2425-1" },
        { fa: "اون داره تو آشپزخونه غذا درست می‌کنه", pin: "oon dāreh too āshpazkhooneh ghazā dorost mikoneh", en: "He/she is cooking in the kitchen", source: "phrase:31" },
      ] },
    { id: "35.v.yakh", type: "vocabulary", fa: "یخ", pin: "yakh", en: "ice", notes: "ی-خ" },
    { id: "35.v.yakhchal", type: "vocabulary", fa: "یخچال", pin: "yakhchāl", en: "fridge, refrigerator", notes: "یخ (ice) + چال (pit) — an 'ice pit'",
      examples: [
        { fa: "غذا توی یخچاله.", pin: "Ghazā tuye yakhchāl-eh.", en: "The food is in the fridge.", source: "phrase:35" },
        { fa: "علی کلید رو برمی‌داره و می‌گه: «دیگه هیچ‌وقت کلیدم رو روی یخچال نمی‌ذارم!»", pin: "Ali kelid ro barmidāreh va migeh: \"Dige hichvaght kelidam ro ruye yakhchāl nemizāram!\"", en: "Ali picks up the key and says: \"I'll never put my key on the fridge again!\"", source: "story:st-35-1" },
        { fa: "تخم مرغ‌ها توی یخچال نیستند.", pin: "Tokhm-e morgh hā tuye yakhchāl nistand.", en: "The eggs are not in the fridge.", source: "phrase:35" },
        { fa: "میوه‌ها توی یخچال بودند.", pin: "Mive hā tuye yakhchāl boodand.", en: "(But) the fruits were in the fridge.", source: "phrase:35" },
      ] },
    { id: "35.v.kif", type: "vocabulary", fa: "کیف", pin: "kif", en: "bag", notes: "ک-ی-ف — کیفش = his/her bag",
      examples: [
        { fa: "کیفش توی ماشین نبود.", pin: "Kifesh tuye māshin nabood.", en: "His bag was not in the car.", source: "phrase:35" },
        { fa: "سارا می‌گه: «توی کیفت چی؟»", pin: "Sārā migeh: \"Tuye kifet chi?\"", en: "Sara says: \"What about in your bag?\"", source: "story:st-35-1" },
        { fa: "این کیف مال اونه", pin: "in kif māl-e oon-e", en: "This bag is hers/his", source: "phrase:29" },
        { fa: "علی کیفش رو برمی‌داره. کلید توی کیف هم نیست!", pin: "Ali kifesh ro barmidāreh. Kelid tuye kif ham nist!", en: "Ali picks up his bag. The key isn't in the bag either!", source: "story:st-35-1" },
      ] },
    { id: "35.v.joorab", type: "vocabulary", fa: "جوراب", pin: "joorāb", en: "sock", notes: "ج-و-ر-ا-ب — plural جوراب‌ها",
      examples: [
        { fa: "جوراب‌های من کجا هستند؟", pin: "Joorāb hāye man kojā hastand?", en: "Where are my socks?", source: "phrase:35" },
        { fa: "زیر کاناپه یه جوراب و یه کتاب هست، ولی کلید نیست.", pin: "Zir-e kānāpeh ye joorāb o ye ketāb hast, vali kelid nist.", en: "Under the couch there's a sock and a book, but no key.", source: "story:st-35-1" },
        { fa: "جوراب‌هام کجان؟", pin: "Joorāb hām kojān(d)?", en: "Where are my socks? (spoken)", source: "phrase:35" },
      ] },
    { id: "35.v.komod", type: "vocabulary", fa: "کمد", pin: "komod", en: "wardrobe, chest of drawers", notes: "ک-م-د",
      examples: [
        { fa: "لباس‌هام توی کمدند.", pin: "Lebās hām tuye komod-and.", en: "My clothes are in the wardrobe.", source: "phrase:35" },
        { fa: "توی کمد.", pin: "Tuye komod.", en: "Inside the wardrobe.", source: "phrase:35" },
      ] },
    { id: "35.v.kelid-kilid", type: "vocabulary", fa: "کلید", pin: "kelid / kilid", en: "key", notes: "ک-ل-ی-د — کلیدم = my key",
      examples: [
        { fa: "تو می‌دونی کلیدم کجاست؟", pin: "To midooni kelidam kojāst?", en: "Do you know where my key is?", source: "phrase:35" },
        { fa: "کلید روی میز نیست.", pin: "Kelid ruye miz nist.", en: "The key isn't on the table.", source: "story:st-35-1" },
        { fa: "نمی‌دونم کلیدت کجاست!", pin: "Nemidoonam kelidet kojāst!", en: "I don't know where your key is!", source: "phrase:35" },
        { fa: "ببین! کلیدت روی میزه.", pin: "Bebin! Kelidet ruye miz-eh.", en: "Look! Your key is on the table.", source: "phrase:35" },
      ] },
    { id: "35.v.dasteh", type: "vocabulary", fa: "دسته", pin: "dasteh", en: "handle", notes: "د-س-ت-ه — also a bunch, a bundle" },
    { id: "35.v.dasteh-kelid", type: "vocabulary", fa: "دسته‌کلید", pin: "dasteh kelid", en: "keychain, bunch of keys", notes: "دسته (bunch) + کلید (key)" },
    { id: "35.v.dasteh-gol", type: "vocabulary", fa: "دسته‌گل", pin: "dasteh gol", en: "bouquet", notes: "دسته (bunch) + گل (flower)" },
    { id: "35.v.miz", type: "vocabulary", fa: "میز", pin: "miz", en: "table", notes: "م-ی-ز",
      examples: [
        { fa: "ببین! کلیدت روی میزه.", pin: "Bebin! Kelidet ruye miz-eh.", en: "Look! Your key is on the table.", source: "phrase:35" },
        { fa: "سارا می‌گه: «نمی‌دونم! روی میز نیست؟»", pin: "Sārā migeh: \"Nemidoonam! Ruye miz nist?\"", en: "Sara says: \"I don't know! Isn't it on the table?\"", source: "story:st-35-1" },
        { fa: "کتاب روی میزه.", pin: "Ketāb ruye miz-eh.", en: "The book is on the table.", source: "phrase:35" },
        { fa: "یه میز در مرکز اتاق قرار دارد.", pin: "Ye miz dar markaz-e otāgh gharār dārad.", en: "There is a table in the center of the room.", source: "phrase:35" },
      ] },
    { id: "35.v.lebas", type: "vocabulary", fa: "لباس", pin: "lebās", en: "clothes", notes: "ل-ب-ا-س — لباس‌هات = your clothes",
      examples: [
        { fa: "لباس‌هات روی تخت هستند.", pin: "Lebās hāt ruye takht hastand.", en: "Your clothes are on the bed.", source: "phrase:35" },
        { fa: "لباس‌هام روی تخت‌اند.", pin: "Lebās hām ruye takht-and.", en: "My clothes are on the bed.", source: "phrase:35" },
        { fa: "لباس‌هام توی کمدند.", pin: "Lebās hām tuye komod-and.", en: "My clothes are in the wardrobe.", source: "phrase:35" },
      ] },
    { id: "35.v.mobayl-mobil", type: "vocabulary", fa: "موبایل", pin: "mobāyl / mobil", en: "mobile phone", notes: "from English — موبایلم = my phone",
      examples: [
        { fa: "موبایلم کجا بود؟", pin: "Mobāylam kojā bood?", en: "Where was my phone?", source: "phrase:35" },
        { fa: "سارا می‌خنده: «موبایلت توی دستته! و کلیدت روی یخچاله.»", pin: "Sārā mikhandeh: \"Mobāylet tuye dastet-eh! Va kelidet ruye yakhchāl-eh.\"", en: "Sara laughs: \"Your phone is in your hand! And your key is on the fridge.\"", source: "story:st-35-1" },
        { fa: "موبایلت زنگ می‌زنه", pin: "mobāilet zang mizaneh", en: "Your mobile is ringing", source: "phrase:33" },
        { fa: "«موبایلم کجاست؟ موبایلم هم نیست!»", pin: "\"Mobāylam kojāst? Mobāylam ham nist!\"", en: "\"Where's my phone? My phone's gone too!\"", source: "story:st-35-1" },
      ] },
    { id: "35.v.sandali", type: "vocabulary", fa: "صندلی", pin: "sandali", en: "chair", notes: "ص-ن-د-ل-ی",
      examples: [
        { fa: "اینجا، روی این صندلی.", pin: "Injā, ruye in sandali.", en: "Here, on this chair.", source: "phrase:35" },
        { fa: "جلوی پنجره یه میز کوچیک و دو تا صندلی هست.", pin: "Jeloye panjereh ye miz-e koochik o do tā sandali hast.", en: "In front of the window there's a small table and two chairs.", source: "story:st-35-2" },
        { fa: "گربه زیر صندلی بود.", pin: "Gorbeh zir-e sandali bood.", en: "The cat was under the chair.", source: "phrase:35" },
      ] },
    { id: "35.v.ghablameh", type: "vocabulary", fa: "قابلمه", pin: "ghāblameh", en: "pot, saucepan", notes: "ق-ا-ب-ل-م-ه",
      examples: [
        { fa: "قابلمه روی اجاقه.", pin: "Ghāblameh ruye ojāgh-eh.", en: "The pot is on the stove.", source: "phrase:35" },
        { fa: "روی گاز همیشه یه قابلمه هست.", pin: "Ruye gāz hamisheh ye ghāblameh hast.", en: "There's always a pot on the stove.", source: "story:st-35-2" },
      ] },
    { id: "35.v.ojagh", type: "vocabulary", fa: "اجاق", pin: "ojāgh", en: "stove, cooker", notes: "ا-ج-ا-ق",
      examples: [
        { fa: "قابلمه روی اجاقه.", pin: "Ghāblameh ruye ojāgh-eh.", en: "The pot is on the stove.", source: "phrase:35" },
        { fa: "یخچال سمت راست در هست و اجاق کنار یخچاله.", pin: "Yakhchāl samt-e rāst-e dar hast va ojāgh kenār-e yakhchāl-eh.", en: "The fridge is on the right side of the door, and the stove is next to the fridge.", source: "story:st-35-2" },
        { fa: "تابه‌ها توی کابینت، زیر اجاق هستن.", pin: "Tābeh hā tuye kābinet, zir-e ojāgh hastan.", en: "The pans are in the cupboard under the stove.", source: "story:st-35-2" },
      ] },
    { id: "35.v.gaz", type: "vocabulary", fa: "گاز", pin: "gāz", en: "gas; gas stove", notes: "گ-ا-ز — روی گاز = on the stove",
      examples: [
        { fa: "غذا روی گازه.", pin: "Ghazā ruye gāz-eh.", en: "The food is on the stove.", source: "phrase:35" },
        { fa: "روی گاز همیشه یه قابلمه هست.", pin: "Ruye gāz hamisheh ye ghāblameh hast.", en: "There's always a pot on the stove.", source: "story:st-35-2" },
        { fa: "مامانم می‌گه: «ماهی‌تابه رو بردار و روی گاز بذار!»", pin: "Māmānam migeh: \"Māhi-tābeh ro bardār va ruye gāz bezār!\"", en: "My mom says: \"Take the frying pan and put it on the stove!\"", source: "story:st-35-2" },
        { fa: "من ماهی‌تابه رو برمی‌دارم و روی گاز می‌ذارم.", pin: "Man māhi-tābeh ro barmidāram va ruye gāz mizāram.", en: "I take the frying pan and put it on the stove.", source: "story:st-35-2" },
      ] },
    { id: "35.v.ketab", type: "vocabulary", fa: "کتاب", pin: "ketāb", en: "book", notes: "ک-ت-ا-ب",
      examples: [
        { fa: "کتاب روی میزه.", pin: "Ketāb ruye miz-eh.", en: "The book is on the table.", source: "phrase:35" },
        { fa: "این کتاب‌ها رو نمی‌خوام", pin: "in ketāb-hā ro nemikhām", en: "I don't want these books", source: "phrase:28" },
        { fa: "سارا هر روز به کتاب‌فروشی می‌ره و یه کتاب می‌خره.", pin: "Sārā har rooz be ketāb-forushi mireh va ye ketāb mikhareh.", en: "Every day Sara goes to the bookshop and buys a book.", source: "story:st-31-2" },
        { fa: "این کتاب مال منه", pin: "in ketāb māl-e man-e", en: "This book is mine", source: "phrase:29" },
      ] },
    { id: "35.v.kafsh", type: "vocabulary", fa: "کفش", pin: "kafsh", en: "shoe", notes: "ک-ف-ش — کفش‌هات = your shoes",
      examples: [
        { fa: "کفش‌های تو زیر تخت نبودند.", pin: "Kafsh hāye to zir-e takht naboodand.", en: "Your shoes weren't under the bed.", source: "phrase:35" },
        { fa: "این کفش خوشگل‌تره.", pin: "In kafsh khoshgeltar-eh.", en: "This shoe is prettier.", source: "phrase:34" },
        { fa: "کفش‌هات زیر تخت نبودند.", pin: "Kafsh hāt zir-e takht naboodand.", en: "Your shoes weren't under the bed. (spoken)", source: "phrase:35" },
      ] },
    { id: "35.v.mobl", type: "vocabulary", fa: "مبل", pin: "mobl", en: "sofa, armchair", notes: "م-ب-ل",
      examples: [
        { fa: "اونها زیر مبل هستند!", pin: "Oonhā zir-e mobl hastand!", en: "They are under the sofa!", source: "phrase:35" },
      ] },
    { id: "35.v.kanapeh", type: "vocabulary", fa: "کاناپه", pin: "kānāpeh", en: "sofa, couch", notes: "from French canapé",
      examples: [
        { fa: "زیر کاناپه یه جوراب و یه کتاب هست، ولی کلید نیست.", pin: "Zir-e kānāpeh ye joorāb o ye ketāb hast, vali kelid nist.", en: "Under the couch there's a sock and a book, but no key.", source: "story:st-35-1" },
      ] },
    { id: "35.v.zan", type: "vocabulary", fa: "زن", pin: "zan", en: "wife; woman", notes: "ز-ن — زنش = his wife",
      examples: [
        { fa: "علی کنار زنشه.", pin: "Ali kenār-e zanesh-eh.", en: "Ali is next to his wife.", source: "phrase:35" },
        { fa: "اونها زن و شوهرن و سه تا بچه دارن.", pin: "oonhā zan-o shohar-an va se tā bache dāran.", en: "They are husband and wife and have three children.", source: "story:32" },
      ] },
    { id: "35.v.panjereh", type: "vocabulary", fa: "پنجره", pin: "panjereh", en: "window", notes: "پ-ن-ج-ر-ه",
      examples: [
        { fa: "جلوی پنجره یه میز کوچیک و دو تا صندلی هست.", pin: "Jeloye panjereh ye miz-e koochik o do tā sandali hast.", en: "In front of the window there's a small table and two chairs.", source: "story:st-35-2" },
      ] },
    { id: "35.v.ghahveh-joosh", type: "vocabulary", fa: "قهوه‌جوش", pin: "ghahveh joosh", en: "coffee pot, coffee maker", notes: "قهوه (coffee) + جوش (boil)" },
    { id: "35.v.ab-e-joosh", type: "vocabulary", fa: "آب‌جوش", pin: "āb-e joosh", en: "boiling water", notes: "آب (water) + جوش (boil)" },
    { id: "35.v.jooshidan", type: "vocabulary", fa: "جوشیدن", pin: "jooshidan", en: "to boil", notes: "present stem: جوش — می‌جوشه = it's boiling",
      examples: [
        { fa: "آب داره می‌جوشه.", pin: "Āb dāreh mijoosheh.", en: "The water is boiling.", source: "phrase:35" },
        { fa: "کتری روی گازه و آب داره می‌جوشه.", pin: "Ketri ruye gāz-eh va āb dāreh mijoosheh.", en: "The kettle is on the stove and the water is boiling.", source: "story:st-35-2" },
      ] },
    { id: "35.v.mahi-tabeh", type: "vocabulary", fa: "ماهی‌تابه", pin: "māhi-tābeh", en: "frying pan", notes: "ماهی (fish) + تابه (pan)",
      examples: [
        { fa: "مامانم می‌گه: «ماهی‌تابه رو بردار و روی گاز بذار!»", pin: "Māmānam migeh: \"Māhi-tābeh ro bardār va ruye gāz bezār!\"", en: "My mom says: \"Take the frying pan and put it on the stove!\"", source: "story:st-35-2" },
        { fa: "من ماهی‌تابه رو برمی‌دارم و روی گاز می‌ذارم.", pin: "Man māhi-tābeh ro barmidāram va ruye gāz mizāram.", en: "I take the frying pan and put it on the stove.", source: "story:st-35-2" },
      ] },
    { id: "35.v.tabeh", type: "vocabulary", fa: "تابه", pin: "tābeh", en: "pan", notes: "ت-ا-ب-ه",
      examples: [
        { fa: "تابه‌ها توی کابینت، زیر اجاق هستن.", pin: "Tābeh hā tuye kābinet, zir-e ojāgh hastan.", en: "The pans are in the cupboard under the stove.", source: "story:st-35-2" },
      ] },
    { id: "35.v.ghoori", type: "vocabulary", fa: "قوری", pin: "ghoori", en: "teapot", notes: "ق-و-ر-ی — قوریِ چای = teapot",
      examples: [
        { fa: "روی میز یه ظرف میوه و یه قوری هست.", pin: "Ruye miz ye zarf-e miveh o ye ghoori hast.", en: "On the table there's a fruit bowl and a teapot.", source: "story:st-35-2" },
        { fa: "مامانم می‌گه: «توی سبد، کنار قوری.»", pin: "Māmānam migeh: \"Tuye sabad, kenār-e ghoori.\"", en: "My mom says: \"In the basket, next to the teapot.\"", source: "story:st-35-2" },
      ] },
    { id: "35.v.ketri", type: "vocabulary", fa: "کتری", pin: "ketri", en: "kettle", notes: "ک-ت-ر-ی",
      examples: [
        { fa: "کتری روی گازه و آب داره می‌جوشه.", pin: "Ketri ruye gāz-eh va āb dāreh mijoosheh.", en: "The kettle is on the stove and the water is boiling.", source: "story:st-35-2" },
      ] },
    { id: "35.v.sabad-e-miveh", type: "vocabulary", fa: "سبدِ میوه", pin: "sabad-e miveh", en: "fruit basket", notes: "سبد (basket) + ezāfe + میوه" },
    { id: "35.v.zarf-e-miveh", type: "vocabulary", fa: "ظرفِ میوه", pin: "zarf-e miveh", en: "fruit bowl", notes: "ظرف (dish) + ezāfe + میوه",
      examples: [
        { fa: "روی میز یه ظرف میوه و یه قوری هست.", pin: "Ruye miz ye zarf-e miveh o ye ghoori hast.", en: "On the table there's a fruit bowl and a teapot.", source: "story:st-35-2" },
      ] },
    { id: "35.v.botri-ye-ab", type: "vocabulary", fa: "بطریِ آب", pin: "botri-ye āb", en: "water bottle", notes: "بطری (bottle) + ezāfe + آب" },
    { id: "35.v.jabeh", type: "vocabulary", fa: "جعبه", pin: "ja'beh", en: "box", notes: "ج-ع-ب-ه" },
    { id: "35.v.jabe-ye-tokhm-e-morgh", type: "vocabulary", fa: "جعبه‌ی تخم مرغ", pin: "ja'be-ye tokhm-e morgh", en: "egg box", notes: "جعبه + ezāfe + تخم مرغ" },
    { id: "35.v.satl-e-zobaleh", type: "vocabulary", fa: "سطلِ زباله", pin: "satl-e zobāleh", en: "trash can, rubbish bin", notes: "سطل (bucket) + ezāfe + زباله (rubbish)" },
    { id: "35.v.satl-e-ashghal", type: "vocabulary", fa: "سطلِ آشغال", pin: "satl-e āshghāl", en: "trash can (everyday word)", notes: "سطل (bucket) + ezāfe + آشغال (junk)",
      examples: [
        { fa: "سطل آشغال زیر میزه.", pin: "Satl-e āshghāl zir-e miz-eh.", en: "The bin is under the table.", source: "story:st-35-2" },
      ] },
    { id: "35.v.ard", type: "vocabulary", fa: "آرد", pin: "ārd", en: "flour", notes: "آ-ر-د" },
    { id: "35.v.livan-e-ab", type: "vocabulary", fa: "لیوانِ آب", pin: "livān-e āb", en: "glass of water", notes: "لیوان (glass) + ezāfe + آب" },
    { id: "35.v.sofreh", type: "vocabulary", fa: "سفره", pin: "sofreh", en: "tablecloth, spread", notes: "the cloth a meal is laid on — سفره‌ی هفت‌سین" },
    { id: "35.v.naghsheh", type: "vocabulary", fa: "نقشه", pin: "naghsheh", en: "map", notes: "ن-ق-ش-ه — also a plan" },
    { id: "35.v.joghrafia", type: "vocabulary", fa: "جغرافیا", pin: "joghrāfiā", en: "geography", notes: "ج-غ-ر-ا-ف-ی-ا" },
    { id: "35.v.joghrafiayi", type: "vocabulary", fa: "جغرافیایی", pin: "joghrāfiāyi", en: "geographic", notes: "جغرافیا + یی (adjective ending)" },
    { id: "35.v.jahat-haye-joghrafiayi", type: "vocabulary", fa: "جهت‌های جغرافیایی", pin: "jahat hāye joghrāfiāyi", en: "geographic directions", notes: "جهت (direction) + ها + ezāfe + جغرافیایی" },
    { id: "35.v.shomal", type: "vocabulary", fa: "شمال", pin: "shomāl", en: "north", notes: "ش-م-ا-ل" },
    { id: "35.v.jonoob", type: "vocabulary", fa: "جنوب", pin: "jonoob", en: "south", notes: "ج-ن-و-ب",
      examples: [
        { fa: "خلیج فارس در جنوب ایران قرار دارد.", pin: "Khalij-e Fārs dar jonoob-e Irān gharār dārad.", en: "The Persian Gulf is located in the south of Iran.", source: "phrase:35" },
      ] },
    { id: "35.v.shargh", type: "vocabulary", fa: "شرق", pin: "shargh", en: "east", notes: "ش-ر-ق" },
    { id: "35.v.gharb", type: "vocabulary", fa: "غرب", pin: "gharb", en: "west", notes: "غ-ر-ب" },
    { id: "35.v.shomal-e-sharghi", type: "vocabulary", fa: "شمالِ شرقی", pin: "shomāl-e sharghi", en: "northeast", notes: "شمال + ezāfe + شرق + ی" },
    { id: "35.v.jonoob-e-sharghi", type: "vocabulary", fa: "جنوبِ شرقی", pin: "jonoob-e sharghi", en: "southeast", notes: "جنوب + ezāfe + شرق + ی" },
    { id: "35.v.shomal-e-gharbi", type: "vocabulary", fa: "شمالِ غربی", pin: "shomāl-e gharbi", en: "northwest", notes: "شمال + ezāfe + غرب + ی" },
    { id: "35.v.jonoob-e-gharbi", type: "vocabulary", fa: "جنوبِ غربی", pin: "jonoob-e gharbi", en: "southwest", notes: "جنوب + ezāfe + غرب + ی" },
    { id: "35.v.keshvar", type: "vocabulary", fa: "کشور", pin: "keshvar", en: "country", notes: "ک-ش-و-ر — کشورهای همسایه = neighbouring countries",
      examples: [
        { fa: "کشورهای همسایه‌ی ایران", pin: "Keshvar hāye hamsāye-ye Irān", en: "Iran's neighbouring countries", source: "phrase:35" },
      ] },
    { id: "35.v.gharar", type: "vocabulary", fa: "قرار", pin: "gharār", en: "appointment, meeting, date", notes: "ق-ر-ا-ر",
      examples: [
        { fa: "من قرار دارم.", pin: "Man gharār dāram.", en: "I have an appointment.", source: "phrase:35" },
        { fa: "علی ساعت نه و ربع به قرارش می‌رسه.", pin: "Ali sāat-e noh-o rob' be gharāresh mireseh.", en: "Ali gets to his meeting at a quarter past nine.", source: "story:st-35-1" },
        { fa: "ما با هم قرار داریم.", pin: "Mā bā ham gharār dārim.", en: "We're meeting. / We have a date.", source: "phrase:35" },
        { fa: "یه میز در مرکز اتاق قرار دارد.", pin: "Ye miz dar markaz-e otāgh gharār dārad.", en: "There is a table in the center of the room.", source: "phrase:35" },
      ] },
    { id: "35.v.gharar-e-kari", type: "vocabulary", fa: "قرارِ کاری", pin: "gharār-e kāri", en: "work appointment, business meeting", notes: "قرار + ezāfe + کار + ی",
      examples: [
        { fa: "من قرار کاری دارم.", pin: "Man gharār-e kāri dāram.", en: "I have a work appointment / a business meeting.", source: "phrase:35" },
        { fa: "علی امروز ساعت نه قرار کاری داره.", pin: "Ali emrooz sāat-e noh gharār-e kāri dāreh.", en: "Ali has a business meeting at nine today.", source: "story:st-35-1" },
      ] },
    { id: "35.v.bigharar", type: "vocabulary", fa: "بی‌قرار", pin: "bigharār", en: "restless, fidgety; anxious", notes: "بی (without) + قرار (rest, calm)",
      examples: [
        { fa: "بچه خیلی بی‌قرار هست.", pin: "Bacheh kheili bigharār hast.", en: "The kid is very fidgety.", source: "phrase:35" },
        { fa: "مامانم خیلی بی‌قرار هست، من نگرانش هستم.", pin: "Māmānam kheili bigharār hast, man negarānesh hastam.", en: "My mom is really anxious, and I'm worried about her.", source: "phrase:35" },
      ] },
    { id: "35.v.gharar-dashtan", type: "vocabulary", fa: "قرار داشتن", pin: "gharār dāshtan", en: "to be located, to be situated", notes: "قرار + داشتن — formal: قرار دارد",
      examples: [
        { fa: "من قرار دارم.", pin: "Man gharār dāram.", en: "I have an appointment.", source: "phrase:35" },
        { fa: "ما با هم قرار داریم.", pin: "Mā bā ham gharār dārim.", en: "We're meeting. / We have a date.", source: "phrase:35" },
        { fa: "یه میز در مرکز اتاق قرار دارد.", pin: "Ye miz dar markaz-e otāgh gharār dārad.", en: "There is a table in the center of the room.", source: "phrase:35" },
        { fa: "ایران در خاورمیانه قرار دارد.", pin: "Irān dar khāvar-e miāneh gharār dārad.", en: "Iran is located in the Middle East.", source: "phrase:35" },
      ] },
    { id: "35.v.markaz", type: "vocabulary", fa: "مرکز", pin: "markaz", en: "center", notes: "م-ر-ک-ز",
      examples: [
        { fa: "یه میز در مرکز اتاق قرار دارد.", pin: "Ye miz dar markaz-e otāgh gharār dārad.", en: "There is a table in the center of the room.", source: "phrase:35" },
        { fa: "مرکز استان فارس شیراز هست.", pin: "Markaz-e ostān-e Fārs Shirāz hast.", en: "The center of Fars Province is Shiraz.", source: "phrase:35" },
      ] },
    { id: "35.v.markaz-e-shahr", type: "vocabulary", fa: "مرکزِ شهر", pin: "markaz-e shahr", en: "city center", notes: "مرکز + ezāfe + شهر" },
    { id: "35.v.otagh", type: "vocabulary", fa: "اتاق", pin: "otāgh", en: "room", notes: "ا-ت-ا-ق",
      examples: [
        { fa: "یه میز در مرکز اتاق قرار دارد.", pin: "Ye miz dar markaz-e otāgh gharār dārad.", en: "There is a table in the center of the room.", source: "phrase:35" },
        { fa: "در شیراز، سارا یه اتاق در یه مهمون‌خونه‌ی قدیمی اجاره می‌کنه.", pin: "Dar Shirāz, Sārā ye otāgh dar ye mehmoon-khoone-ye ghadimi ejāreh mikoneh.", en: "In Shiraz, Sara rents a room in an old guesthouse.", source: "story:st-31-2" },
        { fa: "اتاق رو رنگ بزن", pin: "otāgh ro rang bezan", en: "Paint the room", source: "phrase:33" },
        { fa: "اتاق نشیمن رو توصیف کن.", pin: "Otāgh-e neshiman ro tosif kon.", en: "Describe the sitting room.", source: "phrase:35" },
      ] },
    { id: "35.v.otagh-e-neshiman", type: "vocabulary", fa: "اتاقِ نشیمن", pin: "otāgh-e neshiman", en: "sitting room, living room", notes: "اتاق + ezāfe + نشیمن (sitting) — from نشستن",
      examples: [
        { fa: "اتاق نشیمن رو توصیف کن.", pin: "Otāgh-e neshiman ro tosif kon.", en: "Describe the sitting room.", source: "phrase:35" },
      ] },
    { id: "35.v.khavar-e-mianeh", type: "vocabulary", fa: "خاورمیانه", pin: "khāvar-e miāneh", en: "the Middle East", notes: "خاور (east) + میانه (middle)",
      examples: [
        { fa: "ایران در خاورمیانه قرار دارد.", pin: "Irān dar khāvar-e miāneh gharār dārad.", en: "Iran is located in the Middle East.", source: "phrase:35" },
      ] },
    { id: "35.v.hotel", type: "vocabulary", fa: "هتل", pin: "hotel", en: "hotel", notes: "from French hôtel",
      examples: [
        { fa: "هتل نزدیک ساحل قرار دارد.", pin: "Hotel nazdik-e sāhel gharār dārad.", en: "The hotel is located near the beach.", source: "phrase:35" },
      ] },
    { id: "35.v.sahel", type: "vocabulary", fa: "ساحل", pin: "sāhel", en: "beach, coast", notes: "س-ا-ح-ل",
      examples: [
        { fa: "هتل نزدیک ساحل قرار دارد.", pin: "Hotel nazdik-e sāhel gharār dārad.", en: "The hotel is located near the beach.", source: "phrase:35" },
      ] },
    { id: "35.v.khalij-e-fars", type: "vocabulary", fa: "خلیج فارس", pin: "khalij-e Fārs", en: "the Persian Gulf", notes: "خلیج (gulf) + ezāfe + فارس",
      examples: [
        { fa: "خلیج فارس در جنوب ایران قرار دارد.", pin: "Khalij-e Fārs dar jonoob-e Irān gharār dārad.", en: "The Persian Gulf is located in the south of Iran.", source: "phrase:35" },
      ] },
    { id: "35.v.ostan", type: "vocabulary", fa: "استان", pin: "ostān", en: "province", notes: "ا-س-ت-ا-ن",
      examples: [
        { fa: "ایران سی و یک استان دارد.", pin: "Irān si-o-yek ostān dārad.", en: "Iran has thirty-one provinces.", source: "phrase:35" },
        { fa: "مرکز استان فارس شیراز هست.", pin: "Markaz-e ostān-e Fārs Shirāz hast.", en: "The center of Fars Province is Shiraz.", source: "phrase:35" },
      ] },
    { id: "35.v.paytakht", type: "vocabulary", fa: "پایتخت", pin: "pāytakht", en: "capital (city)", notes: "پای (foot) + تخت (throne)",
      examples: [
        { fa: "تهران پایتخت ایران هست.", pin: "Tehrān pāytakht-e Irān hast.", en: "Tehran is the capital of Iran.", source: "phrase:35" },
      ] },
    { id: "35.v.tosif-kardan", type: "vocabulary", fa: "توصیف کردن", pin: "tosif kardan", en: "to describe", notes: "توصیف (description) + کردن",
      examples: [
        { fa: "اتاق نشیمن رو توصیف کن.", pin: "Otāgh-e neshiman ro tosif kon.", en: "Describe the sitting room.", source: "phrase:35" },
      ] },
    { id: "35.v.bardashtan", type: "vocabulary", fa: "برداشتن", pin: "bardāshtan", en: "to pick up, to take, to remove", notes: "بر (up) + داشتن — present stem: بردار",
      examples: [
        { fa: "علی کیفش رو برمی‌داره. کلید توی کیف هم نیست!", pin: "Ali kifesh ro barmidāreh. Kelid tuye kif ham nist!", en: "Ali picks up his bag. The key isn't in the bag either!", source: "story:st-35-1" },
        { fa: "مامانم می‌گه: «ماهی‌تابه رو بردار و روی گاز بذار!»", pin: "Māmānam migeh: \"Māhi-tābeh ro bardār va ruye gāz bezār!\"", en: "My mom says: \"Take the frying pan and put it on the stove!\"", source: "story:st-35-2" },
        { fa: "من ماهی‌تابه رو برمی‌دارم و روی گاز می‌ذارم.", pin: "Man māhi-tābeh ro barmidāram va ruye gāz mizāram.", en: "I take the frying pan and put it on the stove.", source: "story:st-35-2" },
        { fa: "علی کلید رو برمی‌داره و می‌گه: «دیگه هیچ‌وقت کلیدم رو روی یخچال نمی‌ذارم!»", pin: "Ali kelid ro barmidāreh va migeh: \"Dige hichvaght kelidam ro ruye yakhchāl nemizāram!\"", en: "Ali picks up the key and says: \"I'll never put my key on the fridge again!\"", source: "story:st-35-1" },
      ] },
    { id: "35.v.gozashtan", type: "vocabulary", fa: "گذاشتن", pin: "gozāshtan", en: "to put, to place, to set down", notes: "present stem: گذار — spoken ذار",
      examples: [
        { fa: "علی کلید رو برمی‌داره و می‌گه: «دیگه هیچ‌وقت کلیدم رو روی یخچال نمی‌ذارم!»", pin: "Ali kelid ro barmidāreh va migeh: \"Dige hichvaght kelidam ro ruye yakhchāl nemizāram!\"", en: "Ali picks up the key and says: \"I'll never put my key on the fridge again!\"", source: "story:st-35-1" },
        { fa: "مامانم می‌گه: «ماهی‌تابه رو بردار و روی گاز بذار!»", pin: "Māmānam migeh: \"Māhi-tābeh ro bardār va ruye gāz bezār!\"", en: "My mom says: \"Take the frying pan and put it on the stove!\"", source: "story:st-35-2" },
        { fa: "من ماهی‌تابه رو برمی‌دارم و روی گاز می‌ذارم.", pin: "Man māhi-tābeh ro barmidāram va ruye gāz mizāram.", en: "I take the frying pan and put it on the stove.", source: "story:st-35-2" },
      ] },
    // Grammar
    { id: "35.g.tu-tuye", type: "grammar", fa: "تو / توی", pin: "tu / tuye", en: "in, inside", notes: "bare تو; before a noun توی — توی یخچال (in the fridge)" },
    { id: "35.g.ru-ruye", type: "grammar", fa: "رو / روی", pin: "ru / ruye", en: "on, on top of", notes: "bare رو; before a noun روی — روی میز (on the table)" },
    { id: "35.g.zir-zir-e", type: "grammar", fa: "زیر / زیرِ", pin: "zir / zir-e", en: "under, beneath", notes: "+ ezāfe before a noun — زیرِ صندلی" },
    { id: "35.g.kenar-kenar-e", type: "grammar", fa: "کنار / کنارِ", pin: "kenār / kenār-e", en: "beside, next to", notes: "+ ezāfe before a noun — کنارِ من" },
    { id: "35.g.jeloye", type: "grammar", fa: "جلوی", pin: "jeloye", en: "in front of", notes: "جلو + ی (ezāfe before a noun)" },
    { id: "35.g.posht-e", type: "grammar", fa: "پشتِ", pin: "posht-e", en: "behind", notes: "پشت (back) + ezāfe" },
    { id: "35.g.beyn-e-mian-e", type: "grammar", fa: "بینِ / میانِ", pin: "beyn-e / miān-e", en: "between", notes: "بین is everyday; میان is more formal" },
    { id: "35.g.balaye", type: "grammar", fa: "بالای", pin: "bālāye", en: "above", notes: "بالا (up) + ی (ezāfe)" },
    { id: "35.g.payin-e", type: "grammar", fa: "پایینِ", pin: "pāyin-e", en: "below", notes: "پایین (down) + ezāfe" },
    { id: "35.g.kojan-d", type: "grammar", fa: "کجان؟", pin: "kojān(d)?", en: "where are they?", notes: "کجا + هستند → کجان (spoken)" },
    { id: "35.g.and-an", type: "grammar", fa: "ـند / ـن", pin: "-and / -an", en: "they are (short form)", notes: "هستند shortened after a word — لباس‌هام روی تخت‌اند" },
    { id: "35.g.joorab-haye-man-joorab-ham", type: "grammar", fa: "جوراب‌های من = جوراب‌هام", pin: "joorāb hāye man = joorāb hām", en: "my socks", notes: "plural + ezāfe + من → plural + ـم" },
    { id: "35.g.kafsh-haye-to-kafsh-hat", type: "grammar", fa: "کفش‌های تو = کفش‌هات", pin: "kafsh hāye to = kafsh hāt", en: "your shoes", notes: "plural + ezāfe + تو → plural + ـت" },
    { id: "35.g.barmidaram", type: "grammar", fa: "برمی‌دارم", pin: "barmidāram", en: "I pick up, I take", notes: "بر + می + دار + م — می goes after بر" },
    { id: "35.g.barnadashtam", type: "grammar", fa: "برنداشتم", pin: "barnadāshtam", en: "I didn't pick up", notes: "بر + ن + داشت + م — ن goes after بر" },
    { id: "35.g.bardar-bardarid", type: "grammar", fa: "بردار / بردارید", pin: "bardār / bardārid", en: "pick it up! take it!", notes: "بر + دار — no بـ in the command" },
    { id: "35.g.barnadar-barnadarid", type: "grammar", fa: "برندار / برندارید", pin: "barnadār / barnadārid", en: "don't pick it up! don't take it!", notes: "بر + ن + دار" },
    { id: "35.g.migozaram-mizaram", type: "grammar", fa: "می‌گذارم / می‌ذارم", pin: "migozāram / mizāram", en: "I put, I place", notes: "written گذار, spoken ذار" },
    { id: "35.g.nemizaram", type: "grammar", fa: "نمی‌ذارم", pin: "nemizāram", en: "I don't put", notes: "نمی + ذار + م" },
    { id: "35.g.nagozashtam-nazashtam", type: "grammar", fa: "نگذاشتم / نذاشتم", pin: "nagozāshtam / nazāshtam", en: "I didn't put", notes: "ن + گذاشت + م — گ often dropped in speech" },
    { id: "35.g.begozar-bezar", type: "grammar", fa: "بگذار / بذار", pin: "begozār / bezār", en: "put! place!", notes: "بـ + گذار — spoken بذار; plural بذارید" },
    { id: "35.g.nagozar-nazar", type: "grammar", fa: "نگذار / نذار", pin: "nagozār / nazār", en: "don't put!", notes: "نـ + گذار — spoken نذار; plural نذارید" },
    { id: "35.g.gharar-darad", type: "grammar", fa: "… قرار دارد", pin: "… gharār dārad", en: "… is located", notes: "[place] + در + [location] + قرار دارد (formal register)" },
    { id: "35.g.i", type: "grammar", fa: "ـی (adjective)", pin: "-i", en: "makes an adjective", notes: "شرق → شرقی، کار → کاری، جغرافیا → جغرافیایی" },
    { id: "35.g.bi", type: "grammar", fa: "بی‌ـ", pin: "bi-", en: "without, -less", notes: "بی + قرار → بی‌قرار (restless)" },
    // Phrases
    { id: "35.p.zendegi-bala-o-payin-dareh", type: "phrases", fa: "زندگی بالا و پایین داره.", pin: "Zendegi bālā-o pāyin dāreh.", en: "Life has its ups and downs.", notes: "بالا و پایین = ups and downs" },
    { id: "35.p.ghaza-koja-hast", type: "phrases", fa: "غذا کجا هست؟", pin: "Ghazā kojā hast?", en: "Where is the food?", notes: "کجا + هست — or کجاست" },
    { id: "35.p.ghaza-tuye-yakhchal-eh", type: "phrases", fa: "غذا توی یخچاله.", pin: "Ghazā tuye yakhchāl-eh.", en: "The food is in the fridge.", notes: "توی + یخچال + ـه (is)" },
    { id: "35.p.tokhm-e-morgh-ha-tuye-yakhchal", type: "phrases", fa: "تخم مرغ‌ها توی یخچال نیستند.", pin: "Tokhm-e morgh hā tuye yakhchāl nistand.", en: "The eggs are not in the fridge.", notes: "نیستند = they are not" },
    { id: "35.p.mive-ha-tuye-yakhchal-boodand", type: "phrases", fa: "میوه‌ها توی یخچال بودند.", pin: "Mive hā tuye yakhchāl boodand.", en: "(But) the fruits were in the fridge.", notes: "بودند = they were" },
    { id: "35.p.kifesh-tuye-mashin-nabood", type: "phrases", fa: "کیفش توی ماشین نبود.", pin: "Kifesh tuye māshin nabood.", en: "His bag was not in the car.", notes: "کیف + ش (his) + نبود" },
    { id: "35.p.joorab-haye-man-koja-hastand", type: "phrases", fa: "جوراب‌های من کجا هستند؟", pin: "Joorāb hāye man kojā hastand?", en: "Where are my socks?", notes: "full form" },
    { id: "35.p.joorab-ham-kojan-d", type: "phrases", fa: "جوراب‌هام کجان؟", pin: "Joorāb hām kojān(d)?", en: "Where are my socks? (spoken)", notes: "spoken form — ـهام + کجان" },
    { id: "35.p.tuye-komod", type: "phrases", fa: "توی کمد.", pin: "Tuye komod.", en: "Inside the wardrobe.", notes: "توی + کمد" },
    { id: "35.p.kelidam-kojast", type: "phrases", fa: "کلیدم کجاست؟", pin: "Kelidam kojāst?", en: "Where is my key?", notes: "کلید + م + کجاست" },
    { id: "35.p.to-midooni-kelidam-kojast", type: "phrases", fa: "تو می‌دونی کلیدم کجاست؟", pin: "To midooni kelidam kojāst?", en: "Do you know where my key is?", notes: "می‌دونی (you know) from دونستن" },
    { id: "35.p.nemidoonam-kelidet-kojast", type: "phrases", fa: "نمی‌دونم کلیدت کجاست!", pin: "Nemidoonam kelidet kojāst!", en: "I don't know where your key is!", notes: "کلید + ت (your)" },
    { id: "35.p.bebin-kelidet-ruye-miz-eh", type: "phrases", fa: "ببین! کلیدت روی میزه.", pin: "Bebin! Kelidet ruye miz-eh.", en: "Look! Your key is on the table.", notes: "ببین (look!) + روی میز + ـه" },
    { id: "35.p.lebas-hat-ruye-takht-hastand", type: "phrases", fa: "لباس‌هات روی تخت هستند.", pin: "Lebās hāt ruye takht hastand.", en: "Your clothes are on the bed.", notes: "لباس‌ها + ت (your)" },
    { id: "35.p.lebas-ham-ruye-takht-and", type: "phrases", fa: "لباس‌هام روی تخت‌اند.", pin: "Lebās hām ruye takht-and.", en: "My clothes are on the bed.", notes: "هستند → ـند after a word" },
    { id: "35.p.lebas-ham-tuye-komod-and", type: "phrases", fa: "لباس‌هام توی کمدند.", pin: "Lebās hām tuye komod-and.", en: "My clothes are in the wardrobe.", notes: "کمد + ـند" },
    { id: "35.p.mobaylam-koja-bood", type: "phrases", fa: "موبایلم کجا بود؟", pin: "Mobāylam kojā bood?", en: "Where was my phone?", notes: "کجا + بود (was)" },
    { id: "35.p.inja-ruye-in-sandali", type: "phrases", fa: "اینجا، روی این صندلی.", pin: "Injā, ruye in sandali.", en: "Here, on this chair.", notes: "روی + این + صندلی" },
    { id: "35.p.ghablameh-ruye-ojagh-eh", type: "phrases", fa: "قابلمه روی اجاقه.", pin: "Ghāblameh ruye ojāgh-eh.", en: "The pot is on the stove.", notes: "روی + اجاق + ـه" },
    { id: "35.p.ghaza-ruye-gaz-eh", type: "phrases", fa: "غذا روی گازه.", pin: "Ghazā ruye gāz-eh.", en: "The food is on the stove.", notes: "گاز = the (gas) stove" },
    { id: "35.p.ketab-ruye-miz-eh", type: "phrases", fa: "کتاب روی میزه.", pin: "Ketāb ruye miz-eh.", en: "The book is on the table.", notes: "روی + میز + ـه" },
    { id: "35.p.gorbeh-zir-e-sandali-bood", type: "phrases", fa: "گربه زیر صندلی بود.", pin: "Gorbeh zir-e sandali bood.", en: "The cat was under the chair.", notes: "زیرِ + صندلی" },
    { id: "35.p.kafsh-haye-to-zir-e-takht", type: "phrases", fa: "کفش‌های تو زیر تخت نبودند.", pin: "Kafsh hāye to zir-e takht naboodand.", en: "Your shoes weren't under the bed.", notes: "نبودند = they weren't" },
    { id: "35.p.kafsh-hat-zir-e-takht-naboodand", type: "phrases", fa: "کفش‌هات زیر تخت نبودند.", pin: "Kafsh hāt zir-e takht naboodand.", en: "Your shoes weren't under the bed. (spoken)", notes: "spoken: کفش‌های تو → کفش‌هات" },
    { id: "35.p.oonha-zir-e-mobl-hastand", type: "phrases", fa: "اونها زیر مبل هستند!", pin: "Oonhā zir-e mobl hastand!", en: "They are under the sofa!", notes: "also زیرِ کاناپه; short form مبل‌اند" },
    { id: "35.p.sara-kenar-e-man-hast", type: "phrases", fa: "سارا کنار من هست.", pin: "Sārā kenār-e man hast.", en: "Sara is next to me.", notes: "کنارِ + من" },
    { id: "35.p.ali-kenar-e-zanesh-eh", type: "phrases", fa: "علی کنار زنشه.", pin: "Ali kenār-e zanesh-eh.", en: "Ali is next to his wife.", notes: "زن + ش (his) + ـه (is)" },
    { id: "35.p.kenar-e-doostam", type: "phrases", fa: "کنار دوستم", pin: "Kenār-e doostam", en: "next to my friend", notes: "کنارِ + دوست + م" },
    { id: "35.p.kenar-e-to", type: "phrases", fa: "کنار تو", pin: "Kenār-e to", en: "next to you", notes: "کنارِ + تو" },
    { id: "35.p.man-kenar-e-to-mishinam", type: "phrases", fa: "من کنار تو می‌شینم.", pin: "Man kenār-e to mishinam.", en: "I sit next to you.", notes: "می‌شینم from نشستن" },
    { id: "35.p.ma-kenar-e-ham-mishinim", type: "phrases", fa: "ما کنار هم می‌شینیم.", pin: "Mā kenār-e ham mishinim.", en: "We sit next to each other.", notes: "هم / همدیگه = each other" },
    { id: "35.p.ab-dareh-mijoosheh", type: "phrases", fa: "آب داره می‌جوشه.", pin: "Āb dāreh mijoosheh.", en: "The water is boiling.", notes: "داره + می‌جوشه (right now)" },
    { id: "35.p.keshvar-haye-hamsaye-ye-iran", type: "phrases", fa: "کشورهای همسایه‌ی ایران", pin: "Keshvar hāye hamsāye-ye Irān", en: "Iran's neighbouring countries", notes: "کشورها + ezāfe + همسایه + ezāfe + ایران" },
    { id: "35.p.man-gharar-daram", type: "phrases", fa: "من قرار دارم.", pin: "Man gharār dāram.", en: "I have an appointment.", notes: "قرار + داشتن" },
    { id: "35.p.man-gharar-e-kari-daram", type: "phrases", fa: "من قرار کاری دارم.", pin: "Man gharār-e kāri dāram.", en: "I have a work appointment / a business meeting.", notes: "قرارِ کاری" },
    { id: "35.p.man-ba-ali-gharar-daram", type: "phrases", fa: "من با علی قرار دارم.", pin: "Man bā Ali gharār dāram.", en: "I'm meeting Ali.", notes: "با + [person] + قرار داشتن" },
    { id: "35.p.ma-ba-ham-gharar-darim", type: "phrases", fa: "ما با هم قرار داریم.", pin: "Mā bā ham gharār dārim.", en: "We're meeting. / We have a date.", notes: "با هم / با همدیگه = with each other" },
    { id: "35.p.bacheh-kheili-bigharar-hast", type: "phrases", fa: "بچه خیلی بی‌قرار هست.", pin: "Bacheh kheili bigharār hast.", en: "The kid is very fidgety.", notes: "بی‌قرار = restless (physical)" },
    { id: "35.p.mamanam-kheili-bigharar-hast-man", type: "phrases", fa: "مامانم خیلی بی‌قرار هست، من نگرانش هستم.", pin: "Māmānam kheili bigharār hast, man negarānesh hastam.", en: "My mom is really anxious, and I'm worried about her.", notes: "بی‌قرار = anxious (mental); نگران + ش (about her)" },
    { id: "35.p.ye-miz-dar-markaz-e-otagh-gharar", type: "phrases", fa: "یه میز در مرکز اتاق قرار دارد.", pin: "Ye miz dar markaz-e otāgh gharār dārad.", en: "There is a table in the center of the room.", notes: "قرار دارد = is located" },
    { id: "35.p.iran-dar-khavar-e-mianeh-gharar", type: "phrases", fa: "ایران در خاورمیانه قرار دارد.", pin: "Irān dar khāvar-e miāneh gharār dārad.", en: "Iran is located in the Middle East.", notes: "در + خاورمیانه + قرار دارد" },
    { id: "35.p.hotel-nazdik-e-sahel-gharar", type: "phrases", fa: "هتل نزدیک ساحل قرار دارد.", pin: "Hotel nazdik-e sāhel gharār dārad.", en: "The hotel is located near the beach.", notes: "نزدیکِ + ساحل" },
    { id: "35.p.khalij-e-fars-dar-jonoob-e-iran", type: "phrases", fa: "خلیج فارس در جنوب ایران قرار دارد.", pin: "Khalij-e Fārs dar jonoob-e Irān gharār dārad.", en: "The Persian Gulf is located in the south of Iran.", notes: "جنوبِ ایران" },
    { id: "35.p.iran-si-o-yek-ostan-darad", type: "phrases", fa: "ایران سی و یک استان دارد.", pin: "Irān si-o-yek ostān dārad.", en: "Iran has thirty-one provinces.", notes: "سی و یک = 31" },
    { id: "35.p.markaz-e-ostan-e-fars-shiraz", type: "phrases", fa: "مرکز استان فارس شیراز هست.", pin: "Markaz-e ostān-e Fārs Shirāz hast.", en: "The center of Fars Province is Shiraz.", notes: "مرکزِ + استانِ + فارس" },
    { id: "35.p.tehran-paytakht-e-iran-hast", type: "phrases", fa: "تهران پایتخت ایران هست.", pin: "Tehrān pāytakht-e Irān hast.", en: "Tehran is the capital of Iran.", notes: "پایتختِ + ایران" },
    { id: "35.p.otagh-e-neshiman-ro-tosif-kon", type: "phrases", fa: "اتاق نشیمن رو توصیف کن.", pin: "Otāgh-e neshiman ro tosif kon.", en: "Describe the sitting room.", notes: "رو (object marker) + توصیف کن (describe!)" },
  ],
});
