// Build lessons/stories.js from tools/stories-src/stories.src.js, scoring each
// story with tools/coverage.js against the deck as taught up to its session.
//
//   node tools/stories-src/build-stories.js
//
// Practice stories are generated, not the teacher's material: every story
// keeps generated: true and the reader labels it as such. Aim for >= 98% of
// tokens known at the story's session (95% is the hard floor, flagged FAIL),
// 60-140 words, and give a gloss in stories.src.js for every unknown word.
// After adding stories, rebuild the example sentences:
//   node tools/stories-src/build-examples.js && node tools/apply-examples.js
'use strict';
const fs = require('fs');
const path = require('path');
const cov = require('../coverage.js');

const ROOT = path.resolve(__dirname, '..', '..');
const OUT = path.join(ROOT, 'lessons', 'stories.js');
const deck = cov.loadDeck({ repo: ROOT });
const notesFiles = cov.findNotes(ROOT);
delete require.cache[require.resolve('./stories.src.js')];
const src = require('./stories.src.js');
const out = [];
let problems = 0;
for (const st of src) {
  const lex = cov.buildLexicon(deck, st.session, { notesFiles, names: st.names || [] });
  const text = st.lines.map(l => l[0]).join(' ');
  const res = cov.analyse(text, lex);
  const words = cov.tokenise(text).length;
  const unknown = [];
  const missing = [];
  for (const u of res.unknown) {
    const g = st.gloss[u.token] || st.gloss[cov.key(u.token)];
    if (g) unknown.push({ fa: u.token, pin: g[0], en: g[1] });
    else missing.push(u.token + (u.laterSession ? '(' + u.laterSession + ')' : ''));
  }
  const unused = Object.keys(st.gloss).filter(k => !res.unknown.some(u => u.token === k || cov.key(u.token) === cov.key(k)));
  const pct = (res.coverage * 100).toFixed(1);
  const flag = res.coverage < 0.95 ? ' FAIL<95' : res.coverage < 0.98 ? ' below98' : '';
  console.log(`${st.id.padEnd(10)} ${String(words).padStart(3)}w ${pct}%${flag}  unknown: ${res.unknown.map(u => u.token).join(' ')}${missing.length ? '  MISSING GLOSS: ' + missing.join(' ') : ''}${unused.length ? '  unused gloss: ' + unused.join(' ') : ''}`);
  if (missing.length || res.coverage < 0.95 || words < 60 || words > 140) problems++;
  if (words < 60 || words > 140) console.log('   word count out of range: ' + words);
  out.push({
    id: st.id, session: st.session, title_en: st.title_en, title_fa: st.title_fa, generated: true,
    coverage: Math.round(res.coverage * 1000) / 1000,
    unknown,
    lines: st.lines.map(([fa, pin, en]) => ({ fa, pin, en })),
  });
}

// One story object per block, one line per sentence, so diffs stay readable.
const J = v => JSON.stringify(v);
const body = out.map(st => [
  '  {',
  `    id: ${J(st.id)}, session: ${J(st.session)}, generated: true, coverage: ${st.coverage},`,
  `    title_en: ${J(st.title_en)}, title_fa: ${J(st.title_fa)},`,
  `    unknown: [${st.unknown.map(u => `{ fa: ${J(u.fa)}, pin: ${J(u.pin)}, en: ${J(u.en)} }`).join(', ')}],`,
  '    lines: [',
  ...st.lines.map(l => `      { fa: ${J(l.fa)}, pin: ${J(l.pin)}, en: ${J(l.en)} },`),
  '    ],',
  '  },',
].join('\n')).join('\n');
fs.writeFileSync(OUT, `// Practice stories: short graded readers written for this deck, NOT the
// teacher's material (generated: true; the reader labels them "written for
// you"). Each is checked with tools/coverage.js to use >= 95% (aim 98%) words
// already taught by its session; words not yet taught are glossed in unknown.
// GENERATED by tools/stories-src/build-stories.js from stories.src.js; edit
// the source and rebuild rather than editing this file.
// Story ids are permanent (read state is stored by id).
F.stories = (F.stories || []).concat([
${body}
]);
`);
console.log(`wrote ${path.relative(ROOT, OUT)} (${out.length} stories)`);
console.log(problems ? `${problems} stories need work` : 'all stories OK');
