// Source for stories.json. Each line: [fa, pin, en].
// gloss: { "<token as written in the story>": ["pin", "en"] } for words not yet taught at that session.
module.exports = [
{
  id: 'st-22-1', session: '22', title_en: 'Ali and his mom', title_fa: 'علی و مامانش',
  gloss: {},
  lines: [
    ['این علی هست.', 'In Ali hast.', 'This is Ali.'],
    ['علی ایرانی هست و خیلی باهوشه.', 'Ali irāni hast va kheili bāhoosh-eh.', 'Ali is Iranian and very smart.'],
    ['سارا دوست علی هست.', 'Sārā doost-e Ali hast.', "Sara is Ali's friend."],
    ['سارا خیلی خوب و باهوشه.', 'Sārā kheili khoob o bāhoosh-eh.', 'Sara is very nice and smart.'],
    ['امروز مامان و بابای علی اینجا هستن.', 'Emrooz māmān o bābā-ye Ali injā hastan.', "Today Ali's mom and dad are here."],
    ['علی: «مامان، تو چطوری؟»', 'Ali: "Māmān, to chetori?"', 'Ali: "Mom, how are you?"'],
    ['مامان: «من خوبم، ممنون. تو چطوری؟»', 'Māmān: "Man khoobam, mamnoon. To chetori?"', 'Mom: "I\'m fine, thanks. How are you?"'],
    ['علی: «من خیلی خوبم! مامان‌بزرگ و بابابزرگ چطورن؟»', 'Ali: "Man kheili khoobam! Māmānbozorg o bābābozorg chetoran?"', 'Ali: "I\'m really well! How are Grandma and Grandpa?"'],
    ['مامان: «اونا خوبن. بد نیستن.»', 'Māmān: "Oonā khooban. Bad nistan."', 'Mom: "They\'re well. Not bad."'],
    ['امروز علی و باباش ورزش می‌کنن.', 'Emrooz Ali o bābāsh varzesh mikonan.', 'Today Ali and his dad are exercising.'],
    ['پلو و گیلاس اینجا هست.', 'Polo o gilās injā hast.', "There's rice and cherries here."],
    ['پلو خیلی خوشمزه هست!', 'Polo kheili khoshmazeh hast!', 'The rice is really delicious!'],
    ['زندگی خوبه!', 'Zendegi khoob-eh!', 'Life is good!'],
  ],
},
{
  id: 'st-23-1', session: '23', title_en: 'Sara is a vegetarian', title_fa: 'سارا گیاه‌خواره',
  gloss: {},
  lines: [
    ['سارا گیاه‌خواره.', 'Sārā giāh-khār-eh.', 'Sara is a vegetarian.'],
    ['اون گوشت و ماهی نمی‌خوره.', 'Oon goosht o māhi nemikhoreh.', "She doesn't eat meat or fish."],
    ['سارا سبزیجات و میوه رو خیلی دوست داره.', 'Sārā sabzijāt o miveh ro kheili doost dāreh.', 'Sara really loves vegetables and fruit.'],
    ['دوستش، علی، گیاه‌خوار نیست.', 'Doostesh, Ali, giāh-khār nist.', "Her friend Ali isn't a vegetarian."],
    ['علی گوشت و خورشت رو خیلی دوست داره.', 'Ali goosht o khorosht ro kheili doost dāreh.', 'Ali really loves meat and stew.'],
    ['امروز سارا و علی اینجا غذا می‌خورن.', 'Emrooz Sārā o Ali injā ghazā mikhoran.', 'Today Sara and Ali are eating here.'],
    ['علی خورشت و پلو می‌خوره.', 'Ali khorosht o polo mikhoreh.', 'Ali has stew and rice.'],
    ['سارا سبزی پلو و ماست می‌خوره.', 'Sārā sabzi polo o māst mikhoreh.', 'Sara has herb rice and yogurt.'],
    ['علی: «سارا، تو شراب می‌خوری؟»', 'Ali: "Sārā, to sharāb mikhori?"', 'Ali: "Sara, will you have some wine?"'],
    ['سارا: «نه، ممنون. من مشروب نمی‌خورم. من چای سبز می‌خورم.»', 'Sārā: "Na, mamnoon. Man mashroob nemikhoram. Man chāy-e sabz mikhoram."', 'Sara: "No, thanks. I don\'t drink alcohol. I\'ll have green tea."'],
    ['علی: «با شکر؟»', 'Ali: "Bā shekar?"', 'Ali: "With sugar?"'],
    ['سارا: «نه، بدون شکر، لطفاً.»', 'Sārā: "Na, bedoon-e shekar, lotfan."', 'Sara: "No, without sugar, please."'],
    ['علی آب جو می‌خوره.', 'Ali āb-jo mikhoreh.', 'Ali drinks beer.'],
    ['علی: «به سلامتی!»', 'Ali: "Be salāmati!"', 'Ali: "Cheers!"'],
    ['غذا خیلی خوشمزه هست.', 'Ghazā kheili khoshmazeh hast.', 'The food is very tasty.'],
    ['سارا: «نوش جان!»', 'Sārā: "Noosh-e jān!"', 'Sara: "Enjoy!"'],
  ],
},
{
  id: 'st-2425-1', session: '24-25', title_en: "Maryam's restaurant", title_fa: 'رستوران مریم',
  gloss: {},
  lines: [
    ['مریم در شهر یزد زندگی می‌کنه.', 'Maryam dar shahr-e Yazd zendegi mikoneh.', 'Maryam lives in the city of Yazd.'],
    ['اون یه رستوران سنتی داره.', 'Oon ye restorān-e sonnati dāreh.', 'She has a traditional restaurant.'],
    ['رستوران مریم همیشه شلوغه.', "Restorān-e Maryam hamisheh sholugh-eh.", "Maryam's restaurant is always busy."],
    ['مریم هر روز در آشپزخونه آشپزی می‌کنه.', 'Maryam har rooz dar āshpazkhooneh āshpazi mikoneh.', 'Maryam cooks in the kitchen every day.'],
    ['اون معمولاً خورشت بادمجان درست می‌کنه.', "Oon ma'moolan khorosht-e bādemjān dorost mikoneh.", 'She usually makes aubergine stew.'],
    ['خورشت بادمجان خورشت مورد علاقه‌ی من هست.', "Khorosht-e bādemjān khorosht-e mored-e alāghe-ye man hast.", 'Aubergine stew is my favourite stew.'],
    ['امروز من و دوستم به رستوران مریم می‌ریم.', 'Emrooz man o doostam be restorān-e Maryam mirim.', "Today my friend and I are going to Maryam's restaurant."],
    ['مریم می‌گه: «سلام! بفرمایید بشینید!»', 'Maryam migeh: "Salām! Befarmāyid beshinid!"', 'Maryam says: "Hello! Please, have a seat!"'],
    ['بعد می‌گه: «بفرمایید بخورید! نوش جان!»', "Ba'd migeh: \"Befarmāyid bokhorid! Noosh-e jān!\"", 'Then she says: "Please, eat! Enjoy!"'],
    ['غذا خیلی خوشمزه و تازه هست.', 'Ghazā kheili khoshmazeh o tāzeh hast.', 'The food is very tasty and fresh.'],
    ['بعد از غذا، ما دسر و چای می‌خوریم.', "Ba'd az ghazā, mā deser o chāy mikhorim.", 'After the meal, we have dessert and tea.'],
    ['من به مریم می‌گم: «خیلی ممنون! من عاشق این رستوران هستم!»', 'Man be Maryam migam: "Kheili mamnoon! Man āshegh-e in restorān hastam!"', 'I say to Maryam: "Thank you so much! I love this restaurant!"'],
    ['مریم می‌خنده و می‌گه: «به مامانت سلام برسون!»', 'Maryam mikhandeh va migeh: "Be māmānet salām beresoon!"', 'Maryam laughs and says: "Say hi to your mom!"'],
  ],
},
{
  id: 'st-26-1', session: '26', title_en: 'What time is it?', title_fa: 'ساعت چنده؟',
  gloss: {},
  lines: [
    ['سارا سی و دو سالشه.', 'Sārā si-o do sālesh-eh.', 'Sara is thirty-two.'],
    ['اون هر روز ساعت هفت صبحونه می‌خوره.', 'Oon har rooz sāat-e haft sobhooneh mikhoreh.', 'Every day she has breakfast at seven.'],
    ['ساعت نه کلاس ریاضی داره.', 'Sāat-e noh kelās-e riāzi dāreh.', 'At nine she has a maths class.'],
    ['ساعت یک، سارا با همکارش، رضا، ناهار می‌خوره.', 'Sāat-e yek, Sārā bā hamkāresh, Rezā, nāhār mikhoreh.', 'At one, Sara has lunch with her colleague Reza.'],
    ['رضا خیلی باهوشه، ولی ساعت نداره.', 'Rezā kheili bāhoosh-eh, vali sāat nadāreh.', "Reza is very smart, but he doesn't have a watch."],
    ['امروز رضا می‌گه: «ببخشید، الان ساعت چنده؟»', 'Emrooz Rezā migeh: "Bebakhshid, alān sāat chand-eh?"', 'Today Reza says: "Excuse me, what time is it now?"'],
    ['سارا می‌گه: «ساعت دو و ربعه.»', 'Sārā migeh: "Sāat do-o rob\'-eh."', 'Sara says: "It\'s a quarter past two."'],
    ['رضا می‌گه: «من ساعت دو و نیم کلاس دارم!»', 'Rezā migeh: "Man sāat-e do-o nim kelās dāram!"', 'Reza says: "I have a class at half past two!"'],
    ['سارا می‌گه: «کلاس کجاست؟»', 'Sārā migeh: "Kelās kojāst?"', 'Sara says: "Where is the class?"'],
    ['رضا می‌گه: «نمی‌دونم!»', 'Rezā migeh: "Nemidoonam!"', 'Reza says: "I don\'t know!"'],
    ['شب، سارا با شوهرش شام می‌خوره.', 'Shab, Sārā bā shoharesh shām mikhoreh.', 'In the evening, Sara has dinner with her husband.'],
    ['شوهرش امشب شام درست می‌کنه.', 'Shoharesh emshab shām dorost mikoneh.', 'Her husband is cooking dinner tonight.'],
    ['شام خیلی خوشمزه هست.', 'Shām kheili khoshmazeh hast.', 'Dinner is very tasty.'],
  ],
},
{
  id: 'st-27-1', session: '27', title_en: 'A rainy day', title_fa: 'یه روز بارونی',
  gloss: {},
  lines: [
    ['امروز هوا بارونیه.', 'Emrooz havā bārooni-eh.', 'Today the weather is rainy.'],
    ['سارا خیلی ناراحته.', 'Sārā kheili nārāhat-eh.', 'Sara is very upset.'],
    ['علی می‌گه: «سارا، چرا ناراحتی؟»', 'Ali migeh: "Sārā, cherā nārāhati?"', 'Ali says: "Sara, why are you upset?"'],
    ['سارا می‌گه: «چون هوا بارونیه و من سردمه.»', 'Sārā migeh: "Chon havā bārooni-eh va man sardam-eh."', 'Sara says: "Because it\'s rainy and I\'m cold."'],
    ['«زندگی کردن در لندن خیلی سخته!»', '"Zendegi kardan dar London kheili sakht-eh!"', '"Living in London is really hard!"'],
    ['علی می‌گه: «نگران نباش! من چای درست می‌کنم.»', 'Ali migeh: "Negarān nabāsh! Man chāy dorost mikonam."', 'Ali says: "Don\'t worry! I\'ll make tea."'],
    ['علی خیلی مهمان‌نوازه.', 'Ali kheili mehmān-navāz-eh.', 'Ali is very hospitable.'],
    ['اون برای سارا یه چای شیرین درست می‌کنه و می‌گه: «راحت باش!»', 'Oon barāye Sārā ye chāy-e shirin dorost mikoneh va migeh: "Rāhat bāsh!"', 'He makes Sara a sweet tea and says: "Make yourself comfortable!"'],
    ['الان سارا خوشحاله.', 'Alān Sārā khoshhāl-eh.', 'Now Sara is happy.'],
    ['اون می‌گه: «تو دوست خیلی خوبی هستی.»', 'Oon migeh: "To doost-e kheili khoobi hasti."', 'She says: "You\'re a really good friend."'],
    ['«داشتن یه دوست خوب خیلی مهمه!»', '"Dāshtan-e ye doost-e khoob kheili mohem-eh!"', '"Having a good friend is so important!"'],
  ],
},
{
  id: 'st-28-1', session: '28', title_en: 'Plans for tomorrow', title_fa: 'فردا',
  gloss: {},
  lines: [
    ['علی و سارا همدیگه رو خیلی دوست دارن.', 'Ali o Sārā hamdige ro kheili doost dāran.', 'Ali and Sara love each other very much.'],
    ['اونا با همدیگه زندگی می‌کنن.', 'Oonā bā hamdige zendegi mikonan.', 'They live together.'],
    ['الان علی داره شام درست می‌کنه و سارا داره کتاب می‌خونه.', 'Alān Ali dāreh shām dorost mikoneh va Sārā dāreh ketāb mikhooneh.', 'Right now Ali is making dinner and Sara is reading a book.'],
    ['سارا می‌گه: «علی، فردا سر کار می‌ری؟»', 'Sārā migeh: "Ali, fardā sar-e kār miri?"', 'Sara says: "Ali, are you going to work tomorrow?"'],
    ['علی می‌گه: «نه، من فردا کار نمی‌کنم. تو چی؟»', 'Ali migeh: "Na, man fardā kār nemikonam. To chi?"', 'Ali says: "No, I\'m not working tomorrow. What about you?"'],
    ['سارا می‌گه: «من فردا صبح سر کار می‌رم، ولی بعد از ظهر وقت دارم.»', "Sārā migeh: \"Man fardā sobh sar-e kār miram, vali ba'd az zohr vaght dāram.\"", 'Sara says: "I\'m going to work tomorrow morning, but I\'m free in the afternoon."'],
    ['علی می‌گه: «فردا بعد از ظهر با همدیگه می‌ریم سینما؟»', "Ali migeh: \"Fardā ba'd az zohr bā hamdige mirim cinemā?\"", 'Ali says: "Shall we go to the cinema together tomorrow afternoon?"'],
    ['سارا می‌گه: «آره! بعدش هم با همدیگه شام می‌خوریم.»', "Sārā migeh: \"Āreh! Ba'desh ham bā hamdige shām mikhorim.\"", 'Sara says: "Yes! And afterwards we\'ll have dinner together."'],
    ['علی می‌گه: «و سال دیگه با همدیگه به ایران سفر می‌کنیم!»', 'Ali migeh: "Va sāl-e dige bā hamdige be Irān safar mikonim!"', 'Ali says: "And next year we\'ll travel to Iran together!"'],
    ['سارا می‌خنده.', 'Sārā mikhandeh.', 'Sara laughs.'],
  ],
},
{
  id: 'st-29-1', session: '29', title_en: 'Whose pen is this?', title_fa: 'این مال کیه؟',
  gloss: {},
  lines: [
    ['سارا همیشه زود می‌رسه، ولی علی همیشه دیر می‌رسه.', 'Sārā hamisheh zood mireseh, vali Ali hamisheh dir mireseh.', 'Sara always arrives early, but Ali always arrives late.'],
    ['امروز کلاس فارسی ساعت پنج هست.', 'Emrooz kelās-e Fārsi sāat-e panj hast.', 'Today the Persian class is at five.'],
    ['سارا سر وقت به کلاس می‌رسه.', 'Sārā sar-e vaght be kelās mireseh.', 'Sara arrives at the class on time.'],
    ['اون می‌گه: «کسی اینجا هست؟»', 'Oon migeh: "Kasi injā hast?"', 'She says: "Is anyone here?"'],
    ['کسی اینجا نیست، ولی یه خودکار و یه مداد اینجا هست.', 'Kasi injā nist, vali ye khodkār o ye medād injā hast.', "No one is here, but there's a pen and a pencil here."],
    ['پنج دقیقه بعد، علی می‌رسه و می‌گه: «ببخشید دیر شد!»', "Panj daghigheh ba'd, Ali mireseh va migeh: \"Bebakhshid dir shod!\"", 'Five minutes later, Ali arrives and says: "Sorry I\'m late!"'],
    ['سارا می‌گه: «این خودکار مال توئه؟»', 'Sārā migeh: "In khodkār māl-e to-eh?"', 'Sara says: "Is this pen yours?"'],
    ['علی می‌گه: «نه، مال من نیست. این مداد مال منه.»', 'Ali migeh: "Na, māl-e man nist. In medād māl-e man-eh."', 'Ali says: "No, it\'s not mine. This pencil is mine."'],
    ['سارا می‌گه: «این خودکار مال کیه؟»', 'Sārā migeh: "In khodkār māl-e ki-eh?"', 'Sara says: "Whose pen is this, then?"'],
    ['بعد مریم می‌رسه و می‌گه: «اون خودکار مال منه!»', "Ba'd Maryam mireseh va migeh: \"Oon khodkār māl-e man-eh!\"", 'Then Maryam arrives and says: "That pen is mine!"'],
    ['علی می‌خنده و می‌گه: «مراقب خودکارت باش!»', 'Ali mikhandeh va migeh: "Morāgheb-e khodkāret bāsh!"', 'Ali laughs and says: "Look after your pen!"'],
  ],
},
{
  id: 'st-30-1', session: '30', title_en: 'On foot or by car?', title_fa: 'پیاده یا با ماشین؟',
  gloss: {},
  lines: [
    ['علی هر روز از خونه تا سر کار راه می‌ره.', 'Ali har rooz az khooneh tā sar-e kār rāh mireh.', 'Every day Ali walks from home to work.'],
    ['اون پیاده‌روی رو خیلی دوست داره.', 'Oon piāderavi ro kheili doost dāreh.', 'He really loves walking.'],
    ['ولی سارا از خونه تا سر کار رانندگی می‌کنه.', 'Vali Sārā az khooneh tā sar-e kār rānandegi mikoneh.', 'But Sara drives from home to work.'],
    ['سارا می‌گه: «پیاده‌روی برای من سخته.»', 'Sārā migeh: "Piāderavi barāye man sakht-eh."', 'Sara says: "Walking is hard for me."'],
    ['علی هفته‌ای سه بار باشگاه هم می‌ره.', 'Ali hafte-i seh bār bāshgāh ham mireh.', 'Ali also goes to the gym three times a week.'],
    ['سارا ماهی یه بار باشگاه می‌ره!', 'Sārā māhi ye bār bāshgāh mireh!', 'Sara goes to the gym once a month!'],
    ['هر روز صبح، علی تو راه یه راننده‌ی تاکسی رو می‌بینه.', 'Har rooz sobh, Ali too rāh ye rānande-ye tāksi ro mibineh.', 'Every morning, Ali sees a taxi driver on the way.'],
    ['راننده می‌گه: «سلام! امروز هم پیاده‌ای؟»', 'Rānandeh migeh: "Salām! Emrooz ham piāde-i?"', 'The driver says: "Hi! On foot again today?"'],
    ['علی می‌گه: «آره! هوا خوبه، من پیاده می‌رم.»', 'Ali migeh: "Āreh! Havā khoob-eh, man piādeh miram."', 'Ali says: "Yes! The weather\'s nice, I\'m walking."'],
    ['راننده می‌خنده و می‌گه: «فردا دوباره می‌بینمت!»', 'Rānandeh mikhandeh va migeh: "Fardā dobāreh mibinamet!"', 'The driver laughs and says: "See you again tomorrow!"'],
  ],
},
{
  id: 'st-30-2', session: '30', title_en: "Grandma's house", title_fa: 'خونه‌ی مامان‌بزرگ',
  gloss: {},
  lines: [
    ['مامان‌بزرگ سارا هشتاد و پنج سالشه.', "Māmānbozorg-e Sārā hashtād-o panj sālesh-eh.", "Sara's grandma is eighty-five."],
    ['سارا ماهی سه بار مامان‌بزرگش رو می‌بینه.', 'Sārā māhi seh bār māmānbozorgesh ro mibineh.', 'Sara sees her grandma three times a month.'],
    ['اون از خونه‌ی خودش تا خونه‌ی مامان‌بزرگ رانندگی می‌کنه.', 'Oon az khoone-ye khodesh tā khoone-ye māmānbozorg rānandegi mikoneh.', "She drives from her own home to Grandma's house."],
    ['مامان‌بزرگ هر بار می‌گه: «بشین! چای می‌خوری؟»', 'Māmānbozorg har bār migeh: "Beshin! Chāy mikhori?"', 'Every time, Grandma says: "Sit down! Will you have some tea?"'],
    ['مامان‌بزرگ خیلی پیر هست، ولی روزی دو بار پیاده‌روی می‌کنه.', 'Māmānbozorg kheili pir hast, vali roozi do bār piāderavi mikoneh.', 'Grandma is very old, but she goes for a walk twice a day.'],
    ['اون از ساعت نه تا ده صبح و از ساعت پنج تا شش بعد از ظهر راه می‌ره.', "Oon az sāat-e noh tā dah-e sobh va az sāat-e panj tā shish-e ba'd az zohr rāh mireh.", 'She walks from nine to ten in the morning and from five to six in the afternoon.'],
    ['سارا می‌گه: «مامان‌بزرگ، من هفته‌ای یه بار هم پیاده‌روی نمی‌کنم!»', 'Sārā migeh: "Māmānbozorg, man hafte-i ye bār ham piāderavi nemikonam!"', 'Sara says: "Grandma, I don\'t even go for a walk once a week!"'],
    ['ساعت هفت، سارا می‌گه: «هفته‌ی دیگه دوباره می‌بینمت!»', 'Sāat-e haft, Sārā migeh: "Hafte-ye dige dobāreh mibinamet!"', 'At seven, Sara says: "See you again next week!"'],
    ['مامان‌بزرگ می‌گه: «مراقب خودت باش!»', 'Māmānbozorg migeh: "Morāgheb-e khodet bāsh!"', 'Grandma says: "Take care of yourself!"'],
  ],
},
{
  id: 'st-31-1', session: '31', title_en: 'Errands', title_fa: 'خرید',
  gloss: {},
  lines: [
    ['امروز علی سرش خیلی شلوغه.', 'Emrooz Ali saresh kheili sholugh-eh.', 'Ali is very busy today.'],
    ['صبح، اون با دوچرخه به نونوایی می‌ره و نون می‌خره.', 'Sobh, oon bā docharkheh be noonvāyi mireh va noon mikhareh.', 'In the morning, he goes to the bakery by bike and buys bread.'],
    ['بعد به میوه‌فروشی می‌ره.', "Ba'd be miveh-forushi mireh.", "Then he goes to the greengrocer's."],
    ['میوه‌فروش می‌گه: «سلام آقا! سیب‌ها خیلی تازه هستن.»', 'Miveh-foroush migeh: "Salām āghā! Sib hā kheili tāzeh hastan."', 'The greengrocer says: "Hello, sir! The apples are really fresh."'],
    ['علی سیب و گیلاس می‌خره.', 'Ali sib o gilās mikhareh.', 'Ali buys apples and cherries.'],
    ['بعد علی با اتوبوس به داروخونه می‌ره، چون داروخونه از اینجا خیلی دوره.', "Ba'd Ali bā otobus be dārookhooneh mireh, chon dārookhooneh az injā kheili dour-eh.", 'Then Ali takes the bus to the pharmacy, because the pharmacy is very far from here.'],
    ['ایستگاه اتوبوس نزدیک میوه‌فروشی هست.', 'Istgāh-e otobus nazdik-e miveh-forushi hast.', "The bus stop is near the greengrocer's."],
    ['ساعت دو، علی خونه هست.', 'Sāat-e do, Ali khooneh hast.', 'At two, Ali is home.'],
    ['سارا می‌گه: «علی، ما دیگه شیر نداریم! لطفاً شیر بخر!»', 'Sārā migeh: "Ali, mā dige shir nadārim! Lotfan shir bekhar!"', 'Sara says: "Ali, we\'re out of milk! Please buy some milk!"'],
    ['علی می‌خنده و دوباره می‌ره خرید.', 'Ali mikhandeh va dobāreh mireh kharid.', 'Ali laughs and goes shopping again.'],
  ],
},
{
  id: 'st-31-2', session: '31', title_en: 'A trip to Shiraz', title_fa: 'سفر به شیراز',
  gloss: { 'اتاق': ['otāgh', 'room'] },
  lines: [
    ['سارا این هفته به مسافرت می‌ره.', 'Sārā in hafteh be mosāferat mireh.', 'Sara is going on a trip this week.'],
    ['اون از تهران به شیراز سفر می‌کنه.', 'Oon az Tehrān be Shirāz safar mikoneh.', "She's travelling from Tehran to Shiraz."],
    ['سارا با هواپیما نمی‌ره، با قطار می‌ره.', 'Sārā bā havāpeymā nemireh, bā ghatār mireh.', "Sara isn't going by plane, she's going by train."],
    ['ساعت شش صبح، اون با تاکسی به ایستگاه قطار می‌ره.', 'Sāat-e shish-e sobh, oon bā tāksi be istgāh-e ghatār mireh.', 'At six in the morning, she takes a taxi to the railway station.'],
    ['الان سارا سوار قطاره.', 'Alān Sārā savār-e ghatār-eh.', 'Now Sara is on the train.'],
    ['یه مسافر پیر می‌گه: «سفر کاری می‌رید؟»', 'Ye mosāfer-e pir migeh: "Safar-e kāri mirid?"', 'An old passenger says: "Are you going on a business trip?"'],
    ['سارا می‌گه: «نه! من عاشق شیراز هستم.»', 'Sārā migeh: "Na! Man āshegh-e Shirāz hastam."', 'Sara says: "No! I love Shiraz."'],
    ['در شیراز، سارا یه اتاق در یه مهمون‌خونه‌ی قدیمی اجاره می‌کنه.', 'Dar Shirāz, Sārā ye otāgh dar ye mehmoon-khoone-ye ghadimi ejāreh mikoneh.', 'In Shiraz, Sara rents a room in an old guesthouse.'],
    ['مهمون‌خونه نزدیک یه کتاب‌فروشی و یه بستنی‌فروشی هست.', 'Mehmoon-khooneh nazdik-e ye ketāb-forushi o ye bastani-forushi hast.', 'The guesthouse is near a bookshop and an ice cream shop.'],
    ['سارا هر روز به کتاب‌فروشی می‌ره و یه کتاب می‌خره.', 'Sārā har rooz be ketāb-forushi mireh va ye ketāb mikhareh.', 'Every day Sara goes to the bookshop and buys a book.'],
    ['بعد به بستنی‌فروشی می‌ره!', "Ba'd be bastani-forushi mireh!", 'Then she goes to the ice cream shop!'],
  ],
},
{
  id: 'st-32-1', session: '32', title_en: 'But last night...', title_fa: 'ولی دیشب...',
  gloss: {},
  lines: [
    ['دیشب سعید و میترا ساعت ده نخوابیدن.', 'Dishab Saeed o Mitrā sāat-e dah nakhābidan.', "Last night Saeed and Mitra didn't go to bed at ten."],
    ['سعید سردرد داشت و میترا دل‌درد داشت.', 'Saeed sar-dard dāsht va Mitrā del-dard dāsht.', 'Saeed had a headache and Mitra had a stomachache.'],
    ['ساعت یازده، بچه‌ها هم بیدار شدن.', 'Sāat-e yāzdah, bacheh hā ham bidār shodan.', 'At eleven, the children woke up too.'],
    ['یکی گفت: «مامان، من گشنمه!»', 'Yeki goft: "Māmān, man goshnam-eh!"', 'One said: "Mom, I\'m hungry!"'],
    ['یکی دیگه گفت: «بابا، من آب می‌خوام!»', 'Yeki dige goft: "Bābā, man āb mikhām!"', 'Another said: "Dad, I want some water!"'],
    ['ساعت دوازده، همسایه اومد.', 'Sāat-e davāzdah, hamsāyeh oomad.', 'At twelve, the neighbour came over.'],
    ['سعید در رو باز کرد.', 'Saeed dar ro bāz kard.', 'Saeed opened the door.'],
    ['همسایه گفت: «ببخشید! کمک لازم دارید؟»', 'Hamsāyeh goft: "Bebakhshid! Komak lāzem dārid?"', 'The neighbour said: "Excuse me! Do you need help?"'],
    ['سعید گفت: «نه، ممنون. ما خوبیم.»', 'Saeed goft: "Na, mamnoon. Mā khoobim."', 'Saeed said: "No, thanks. We\'re fine."'],
    ['بعد در رو بست.', "Ba'd dar ro bast.", 'Then he closed the door.'],
    ['اونها ساعت یک خوابیدن.', 'Oonhā sāat-e yek khābidan.', 'They went to sleep at one.'],
    ['امروز صبح، سعید و میترا خیلی خسته بودن.', 'Emrooz sobh, Saeed o Mitrā kheili khasteh boodan.', 'This morning, Saeed and Mitra were very tired.'],
    ['ولی بچه‌ها ساعت شیش بیدار شدن و گفتن: «ما صبحونه می‌خوایم!»', 'Vali bacheh hā sāat-e shish bidār shodan va goftan: "Mā sobhooneh mikhāym!"', 'But the children woke up at six and said: "We want breakfast!"'],
  ],
},
{
  id: 'st-32-2', session: '32', title_en: "Ali's bad day", title_fa: 'روز بد علی',
  gloss: {},
  lines: [
    ['دیروز علی ساعت هفت از خواب بیدار شد.', 'Dirooz Ali sāat-e haft az khāb bidār shod.', 'Yesterday Ali woke up at seven.'],
    ['اون خیلی سردرد داشت.', 'Oon kheili sar-dard dāsht.', 'He had a bad headache.'],
    ['علی صبحونه نخورد و سر کار نرفت.', 'Ali sobhooneh nakhord va sar-e kār naraft.', "Ali didn't eat breakfast and didn't go to work."],
    ['ساعت ده، مامانش اومد.', 'Sāat-e dah, māmānesh oomad.', 'At ten, his mom came over.'],
    ['مامان گفت: «علی، کجات درد می‌کنه؟»', 'Māmān goft: "Ali, kojāt dard mikoneh?"', 'Mom said: "Ali, where does it hurt?"'],
    ['علی گفت: «سرم درد می‌کنه، گوشم درد می‌کنه، کمرم هم درد می‌کنه!»', 'Ali goft: "Saram dard mikoneh, goosham dard mikoneh, kamaram ham dard mikoneh!"', 'Ali said: "My head hurts, my ear hurts, and my back hurts too!"'],
    ['مامان گفت: «بخواب!»', 'Māmān goft: "Bekhāb!"', 'Mom said: "Go to sleep!"'],
    ['علی تا ساعت سه بعد از ظهر خوابید.', "Ali tā sāat-e seh ba'd az zohr khābid.", 'Ali slept until three in the afternoon.'],
    ['بعد اون نون و پنیر و چای خورد.', "Ba'd oon noon o panir o chāy khord.", 'Then he had bread, cheese and tea.'],
    ['شب، علی گفت: «مامان، دستت درد نکنه! الان خوبم.»', 'Shab, Ali goft: "Māmān, dastet dard nakoneh! Alān khoobam."', 'In the evening, Ali said: "Mom, thank you! I\'m fine now."'],
    ['مامان گفت: «مراقب خودت باش!»', 'Māmān goft: "Morāgheb-e khodet bāsh!"', 'Mom said: "Take care of yourself!"'],
  ],
},
{
  id: 'st-33-1', session: '33', title_en: "Mom's phone call", title_fa: 'تلفن مامان',
  gloss: {},
  lines: [
    ['مامانم هر هفته به من زنگ می‌زنه.', 'Māmānam har hafteh be man zang mizaneh.', 'My mom calls me every week.'],
    ['ولی هفته‌ی پیش زنگ نزد.', 'Vali hafte-ye pish zang nazad.', "But last week she didn't call."],
    ['دو روز پیش، من بهش زنگ زدم.', 'Do rooz-e pish, man behesh zang zadam.', 'Two days ago, I called her.'],
    ['مامانم گفت: «ببخشید! سرم خیلی شلوغ بود. من الان هر روز پیانو می‌زنم!»', 'Māmānam goft: "Bebakhshid! Saram kheili sholugh bood. Man alān har rooz piāno mizanam!"', 'My mom said: "Sorry! I\'ve been really busy. I play the piano every day now!"'],
    ['من گفتم: «واقعاً؟ پیانو؟»', 'Man goftam: "Vāghean? Piāno?"', 'I said: "Really? The piano?"'],
    ['مامانم گفت: «آره! فردا بیا خونه، برات پیانو می‌زنم.»', 'Māmānam goft: "Āreh! Fardā biā khooneh, barāt piāno mizanam."', 'My mom said: "Yes! Come over tomorrow, I\'ll play the piano for you."'],
    ['دیروز من رفتم خونه‌ی مامانم.', 'Dirooz man raftam khoone-ye māmānam.', "Yesterday I went to my mom's house."],
    ['قبل از شام، ما با همدیگه گپ زدیم.', 'Ghabl az shām, mā bā hamdige gap zadim.', 'Before dinner, we chatted.'],
    ['بعد از شام، مامانم پیانو زد و من براش دست زدم.', "Ba'd az shām, māmānam piāno zad va man barāsh dast zadam.", 'After dinner, my mom played the piano and I clapped for her.'],
    ['همه‌چیز عالی بود!', 'Hameh-chiz āli bood!', 'Everything was great!'],
    ['شب، مامانم گفت: «به همه سلام برسون!»', 'Shab, māmānam goft: "Be hameh salām beresoon!"', 'In the evening, my mom said: "Say hello to everyone!"'],
  ],
},
{
  id: 'st-33-2', session: '33', title_en: 'Before school', title_fa: 'قبل از مدرسه',
  gloss: {},
  lines: [
    ['ساعت هفت صبح، مامان بچه‌ها رو صدا می‌زنه: «بچه‌ها، بیدار بشید!»', 'Sāat-e haft-e sobh, māmān bacheh hā ro sedā mizaneh: "Bacheh hā, bidār beshid!"', 'At seven in the morning, Mom calls the children: "Kids, wake up!"'],
    ['قبل از صبحونه، بچه‌ها دندون‌هاشون رو مسواک می‌زنن.', 'Ghabl az sobhooneh, bacheh hā dandoon hāshoon ro mesvāk mizanan.', 'Before breakfast, the children brush their teeth.'],
    ['سارا موهاش رو شونه می‌زنه.', 'Sārā moo hāsh ro shooneh mizaneh.', 'Sara combs her hair.'],
    ['علی سوت می‌زنه و آواز می‌خونه.', 'Ali soot mizaneh va āvāz mikhooneh.', 'Ali whistles and sings.'],
    ['بعد از صبحونه، مامان می‌گه: «زود باشید! همه‌چیز آماده‌ست؟»', 'Ba\'d az sobhooneh, māmān migeh: "Zood bāshid! Hameh-chiz āmādeh-st?"', 'After breakfast, Mom says: "Hurry up! Is everything ready?"'],
    ['بچه‌ها می‌گن: «چشم!»', 'Bacheh hā migan: "Cheshm!"', 'The children say: "Yes, Mom!"'],
    ['ساعت هشت، یکی زنگ در رو می‌زنه.', 'Sāat-e hasht, yeki zang-e dar ro mizaneh.', 'At eight, someone rings the doorbell.'],
    ['همسایه‌ست! بچه‌ها هر روز با ماشین همسایه به مدرسه می‌رن.', 'Hamsāyeh-st! Bacheh hā har rooz bā māshin-e hamsāyeh be madreseh miran.', "It's the neighbour! Every day the children go to school in the neighbour's car."],
    ['علی به مامانش چشمک می‌زنه و می‌گه: «بعد از مدرسه بهت زنگ می‌زنم!»', "Ali be māmānesh cheshmak mizaneh va migeh: \"Ba'd az madreseh behet zang mizanam!\"", 'Ali winks at his mom and says: "I\'ll call you after school!"'],
  ],
},
{
  id: 'st-34-1', session: '34', title_en: 'Tehran or Shiraz?', title_fa: 'تهران یا شیراز؟',
  gloss: {},
  lines: [
    ['علی و سارا با همدیگه حرف می‌زنن.', 'Ali o Sārā bā hamdige harf mizanan.', 'Ali and Sara are talking.'],
    ['علی می‌گه: «به نظر من، تهران بهترین شهر ایرانه.»', 'Ali migeh: "Be nazar-e man, Tehrān behtarin shahr-e Irān-eh."', 'Ali says: "In my opinion, Tehran is the best city in Iran."'],
    ['سارا می‌گه: «نه! تهران از شیراز بزرگ‌تره، ولی شیراز قشنگ‌تره.»', 'Sārā migeh: "Na! Tehrān az Shirāz bozorgtar-eh, vali Shirāz ghashangtar-eh."', 'Sara says: "No! Tehran is bigger than Shiraz, but Shiraz is prettier."'],
    ['«هوای شیراز هم از هوای تهران بهتره.»', '"Havā-ye Shirāz ham az havā-ye Tehrān behtar-eh."', '"And the weather in Shiraz is better than in Tehran."'],
    ['علی می‌گه: «ولی غذای تهران خوشمزه‌تره!»', 'Ali migeh: "Vali ghazā-ye Tehrān khoshmazetar-eh!"', 'Ali says: "But the food in Tehran is tastier!"'],
    ['سارا می‌گه: «خوشمزه‌ترین غذای ایرانی فسنجونه.»', 'Sārā migeh: "Khoshmazetarin ghazā-ye irāni fesenjoon-eh."', 'Sara says: "The tastiest Iranian food is fesenjoon."'],
    ['«و مامان من بهترین فسنجون دنیا رو درست می‌کنه!»', '"Va māmān-e man behtarin fesenjoon-e donyā ro dorost mikoneh!"', '"And my mom makes the best fesenjoon in the world!"'],
    ['علی می‌خنده و می‌گه: «مامان تو از مامان من بهتر آشپزی می‌کنه؟»', 'Ali mikhandeh va migeh: "Māmān-e to az māmān-e man behtar āshpazi mikoneh?"', 'Ali laughs and says: "Your mom cooks better than my mom?"'],
    ['سارا می‌گه: «آره! ولی مامان تو بهترین حلیم رو درست می‌کنه.»', 'Sārā migeh: "Āreh! Vali māmān-e to behtarin halim ro dorost mikoneh."', 'Sara says: "Yes! But your mom makes the best halim."'],
    ['علی می‌گه: «خوب، فردا شب شام خونه‌ی مامان تو!»', 'Ali migeh: "Khob, fardā shab shām khoone-ye māmān-e to!"', 'Ali says: "OK then, tomorrow night it\'s dinner at your mom\'s!"'],
  ],
},
{
  id: 'st-34-2', session: '34', title_en: 'My notes: Friday evening', title_fa: 'یادداشت‌های من: جمعه شب',
  gloss: {},
  lines: [
    ['ساعت هفت شب است.', 'Sāat-e haft-e shab ast.', "It's seven in the evening."],
    ['کلاس رقص امروز خیلی خوب بود.', 'Kelās-e raghs emrooz kheili khoob bood.', 'Dance class was very good today.'],
    ['امروز بهتر از هفته‌ی پیش رقصیدم.', 'Emrooz behtar az hafte-ye pish raghsidam.', 'Today I danced better than last week.'],
    ['هوا امروز سردتر از دیروز بود.', 'Havā emrooz sardtar az dirooz bood.', 'The weather today was colder than yesterday.'],
    ['الان در خانه هستم.', 'Alān dar khāneh hastam.', "Now I'm at home."],
    ['خانه دیگر ساکت نیست.', 'Khāneh digar sāket nist.', "The house isn't quiet anymore."],
    ['بچّه‌ها بیدار هستند و با هم بازی می‌کنند.', 'Bachcheh hā bidār hastand va bā ham bāzi mikonand.', 'The children are awake and playing together.'],
    ['سیاوش شام درست می‌کند: فسنجون و پلو.', 'Siāvash shām dorost mikonad: fesenjoon va polo.', 'Siavash is making dinner: fesenjoon and rice.'],
    ['بوی فسنجون در خانه می‌پیچد.', 'Booye fesenjoon dar khāneh mipichad.', 'The smell of fesenjoon fills the house.'],
    ['من خسته هستم، امّا خیلی خوشحالم، چون رقص را خیلی دوست دارم.', 'Man khasteh hastam, ammā kheili khoshhālam, chun raghs rā kheili doost dāram.', "I'm tired, but I'm very happy, because I really love dancing."],
    ['جمعه هنوز بهترین روز هفته است.', "Jom'eh hanooz behtarin rooz-e hafteh ast.", 'Friday is still the best day of the week.'],
    ['همین.', 'Hamin.', "That's it."],
  ],
},
{
  id: 'st-35-1', session: '35', title_en: "Where's my key?", title_fa: 'کلیدم کجاست؟',
  gloss: {},
  lines: [
    ['علی امروز ساعت نه قرار کاری داره.', 'Ali emrooz sāat-e noh gharār-e kāri dāreh.', 'Ali has a business meeting at nine today.'],
    ['الان ساعت هشت و نیمه.', 'Alān sāat hasht-o nim-eh.', "It's half past eight now."],
    ['علی می‌گه: «سارا! تو می‌دونی کلیدم کجاست؟»', 'Ali migeh: "Sārā! To midooni kelidam kojāst?"', 'Ali says: "Sara! Do you know where my key is?"'],
    ['سارا می‌گه: «نمی‌دونم! روی میز نیست؟»', 'Sārā migeh: "Nemidoonam! Ruye miz nist?"', 'Sara says: "I don\'t know! Isn\'t it on the table?"'],
    ['کلید روی میز نیست.', 'Kelid ruye miz nist.', "The key isn't on the table."],
    ['زیر کاناپه یه جوراب و یه کتاب هست، ولی کلید نیست.', 'Zir-e kānāpeh ye joorāb o ye ketāb hast, vali kelid nist.', "Under the couch there's a sock and a book, but no key."],
    ['سارا می‌گه: «توی کیفت چی؟»', 'Sārā migeh: "Tuye kifet chi?"', 'Sara says: "What about in your bag?"'],
    ['علی کیفش رو برمی‌داره. کلید توی کیف هم نیست!', 'Ali kifesh ro barmidāreh. Kelid tuye kif ham nist!', "Ali picks up his bag. The key isn't in the bag either!"],
    ['«موبایلم کجاست؟ موبایلم هم نیست!»', '"Mobāylam kojāst? Mobāylam ham nist!"', '"Where\'s my phone? My phone\'s gone too!"'],
    ['سارا می‌خنده: «موبایلت توی دستته! و کلیدت روی یخچاله.»', 'Sārā mikhandeh: "Mobāylet tuye dastet-eh! Va kelidet ruye yakhchāl-eh."', 'Sara laughs: "Your phone is in your hand! And your key is on the fridge."'],
    ['علی کلید رو برمی‌داره و می‌گه: «دیگه هیچ‌وقت کلیدم رو روی یخچال نمی‌ذارم!»', 'Ali kelid ro barmidāreh va migeh: "Dige hichvaght kelidam ro ruye yakhchāl nemizāram!"', 'Ali picks up the key and says: "I\'ll never put my key on the fridge again!"'],
    ['علی ساعت نه و ربع به قرارش می‌رسه.', "Ali sāat-e noh-o rob' be gharāresh mireseh.", 'Ali gets to his meeting at a quarter past nine.'],
  ],
},
{
  id: 'st-35-2', session: '35', title_en: "Mom's kitchen", title_fa: 'آشپزخونه‌ی مامان',
  gloss: { 'کابینت': ['kābinet', 'kitchen cupboard'] },
  lines: [
    ['آشپزخونه‌ی مامانم کوچیکه، ولی خیلی تمیزه.', 'Āshpazkhoone-ye māmānam koochik-eh, vali kheili tamiz-eh.', "My mom's kitchen is small, but it's very clean."],
    ['یخچال سمت راست در هست و اجاق کنار یخچاله.', 'Yakhchāl samt-e rāst-e dar hast va ojāgh kenār-e yakhchāl-eh.', 'The fridge is on the right side of the door, and the stove is next to the fridge.'],
    ['روی گاز همیشه یه قابلمه هست.', 'Ruye gāz hamisheh ye ghāblameh hast.', "There's always a pot on the stove."],
    ['جلوی پنجره یه میز کوچیک و دو تا صندلی هست.', 'Jeloye panjereh ye miz-e koochik o do tā sandali hast.', "In front of the window there's a small table and two chairs."],
    ['روی میز یه ظرف میوه و یه قوری هست.', 'Ruye miz ye zarf-e miveh o ye ghoori hast.', "On the table there's a fruit bowl and a teapot."],
    ['سطل آشغال زیر میزه.', 'Satl-e āshghāl zir-e miz-eh.', 'The bin is under the table.'],
    ['تابه‌ها توی کابینت، زیر اجاق هستن.', 'Tābeh hā tuye kābinet, zir-e ojāgh hastan.', 'The pans are in the cupboard under the stove.'],
    ['مامانم می‌گه: «ماهی‌تابه رو بردار و روی گاز بذار!»', 'Māmānam migeh: "Māhi-tābeh ro bardār va ruye gāz bezār!"', 'My mom says: "Take the frying pan and put it on the stove!"'],
    ['من ماهی‌تابه رو برمی‌دارم و روی گاز می‌ذارم.', 'Man māhi-tābeh ro barmidāram va ruye gāz mizāram.', 'I take the frying pan and put it on the stove.'],
    ['بعد مامانم تخم مرغ‌ها رو از یخچال برمی‌داره.', "Ba'd māmānam tokhm-e morgh hā ro az yakhchāl barmidāreh.", 'Then my mom takes the eggs out of the fridge.'],
    ['کتری روی گازه و آب داره می‌جوشه.', 'Ketri ruye gāz-eh va āb dāreh mijoosheh.', 'The kettle is on the stove and the water is boiling.'],
    ['من می‌گم: «مامان، نون کجاست؟»', 'Man migam: "Māmān, noon kojāst?"', 'I say: "Mom, where\'s the bread?"'],
    ['مامانم می‌گه: «توی سبد، کنار قوری.»', 'Māmānam migeh: "Tuye sabad, kenār-e ghoori."', 'My mom says: "In the basket, next to the teapot."'],
    ['صبحونه‌ی مامانم بهترین صبحونه‌ی دنیاست!', 'Sobhoone-ye māmānam behtarin sobhoone-ye donyāst!', "My mom's breakfast is the best breakfast in the world!"],
  ],
},
];
